# Settings

In [1]:
#always run this first!!
#essential reticulate functions that allow us to use python packages in R
#you'll need a conda env with 'leidenalg' and 'pandas' installed to do this
#then route reticulate to the python installed in that conda env with the below functions
Sys.setenv(RETICULATE_PYTHON="/home/welison/.conda/envs/decontX_reticulate/bin/python")
library(reticulate)
reticulate::use_python("/home/welison/.conda/envs/decontX_reticulate/bin/python")
reticulate::use_condaenv("/home/welison/.conda/envs/decontX_reticulate")
reticulate::py_module_available(module='leidenalg') #needs to be TRUE
reticulate::import('leidenalg') #good to make sure this doesn't error
reticulate::import('anndata') #good to make sure this doesn't error

Warning message:
“package ‘reticulate’ was built under R version 4.3.3”

[1] TRUE

Module(leidenalg)

Module(anndata)

In [2]:
library(dplyr)
library(stringr)
library(data.table)
library(tidyr)
library(Seurat)
library(Signac)
library(ggplot2)
library(parallel)
library(anndata)
library(Matrix)

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message:
“package ‘stringr’ was built under R version 4.3.2”

Attaching package: ‘data.table’


The following objects are masked from ‘package:dplyr’:

    between, first, last


Warning message:
“package ‘Seurat’ was built under R version 4.3.3”
Loading required package: SeuratObject

Warning message:
“package ‘SeuratObject’ was built under R version 4.3.3”
Loading required package: sp

Warning message:
“package ‘sp’ was built under R version 4.3.3”

Attaching package: ‘SeuratObject’


The following objects are masked from ‘package:base’:

    intersect, t


Warning message:
“package ‘anndata’ was built under R version 4.3.3”

Attaching package: ‘anndata’


The following object is masked from ‘package:SeuratObject’:

    Layers


Warning message:
“package ‘Matrix’ was built under R version 4.3.2”

Attaching package: ‘Matrix’


The following objects are masked from ‘package:tidyr’:

    expand, pack, unpack

# Load assay

In [3]:
adata <- readRDS('/nfs/lab/projects/nash_nafld_liver/downstream_all/10222024_fnih_liver_final_object.rds')
adata

An object of class Seurat
1648188 features across 408178 samples within 6 assays
Active assay: RNA (36601 features, 0 variable features)
 2 layers present: counts, data
 5 other assays present: SCT, Peaks, signac.peaks, Peaks.1, Peaks.2
 7 dimensional reductions calculated: pca, harmony.rna, umap.rna, lsi, harmony.atac, umap.atac, umap.wnn

In [4]:
adata$RNA
adata$Peaks.1
adata$Peaks.2
adata$SCT

Assay data with 36601 features for 408178 cells
First 10 features:
 MIR1302-2HG, FAM138A, OR4F5, AL627309.1, AL627309.3, AL627309.2,
AL627309.5, AL627309.4, AP006222.2, AL732372.1

ChromatinAssay data with 300000 features for 408178 cells
Variable features: 0
Genome: hg38
Annotation present: FALSE
Motifs present: FALSE
Fragment files: 18

ChromatinAssay data with 311576 features for 408178 cells
Variable features: 0
Genome: hg38
Annotation present: FALSE
Motifs present: FALSE
Fragment files: 18

SCTAssay data with 23755 features for 408178 cells, and 1 SCTModel(s)
Top 10 variable features:
 LDB2, BICC1, PRKG1, LAMA2, ADAMTSL1, LINC02388, NRG3, ST6GALNAC3, HGF,
LIFR

In [5]:
colnames(adata[[]])
table(adata$condition)
table(adata$Fibrosis.stage)

 [1] "orig.ident"                        "nCount_RNA"
 [3] "nFeature_RNA"                      "percent.mt"
 [5] "nCount_RNA_raw"                    "nFeature_RNA_raw"
 [7] "donor_demux"                       "nCount_SCT"
 [9] "nFeature_SCT"                      "SCT.weight"
[11] "seurat_clusters"                   "log_nCount_SCT"
[13] "log_nFeature_SCT"                  "lane"
[15] "batch"                             "gex_raw_reads"
[17] "gex_mapped_reads"                  "gex_conf_intergenic_reads"
[19] "gex_conf_exonic_reads"             "gex_conf_intronic_reads"
[21] "gex_conf_exonic_unique_reads"      "gex_conf_exonic_antisense_reads"
[23] "gex_conf_exonic_dup_reads"         "gex_exonic_umis"
[25] "gex_conf_intronic_unique_reads"    "gex_conf_intronic_antisense_reads"
[27] "gex_conf_intronic_dup_reads"       "gex_intronic_umis"
[29] "gex_conf_txomic_unique_reads"      "gex_umis_count"
[31] "gex_genes_count"                   "atac_raw_reads"
[33] "atac_unmapped_reads"               "atac_lowmapq"
[35] "atac_dup_reads"                    "atac_chimeric_reads"
[37] "atac_mitochondrial_reads"          "atac_fragments"
[39] "atac_TSS_fragments"                "atac_peak_region_fragments"
[41] "atac_peak_region_cutsites"         "TSS.enrichment"
[43] "TSS.percentile"                    "condition"
[45] "disease_status"                    "library"
[47] "amulet"                            "nCount_Peaks"
[49] "nFeature_Peaks"                    "Description"
[51] "Age"                               "BMI"
[53] "Gender"                            "Alcoholic..2..Drinks.Day."
[55] "Steatosis.grade"                   "Steatosis.."
[57] "Fat.distribution"                  "Lobular.inflammation"
[59] "Ballooning"                        "Portal.inflammation"
[61] "Hepatocyte.necrosis"               "MASH.CRN.score..X.8"
[63] "Diagnosis"                         "Peaks.weight"
[65] "value"                             "barcode"
[67] "cellsubtype"                       "celltype"
[69] "nCount_Peaks_Full"                 "nFeature_Peaks_Full"
[71] "Fibrosis.stage"                    "nCount_Peaks.1"
[73] "nFeature_Peaks.1"                  "nCount_Peaks.2"
[75] "nFeature_Peaks.2"

Control    MASH    MASL  MetALD
 131993   88203  131832   56150

     0      1      2      3      4
246974  57000  53227  24213  26764

In [6]:
meta <- data.frame(table(adata[[]][c('donor_demux','celltype')])) %>% 
    pivot_wider(values_from = Freq, names_from = celltype) %>%
    left_join(dplyr::distinct(dplyr::select(adata[[]], donor_demux, batch, disease_status, condition,
               Steatosis.grade, Fibrosis.stage, Fat.distribution, Lobular.inflammation, Ballooning,
               Portal.inflammation, Hepatocyte.necrosis, MASH.CRN.score..X.8, Gender, Age, BMI)))

meta$batch <- factor(meta$batch, levels=c('firstPR','secondPR','thirdPR','fourthPR'))
meta$condition <- factor(meta$condition, levels=c('Control','MASL','MASH','MetALD'))
meta$disease_status <- factor(meta$disease_status, levels=c('Control','Disease'))
meta$Gender <- factor(meta$Gender, levels=c('F','M'))
meta$BMI.scaled <- scale(meta$BMI, center = T, scale = T)
meta$Age.scaled <- scale(meta$Age, center = T, scale = T)

meta

write.table(meta, '/nfs/lab/projects/nash_nafld_liver/downstream_all/01_DESEQ_RNA/RNA.meta.tsv',
           sep='\t', col.names=T, row.names=F, quote=F)

Joining with `by = join_by(donor_demux)`

   donor_demux B   Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK
1  HL150001     85  47            746        8760        308  4    726    167
2  HL150009     19  34            459        2317        329  0    227     23
3  HL150013     93  31            553         541        308 31    459    100
4  HL150015     59  59            410        4421        312  1    199     63
5  HL160017     54  68            662        6986        199  0    683     39
6  HL160022      9 187            349        1097        334  0    468     22
7  HL160026     15  29            721        6012        452  0     66     31
8  HL160029      5   8            299        1104        189  0    136     28
9  HL160030     27  72            728        3785        314  3    213     51
10 HL160032     71 192           2319        1751        519  5   1152    353
11 HL160035     52 146            533        2417        284  4    506    135
12 HL160037    102  67            643        1869        186  8    619    202
13 HL160040     22 120            663        7098        443 10    354    115
14 HL160041     11  27            678        2419         79  1    291     77
15 HL160042      5   8            239        1031         99  0     68     13
16 HL170044     35 448            705        2916        468 13    496     85
17 HL170046     25  58            397        1419        308  0    166     36
18 HL170047     14  65            534        1183        210  6    154     56
19 HL170048     85 126           1842        3455        201 20    804     97
20 HL170049      2 199            369         375        400  0    343     11
21 HL170052     38 245           1023        2721        373  2    214     69
22 HL170055    110 315            458        1943        682  0    337     76
23 HL170058     53 360            581        1281        692  5    360     58
24 HL170060      9   6            199        1324         95  0     67     15
25 HL170062    121 140           1500        7172        424  9    739    167
26 HL170064     92 116           1204        4009        361  8   1296    114
27 HL170065     48 221            882        1656        454 19    944    123
28 HL170066     68 158           1149        3715        741  0   1000    230
29 HL180071     38  61            474         292        174 10    231     59
30 HL180809     58 147           1383        5416        619  1    631    142
⋮  ⋮           ⋮   ⋮             ⋮           ⋮           ⋮   ⋮    ⋮       ⋮
57 HL210207     61 151           1156         1630       344  8   1623    199
58 HL210521    130 138            952          695       580 15   1006    150
59 HL210614     69  48            762         1050       199  1   1176    355
60 HL210621     88  24            822         3685       201  3    638    354
61 HL210706     66 179            742         5019       276  2    630    121
62 HL210726     15 305            590         1327       501  0    295     39
63 HL210727     30 137            981          886       346  2    384    117
64 HL210806     21 313            450          649       767  0    168     51
65 HL211001     23 135            911         8046       423  1    376     70
66 HL211025     69  95            629         2044       252  0    365     97
67 HL211106    126 144           1321          830       266  0    684    269
68 HL211122    127 447            592         3638       739  0    578    120
69 HL220127     39 154            944         1946       564  1    978    174
70 HL220210     53  84            561          981       222  4    825    154
71 HL220216     49  47            409          410       126  1    522     72
72 HL220402     27 211            489         1780       181  1    445     94
73 HL220405     75 185            436         2931       288  0    514    112
74 HL220613     46  26            644         1766       162  6    440     27
75 HL220628     83  74           1028         2762       294  4    415     31
76 HL220825      5   8            232          597       110  0     60      6
77 HL221006    151  57            380         5105       224  2   1019     64
78 HL221019     37  30            127          391       138  0    118     11
79 HL221119    313  61           1365         2178       348  1   2365    132
80 HL221201    156  26            787         5846       143  6    721     58
81 HL221215     41 163            990         5625       453  0    630     43
82 HL230212    150  27            695         3495       220  0    724     55
83 HL230302    115  26            718          311       274  0    533     85
84 HL230316     55  91            821         2625       321  0    287     53
85 HL230324     56  63           1071         6674       384  5    623    102
86 HL230325     63 109           1209        12432       546  2   1135     62
   Schwann ⋯ Lobular.inflammation Ballooning Portal.inflammation
1   8      ⋯ 0                    0          0
2   6      ⋯ 0                    0          0
3   1      ⋯ 1                    1          1-2 Mild/moderate
4   7      ⋯ 0                    0          1
5   2      ⋯ 1                    0          2
6   8      ⋯ 1                    1          1
7   0      ⋯ 0                    0          0
8   5      ⋯ 0                    0          0
9   6      ⋯ 0                    0          0
10 13      ⋯ 0                    0          1
11  2      ⋯ 0                    0          0
12  4      ⋯ 0                    0          1
13  2      ⋯ 0                    0          0
14  1      ⋯ 0                    1          0
15  3      ⋯ 0                    0          0
16  9      ⋯ 0                    0          0
17 11      ⋯ 1                    0          1
18  1      ⋯ 0                    0          0
19  2      ⋯ 1                    0          1
20  1      ⋯ 0                    1          1
21 18      ⋯ 0                    0          0
22  3      ⋯ 1                    1          1
23  8      ⋯ 1                    0          0-1
24  1      ⋯ 2                    0          1
25 16      ⋯ 0                    0          1
26  6      ⋯ 2                    1          1
27  8      ⋯ 2                    0          1
28 11      ⋯ 2                    1          2
29  6      ⋯ 1                    0          1
30 26      ⋯ 0                    0          0
⋮  ⋮       ⋱ ⋮                    ⋮          ⋮
57  5      ⋯ 0                     0         0-1
58  2      ⋯ 1                     0         1
59  5      ⋯ 0                     0         0
60  1      ⋯ 0                     0         1
61  4      ⋯ 1                     0         1
62  4      ⋯ 1                     2         1
63  1      ⋯ 1                     0         1
64  0      ⋯ 1                     2         1
65  6      ⋯ 0                     0         0
66  0      ⋯ 2                     0         2
67  5      ⋯ 0                     0         1
68  4      ⋯ 1                     0         1
69  9      ⋯ 1                     2         1
70 10      ⋯ 0                     0         1
71  0      ⋯ 0                     0         1
72  0      ⋯ 0                     0         0
73  2      ⋯ 2                     0         1
74  4      ⋯ 0                     0         0
75  4      ⋯ 1                     0         0
76  1      ⋯ 0                     0         0
77  1      ⋯ 1                     0         2
78  0      ⋯ 1                     1         1
79  3      ⋯ 0                     0         1
80  5      ⋯ 0                     0         1
81  7      ⋯ 1                     1         1
82  4      ⋯ 1                     0         2
83  3      ⋯ 0                     1         0
84  4      ⋯ 0                    NA         1
85  4      ⋯ 2                     0         1
86  8      ⋯ 2                     0         44928
   Hepatocyte.necrosis                                 MASH.CRN.score..X.8
1  0                                                   1
2  0                                                   1
3  Spotty                                              3
4  0                                                   3
5  0                                                   2
6  0                                                   5
7  Spotty                                              0
8  0                                                   0
9  0                                                   2
10 0                                                   2
11 0                                                   3
12 1 acidophil body                                    1
13 0                                                   0
14 0                                                   6
15 0                                                   3
16 0                                                   0
17 None                                                3
18 0                                                   0
19 Rare                                                2
20 Single hemorrhagic, necrotic regenerative nodule    4
21 0                                                   0
22 Rare, <1%                                           4
23 0                                                   3
24  Spotty, focal (less than 1% of hepatic parenchyma) 5
25 0                                                   0
26 Rare, <1%                                           5
27 0                                                   4
28 Spotty, focal (less than 1% of hepatic parenchyma)  6
29 0                                                   4
30 0                                                   0
⋮  ⋮                                                   ⋮
57 0                                                   0
58 rare                                                2
59 0                                                   0
60 rare                                                0
61 0                                                   2
62 0                                                   6
63 0                                                   2
64 0                                                   6
65 0                                                   0
66 Rare                                                5
67 0                                                   0
68 0                                                   3
69 0                                                   6
70 0                                                   0
71 0                                                   0
72 0                                                   0
73 0                                                   4
74 0                                                   0
75 0                                                   3
76 0                                                   0
77 0                                                   3
78 0                                                   3
79 0                                                   0
80 0                                                   1
81 0                                                   5
82 0                                                   3
83                                                     1
84 minimal centrizonal                                 0
85                                                     3
86 rare                                                5
   Gender Age BMI   BMI.scaled   Age.scaled
1  M      47  27.10 -0.638584666 -0.01553551
2  M      37  29.40 -0.334686949 -0.75778750
3  M      45  35.00  0.405237926 -0.16398591
4  M      59  29.10 -0.374325782  0.87516689
5  M      31  24.00 -1.048185936 -1.20313870
6  F      45  29.80 -0.281835172 -0.16398591
7  F      25  26.00 -0.783927052 -1.64848990
8  F      47  30.86 -0.141777964 -0.01553551
9  M      29  30.20 -0.228983396 -1.35158910
10 M      23  29.40 -0.334686949 -1.79694030
11 F      47  32.20  0.035275488 -0.01553551
12 M      42  34.60  0.352386149 -0.38666151
13 M      51  26.70 -0.691436443  0.28136529
14 M      33  35.40  0.458089703 -1.05468830
15 F      34  25.90 -0.797139996 -0.98046310
16 M      47  32.80  0.114553153 -0.01553551
17 F      53  48.06  2.130848438  0.42981569
18 M      34  23.50 -1.114250657 -0.98046310
19 F      48  31.96  0.003564422  0.05868969
20 F      34  23.79 -1.075933119 -0.98046310
21 M      29  23.60 -1.101037713 -1.35158910
22 M      59  27.70 -0.559307001  0.87516689
23 F      58  38.30  0.841265084  0.80094169
24 F      50  29.80 -0.281835172  0.20714009
25 F      79  27.85 -0.539487584  2.35967088
26 M      66  37.03  0.673460693  1.39474329
27 F      57  60.60  3.787751640  0.72671649
28 M      51  37.74  0.767272597  0.28136529
29 F      52  44.40  1.647254680  0.35559049
30 M      56  24.00 -1.048185936  0.65249129
⋮  ⋮      ⋮   ⋮     ⋮            ⋮
57 F      34  34.48  0.33653062  -0.98046310
58 F      61  30.75 -0.15631220   1.02361729
59 M      43  30.50 -0.18934456  -0.31243631
60 M      64  25.77 -0.81431682   1.24629289
61 F      54  29.32 -0.34525730   0.50404089
62 M      55  34.60  0.35238615   0.57826609
63 M      44  29.30 -0.34789989  -0.23821111
64 F      36  26.20 -0.75750116  -0.83201270
65 F      45  27.00 -0.65179761  -0.16398591
66 F      44  33.60  0.22025671  -0.23821111
67 M      23  30.05 -0.24880281  -1.79694030
68 F      63  33.30  0.18061787   1.17206769
69 F      24  26.67 -0.69540033  -1.72271510
70 M      68  33.50  0.20704376   1.54319369
71 F      22  32.65  0.09473374  -1.87116550
72 F      58  16.66 -2.01801604   0.80094169
73 M      33  25.77 -0.81431682  -1.05468830
74 M      60  32.80  0.11455315   0.94939209
75 M      30  37.50  0.73556153  -1.27736390
76 M      21  22.47 -1.25034398  -1.94539070
77 M      43  29.40 -0.33468695  -0.31243631
78 F      40  17.70 -1.88060142  -0.53511190
79 M      37  23.80 -1.07461182  -0.75778750
80 M      46  39.80  1.03945925  -0.08976071
81 F      43  43.00  1.46227346  -0.31243631
82 M      56  32.20  0.03527549   0.65249129
83 F      60  28.50 -0.45360345   0.94939209
84 F      58  29.30 -0.34789989   0.80094169
85 M      60  34.20  0.29953437   0.94939209
86 M      50  36.40  0.59021914   0.20714009

# Cell count matrix  - RNA

In [25]:
samples = as.character(unique(adata$donor_demux))
samples

 [1] "HL160042" "HL170046" "HL190326" "HL160029" "HL170060" "HL210120"
 [7] "HL200925" "HL230316" "HL220825" "HL191025" "HL210726" "HL200805"
[13] "HL210806" "HL200707" "HL170049" "HL200525" "HL221006" "HL210207"
[19] "HL181010" "HL220127" "HL181031" "HL170066" "HL191002" "HL170044"
[25] "HL160030" "HL160035" "HL150013" "HL211122" "HL180809" "HL210521"
[31] "HL160022" "HL220210" "HL221019" "HL201120" "HL220628" "HL190606"
[37] "HL220402" "HL210614" "HL190624" "HL150001" "HL221215" "HL200115"
[43] "HL230302" "HL170064" "HL170048" "HL230325" "HL191216" "HL230212"
[49] "HL181029" "HL221119" "HL190214" "HL170062" "HL221201" "HL170047"
[55] "HL180071" "HL190603" "HL160032" "HL211106" "HL220216" "HL200615"
[61] "HL170065" "HL160041" "HL210727" "HL190909" "HL210621" "HL220613"
[67] "HL170052" "HL160040" "HL160037" "HL160017" "HL220405" "HL170055"
[73] "HL170058" "HL190215" "HL190114" "HL230324" "HL160026" "HL190827"
[79] "HL150015" "HL200529" "HL211001" "HL210706" "HL211025" "HL150009"
[85] "HL201024" "HL200212"

In [26]:
######## SET TO WHATEVER YOUR ASSIGNMENTS ARE STORED UNDER ########
Idents(object = adata) <- "celltype"
head(Idents(adata))

#pull out list of all cell types, removing ignore
unique_cell_types <- unique(adata$celltype)
#unique_cell_types <- unique_cell_types[-c(11)]
print(unique_cell_types)


sample_bcs <- list()
for (sample in samples){
    sample_bcs[[sample]] <- row.names(adata[[]][adata[[]]$donor == sample,])
}

##############
#### SET TO WHATEVER ASSAY YOU WANT TO USE ######
DefaultAssay(adata) <- 'RNA'
gex.counts <- GetAssayData(adata, slot='counts')
dim(gex.counts)
head(gex.counts)

MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1
                               Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1
                               Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1
                               Endothelial
10 Levels: Endothelial Hepatocytes T HSC Cholangiocyte Myeloid Schwann NK ... Mast

 [1] "Endothelial"   "Hepatocytes"   "T"             "HSC"
 [5] "Cholangiocyte" "Myeloid"       "Schwann"       "NK"
 [9] "B"             "Mast"

[1]  36601 408178

  [[ suppressing 34 column names ‘MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1’, ‘MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1’, ‘MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1’ ... ]]

6 x 408178 sparse Matrix of class "dgCMatrix"

MIR1302-2HG . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
FAM138A     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
OR4F5       . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.1  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.3  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.2  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

MIR1302-2HG ......
FAM138A     ......
OR4F5       ......
AL627309.1  ......
AL627309.3  ......
AL627309.2  ......

 .....suppressing 408144 columns in show(); maybe adjust options(max.print=, width=)
 ..............................

In [27]:
unique_cell_types

 [1] "Endothelial"   "Hepatocytes"   "T"             "HSC"
 [5] "Cholangiocyte" "Myeloid"       "Schwann"       "NK"
 [9] "B"             "Mast"

In [28]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/'

In [29]:
#looping through cell types by making ^ into a function
get_per_sample_gex_SUMS <- function(cell.type, filename){
    print(paste(cell.type,Sys.time()))

    #pull out rows of gex.counts where BC Ident matches cell.type
    if (cell.type=='Bulk') {
        bcs <- names(Idents(adata))
    } else {
        bcs <- names(Idents(adata)[Idents(adata) == cell.type])
    }
    counts <- gex.counts[,colnames(gex.counts) %in% bcs]
    print(dim(counts))

    #initialize the matrix of sample gex
    counts.df <- as.data.frame(rep(0,length(row.names(gex.counts))))
    row.names(counts.df) <- row.names(gex.counts)
    colnames(counts.df) <- c('temp')

    #go through samples and calculate sum of gex values
    for (sample in samples){
        sample_cols <- colnames(counts) %in% sample_bcs[[sample]]
        counts.cut <- counts[,sample_cols]
        
        #if only one bc, this becomes a vector which is an issue
        if (typeof(counts.cut) == 'double'){
            mean.counts <- counts.cut
        #if there are NO bcs, this will return NA (just return 0 for everything)
        } else if(length(colnames(counts.cut)) == 0){
            mean.counts <- rep(0,length(row.names(counts)))
        } else {
            mean.counts <- rowSums(counts.cut)
        }
        counts.df <- cbind(counts.df,as.data.frame(mean.counts))
     }
    fin.counts.df <- counts.df[,-c(1)]
    colnames(fin.counts.df) <- samples
    
    #export df
    write.table(fin.counts.df, filename, sep='\t',quote=FALSE)
}

In [ ]:
##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    filename <- paste(outdir, cell.type, '_perdonor.RNA.counts.tsv', sep = "")
    get_per_sample_gex_SUMS(cell.type, filename)
}

# Making updated gene info that is whole transcript length (not just exonic)

In [33]:
#genes <- read.table('/nfs/lab/elisha/scripts/refdata-gex-GRCh38-2020-A/genes/genes.gtf.gz', sep='\t')
#genes <- filter(genes, V3=='gene')
#
##dim(genes)
##head(genes)
#
#genes$length <- genes$V5 - genes$V4
#genes$gene <- str_remove(str_extract(genes$V9, 'gene_name[^;]*'), 'gene_name\\s')
#gene.info <- dplyr::select(genes, gene, length)
#
##dim(gene.info)
##head(gene.info)
#
##gene.info[duplicated(gene.info$gene),]
#
#gene.info[duplicated(gene.info$gene),]$gene <- paste0(gene.info[duplicated(gene.info$gene),]$gene, '.1')
#
#gene.info[duplicated(gene.info$gene),]
#
#write.table(gene.info, '/nfs/lab/welison/References/refdata-gex-GRCh38-2020-A.full.gene.length.info.tsv',
#           sep='\t', col.names=T, row.names=F, quote=F)

ERROR: Error in filter(genes, V3 == "gene"): ensembldb::filter requires an 'EnsDb' object as input. To call the filter function from the stats or dplyr package use stats::filter and dplyr::filter instead.

# TPM - RNA

In [ ]:
#looping through cell types by making ^ into a function
calculate_TPM <- function(cell.type, tpm.filename, pseudobulk.filename, gene.info){
    x <- read.table(paste(pseudobulk.filename))
    
    x$length <- gene.info[rownames(x),]$length
    x <- dplyr::select(x, length, everything())
    
    #calculate rpk (as a df)
    rpk <- (x[,2:ncol(x)]/x[,1])
    #remove length col from x 
    x2 <- x[,-1]
    
    tpm <- rpk
    for (i in 1:ncol(rpk)){
        tpm[,i] <- rpk[,i]/(sum(rpk[,i])/1e6)
    }
    
    #export df
    write.table(tpm, tpm.filename, sep='\t',quote=FALSE)
}

In [ ]:
indir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/'
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/'

gene.info <- read.table('/nfs/lab/welison/References/refdata-gex-GRCh38-2020-A.full.gene.length.info.tsv',
           sep='\t', header=T)
rownames(gene.info) <- gene.info$gene

dim(gene.info)
head(gene.info)

##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    tpm.filename <- paste(outdir, cell.type, '_perdonor.RNA.TPM.tsv', sep = "")
    pseudobulk.filename <- paste(indir, cell.type, '_perdonor.RNA.counts.tsv', sep = "")
    calculate_TPM(cell.type, tpm.filename, pseudobulk.filename, gene.info)
}

# Cell count matrix  - ATAC

In [6]:
samples = as.character(unique(adata$donor_demux))
samples

 [1] "HL160042" "HL170046" "HL190326" "HL160029" "HL170060" "HL210120"
 [7] "HL200925" "HL230316" "HL220825" "HL191025" "HL210726" "HL200805"
[13] "HL210806" "HL200707" "HL170049" "HL200525" "HL221006" "HL210207"
[19] "HL181010" "HL220127" "HL181031" "HL170066" "HL191002" "HL170044"
[25] "HL160030" "HL160035" "HL150013" "HL211122" "HL180809" "HL210521"
[31] "HL160022" "HL220210" "HL221019" "HL201120" "HL220628" "HL190606"
[37] "HL220402" "HL210614" "HL190624" "HL150001" "HL221215" "HL200115"
[43] "HL230302" "HL170064" "HL170048" "HL230325" "HL191216" "HL230212"
[49] "HL181029" "HL221119" "HL190214" "HL170062" "HL221201" "HL170047"
[55] "HL180071" "HL190603" "HL160032" "HL211106" "HL220216" "HL200615"
[61] "HL170065" "HL160041" "HL210727" "HL190909" "HL210621" "HL220613"
[67] "HL170052" "HL160040" "HL160037" "HL160017" "HL220405" "HL170055"
[73] "HL170058" "HL190215" "HL190114" "HL230324" "HL160026" "HL190827"
[79] "HL150015" "HL200529" "HL211001" "HL210706" "HL211025" "HL150009"
[85] "HL201024" "HL200212"

In [ ]:
######## SET TO WHATEVER YOUR ASSIGNMENTS ARE STORED UNDER ########
Idents(object = adata) <- "celltype"
head(Idents(adata))

#pull out list of all cell types, removing ignore
unique_cell_types <- unique(adata$celltype)
#unique_cell_types <- unique_cell_types[-c(11)]
print(unique_cell_types)


sample_bcs <- list()
for (sample in samples){
    sample_bcs[[sample]] <- row.names(adata[[]][adata[[]]$donor == sample,])
}

##############
#### SET TO WHATEVER ASSAY YOU WANT TO USE ######
DefaultAssay(adata) <- 'Peaks.1'
gex.counts.1 <- GetAssayData(adata, slot='counts')
dim(gex.counts.1)
head(gex.counts.1)

##############
#### SET TO WHATEVER ASSAY YOU WANT TO USE ######
DefaultAssay(adata) <- 'Peaks.2'
gex.counts.2 <- GetAssayData(adata, slot='counts')
dim(gex.counts.2)
head(gex.counts.2)

MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1
                               Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1
                               Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1
                               Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1
                               Endothelial
10 Levels: Endothelial Hepatocytes T HSC Cholangiocyte Myeloid Schwann NK ... Mast

 [1] "Endothelial"   "Hepatocytes"   "T"             "HSC"
 [5] "Cholangiocyte" "Myeloid"       "Schwann"       "NK"
 [9] "B"             "Mast"

Warning message:
“The `slot` argument of `GetAssayData()` is deprecated as of SeuratObject 5.0.0.
ℹ Please use the `layer` argument instead.”

[1] 300000 408178

In [12]:
unique_cell_types

 [1] "Endothelial"   "Hepatocytes"   "T"             "HSC"
 [5] "Cholangiocyte" "Myeloid"       "Schwann"       "NK"
 [9] "B"             "Mast"

In [13]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

In [26]:
#looping through cell types by making ^ into a function
get_per_sample_gex_SUMS_ATAC_2_assay <- function(cell.type, filename){
    print(paste(cell.type,Sys.time()))

    #pull out rows of gex.counts.1 where BC Ident matches cell.type
    if (cell.type=='Bulk') {
        bcs <- names(Idents(adata))
    } else {
        bcs <- names(Idents(adata)[Idents(adata) == cell.type])
    }
    counts.1 <- gex.counts.1[,colnames(gex.counts.1) %in% bcs]
    print(dim(counts.1))
    counts.2 <- gex.counts.2[,colnames(gex.counts.2) %in% bcs]
    print(dim(counts.2))

    #initialize the matrix of sample gex
    counts.df <- as.data.frame(rep(0,(nrow(gex.counts.1) + nrow(gex.counts.2))))
    row.names(counts.df) <- c(row.names(gex.counts.1), row.names(gex.counts.2))
    colnames(counts.df) <- c('temp')

    #go through samples and calculate sum of gex values
    for (sample in samples){
        sample_cols <- colnames(counts.1) %in% sample_bcs[[sample]]
        counts.1.cut <- counts.1[,sample_cols]
        counts.2.cut <- counts.2[,sample_cols]
        
        #if only one bc, this becomes a vector which is an issue
        if (typeof(counts.1.cut) == 'double'){
            mean.counts.1 <- counts.1.cut
        #if there are NO bcs, this will return NA (just return 0 for everything)
        } else if(length(colnames(counts.1.cut)) == 0){
            mean.counts.1 <- rep(0,length(row.names(counts.1.cut)))
        } else {
            mean.counts.1 <- rowSums(counts.1.cut)
        }
            
        #if only one bc, this becomes a vector which is an issue
        if (typeof(counts.2.cut) == 'double'){
            mean.counts.2 <- counts.2.cut
        #if there are NO bcs, this will return NA (just return 0 for everything)
        } else if(length(colnames(counts.2.cut)) == 0){
            mean.counts.2 <- rep(0,length(row.names(counts.2.cut)))
        } else {
            mean.counts.2 <- rowSums(counts.2.cut)
        }
        mean.counts <- c(mean.counts.1,mean.counts.2)
        counts.df <- cbind(counts.df,as.data.frame(mean.counts))
     }
    fin.counts.df <- counts.df[,-c(1)]
    colnames(fin.counts.df) <- samples
    
    #export df
    write.table(fin.counts.df, filename, sep='\t',quote=FALSE)
}

In [27]:
##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    filename <- paste(outdir, cell.type, '_perdonor.ATAC.counts.tsv', sep = "")
    get_per_sample_gex_SUMS_ATAC_2_assay(cell.type, filename)
}

[1] "Endothelial 2024-10-22 15:27:19.655887"
[1] 300000  61975
[1] 311576  61975
[1] "Hepatocytes 2024-10-22 15:31:34.854568"
[1] 300000 233608
[1] 311576 233608
[1] "T 2024-10-22 15:39:10.122878"
[1] 300000  11758
[1] 311576  11758
[1] "HSC 2024-10-22 15:40:13.193114"
[1] 300000  31224
[1] 311576  31224
[1] "Cholangiocyte 2024-10-22 15:41:37.291096"
[1] 300000  10654
[1] 311576  10654
[1] "Myeloid 2024-10-22 15:42:40.040558"
[1] 300000  44814
[1] 311576  44814
[1] "Schwann 2024-10-22 15:44:19.403433"
[1] 300000    456
[1] 311576    456
[1] "NK 2024-10-22 15:45:11.193376"
[1] 300000   8095
[1] 311576   8095
[1] "B 2024-10-22 15:46:06.845656"
[1] 300000   5297
[1] 311576   5297
[1] "Mast 2024-10-22 15:47:03.588002"
[1] 300000    297
[1] 311576    297
[1] "Bulk 2024-10-22 15:47:51.791342"
[1] 300000 408178
[1] 311576 408178

# Calculate CPM for ATAC

CPM = 1000000*(peak counts/depth)

In [28]:
#looping through cell types by making ^ into a function
calculate_CPM <- function(cell.type, cpm.filename, pseudobulk.filename){
    x <- read.table(paste(pseudobulk.filename))
    
    cpm <- x
    for (i in 1:ncol(x)){
        cpm[,i] <- 1e6 * (x[,i]/sum(x[,i]))
    }
    
    #export df
    write.table(cpm, cpm.filename, sep='\t',quote=FALSE)
}

In [29]:
indir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    cpm.filename <- paste(outdir, cell.type, '_perdonor.ATAC.CPM.tsv', sep = "")
    pseudobulk.filename <- paste(indir, cell.type, '_perdonor.ATAC.counts.tsv', sep = "")
    calculate_CPM(cell.type, cpm.filename, pseudobulk.filename)
}

# Cell count matrix  - H3K27ac

In [3]:
DPT.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/'

In [6]:
H3K27ac <- read_h5ad(paste0(DPT.dir, 'FNIH_Liver_pool.H3K27ac.peaks.h5ad'))
H3K27ac

AnnData object with n_obs × n_vars = 94775 × 391368
    obs: 'n_fragment', 'frac_dup', 'frac_mito', 'doublet_probability', 'doublet_score_x', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'percent.ribo', 'RNA_snn_res.0.3', 'seurat_clusters', 'doublet_score_y', 'doublet_ident', 'DROPLET.TYPE', 'BEST.GUESS', 'NEXT.GUESS', 'rna', 'rna_bc', 'dna', 'library_info', 'dna_bc', 'Donor', 'Batch', 'Target', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.1', 'predicted.celltype', 'predicted.celltype_scores', 'predicted.cellsubtype', 'predicted.cellsubtype_scores', 'atac_bc', 'condition', 'leiden'
    var: 'count', 'selected'
    uns: 'spectral_eigenvalue'
    obsm: 'X_spectral', 'X_spectral_harmony', 'X_umap'
    obsp: 'distances'

In [10]:
H3K27ac$obs

                           n_fragment frac_dup            frac_mito
LV003:AAACAAGCAAAGGCCT-1   5671       0.42276349148859105 0.0
LV003:AAACAAGCAACAACAT-1   4036       0.4025728339008702  0.0
LV003:AAACCAGGTAAGTGGC-1    744       0.3853679285410464  0.0
LV003:AAACCAGGTGAGTTAG-1    712       0.39537869062901154 0.0
LV003:AAACCAGGTGTAACAG-1    969       0.36477748193229365 0.0
LV003:AAACCAGGTTAAAGGT-1   1296       0.37476518472135256 0.0
LV003:AAACCAGGTTAATCCA-1   3528       0.37533234859675035 0.0
LV003:AAACCAGGTTATTGTG-1   3811       0.37079905173615957 0.0
LV003:AAACCGCCAAACAAAG-1    167       0.405071967100754   0.0
LV003:AAACCGCCAACCAACA-1    511       0.41842610364683297 0.0
LV003:AAACCGCCACATAGCA-1    840       0.3768701981399111  0.0
LV003:AAACCGCCAGGAATAA-1    156       0.394774011299435   0.0
LV003:AAACCGCCAGGTGAGA-1   1509       0.40108401084010836 0.0
LV003:AAACCGGTCAGCCTGT-1   2355       0.3962860529435006  0.0
LV003:AAACCGGTCAGGAGCC-1   1136       0.3768656716417911  0.0
LV003:AAACCGGTCATAACGA-1     46       0.4182242990654206  0.0
LV003:AAACCGGTCATAGCGG-1   2068       0.3748024384736961  0.0
LV003:AAACCGGTCATGCAAA-1    820       0.39952625345440185 0.0
LV003:AAACCGGTCCACCCTC-1    372       0.40750966316951964 0.0
LV003:AAACCGGTCCGGCTAT-1   2824       0.4058654980616888  0.0
LV003:AAACCGGTCCTAACCA-1   2423       0.3813861386138614  0.0
LV003:AAACCGGTCCTTCGGG-1   1194       0.38553826199740593 0.0
LV003:AAACCGGTCGCTATAT-1   2666       0.3858080992338563  0.0
LV003:AAACCGGTCGGGATGC-1    536       0.38671294000991574 0.0
LV003:AAACCGGTCTAGGCGA-1   5653       0.378629387036856   0.0
LV003:AAACCGGTCTGCAACC-1    335       0.4090131203650884  0.0
LV003:AAACGAACAAATGAAG-1   1262       0.39692780337941624 0.0
LV003:AAACGAACAACAAGTT-1   1398       0.3921227917752679  0.0
LV003:AAACGAACAACCGCCT-1     88       0.3797169811320755  0.0
LV003:AAACGAACAACGGGAA-1    814       0.3891129032258065  0.0
⋮                          ⋮          ⋮                   ⋮
QY_2594:TTTGGCCAGGGTTATA-1 2651       0.7902902902902903  0.0
QY_2594:TTTGGCCAGGGTTGGC-1 5728       0.7868102734051368  0.0
QY_2594:TTTGGCCAGTAACCGG-1  460       0.7835973904939422  0.0
QY_2594:TTTGGTTAGAATCTAG-1 2343       0.7699342453329302  0.0
QY_2594:TTTGGTTAGCCGATAG-1 3373       0.7950291809217146  0.0
QY_2594:TTTGGTTAGCCTTCAA-1 2985       0.7725954716515516  0.0
QY_2594:TTTGGTTAGGCGCGAT-1  235       0.7701375245579568  0.0
QY_2594:TTTGGTTAGGGCTACA-1 2760       0.7937794196508372  0.0
QY_2594:TTTGGTTAGTCATGCC-1 4647       0.7768226015106623  0.0
QY_2594:TTTGGTTAGTCCTCAA-1 4841       0.7834056356743659  0.0
QY_2594:TTTGGTTAGTCCTCCC-1 4082       0.7937650914108313  0.0
QY_2594:TTTGGTTAGTTATGGA-1 3121       0.7803448275862069  0.0
QY_2594:TTTGGTTAGTTGCAAA-1 6003       0.7853808275244611  0.0
QY_2594:TTTGTCGAGAACCTTT-1 2243       0.7633440514469454  0.0
QY_2594:TTTGTCGAGAGCTGCA-1 3277       0.77033658564748    0.0
QY_2594:TTTGTCGAGATATTGG-1 2773       0.7612535220947014  0.0
QY_2594:TTTGTCGAGATTCACT-1 3542       0.7505731585444713  0.0
QY_2594:TTTGTCGAGATTGCCC-1 5381       0.7368694297828156  0.0
QY_2594:TTTGTCGAGCCTTCAA-1 3644       0.7827282728272827  0.0
QY_2594:TTTGTCGAGCTTGTTG-1 7449       0.7941278925105748  0.0
QY_2594:TTTGTCGAGGCTCAAG-1 2324       0.7932472148178525  0.0
QY_2594:TTTGTCGAGGGCTATG-1 5239       0.7929952953476216  0.0
QY_2594:TTTGTCGAGGGCTTTC-1 3681       0.7629172753340908  0.0
QY_2594:TTTGTCGAGTTCGCGT-1  400       0.7642398286937901  0.0
QY_2594:TTTGTGAGTACACCGC-1 2808       0.7724974066390041  0.0
QY_2594:TTTGTGAGTACCGTTG-1 1573       0.7624320936063519  0.0
QY_2594:TTTGTGAGTCATGCCA-1 3953       0.788396835500591   0.0
QY_2594:TTTGTGAGTCTATCTT-1 2204       0.757269385026738   0.0
QY_2594:TTTGTGAGTTAAACGG-1 4444       0.7841771886404632  0.0
QY_2594:TTTGTGAGTTCTGGCA-1 2495       0.7689248788952353  0.0
                           doublet_probability    doublet_score_x
LV003:AAACAAGCAAAGGCCT-1   2.5805991754780877e-32 -1.757884273224534
LV003:AAACAAGCAACAACAT-1   6.342371488649329e-32  -0.553709919775258
LV003:AAACCAGGTAAGTGGC-1   9.294613653482838e-32  -0.055058983293971867
LV003:AAACCAGGTGAGTTAG-1   9.640846661092686e-32  -0.007728843898973197
LV003:AAACCAGGTGTAACAG-1   9.260535184212409e-32  -0.05981618104178641
LV003:AAACCAGGTTAAAGGT-1   9.581552759946369e-32  -0.015707783375865283
LV003:AAACCAGGTTAATCCA-1   6.965372665690794e-32  -0.43076110792592665
LV003:AAACCAGGTTATTGTG-1   6.965372665690794e-32  -0.43076110792592665
LV003:AAACCGCCAAACAAAG-1   8.511026408592977e-32  -0.16930931254170276
LV003:AAACCGCCAACCAACA-1   9.581552759946369e-32  -0.015707783375865283
LV003:AAACCGCCACATAGCA-1   7.374518801967385e-32  -0.35608635696254126
LV003:AAACCGCCAGGAATAA-1   9.669929459912214e-32  -0.0038339007233483937
LV003:AAACCGCCAGGTGAGA-1   8.072399506188295e-32  -0.23813689939435798
LV003:AAACCGGTCAGCCTGT-1   6.665895325448081e-32  -0.4883700646796087
LV003:AAACCGGTCAGGAGCC-1   9.155429148282742e-32  -0.07460385947746657
LV003:AAACCGGTCATAACGA-1   9.669929459912214e-32  -0.0038339007233483937
LV003:AAACCGGTCATAGCGG-1   3.033395356615791e-32  -1.5380541736095168
LV003:AAACCGGTCATGCAAA-1   9.394109796210622e-32  -0.04127275960623208
LV003:AAACCGGTCCACCCTC-1   9.669929459912214e-32  -0.0038339007233483937
LV003:AAACCGGTCCGGCTAT-1   7.036762212825107e-32  -0.41740837671963643
LV003:AAACCGGTCCTAACCA-1   8.770789646804195e-32  -0.13026499454447005
LV003:AAACCGGTCCTTCGGG-1   9.190952684758915e-32  -0.06958630721895473
LV003:AAACCGGTCGCTATAT-1   8.275220572095417e-32  -0.20584009870359876
LV003:AAACCGGTCGGGATGC-1   9.489681825641626e-32  -0.02817233669891013
LV003:AAACCGGTCTAGGCGA-1   2.2705202355110322e-32 -1.9330454671768456
LV003:AAACCGGTCTGCAACC-1   9.394109796210622e-32  -0.04127275960623208
LV003:AAACGAACAAATGAAG-1   9.520706169330017e-32  -0.02394915722774345
LV003:AAACGAACAACAAGTT-1   9.611390130886029e-32  -0.011686299080852386
LV003:AAACGAACAACCGCCT-1   9.489681825641626e-32  -0.02817233669891013
LV003:AAACGAACAACGGGAA-1   9.611390130886029e-32  -0.011686299080852386
⋮                          ⋮                      ⋮
QY_2594:TTTGGCCAGGGTTATA-1 0.0022331961335660417  -0.4749517632563871
QY_2594:TTTGGCCAGGGTTGGC-1 1.0                    26.577630830103832
QY_2594:TTTGGCCAGTAACCGG-1 0.0008455717533678704  -0.05238741455891148
QY_2594:TTTGGTTAGAATCTAG-1 0.0016274683640223222  -0.34961607238772846
QY_2594:TTTGGTTAGCCGATAG-1 0.0032566136421097206  -0.6134409086424838
QY_2594:TTTGGTTAGCCTTCAA-1 0.9998731563959377     -3.5166203779454595
QY_2594:TTTGGTTAGGCGCGAT-1 0.000791595602371662   -0.01856547318133754
QY_2594:TTTGGTTAGGGCTACA-1 0.009171674100652874   -0.9498724629504283
QY_2594:TTTGGTTAGTCATGCC-1 0.3744110247420092     -1.9600244959858915
QY_2594:TTTGGTTAGTCCTCAA-1 0.9990026564972696     -3.224526031288839
QY_2594:TTTGGTTAGTCCTCCC-1 0.0015677032212591264  -0.3341401586393001
QY_2594:TTTGGTTAGTTATGGA-1 0.009171674100652874   -0.9498724629504283
QY_2594:TTTGGTTAGTTGCAAA-1 0.06217837595925347    -1.4742138738505484
QY_2594:TTTGTCGAGAACCTTT-1 0.0009278568007290772  -0.09855669506324108
QY_2594:TTTGTCGAGAGCTGCA-1 0.9999903214502786     -3.857532972295907
QY_2594:TTTGTCGAGATATTGG-1 0.0010378409891455458  -0.15221626615309541
QY_2594:TTTGTCGAGATTCACT-1 0.9905275687121348     5.3573114238265855
QY_2594:TTTGTCGAGATTGCCC-1 0.3744110247420092     -1.9600244959858915
QY_2594:TTTGTCGAGCCTTCAA-1 0.0032566136421097206  -0.6134409086424838
QY_2594:TTTGTCGAGCTTGTTG-1 0.001403836705548638   2.76397200783267
QY_2594:TTTGTCGAGGCTCAAG-1 0.0012911247021229698  -0.25128963756126926
QY_2594:TTTGTCGAGGGCTATG-1 0.00038213880683561673 2.0309766317978832
QY_2594:TTTGTCGAGGGCTTTC-1 0.007985534725568264   -0.9078107092733215
QY_2594:TTTGTCGAGTTCGCGT-1 0.0008118687125816204  -0.0316380523806353
QY_2594:TTTGTGAGTACACCGC-1 0.007985534725568264   -0.9078107092733215
QY_2594:TTTGTGAGTACCGTTG-1 0.0011336545229926065  -0.19310218808505344
QY_2594:TTTGTGAGTCATGCCA-1 0.0010597981675786127  -0.16201749354367173
QY_2594:TTTGTGAGTCTATCTT-1 0.0013702330941704056  -0.2771520977819904
QY_2594:TTTGTGAGTTAAACGG-1 0.6036050605327258     4.621606651713137
QY_2594:TTTGTGAGTTCTGGCA-1 0.0009439524129170596  -0.10693368830765528
                           orig.ident    nCount_RNA nFeature_RNA
LV003:AAACAAGCAAAGGCCT-1   SeuratProject 602        468
LV003:AAACAAGCAACAACAT-1   SeuratProject 405        372
LV003:AAACCAGGTAAGTGGC-1   SeuratProject 2406       1481
LV003:AAACCAGGTGAGTTAG-1   SeuratProject 1025       747
LV003:AAACCAGGTGTAACAG-1   SeuratProject 2973       1737
LV003:AAACCAGGTTAAAGGT-1   SeuratProject 557        476
LV003:AAACCAGGTTAATCCA-1   SeuratProject 2432       1373
LV003:AAACCAGGTTATTGTG-1   SeuratProject 339        294
LV003:AAACCGCCAAACAAAG-1   SeuratProject 322        289
LV003:AAACCGCCAACCAACA-1   SeuratProject 1487       894
LV003:AAACCGCCACATAGCA-1   SeuratProject 1444       943
LV003:AAACCGCCAGGAATAA-1   SeuratProject 6893       3065
LV003:AAACCGCCAGGTGAGA-1   SeuratProject 1536       1077
LV003:AAACCGGTCAGCCTGT-1   SeuratProject 860        669
LV003:AAACCGGTCAGGAGCC-1   SeuratProject 2795       1692
LV003:AAACCGGTCATAACGA-1   SeuratProject 958        718
LV003:AAACCGGTCATAGCGG-1   SeuratProject 1029       731
LV003:AAACCGGTCATGCAAA-1   SeuratProject 1585       1030
LV003:AAACCGGTCCACCCTC-1   SeuratProject 1999       1269
LV003:AAACCGGTCCGGCTAT-1   SeuratProject 1346       973
LV003:AAACCGGTCCTAACCA-1   SeuratProject 1516       972
LV003:AAACCGGTCCTTCGGG-1   SeuratProject 3461       1780
LV003:AAACCGGTCGCTATAT-1   SeuratProject 2935       1786
LV003:AAACCGGTCGGGATGC-1   SeuratProject 1729       1199
LV003:AAACCGGTCTAGGCGA-1   SeuratProject 1105       763
LV003:AAACCGGTCTGCAACC-1   SeuratProject 2389       1518
LV003:AAACGAACAAATGAAG-1   SeuratProject 942        727
LV003:AAACGAACAACAAGTT-1   SeuratProject 649        536
LV003:AAACGAACAACCGCCT-1   SeuratProject 3095       1806
LV003:AAACGAACAACGGGAA-1   SeuratProject 1298       895
⋮                          ⋮             ⋮          ⋮
QY_2594:TTTGGCCAGGGTTATA-1 SeuratProject 6564       2918
QY_2594:TTTGGCCAGGGTTGGC-1 SeuratProject 9829       3525
QY_2594:TTTGGCCAGTAACCGG-1 SeuratProject 6405       2667
QY_2594:TTTGGTTAGAATCTAG-1 SeuratProject 5870       2578
QY_2594:TTTGGTTAGCCGATAG-1 SeuratProject 2922       1710
QY_2594:TTTGGTTAGCCTTCAA-1 SeuratProject 28489      5689
QY_2594:TTTGGTTAGGCGCGAT-1 SeuratProject 1861       1285
QY_2594:TTTGGTTAGGGCTACA-1 SeuratProject 1329       962
QY_2594:TTTGGTTAGTCATGCC-1 SeuratProject 4927       2384
QY_2594:TTTGGTTAGTCCTCAA-1 SeuratProject 10247      3626
QY_2594:TTTGGTTAGTCCTCCC-1 SeuratProject 3622       1992
QY_2594:TTTGGTTAGTTATGGA-1 SeuratProject 17942      4895
QY_2594:TTTGGTTAGTTGCAAA-1 SeuratProject 3765       1995
QY_2594:TTTGTCGAGAACCTTT-1 SeuratProject 14755      4467
QY_2594:TTTGTCGAGAGCTGCA-1 SeuratProject 11224      3615
QY_2594:TTTGTCGAGATATTGG-1 SeuratProject 6099       2743
QY_2594:TTTGTCGAGATTCACT-1 SeuratProject 4554       2338
QY_2594:TTTGTCGAGATTGCCC-1 SeuratProject 8656       3347
QY_2594:TTTGTCGAGCCTTCAA-1 SeuratProject 6881       3040
QY_2594:TTTGTCGAGCTTGTTG-1 SeuratProject 6089       2881
QY_2594:TTTGTCGAGGCTCAAG-1 SeuratProject 2524       1540
QY_2594:TTTGTCGAGGGCTATG-1 SeuratProject 6473       2834
QY_2594:TTTGTCGAGGGCTTTC-1 SeuratProject 9890       3700
QY_2594:TTTGTCGAGTTCGCGT-1 SeuratProject 667        549
QY_2594:TTTGTGAGTACACCGC-1 SeuratProject 3833       2071
QY_2594:TTTGTGAGTACCGTTG-1 SeuratProject 7996       3132
QY_2594:TTTGTGAGTCATGCCA-1 SeuratProject 3274       1812
QY_2594:TTTGTGAGTCTATCTT-1 SeuratProject 7682       3088
QY_2594:TTTGTGAGTTAAACGG-1 SeuratProject 3045       1612
QY_2594:TTTGTGAGTTCTGGCA-1 SeuratProject 4688       2132
                           percent.mt         percent.ribo      ⋯ nCount_SCT
LV003:AAACAAGCAAAGGCCT-1   0.164203612479475  0.328407224958949 ⋯ 3298
LV003:AAACAAGCAACAACAT-1   0.0                0.245098039215686 ⋯ 3144
LV003:AAACCAGGTAAGTGGC-1   0.0                0.121605188488042 ⋯ 4349
LV003:AAACCAGGTGAGTTAG-1   0.0                0.481695568400771 ⋯ 3524
LV003:AAACCAGGTGTAACAG-1   0.0                0.460829493087558 ⋯ 4213
LV003:AAACCAGGTTAAAGGT-1   0.0                1.24555160142349  ⋯ 3256
LV003:AAACCAGGTTAATCCA-1   0.0                0.16116035455278  ⋯ 4349
LV003:AAACCAGGTTATTGTG-1   0.0                0.0               ⋯ 3225
LV003:AAACCGCCAAACAAAG-1   0.31055900621118   0.0               ⋯ 3024
LV003:AAACCGCCAACCAACA-1   0.0                0.397350993377483 ⋯ 3659
LV003:AAACCGCCACATAGCA-1   0.0                0.409836065573771 ⋯ 3487
LV003:AAACCGCCAGGAATAA-1   0.0                0.264550264550265 ⋯ 5368
LV003:AAACCGCCAGGTGAGA-1   0.0                0.512163892445583 ⋯ 3778
LV003:AAACCGGTCAGCCTGT-1   0.0                0.230414746543779 ⋯ 3563
LV003:AAACCGGTCAGGAGCC-1   0.0                0.312717164697707 ⋯ 4113
LV003:AAACCGGTCATAACGA-1   0.0                0.619834710743802 ⋯ 3460
LV003:AAACCGGTCATAGCGG-1   0.0                0.192492781520693 ⋯ 3767
LV003:AAACCGGTCATGCAAA-1   0.0                0.0               ⋯ 3776
LV003:AAACCGGTCCACCCTC-1   0.0                0.487567040468064 ⋯ 3839
LV003:AAACCGGTCCGGCTAT-1   0.0                0.29218407596786  ⋯ 3606
LV003:AAACCGGTCCTAACCA-1   0.0                0.715214564369311 ⋯ 3611
LV003:AAACCGGTCCTTCGGG-1   0.0                0.309249367444476 ⋯ 4269
LV003:AAACCGGTCGCTATAT-1   0.0                0.231175693527081 ⋯ 3995
LV003:AAACCGGTCGGGATGC-1   0.0                0.113442994895065 ⋯ 3809
LV003:AAACCGGTCTAGGCGA-1   0.0                0.357142857142857 ⋯ 3422
LV003:AAACCGGTCTGCAACC-1   0.0                0.733197556008147 ⋯ 4126
LV003:AAACGAACAAATGAAG-1   0.0                0.316122233930453 ⋯ 3386
LV003:AAACGAACAACAAGTT-1   0.0                0.916030534351145 ⋯ 3313
LV003:AAACGAACAACCGCCT-1   0.0                0.470366886171214 ⋯ 4144
LV003:AAACGAACAACGGGAA-1   0.0                0.455927051671732 ⋯ 3565
⋮                          ⋮                  ⋮                 ⋱ ⋮
QY_2594:TTTGGCCAGGGTTATA-1 0.0                0.243762546601663 ⋯ 5455
QY_2594:TTTGGCCAGGGTTGGC-1 0.0                0.300154918667699 ⋯ 5447
QY_2594:TTTGGCCAGTAACCGG-1 0.0                0.241109101868596 ⋯ 5383
QY_2594:TTTGGTTAGAATCTAG-1 0.0                0.197076695680736 ⋯ 5270
QY_2594:TTTGGTTAGCCGATAG-1 0.0                0.299600532623169 ⋯ 4080
QY_2594:TTTGGTTAGCCTTCAA-1 0.0100264028608669 0.287423548678186 ⋯ 4904
QY_2594:TTTGGTTAGGCGCGAT-1 0.0522739153162572 0.261369576581286 ⋯ 3760
QY_2594:TTTGGTTAGGGCTACA-1 0.0730994152046784 0.511695906432749 ⋯ 3484
QY_2594:TTTGGTTAGTCATGCC-1 0.0394088669950739 0.433497536945813 ⋯ 4892
QY_2594:TTTGGTTAGTCCTCAA-1 0.0093231400335633 0.195785940704829 ⋯ 5348
QY_2594:TTTGGTTAGTCCTCCC-1 0.0                0.320598450440823 ⋯ 4168
QY_2594:TTTGGTTAGTTATGGA-1 0.005350454788657  0.444087747458534 ⋯ 4831
QY_2594:TTTGGTTAGTTGCAAA-1 0.0                0.436456996148909 ⋯ 4209
QY_2594:TTTGTCGAGAACCTTT-1 0.006502796202367  0.286123032904149 ⋯ 4742
QY_2594:TTTGTCGAGAGCTGCA-1 0.0                0.26191280838121  ⋯ 5165
QY_2594:TTTGTCGAGATATTGG-1 0.0156911972383493 0.282441550290287 ⋯ 5357
QY_2594:TTTGTCGAGATTCACT-1 0.0417275192989777 0.292092635092844 ⋯ 4546
QY_2594:TTTGTCGAGATTGCCC-1 0.0                0.286690925129562 ⋯ 5551
QY_2594:TTTGTCGAGCCTTCAA-1 0.0417014178482068 0.291909924937448 ⋯ 5396
QY_2594:TTTGTCGAGCTTGTTG-1 0.0313971742543171 0.251177394034537 ⋯ 5368
QY_2594:TTTGTCGAGGCTCAAG-1 0.0386996904024768 0.503095975232198 ⋯ 4386
QY_2594:TTTGTCGAGGGCTATG-1 0.0                0.223048327137546 ⋯ 5397
QY_2594:TTTGTCGAGGGCTTTC-1 0.0096043027276219 0.345754898194391 ⋯ 5438
QY_2594:TTTGTCGAGTTCGCGT-1 0.0                0.594353640416048 ⋯ 3431
QY_2594:TTTGTGAGTACACCGC-1 0.0                0.403734544536967 ⋯ 4236
QY_2594:TTTGTGAGTACCGTTG-1 0.0                0.203422280722747 ⋯ 5482
QY_2594:TTTGTGAGTCATGCCA-1 0.0                0.206185567010309 ⋯ 4082
QY_2594:TTTGTGAGTCTATCTT-1 0.0124269914253759 0.347955759910526 ⋯ 5418
QY_2594:TTTGTGAGTTAAACGG-1 0.0632711167352104 0.379626700411262 ⋯ 3965
QY_2594:TTTGTGAGTTCTGGCA-1 0.0                0.206868018204386 ⋯ 4652
                           nFeature_SCT SCT_snn_res.1 predicted.celltype
LV003:AAACAAGCAAAGGCCT-1   1502         25            Myeloid
LV003:AAACAAGCAACAACAT-1   1630         14            Myeloid
LV003:AAACCAGGTAAGTGGC-1   1476         6             Hepatocytes
LV003:AAACCAGGTGAGTTAG-1   1302         1             Endothelial
LV003:AAACCAGGTGTAACAG-1   1726         6             Hepatocytes
LV003:AAACCAGGTTAAAGGT-1   1517         2             Cholangiocyte
LV003:AAACCAGGTTAATCCA-1   1373         5             Hepatocytes
LV003:AAACCAGGTTATTGTG-1   1658         14            Myeloid
LV003:AAACCGCCAAACAAAG-1   1673         22            NK
LV003:AAACCGCCAACCAACA-1   1172         1             Endothelial
LV003:AAACCGCCACATAGCA-1   1229         15            HSC
LV003:AAACCGCCAGGAATAA-1   3026         5             Hepatocytes
LV003:AAACCGCCAGGTGAGA-1   1257         4             Hepatocytes
LV003:AAACCGGTCAGCCTGT-1   1302         6             Hepatocytes
LV003:AAACCGGTCAGGAGCC-1   1668         2             Cholangiocyte
LV003:AAACCGGTCATAACGA-1   1336         1             Endothelial
LV003:AAACCGGTCATAGCGG-1   1251         11            Hepatocytes
LV003:AAACCGGTCATGCAAA-1   1176         11            Hepatocytes
LV003:AAACCGGTCCACCCTC-1   1327         1             Endothelial
LV003:AAACCGGTCCGGCTAT-1   1298         2             Cholangiocyte
LV003:AAACCGGTCCTAACCA-1   1208         1             Endothelial
LV003:AAACCGGTCCTTCGGG-1   1774         12            Hepatocytes
LV003:AAACCGGTCGCTATAT-1   1745         2             Cholangiocyte
LV003:AAACCGGTCGGGATGC-1   1286         6             Hepatocytes
LV003:AAACCGGTCTAGGCGA-1   1261         15            HSC
LV003:AAACCGGTCTGCAACC-1   1514         2             Cholangiocyte
LV003:AAACGAACAAATGAAG-1   1367         2             Cholangiocyte
LV003:AAACGAACAACAAGTT-1   1498         1             Endothelial
LV003:AAACGAACAACCGCCT-1   1801         12            Hepatocytes
LV003:AAACGAACAACGGGAA-1   1263         1             Endothelial
⋮                          ⋮            ⋮             ⋮
QY_2594:TTTGGCCAGGGTTATA-1 2871         1             Endothelial
QY_2594:TTTGGCCAGGGTTGGC-1 2924         7             Hepatocytes
QY_2594:TTTGGCCAGTAACCGG-1 2627         2             Cholangiocyte
QY_2594:TTTGGTTAGAATCTAG-1 2553         7             Hepatocytes
QY_2594:TTTGGTTAGCCGATAG-1 1689         10            Myeloid
QY_2594:TTTGGTTAGCCTTCAA-1 2505         6             Hepatocytes
QY_2594:TTTGGTTAGGCGCGAT-1 1368         10            Myeloid
QY_2594:TTTGGTTAGGGCTACA-1 1339         16            T
QY_2594:TTTGGTTAGTCATGCC-1 2363         11            Hepatocytes
QY_2594:TTTGGTTAGTCCTCAA-1 2863         7             Hepatocytes
QY_2594:TTTGGTTAGTCCTCCC-1 1971         10            Myeloid
QY_2594:TTTGGTTAGTTATGGA-1 2498         19            Hepatocytes
QY_2594:TTTGGTTAGTTGCAAA-1 1975         9             Myeloid
QY_2594:TTTGTCGAGAACCTTT-1 2333         3             Hepatocytes
QY_2594:TTTGTCGAGAGCTGCA-1 2623         3             Hepatocytes
QY_2594:TTTGTCGAGATATTGG-1 2677         9             Myeloid
QY_2594:TTTGTCGAGATTCACT-1 2309         10            Myeloid
QY_2594:TTTGTCGAGATTGCCC-1 3086         12            Hepatocytes
QY_2594:TTTGTCGAGCCTTCAA-1 3003         19            Hepatocytes
QY_2594:TTTGTCGAGCTTGTTG-1 2844         19            Hepatocytes
QY_2594:TTTGTCGAGGCTCAAG-1 1536         13            Hepatocytes
QY_2594:TTTGTCGAGGGCTATG-1 2805         6             Hepatocytes
QY_2594:TTTGTCGAGGGCTTTC-1 3031         21            Hepatocytes
QY_2594:TTTGTCGAGTTCGCGT-1 1409         3             Hepatocytes
QY_2594:TTTGTGAGTACACCGC-1 2058         3             Hepatocytes
QY_2594:TTTGTGAGTACCGTTG-1 3042         3             Hepatocytes
QY_2594:TTTGTGAGTCATGCCA-1 1779         1             Endothelial

In [4]:
adata_DPT <- qs::qread(paste0(DPT.dir, 'FNIH_Liver_pool_DPT_SNG_SoupX_reference_mapping_filtered.qs'))
adata_DPT

An object of class Seurat
70217 features across 181892 samples within 2 assays
Active assay: SCT (33616 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap

In [6]:
adata_ac <- subset(adata_DPT, Target=='H3K27ac')
adata_ac

An object of class Seurat
70217 features across 94802 samples within 2 assays
Active assay: SCT (33616 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap

In [28]:
rna.meta <- read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/01_DESEQ_RNA/RNA.meta.tsv',
           sep='\t', header=T)
rna.meta <- select(rna.meta, donor_demux, disease_status, condition,
               Steatosis.grade, Fibrosis.stage, Fat.distribution, Lobular.inflammation, Ballooning,
               Portal.inflammation, Hepatocyte.necrosis, MASH.CRN.score..X.8, Gender, Age, BMI)

meta <- data.frame(table(select(adata_ac[[]], donor_demux=Donor, celltype=predicted.celltype))) %>% 
    pivot_wider(values_from = Freq, names_from = celltype) %>%
    left_join(dplyr::distinct(dplyr::select(adata_ac[[]], donor_demux=Donor, batch=Batch))) %>%
    left_join(rna.meta)

meta$batch <- factor(meta$batch)

meta

write.table(meta, '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/H3K27ac.meta.tsv',
           sep='\t', col.names=T, row.names=F, quote=F)

Joining with `by = join_by(donor_demux)`
Joining with `by = join_by(donor_demux)`

   donor_demux B   Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK
1  HL150001    12   17            58          534         15 1     78     10
2  HL150009     3   11           104          761        116 0     65     17
3  HL150013    22   37           112          281         77 4    100     20
4  HL150015    12   69            89         1266         66 0     59     15
5  HL160017    10   32            71         1476         26 0    234     10
6  HL160022     0  129            45          131         28 0     50      0
7  HL160026     2   18           162          959        105 0     19      7
8  HL160029    19  117           415          861        154 0    191     45
9  HL160030     7   59           228          997         55 0     50     12
10 HL160032     6   56           136           99         21 0     65     27
11 HL160035    11   84           126          239         34 0     71     23
12 HL160037    38   75           149          456         42 4    189     62
13 HL160040     8   95           154         1448        102 1    216     20
14 HL160041     5   62           135          548         36 0     83     13
15 HL160042     9  150           294         2231         81 0    131     25
16 HL170044     7  153           355          576         83 1     61      6
17 HL170046    21   37           173          509        110 0     82     10
18 HL170047    22   44           132          546         86 2     86     20
19 HL170048    13   43            94          770         41 0    139      8
20 HL170049     1  168           179          251        172 0    107      0
21 HL170052     5   44           187          214         63 0     63     11
22 HL170055    14   47            56          269         54 0     73      6
23 HL170058     7  284            86          149        110 0     93      3
24 HL170060     8   15           171         1475         30 0     91     26
25 HL170062    35   88           262         1216         92 0    136     20
26 HL170064    36   54           202         1308         75 1    316     30
27 HL170065    12  167           124          335         64 2    181     13
28 HL170066     8   78           242          472         65 0    126     14
29 HL180071    25   88           163          239        122 2    105     24
30 HL180809     7   62           301          988         63 0     47     23
⋮  ⋮           ⋮   ⋮             ⋮           ⋮           ⋮   ⋮    ⋮       ⋮
57 HL210207      8  45           327          241         26 0    250     23
58 HL210521     38 109           321          229        149 3    309     70
59 HL210614     25  24           101          132         30 0    125     61
60 HL210621     16  25           121          814         37 0    164     46
61 HL210706     18 129           256         1325         66 0    277     21
62 HL210726      7 177           132          422         62 0    135      4
63 HL210727      3  31            48          125         19 0     45     10
64 HL210806     19 391            51          354         93 0     79      2
65 HL211001      6 118           263         1765        105 0    139     33
66 HL211025     57  82           238         1116         56 0    225     25
67 HL211106     17  32           150           52         55 1    114     31
68 HL211122     23 255           165          707         93 0     78      9
69 HL220127      5  85           172          150         29 0    135     11
70 HL220210     23  63           142          265         45 2    223     40
71 HL220216     30  57           156          298         54 0    235     21
72 HL220402      9 212           157           96         37 0     58     10
73 HL220405     17  65            75          569         44 0    135     25
74 HL220613     16  38           154          335         22 0    155      3
75 HL220628     17  75           218          527         27 0     46      4
76 HL220825      5  39           156          129         57 1     54     12
77 HL221006     42 126            67         1262         18 0    253     21
78 HL221019    111 102            92          278        261 0    153     19
79 HL221119     54  20           135          387         44 1    308     26
80 HL221201     99  32           183         1511         57 5    326     15
81 HL221215      7  85           130          359         32 0    172      1
82 HL230212     24  19            59          577         32 1    106      4
83 HL230302     31  35           149          116         74 0    202     19
84 HL230316     34 292           369          614         84 1    171      4
85 HL230324     10  33           168          540         17 0    109     12
86 HL230325      7  83           143         2329         62 0    257     17
   Schwann ⋯ Fibrosis.stage Fat.distribution       Lobular.inflammation
1  0       ⋯ 0              Centrizonal            0
2  3       ⋯ 0              centrizonal            0
3  0       ⋯ 2              Centrilobular, Diffuse 1
4  0       ⋯ 1              Centrilobular, Diffuse 0
5  1       ⋯ 2              Centrilobular          1
6  2       ⋯ 2              Diffuse                1
7  0       ⋯ 0              0                      0
8  2       ⋯ 0              <5%                    0
9  3       ⋯ 0              N/A                    0
10 1       ⋯ 0              N/A                    0
11 1       ⋯ 1              Diffuse                0
12 1       ⋯ 0              0                      0
13 1       ⋯ 0              0                      0
14 0       ⋯ 2              Diffuse                0
15 4       ⋯ 0              Diffuse                0
16 3       ⋯ 0              0                      0
17 0       ⋯ 1              Centrilobular          1
18 0       ⋯ 0              0                      0
19 2       ⋯ 1              Centrilobular          1
20 0       ⋯ 4              Diffuse                0
21 1       ⋯ 0                                     0
22 0       ⋯ 4              Diffuse                1
23 1       ⋯ 2              Centrilobular          1
24 0       ⋯ 2               centrilobular/Diffuse 2
25 0       ⋯ 0              0                      0
26 1       ⋯ 1              Centrilobular          2
27 0       ⋯ 0              Centrilobular          2
28 1       ⋯ 2              Diffuse                2
29 1       ⋯ 3              Diffuse                1
30 5       ⋯ 0              Centrizonal            0
⋮  ⋮       ⋱ ⋮              ⋮                      ⋮
57 0       ⋯ 0              0                      0
58 1       ⋯ 0              Diffuse                1
59 2       ⋯ 0                                     0
60 0       ⋯ 0                                     0
61 0       ⋯ 0              Peripotal              1
62 0       ⋯ 4              Diffuse                1
63 2       ⋯ 0              Centrizonal            1
64 1       ⋯ 4              Diffuse                1
65 0       ⋯ 0              N/A                    0
66 1       ⋯ 0              Diffuse                2
67 1       ⋯ 0              N/A                    0
68 1       ⋯ 3              diffuse                1
69 0       ⋯ 1              diffuse                1
70 2       ⋯ 0              N/A                    0
71 0       ⋯ 0              N/A                    0
72 0       ⋯ 0              N/A                    0
73 1       ⋯ 0              Centrizonal            2
74 1       ⋯ 0              N/A                    0
75 1       ⋯ 0              Centrizonal            1
76 3       ⋯ 0              None                   0
77 3       ⋯ 1              Centrizonal            1
78 2       ⋯ 4              Diffuse                1
79 0       ⋯ 0              None                   0
80 2       ⋯ 0              Centrizonal            0
81 0       ⋯ 1              Diffuse                1
82 0       ⋯ 1              centrizonal            1
83 1       ⋯ 2              0                      0
84 0       ⋯ 0                                     0
85 1       ⋯ 0              cntrizonal             2
86 2       ⋯ 2              diffuse                2
   Ballooning Portal.inflammation
1  0          0
2  0          0
3  1          1-2 Mild/moderate
4  0          1
5  0          2
6  1          1
7  0          0
8  0          0
9  0          0
10 0          1
11 0          0
12 0          1
13 0          0
14 1          0
15 0          0
16 0          0
17 0          1
18 0          0
19 0          1
20 1          1
21 0          0
22 1          1
23 0          0-1
24 0          1
25 0          1
26 1          1
27 0          1
28 1          2
29 0          1
30 0          0
⋮  ⋮          ⋮
57  0         0-1
58  0         1
59  0         0
60  0         1
61  0         1
62  2         1
63  0         1
64  2         1
65  0         0
66  0         2
67  0         1
68  0         1
69  2         1
70  0         1
71  0         1
72  0         0
73  0         1
74  0         0
75  0         0
76  0         0
77  0         2
78  1         1
79  0         1
80  0         1
81  1         1
82  0         2
83  1         0
84 NA         1
85  0         1
86  0         44928
   Hepatocyte.necrosis                                 MASH.CRN.score..X.8
1  0                                                   1
2  0                                                   1
3  Spotty                                              3
4  0                                                   3
5  0                                                   2
6  0                                                   5
7  Spotty                                              0
8  0                                                   0
9  0                                                   2
10 0                                                   2
11 0                                                   3
12 1 acidophil body                                    1
13 0                                                   0
14 0                                                   6
15 0                                                   3
16 0                                                   0
17 None                                                3
18 0                                                   0
19 Rare                                                2
20 Single hemorrhagic, necrotic regenerative nodule    4
21 0                                                   0
22 Rare, <1%                                           4
23 0                                                   3
24  Spotty, focal (less than 1% of hepatic parenchyma) 5
25 0                                                   0
26 Rare, <1%                                           5
27 0                                                   4
28 Spotty, focal (less than 1% of hepatic parenchyma)  6
29 0                                                   4
30 0                                                   0
⋮  ⋮                                                   ⋮
57 0                                                   0
58 rare                                                2
59 0                                                   0
60 rare                                                0
61 0                                                   2
62 0                                                   6
63 0                                                   2
64 0                                                   6
65 0                                                   0
66 Rare                                                5
67 0                                                   0
68 0                                                   3
69 0                                                   6
70 0                                                   0
71 0                                                   0
72 0                                                   0
73 0                                                   4
74 0                                                   0
75 0                                                   3
76 0                                                   0
77 0                                                   3
78 0                                                   3
79 0                                                   0
80 0                                                   1
81 0                                                   5
82 0                                                   3
83                                                     1
84 minimal centrizonal                                 0
85                                                     3
86 rare                                                5
   Gender Age BMI
1  M      47  27.10
2  M      37  29.40
3  M      45  35.00
4  M      59  29.10
5  M      31  24.00
6  F      45  29.80
7  F      25  26.00
8  F      47  30.86
9  M      29  30.20
10 M      23  29.40
11 F      47  32.20
12 M      42  34.60
13 M      51  26.70
14 M      33  35.40
15 F      34  25.90
16 M      47  32.80
17 F      53  48.06
18 M      34  23.50
19 F      48  31.96
20 F      34  23.79
21 M      29  23.60
22 M      59  27.70
23 F      58  38.30
24 F      50  29.80
25 F      79  27.85
26 M      66  37.03
27 F      57  60.60
28 M      51  37.74
29 F      52  44.40
30 M      56  24.00
⋮  ⋮      ⋮   ⋮
57 F      34  34.48
58 F      61  30.75
59 M      43  30.50
60 M      64  25.77
61 F      54  29.32
62 M      55  34.60
63 M      44  29.30
64 F      36  26.20
65 F      45  27.00
66 F      44  33.60
67 M      23  30.05
68 F      63  33.30
69 F      24  26.67
70 M      68  33.50
71 F      22  32.65
72 F      58  16.66
73 M      33  25.77
74 M      60  32.80
75 M      30  37.50
76 M      21  22.47
77 M      43  29.40
78 F      40  17.70
79 M      37  23.80
80 M      46  39.80
81 F      43  43.00
82 M      56  32.20
83 F      60  28.50
84 F      58  29.30
85 M      60  34.20
86 M      50  36.40

In [16]:
samples = as.character(unique(adata_ac$Donor))
samples

 [1] "HL160029" "HL170060" "HL230316" "HL190326" "HL200525" "HL211106"
 [7] "HL221019" "HL170049" "HL210120" "HL210726" "HL221201" "HL210521"
[13] "HL160042" "HL200707" "HL170046" "HL191025" "HL160030" "HL200925"
[19] "HL210806" "HL190214" "HL220825" "HL210614" "HL200805" "HL230325"
[25] "HL170062" "HL230324" "HL210706" "HL160040" "HL200115" "HL230302"
[31] "HL220405" "HL160032" "HL220613" "HL160041" "HL221119" "HL160026"
[37] "HL221215" "HL191216" "HL170058" "HL170065" "HL150001" "HL210621"
[43] "HL230212" "HL190603" "HL170052" "HL201024" "HL210727" "HL190215"
[49] "HL200529" "HL211001" "HL220216" "HL211025" "HL190909" "HL200212"
[55] "HL170064" "HL190114" "HL220210" "HL190827" "HL170047" "HL150015"
[61] "HL170055" "HL150013" "HL160017" "HL180071" "HL200615" "HL191002"
[67] "HL170048" "HL190624" "HL150009" "HL160037" "HL201120" "HL170044"
[73] "HL220628" "HL210207" "HL170066" "HL160035" "HL180809" "HL220127"
[79] "HL211122" "HL221006" "HL160022" "HL181010" "HL181031" "HL190606"
[85] "HL181029" "HL220402"

In [96]:
######## SET TO WHATEVER YOUR ASSIGNMENTS ARE STORED UNDER ########
Idents(object = adata_ac) <- "predicted.celltype"
head(Idents(adata_ac))

#pull out list of all cell types, removing ignore
unique_cell_types <- unique(adata_ac$predicted.celltype)
#unique_cell_types <- unique_cell_types[-c(11)]
print(unique_cell_types)


sample_bcs <- list()
for (sample in samples){
    sample_bcs[[sample]] <- paste0(adata_ac$dna,":",adata_ac$dna_bc)][adata_ac[[]]$Donor == sample]
}

##############
#### SET TO WHATEVER ASSAY YOU WANT TO USE ######
DefaultAssay(adata_ac) <- 'RNA'
gex.counts <- t(H3K27ac$X)
dim(gex.counts)
head(gex.counts)

ERROR: Error in parse(text = x, srcfile = src): <text>:13:69: unexpected ']'
12: for (sample in samples){
13:     sample_bcs[[sample]] <- paste0(adata_ac$dna,":",adata_ac$dna_bc)]
                                                                        ^

In [35]:
unique_cell_types

 [1] "Hepatocytes"   "T"             "HSC"           "Endothelial"
 [5] "Cholangiocyte" "NK"            "Myeloid"       "Schwann"
 [9] "B"             "Mast"

In [36]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

In [63]:
paste0(adata_ac$dna,":",adata_ac$dna_bc)[Idents(adata_ac) == cell.type]
Idents(adata_ac)[Idents(adata_ac) == cell.type]

   [1] "QY_2576:AATCATGAGATGGAGA-1" "QY_2576:GGCCTTCCAGCTAGAC-1"
   [3] "QY_2576:GCCATCAGTAACCTTA-1" "QY_2576:AAACGGGCATTTCGCG-1"
   [5] "QY_2576:CGACCTTAGATTAGCA-1" "QY_2576:CGCTAAACAAGTGCAC-1"
   [7] "QY_2576:GAATCAGGTATGGTCT-1" "QY_2576:CATAGCTGTGCACCAC-1"
   [9] "QY_2576:TACCTAGTCCACCCTC-1" "QY_2576:TCACATTAGTCCCGCA-1"
  [11] "QY_2576:GCCTTAATCAATCGGG-1" "QY_2576:ACCAGGTCATAAGTCG-1"
  [13] "QY_2576:CGTACCTAGATTAGCA-1" "QY_2576:TCGCAATGTTAATCGC-1"
  [15] "QY_2576:GACATCCTCTGTTGCA-1" "QY_2576:GGTTCCTAGCAAGTGT-1"
  [17] "QY_2576:GGTTCCTAGTCACCAC-1" "QY_2576:CGGGACTAGAGCAAGA-1"
  [19] "QY_2576:GGAACTTAGGTGCGTA-1" "QY_2576:CGAGCGAGTTGGGTTT-1"
  [21] "QY_2576:TCCAAATTCGCGAGTA-1" "QY_2576:AGCTAATCAGCTAACA-1"
  [23] "QY_2576:GATTAACCATACTGAG-1" "QY_2576:TGTGGCTTCACTAAGA-1"
  [25] "QY_2576:GAGGTACGTCACACTG-1" "QY_2576:TCACGCCCAAACTAGT-1"
  [27] "QY_2576:TGGTTCTCAGGTAAGG-1" "QY_2576:CAAGTCCTCCTCAGTA-1"
  [29] "QY_2576:CAGGATAGTTGCGAGG-1" "QY_2576:GACTTAAAGTAGGTTA-1"
  [31] "QY_2576:GTTCCAGGTTGAGTCT-1" "QY_2576:ATGTTGTTCGCAACTC-1"
  [33] "QY_2576:CTTCATTGTACTGGCC-1" "QY_2576:TCGAAGTAGAGAGGCG-1"
  [35] "QY_2576:ATTCCTCTCCTTGCAA-1" "QY_2576:CATGGCTTCAGGAGCC-1"
  [37] "QY_2576:CCCTCAACACGCGCAA-1" "QY_2576:GTCGCTAGTGCTAGCC-1"
  [39] "QY_2576:CACCTTAAGGTCCGTT-1" "QY_2576:CCTCACCTCGCTTGTA-1"
  [41] "QY_2576:GGAGCAACAGCTCGCT-1" "QY_2576:TGGATCACACCTGTAT-1"
  [43] "QY_2576:TGGATCACAACCAACA-1" "QY_2576:GTTGTTGTCAATCGGG-1"
  [45] "QY_2576:GGTTGGATCGATATTC-1" "QY_2576:GACTAAGGTTACTTAG-1"
  [47] "QY_2576:GTCTAATTCGCAACTC-1" "QY_2576:CTCCTCATCGACATTT-1"
  [49] "QY_2576:GCAATAATCCTCACGG-1" "QY_2576:GACCGTGCAGCTACCC-1"
  [51] "QY_2576:TTATCGAGTTCGCTTC-1" "QY_2576:GCGTGTTTCAATCGTT-1"
  [53] "QY_2576:AGCTTCTCACATAGCA-1" "QY_2576:GCAACATAGCACAGCA-1"
  [55] "QY_2576:AAACTAGTCAGCCATC-1" "QY_2576:TACCGGCGTCATTACA-1"
  [57] "QY_2576:TCCACAATCGGCTATC-1" "QY_2576:CCTATTTGTATTCAGC-1"
  [59] "QY_2576:CTTGATGTCGCAATCC-1" "QY_2576:TTACTTGCATAGCATG-1"
  [61] "QY_2576:CAATTGCGTAGCTTAC-1" "QY_2576:GTCGTTATCGCAATCC-1"
  [63] "QY_2576:ATGTAAGTCTAGCCTA-1" "QY_2576:ATGTAAGTCCTAAATC-1"
  [65] "QY_2576:CGATATGCATGGCTAA-1" "QY_2576:ATCACTAGTTGTCATA-1"
  [67] "QY_2576:GATTGAATCCAGGATG-1" "QY_2576:TTCAAGCGTTTACCAA-1"
  [69] "QY_2576:GGACATAGTTTGCTCC-1" "QY_2576:CTTATTGCAGCATTAG-1"
  [71] "QY_2576:TAACTTGGTAGGTGAC-1" "QY_2576:CGAATCTGTTTCTCAT-1"
  [73] "QY_2576:CAAGTGAGTAGTTGGA-1" "QY_2576:CGCACTAGTGCTTCGA-1"
  [75] "QY_2576:CAACAACAGCATCTAT-1" "QY_2576:CGATTGCTCTAAGTCT-1"
  [77] "QY_2576:CTAGCTATCGATATGA-1" "QY_2576:CTTACTTGTGCAAGTA-1"
  [79] "QY_2576:AAGCTCGAGTACTGGG-1" "QY_2576:ACGTATTTCCTTCGGG-1"
  [81] "QY_2576:ATAATGGTCCTTGAGC-1" "QY_2576:CATTACCCAGGAGGAC-1"
  [83] "QY_2576:AATCCTTAGAGGCTAT-1" "QY_2576:ATGCACCTCGGTAATA-1"
  [85] "QY_2576:ACCGGTTTCGGTAATA-1" "QY_2576:CATTGACGTCCTTAGG-1"
  [87] "QY_2576:CAGAGGGAGTGCGGTA-1" "QY_2576:AGGAATCTCCAGCTCG-1"
  [89] "QY_2576:CTAACGACATCCTCCT-1" "QY_2576:ATTAGGATCCCTGTGG-1"
  [91] "QY_2576:ACAAAGGAGCCATAAA-1" "QY_2576:TGAATCTTCAATAGCA-1"
  [93] "QY_2576:AGAATCTCAGGTATAT-1" "QY_2576:TCGCTAGGTACCGGCT-1"
  [95] "QY_2576:CCCGCAATCAAGCTCC-1" "QY_2576:ATCGCGAAGGCAATCG-1"
  [97] "QY_2576:GTTAGGAGTCCGGTTA-1" "QY_2576:GTTAGGAGTCGCATAT-1"
  [99] "QY_2576:CAAATCAAGCAGCTCT-1" "QY_2576:TTAAGCGCACCAGCTC-1"
 [101] "QY_2576:GAGCTTGAGCTAACGG-1" "QY_2576:CGTCACTAGCTTGTTG-1"
 [103] "QY_2576:AGTCATTTCAATCGTT-1" "QY_2576:GCCACTTAGGTCCGTT-1"
 [105] "QY_2576:TTGATCAGTGGACAAC-1" "QY_2576:GGAGCGAAGCAGGTAT-1"
 [107] "QY_2576:CAACAAGGTAAAGGTT-1" "QY_2576:TTAGGCCTCACATTAC-1"
 [109] "QY_2576:TTAGGCCTCATTAAGG-1" "QY_2576:ATTGTGTTCAAATACG-1"
 [111] "QY_2576:ACATTACTCAAGGTGT-1" "QY_2576:GGGTCACAGGACAACT-1"
 [113] "QY_2576:GACTCACTCCAGCTCG-1" "QY_2576:AAATGGACATATTGCC-1"
 [115] "QY_2576:AATTACCTCGATTCAT-1" "QY_2576:GAGCTTTGTGTCCTGA-1"
 [117] "QY_2576:AAAGCCAGTTGGCGGA-1" "QY_2576:AGATTGCAGGGCTTTC-1"
 [119] "QY_2576:AGGTTCTGTTTCTCAT-1" "QY_2576:CCCTCACTCACTAATC-1"
 [121] "QY_2576:ATTTCGCCAGTATGTG-1" "QY_2576:TCCCGAAGTGGCTTCA-1"
 [123] "QY_2576:CCTTAGTCATCATCAC-1" "QY_2576:ACGGTCAAGTGCTCCG-1"
 [125] "QY_2576:GTTTAGCGTTTGAGTC-1" "QY_2576:GTTTAGCGTGTGATTC-1"
 [127] "QY_2576:CCTCATGCAATATCCC-1" "QY_2576:GTAACGGTCTAAATCC-1"
 [129] "QY_2576:GACTGACCAGTATTGG-1" "QY_2576:GACTGACCAGGGAGTA-1"
 [131] "QY_2576:GTAATAGTCAAACCTT-1" "QY_2576:CAACATAAGCTTGAAA-1"
 [133] "QY_2576:TGGTCTATCAATATCC-1" "QY_2576:GGGCAACTCAGGAGGG-1"
 [135] "QY_2576:ATGAATCCATTATCTG-1" "QY_2576:GCAAGCTCATGATGGC-1"
 [137] "QY_2576:AGTAATCCAAATACCG-1" "QY_2576:AGTAATCCAACGGTAC-1"
 [139] "QY_2576:AGTAATCCAAATGCGC-1" "QY_2576:CGTTTGGGTAATCCAC-1"
 [141] "QY_2576:ATCCTAGTCTTGGACC-1" "QY_2576:GTTGAGGTCTTGCTCT-1"
 [143] "QY_2576:CTTGTGTCACTCGCTA-1" "QY_2576:GTAATCGCAGCAAGCT-1"
 [145] "QY_2576:AGATTGATCAAACATG-1" "QY_2576:CAGTCTATCACAATAG-1"
 [147] "QY_2576:GCGCTAAAGGTGCTTC-1" "QY_2576:GTAGCGGGTGCAACAA-1"
 [149] "QY_2576:CCCGATTAGGAGCAAA-1" "QY_2576:TTCGCAGGTTGCTTCC-1"
 [151] "QY_2576:GCTTCTAAGACTCCGT-1" "QY_2576:GATCCTGGTAAACCCT-1"
 [153] "QY_2576:TCAAGCGAGCCAATCC-1" "QY_2576:CGCTGGACATGCCTGC-1"
 [155] "QY_2576:ACACCGTTCTTGGACC-1" "QY_2576:GGTGGATGTCCAAATC-1"
 [157] "QY_2576:CATACCGGTAAGTGGC-1" "QY_2576:GTTCCTCGTCAGTAAG-1"
 [159] "QY_2576:GCAAATCAGCTAAATG-1" "QY_2576:TGGCCAGCAGGTGGAA-1"
 [161] "QY_2576:TACGCCTAGGGACTTG-1" "QY_2576:GCTGGACAGTCACACC-1"
 [163] "QY_2576:CCTTCTAGTTTATCCT-1" "QY_2576:GTCTAGCTCAAACTTC-1"
 [165] "QY_2576:TTGCCTGCATTCCTGG-1" "QY_2576:ATACTGTTCGCTTCGG-1"
 [167] "QY_2576:CGGCTTTAGTAACGTA-1" "QY_2576:GAGCACGGTTGTTCTT-1"
 [169] "QY_2576:GCAATCTGTGACCTTG-1" "QY_2576:TGGCATGAGCTGGCAA-1"
 [171] "QY_2576:TCGCGCTCATCAGTAG-1" "QY_2576:CCATAAGCAAGGCTTA-1"
 [173] "QY_2576:AGAGGAATCCAACCTA-1" "QY_2576:TCTGGCTAGATAACCA-1"
 [175] "QY_2576:AAGTGGCGTTAGTGCT-1" "QY_2576:TTACACCCATCCTGCA-1"
 [177] "QY_2576:TAAGACCAGCGAGTTG-1" "QY_2576:CTAGGATAGTTGCAAA-1"
 [179] "QY_2576:AAAGGGATCCTGATAT-1" "QY_2576:CTTATCTGTTAGTACC-1"
 [181] "QY_2576:CTTATCTGTGCGGTAG-1" "QY_2576:TTTGCTGAGGGAGTAA-1"
 [183] "QY_2576:CTCCACCTCATGTTGT-1" "QY_2576:CTACAACGTGCTTTAA-1"
 [185] "QY_2576:TCCGGTTAGCTGGCAA-1" "QY_2576:TAGTTACTCCCACCTC-1"
 [187] "QY_2576:GTAGCTGAGCAGGTTG-1" "QY_2576:TGTGAGTAGAATCGAC-1"
 [189] "QY_2576:CAAGGTCCAAGCTCAA-1" "QY_2576:CAAGGTCCACGCTAGG-1"
 [191] "QY_2576:AGCTCAACATAGCTAG-1" "QY_2576:TCTGTGATCTCTCGCC-1"
 [193] "QY_2576:TGCTCACAGGAGTATC-1" "QY_2576:CGCCTTTGTTGGCGGA-1"
 [195] "QY_2576:CATTTGCCAATGTCAG-1" "QY_2576:TATGGCTGTTTGCTCC-1"
 [197] "QY_2576:AGTCCTTCAATAGCAT-1" "QY_2576:CTTATGTAGTCAAGAC-1"
 [199] "QY_2576:GTGTGTGAGCAAGTGT-1" "QY_2576:CGTTTCGCAACCGCTC-1"
 [201] "QY_2576:GCTTTGGGTATCGCTG-1" "QY_2576:TCGGTTATCTCACTTC-1"
 [203] "QY_2576:CTTAGTTAGCAAATTG-1" "QY_2576:ACGTAATCACCGTTAT-1"
 [205] "QY_2576:CGAATTAAGTCCTGCG-1" "QY_2576:GATCCTTCACAAACGC-1"
 [207] "QY_2576:GATCCTTCATGCCTGC-1" "QY_2576:TGTAAACCATCAATCC-1"
 [209] "QY_2576:CCCAACTAGGAACCTG-1" "QY_2576:CGATGAAGTCCCGGAT-1"
 [211] "QY_2576:GGTGATTAGGCTAAAC-1" "QY_2576:AAACCAGGTTTCCGGA-1"
 [213] "QY_2576:AACACTAAGCGGGAAG-1" "QY_2576:GTTAACCGTGGACAAC-1"
 [215] "QY_2576:GGGCTTAAGGCACGTA-1" "QY_2576:CGCGATTTCTTGACCA-1"
 [217] "QY_2576:ATTGTCAGTCTAATCA-1" "QY_2576:CATAGGTAGCACTAAA-1"
 [219] "QY_2576:TGCAGGATCAGGGCTA-1" "QY_2576:GAGGAAGGTTAGCTCG-1"
 [221] "QY_2576:GGCTATGAGCATTATC-1" "QY_2576:GGCTATGAGGTAGCTG-1"
 [223] "QY_2576:GCATCACTCGCTATGC-1" "QY_2576:TAGGATCAGTGTCCAC-1"
 [225] "QY_2576:ACTAACCGTTGTGCGC-1" "QY_2576:AGAGGAGGTTGCGCGT-1"
 [227] "QY_2576:AAGGGCCTCTTTGGTG-1" "QY_2576:CAATGAATCAAGGGTT-1"
 [229] "QY_2576:CGATCATGTTGCAATC-1" "QY_2576:CGATCATGTCCTGACA-1"
 [231] "QY_2576:TCATGCCAGGAGCCGT-1" "QY_2576:ATCAGCACAGCCAGTG-1"
 [233] "QY_2576:TTGCATCCAAATCCCT-1" "QY_2576:TAAGCCACACTAAGGC-1"
 [235] "QY_2576:CCGTAAACAATCATGG-1" "QY_2576:GTGGCTAAGCACAGCA-1"
 [237] "QY_2576:CTGTCCACATTGTCCG-1" "QY_2576:GTCTTTGAGGCTAATA-1"
 [239] "QY_2576:GGTAATGGTTGGGCCT-1" "QY_2576:AAAGCCTAGCTTCCTT-1"
 [241] "QY_2576:ACCAACCTCTGTTGGC-1" "QY_2576:TGTCTTGAGCACTAAA-1"
 [243] "QY_2576:ATGGCTACAGGCCTAG-1" "QY_2576:TCCGGGACACCACAAA-1"
 [245] "QY_2576:CATAACTTCATGGTCC-1" "QY_2576:AGGACTTAGAACCTGG-1"
 [247] "QY_2576:AGTTTCTAGGCTAAAC-1" "QY_2576:AGTTTCTAGGAGCAGG-1"
 [249] "QY_2576:AGTTTCTAGGTGGAAA-1" "QY_2576:TCTATTGCATAACCGA-1"
 [251] "QY_2576:TACCTGATCACAATAG-1" "QY_2576:ACAGCACCAAGTGGCT-1"
 [253] "QY_2576:CTGACAACACATTGTC-1" "QY_2576:CCGCCAATCCTGTTAG-1"
 [255] "QY_2576:ATAGCAATCAACAACA-1" "QY_2576:TAAGGATGTGGTTAAG-1"
 [257] "QY_2576:AAATCGATCGATATAG-1" "QY_2576:CCTCAAATCACAAAGC-1"
 [259] "QY_2576:CACGTTATCCCAATTG-1" "QY_2576:TGTGGCGCAATCGTGA-1"
 [261] "QY_2576:AGTAATGTCAGGAGCC-1" "QY_2576:GCCTCACCAAATAGCT-1"
 [263] "QY_2576:GGTTAACAGCTCATTG-1" "QY_2576:ATTGCCGGTCCTTAGG-1"
 [265] "QY_2576:CATTGCCAGGTGGGAG-1" "QY_2576:AGTATTGAGCTCAAGG-1"
 [267] "QY_2576:GAAACATGTCCTGACA-1" "QY_2576:CAAGTAATCCAGGTGA-1"
 [269] "QY_2576:TTACTCACAATCGCCC-1" "QY_2576:ACATTGTTCCACTATG-1"
 [271] "QY_2576:TACGGATAGGCGCGAT-1" "QY_2576:TGTCAATTCCGCACCA-1"
 [273] "QY_2576:GTTTGGTGTTATTGTG-1" "QY_2578:CAGTTTCCAACGGTTA-1"
 [275] "QY_2578:TCCTCAGCAATTGACG-1" "QY_2578:GAACGGTGTGAAACAT-1"
 [277] "QY_2578:CAACTACGTGTCCACA-1" "QY_2578:AGCACCTTCAAACCTT-1"
 [279] "QY_2578:TTGCCTTTCTCAGCTA-1" "QY_2578:GCTTCAATCATTTGGT-1"
 [281] "QY_2578:TCTAGCCAGAGCCGGT-1" "QY_2578:AACGGTGTCGCTTGAC-1"
 [283] "QY_2578:TGAAGGAAGGCGTAAT-1" "QY_2578:CGCTAAACAAGGAATA-1"
 [285] "QY_2578:GCTTAGTGTTACAACC-1" "QY_2578:GGATCAGTCATGTTGT-1"
 [287] "QY_2578:GGATCAGTCTCTCGCC-1" "QY_2578:ACTCAGGAGGACGAAA-1"
 [289] "QY_2578:TAGTGAGGTGGTTAGA-1" "QY_2578:TTGATGAAGAACCTAA-1"
 [291] "QY_2578:CGTAAACAGGGTGGGA-1" "QY_2578:TGCTCCACAGGATGTC-1"
 [293] "QY_2578:TGCTCCACACCAGCTC-1" "QY_2578:ACCTTGCAGCTTGAAA-1"
 [295] "QY_2578:GGAACTTAGCGCTCCA-1" "QY_2578:CGAGCGAGTATTACTG-1"
 [297] "QY_2578:CGAGCGAGTCATAGAG-1" "QY_2578:CTGCAATGTAGCTAAG-1"
 [299] "QY_2578:CTGCAATGTTTAGCGT-1" "QY_2578:CGCAGGTAGGCTTGTC-1"
 [301] "QY_2578:ATGCTAAAGTTGCAAA-1" "QY_2578:GGCTGAGGTTAGGCTT-1"
 [303] "QY_2578:ACAGTGAGTTAGGCTT-1" "QY_2578:ACCATATTCGTTAGCC-1"
 [305] "QY_2578:CAGGATAGTATTTACG-1" "QY_2578:CAGGATAGTGAACGGT-1"
 [307] "QY_2578:CATAATCTCTAAGTCT-1" "QY_2578:TGCCTCACAAACATGT-1"
 [309] "QY_2578:AATTGGATCGCACACT-1" "QY_2578:TCGAAGTAGATTGAGC-1"
 [311] "QY_2578:TGAGGTCCAAGCCTGG-1" "QY_2578:TACCCGGTCTTGTCGA-1"
 [313] "QY_2578:CATTATGGTTCTGGCA-1" "QY_2578:GCTACCTAGCATCCTA-1"
 [315] "QY_2578:GGAGCAACATTGTCTA-1" "QY_2578:GTGTGCAAGGGTTAAC-1"
 [317] "QY_2578:TCTAGCTCAGAAATGA-1" "QY_2578:GCATTTAGTGCAGTAA-1"
 [319] "QY_2578:GATTGATCAGTGAACC-1" "QY_2578:CGGTAATAGTCCTGCG-1"
 [321] "QY_2578:GCCTTCCTCGCGTTAC-1" "QY_2578:GGACCAGGTGTCCGGT-1"
 [323] "QY_2578:GACTAAGGTTGTTGTA-1" "QY_2578:GACTAAGGTGCAACGG-1"
 [325] "QY_2578:GACTAAGGTGTAATGG-1" "QY_2578:ATTAGTGAGGCTATAA-1"
 [327] "QY_2578:GCTTAACGTTGCTCAG-1" "QY_2578:CGGTTTATCATTTGGT-1"
 [329] "QY_2578:GCAACATAGCTATCGC-1" "QY_2578:AAACTAGTCCACAATT-1"
 [331] "QY_2578:TACCGGCGTCCTCCAT-1" "QY_2578:GTCCTTGCATAATGCG-1"
 [333] "QY_2578:GTCCTTGCATTGTCCG-1" "QY_2578:GGTGTGCAGGTTGGAT-1"
 [335] "QY_2578:CAATGAGGTCCTCCAT-1" "QY_2578:GTATCCGGTAACAGGC-1"
 [337] "QY_2578:CCACTAATCGCGAAGC-1" "QY_2578:CTTATTGCAGGTTCCC-1"
 [339] "QY_2578:GCCTACTAGAGGAACA-1" "QY_2578:TAACTTGGTCCAGCAC-1"
 [341] "QY_2578:TGGCTAGAGATAGACC-1" "QY_2578:TGGCTAGAGCCATAAA-1"
 [343] "QY_2578:CGAATCTGTTGTTGTA-1" "QY_2578:CGAATCTGTGAGACTA-1"
 [345] "QY_2578:CGGCTCTCAAGCCTGG-1" "QY_2578:CCAACCGTCTTTAGCG-1"
 [347] "QY_2578:GAAGCCATCCGCACCA-1" "QY_2578:AAGCTCGAGCAAGGAA-1"
 [349] "QY_2578:GTCATTTAGCGCTTGT-1" "QY_2578:GACCAGGGTGGGTAAC-1"
 [351] "QY_2578:CACCGTTAGTTGCAGG-1" "QY_2578:TGGTGAGTCAGGTTGG-1"
 [353] "QY_2578:TAGCTACGTTATGGAG-1" "QY_2578:GTTTGCATCCAATTAC-1"
 [355] "QY_2578:GTTGAATCACAACATG-1" "QY_2578:ATTTGCAGTTTCTAAG-1"
 [357] "QY_2578:GGTTAAGGTAAATAGC-1" "QY_2578:GCCCAGTGTGAGCATA-1"
 [359] "QY_2578:GTCGGTTTCCCACCCT-1" "QY_2578:CCCTAATCACGTAGGT-1"
 [361] "QY_2578:TATTCAGGTAGACAAT-1" "QY_2578:TATTCAGGTTAACCAC-1"
 [363] "QY_2578:GAGAGGAGTGAGTTTC-1" "QY_2578:GATCAATCAAGGAATA-1"
 [365] "QY_2578:GGCAATTAGTTACCGC-1" "QY_2578:CAAAGGCGTTGTCAGT-1"
 [367] "QY_2578:TAAACCCGTTGAGTCT-1" "QY_2578:GTTCAAGCAACCGTAA-1"
 [369] "QY_2578:AAACGGTTCTTGTTCC-1" "QY_2578:GCTCGTTAGGCTAAAC-1"
 [371] "QY_2578:GCTCGTTAGAATCACA-1" "QY_2578:AAAGGCAAGTGCTCAC-1"
 [373] "QY_2578:TCCTTTGGTATTCGGT-1" "QY_2578:GGAGCGAAGAGGAATG-1"
 [375] "QY_2578:GCACACAAGGTATAGC-1" "QY_2578:AACTAACCATCAGGAC-1"
 [377] "QY_2578:GGCAACATCCCAATAT-1" "QY_2578:CGTATTGTCTTCAAGT-1"
 [379] "QY_2578:GAGGTCCAGGAGCCGT-1" "QY_2578:TTGGCCAGTGTCACGC-1"
 [381] "QY_2578:CCTCATGCAGTGAGAG-1" "QY_2578:TCCTTGAAGTTTGTCG-1"
 [383] "QY_2578:ACAAGGTTCGCTCAGT-1" "QY_2578:TTCGGTCAGGCAGGTC-1"
 [385] "QY_2578:AAGCCTCTCAAGGTCG-1" "QY_2578:ACACAATCACCTGGTC-1"
 [387] "QY_2578:ACCCTTAAGACTTAGA-1" "QY_2578:CAGTTTGTCCCACCTC-1"
 [389] "QY_2578:CAAGGTTAGACAGGTT-1" "QY_2578:CAAGGTTAGCTTAGAA-1"
 [391] "QY_2578:TCGATATTCATAACCT-1" "QY_2578:ACGGTTTGTAGAGGGA-1"
 [393] "QY_2578:AGGTCAAGTACGGTTT-1" "QY_2578:CGTTTGGGTTAAACGG-1"
 [395] "QY_2578:TATAGTGAGTCATCAT-1" "QY_2578:CAGTCTATCAATAGGC-1"
 [397] "QY_2578:AAGCGCTCACGCGCAA-1" "QY_2578:CCAAAGGTCAATAGCA-1"
 [399] "QY_2578:CTTCCTCCACTTAGCT-1" "QY_2578:CTTCCTCCAAAGGACG-1"
 [401] "QY_2578:GACAAGCGTGCCGGAA-1" "QY_2578:CGCAATTGTGAGTAGC-1"
 [403] "QY_2578:TGAGCAAGTTCCTGGA-1" "QY_2578:AGTAACTCACAATAAC-1"
 [405] "QY_2578:ACATTGCGTCCTTAGG-1" "QY_2578:AATATCGAGGGAGTAA-1"
 [407] "QY_2578:AATATCGAGGGTGGGA-1" "QY_2578:GTCAAGCCAGGTTGTA-1"
 [409] "QY_2578:GGTAAGCGTGAATCGA-1" "QY_2578:TCGCAGGCAGGTTACA-1"
 [411] "QY_2578:ATGCTTAGTACTGGCC-1" "QY_2578:CTTGGTCAGTCCTTAG-1"
 [413] "QY_2578:TGGCCAGCAGGAATAA-1" "QY_2578:TGGCCAGCACATGCCC-1"
 [415] "QY_2578:TACGCCTAGACTTAGA-1" "QY_2578:GAATCGCCAGGTGAGA-1"
 [417] "QY_2578:CACATAGCAACCTCGC-1" "QY_2578:GAGCATGTCAAGGTCG-1"
 [419] "QY_2578:TTGCCTGCAACCAAAT-1" "QY_2578:AAGTTTGAGCATATAG-1"
 [421] "QY_2578:GCAATTAAGTCCTGCG-1" "QY_2578:AAGACTCAGTTTACGT-1"
 [423] "QY_2578:GAGGTGGAGAAAGGCA-1" "QY_2578:ATTCCGGGTGGTTAGA-1"
 [425] "QY_2578:CCTCATTTCATAACCT-1" "QY_2578:CACTGTCAGTTACTAC-1"
 [427] "QY_2578:AACTGGCCATCAGTAG-1" "QY_2578:CTTATGAGTCCTCACT-1"
 [429] "QY_2578:GTATAGCAGATTCAAG-1" "QY_2578:CCATAAGCAACAACAT-1"
 [431] "QY_2578:AAGCGGGAGTTACGAA-1" "QY_2578:ATTTGTGGTCACACTG-1"
 [433] "QY_2578:ATCCGCTAGTTAGGAC-1" "QY_2578:ATCCGCTAGGGTTATA-1"
 [435] "QY_2578:CTACCTAAGGCACTAG-1" "QY_2578:ATTATGGAGCAATACA-1"
 [437] "QY_2578:CCGCCTAAGTTATGGA-1" "QY_2578:CCGCCTAAGAGCAATC-1"
 [439] "QY_2578:CTTTCATGTTATCCGG-1" "QY_2578:ACATGCCTCAACAACA-1"
 [441] "QY_2578:CTAGGATAGAGCTGCA-1" "QY_2578:GTAATTGAGCGAGTTG-1"
 [443] "QY_2578:GTAATTGAGGTTGTAA-1" "QY_2578:TACATACTCCTAATGT-1"
 [445] "QY_2578:GATTAGCAGGTCATGG-1" "QY_2578:GATTAGCAGTTACGTT-1"
 [447] "QY_2578:ATATTGCTCCTAATGT-1" "QY_2578:TAAGTCAAGCTTAAAG-1"
 [449] "QY_2578:GTAGCTGAGGGTCTAG-1" "QY_2578:CTATTGCCAACAACAT-1"
 [451] "QY_2578:TGTGAGTAGAGCAATC-1" "QY_2578:CAAGGTCCAGTGTGAC-1"
 [453] "QY_2578:AAGCTAATCGATTAAG-1" "QY_2578:TCGCTAATCCGCACCA-1"
 [455] "QY_2578:TCGCTAATCACGGATG-1" "QY_2578:GTTAGCTGTAGTCCTG-1"
 [457] "QY_2578:TTAACCTAGGATTATG-1" "QY_2578:TTAACCTAGGTAAGTC-1"
 [459] "QY_2578:TTCCGCCTCACACAAA-1" "QY_2578:TGCATGACATATGGTG-1"
 [461] "QY_2578:GGTTATCGTACACCGC-1" "QY_2578:GCATGAAGTGGACATA-1"
 [463] "QY_2578:GTGTGTGAGGAGTCGC-1" "QY_2578:GTGGGAACACGCCCAT-1"
 [465] "QY_2578:TAGCTTTAGTTAACGA-1" "QY_2578:AGTTACGCATTGTGGA-1"
 [467] "QY_2578:TAGTTAGAGGTTATAG-1" "QY_2578:CCAAGTGAGGCTCAAG-1"
 [469] "QY_2578:GTATTCGTCTTGGACC-1" "QY_2578:GCGCTACGTTATATCG-1"
 [471] "QY_2578:TGCTGGTTCTGTCAGC-1" "QY_2578:TCCGTGAGTTCGGTAT-1"
 [473] "QY_2578:ACGGTAAGTAGTTACC-1" "QY_2578:TATGGACAGCAGCCAA-1"
 [475] "QY_2578:CGCGATTTCCAATACT-1" "QY_2578:CCTCGCTTCCAACCTA-1"
 [477] "QY_2578:ACCTTAGTCGTCCTAA-1" "QY_2578:ACGCTAACAATAGAAG-1"
 [479] "QY_2578:GAAACGCGTGACCTTG-1" "QY_2578:ACGCATGAGCATCCTA-1"
 [481] "QY_2578:ACCTAAGCAACAGAGG-1" "QY_2578:AATCACTTCAAACCGG-1"
 [483] "QY_2578:CTAAGTGCAAGGGCTT-1" "QY_2578:GCCACCTCACTAGTAG-1"
 [485] "QY_2578:TGACCTGGTCAGGCTC-1" "QY_2578:TAATTCGGTGAGTCCC-1"
 [487] "QY_2578:GATTGCACAAGCTATG-1" "QY_2578:GTCATCATCAGGAGCC-1"
 [489] "QY_2578:ATGCGATAGCCTTGCG-1" "QY_2578:TGGTTAAAGAACCTGG-1"
 [491] "QY_2578:CATGCCAGTCATTATG-1" "QY_2578:TTTAGGCGTTATGTTG-1"
 [493] "QY_2578:TTGTTGTAGTATTGGA-1" "QY_2578:CATATAGAGTTATGGA-1"
 [495] "QY_2578:CATTAGCGTCATCACG-1" "QY_2578:TGTTTGTAGAACAAGG-1"
 [497] "QY_2578:TGTTTGTAGCACTAAA-1" "QY_2578:CTCATTGAGATGCAAC-1"
 [499] "QY_2578:GATAAAGCAAGGCCTG-1" "QY_2578:AAAGCGAAGGAGGTAA-1"
 [501] "QY_2578:TAAGCCACATCCTGCA-1" "QY_2578:CCTTTATGTAGGCGCA-1"
 [503] "QY_2578:TCCTCCATCGCTATGC-1" "QY_2578:CTGTCCACAACAAAGA-1"
 [505] "QY_2578:CGTGATGAGTATAGTG-1" "QY_2578:TAAGTCGCAGGAGGTA-1"
 [507] "QY_2578:GACTGAGTCGATTCAT-1" "QY_2578:TCTGGATGTTGAAGCA-1"
 [509] "QY_2578:GAACTAATCAGCGGGT-1" "QY_2578:TGTCTTGAGCTCATTG-1"
 [511] "QY_2578:CCAAAGCCAGCTAACA-1" "QY_2578:GGATTGAGTAACGTGA-1"
 [513] "QY_2578:TGTCCTTTCTTGACCA-1" "QY_2578:AACATCAAGCCGCTAT-1"
 [515] "QY_2578:GCCAAACCATAGGTGC-1" "QY_2578:GGTTTGCTCGGGATGC-1"
 [517] "QY_2578:CTCAGCTAGGTTGGTG-1" "QY_2578:ATGGGCATCTAGGAAC-1"
 [519] "QY_2578:CGAGTAAGTTGTTTGA-1" "QY_2578:GTCATAAAGTTTCTGG-1"
 [521] "QY_2578:GGTCAACCAGGAATAA-1" "QY_2578:TCTCACTTCAAGGTTA-1"
 [523] "QY_2578:GAAGCTAGTTCTTTGT-1" "QY_2578:ACCCTGGTCCAAGTGG-1"
 [525] "QY_2578:CCAGTTTCACACAAGC-1" "QY_2578:AAAGGCGCAGGTTGCG-1"
 [527] "QY_2578:CGCAATGAGGGTTATA-1" "QY_2578:GGTGAAGCAAGCTCAA-1"
 [529] "QY_2578:TACCTCAAGCGCTACT-1" "QY_2578:CGCCTAAGTCAGTAAG-1"
 [531] "QY_2578:TGCAATCGTTACAGCT-1" "QY_2578:TACGGATAGTTTCTGG-1"
 [533] "QY_2584:CATTTAGGTCAGTGCC-1" "QY_2584:CTTTATCGTCCAAATC-1"
 [535] "QY_2584:GAACGGTGTTGGGCCT-1" "QY_2584:TAGTGTGCATGTTGGA-1"
 [537] "QY_2584:CTATTACAGCATCTAT-1" "QY_2584:CAGCATGAGACAGGTT-1"
 [539] "QY_2584:GGCCTTCCAAGTGGCT-1" "QY_2584:CGCTAAACAAGCGCAT-1"
 [541] "QY_2584:CTGAGTCTCAGTATAG-1" "QY_2584:AAGCTTGCATCCCAAT-1"
 [543] "QY_2584:CGTAAAGGTTGTCATA-1" "QY_2584:TAGTGAGGTGCAATAG-1"
 [545] "QY_2584:CGTAAACAGCGATGCA-1" "QY_2584:AGGGAGTAGCTAGTTT-1"
 [547] "QY_2584:TTGGTTAGTTGTCAGT-1" "QY_2584:CTCCAAATCATCACAT-1"
 [549] "QY_2584:GGTTCCTAGACAAGCT-1" "QY_2584:GGAACTTAGCGCAACA-1"
 [551] "QY_2584:CCCATAATCCAAACTT-1" "QY_2584:GAAGTATGTTAAGTGG-1"
 [553] "QY_2584:TAGGGTTAGTGCTCCG-1" "QY_2584:CAAGCCTTCATAGCCC-1"
 [555] "QY_2584:CAAGTCCTCCAACCTA-1" "QY_2584:GATGAGGCATAGCTAG-1"
 [557] "QY_2584:GAACAATGTACTTATG-1" "QY_2584:ATGTTGTTCAGTGAAC-1"
 [559] "QY_2584:CGATTTAGTAAGTGCA-1" "QY_2584:CATTATGGTTGGTTTA-1"
 [561] "QY_2584:ACGTTTCCAAGGGCTT-1" "QY_2584:GCTATTAGTCGATTAC-1"
 [563] "QY_2584:TCACTCGCAATTGACG-1" "QY_2584:CTACTGATCTAATCCG-1"
 [565] "QY_2584:TCTAGCTCATAGCTTC-1" "QY_2584:GTGGACCAGGTATAGC-1"
 [567] "QY_2584:CGGTAATAGAACCTGG-1" "QY_2584:CTGTTCAAGCTTAGGG-1"
 [569] "QY_2584:AACGGATTCATTAAGG-1" "QY_2584:AATTCGTTCAAGGTGT-1"
 [571] "QY_2584:GGCAATCCAAGCTATG-1" "QY_2584:AGCGCCTGTAGACTAG-1"
 [573] "QY_2584:GAAGCACGTTCAATTG-1" "QY_2584:TCCAAGACATCCTGTG-1"
 [575] "QY_2584:CGATATGCATACTGAG-1" "QY_2584:GCTTTAAGTGTCCGGT-1"
 [577] "QY_2584:TAGTACGCAAGGTATT-1" "QY_2584:TATGATGAGGCAACAT-1"
 [579] "QY_2584:TGGCTAGAGAGCTGGC-1" "QY_2584:CAATTACTCAAACCTT-1"
 [581] "QY_2584:AGGCTTGAGAAGGGTA-1" "QY_2584:CGTGAACCAACCCTTG-1"
 [583] "QY_2584:TAGCAGCCAGGTTTGA-1" "QY_2584:TCTTGGATCATTATGC-1"
 [585] "QY_2584:GGTTGTTGTGATCCTG-1" "QY_2584:CACTTGCAGATTCCTG-1"
 [587] "QY_2584:GTCTATGTCCACCTGG-1" "QY_2584:GGTTTGACATGCTTTA-1"
 [589] "QY_2584:CGCTAACTCCACAATT-1" "QY_2584:TGACATGCAGGTTACA-1"
 [591] "QY_2584:CTAACGACAGAAATGA-1" "QY_2584:TAGCGGTCAGGAATAA-1"
 [593] "QY_2584:TACCTAAGTCGCAATT-1" "QY_2584:CGAGGAACAATTGACG-1"
 [595] "QY_2584:CAAACCTGTGCACAAA-1" "QY_2584:GGGCCATAGCTATATC-1"
 [597] "QY_2584:GAGCTTGAGGATGCGC-1" "QY_2584:TCCCATAAGTTAGCTT-1"
 [599] "QY_2584:TTGTGGCTCAAGGGTT-1" "QY_2584:CAACAAGGTAAAGCAT-1"
 [601] "QY_2584:CGGTCCATCTTGCATG-1" "QY_2584:CGTATTGTCAAGGTGT-1"
 [603] "QY_2584:ATTGCCTCATGCTTTA-1" "QY_2584:AGATTGCAGGGTGGGA-1"
 [605] "QY_2584:AGGCATTAGTGTGGTG-1" "QY_2584:CCTCATGCAGGATGGA-1"
 [607] "QY_2584:TTCGGTCAGTGCTGAG-1" "QY_2584:CCTTCCTCAATAAAGG-1"
 [609] "QY_2584:ACACAATCATCCTAGT-1" "QY_2584:TCGATATTCTATATGC-1"
 [611] "QY_2584:ACGGTTTGTATTTGGC-1" "QY_2584:AGCGCTAAGCCGGTAA-1"
 [613] "QY_2584:TTTAGCTAGGATCCAG-1" "QY_2584:GACTTTGTCTTCAAGT-1"

QY_2577:AACCTCCTCATCGTTT-1 QY_2577:AACGCTAGTGGATGTC-1
                         B                          B
QY_2577:AACTACTCACGAATCC-1 QY_2577:AAGAACAGTACCTTAC-1
                         B                          B
QY_2577:AAGCAAGTCGAGCAAA-1 QY_2577:AAGCTTGGTGCTGGTG-1
                         B                          B
QY_2577:AATCCATCAGCTAACC-1 QY_2577:AATCGCCCATAAACCT-1
                         B                          B
QY_2577:AATGTCCAGGGACGCA-1 QY_2577:ACACTAATCACACAGT-1
                         B                          B
QY_2577:ACAGGTAAGGAGTCGG-1 QY_2577:ACAGTATGTCCTTCAG-1
                         B                          B
QY_2577:ACATTAGTCGAGCAAA-1 QY_2577:ACCAGGACAGAACCGA-1
                         B                          B
QY_2577:ACCAGGGAGAGGCTAA-1 QY_2577:ACCTAAATCAACAAGG-1
                         B                          B
QY_2577:ACCTAAATCCGCCTCA-1 QY_2577:ACCTCACTCAGTTCCC-1
                         B                          B
QY_2577:ACGAATCTCACTCAAA-1 QY_2577:ACGCAAGCACCTCGCT-1
                         B                          B
QY_2577:ACGCCACAGCTGTCAG-1 QY_2577:ACGGTACGTTCACCCA-1
                         B                          B
QY_2577:ACGTCAAGTTAGGCGT-1 QY_2577:ACGTCCAAGCAATAGG-1
                         B                          B
QY_2577:ACTAACTCACGAACAG-1 QY_2577:ACTAGGCGTCTAACCT-1
                         B                          B
QY_2577:ACTCACTGTTCATCTA-1 QY_2577:ACTTATGAGCACAGCC-1
                         B                          B
QY_2577:AGAGAAGCATGTCAAT-1 QY_2577:AGATGCTTCCAGCACA-1
                         B                          B
QY_2577:AGCACAGCAATGCCCG-1 QY_2577:AGCGCCTAGATGGAGC-1
                         B                          B
QY_2577:AGCTAAACACCAACCG-1 QY_2577:AGCTTAATCAGGAACA-1
                         B                          B
QY_2577:AGCTTTAAGGCCTGGT-1 QY_2577:AGGATTGAGTATTGTG-1
                         B                          B
QY_2577:AGGCCCAGTCAATACG-1 QY_2577:AGGCTAGCAAGGTGGC-1
                         B                          B
QY_2577:AGGGCCTTCCTAGTTT-1 QY_2577:AGGTCAAAGCGCTCAA-1
                         B                          B
QY_2577:AGTCCTTGTTTGTTGC-1 QY_2577:AGTGCACGTCAATGTG-1
                         B                          B
QY_2577:AGTGCACGTGCATTAG-1 QY_2577:AGTGCGGAGGAGTCGG-1
                         B                          B
QY_2577:AGTGGACAGTTAGCTA-1 QY_2577:ATATGTCCAGCATGTC-1
                         B                          B
QY_2577:ATCACTAAGATGGAGC-1 QY_2577:ATCCGTGAGCCTGTTC-1
                         B                          B
QY_2577:ATCGGCCAGGTGTCCA-1 QY_2577:ATCTTTGGTCCTAAGA-1
                         B                          B
QY_2577:ATGCAAACACGGTTTA-1 QY_2577:ATGCCTGAGGTTAGAG-1
                         B                          B
QY_2577:ATGGCCGGTTTGGGTA-1 QY_2577:ATGGTTATCCTGATTT-1
                         B                          B
QY_2577:ATGTTCAAGGACACTT-1 QY_2577:ATGTTGTCATTAAAGG-1
                         B                          B
QY_2577:ATGTTTGAGCACGTTG-1 QY_2577:ATTAACCCACAGAACG-1
                         B                          B
QY_2577:ATTACTGAGGTGTTAC-1 QY_2577:ATTAGCGGTGTAACCA-1
                         B                          B
QY_2577:ATTCAACCAACCTAAT-1 QY_2577:ATTCATGAGGTGTTAC-1
                         B                          B
QY_2577:ATTGGCTAGGAAGCAC-1 QY_2577:ATTGGCTAGGAGCAAC-1
                         B                          B
QY_2577:ATTGTCCGTGCATCGG-1 QY_2577:CAAAGCGCAATTATGC-1
                         B                          B
QY_2577:CAAAGTGAGGAACGCG-1 QY_2577:CAACAGGCACTAAATC-1
                         B                          B
QY_2577:CAACCCGCACAGGATG-1 QY_2577:CAAGCTAGTGGCTTCC-1
                         B                          B
QY_2577:CAAGTAACAAACGGGC-1 QY_2577:CAATCGCCACAATACT-1
                         B                          B
QY_2577:CAATGAACAGACAAAC-1 QY_2577:CAATGCCCATTGTGGC-1
                         B                          B
QY_2577:CACAATATCTACCTGC-1 QY_2577:CACATACAGTGCACGC-1
                         B                          B
QY_2577:CACATTAAGAAACTGG-1 QY_2577:CAGCAAGCATAATGTC-1
                         B                          B
QY_2577:CAGCATGTCTTGCAAA-1 QY_2577:CAGCTCAAGGCATTGT-1
                         B                          B
QY_2577:CAGGTCCAGGCTACTG-1 QY_2577:CATGGCGGTCACAAAT-1
                         B                          B
QY_2577:CATTCATTCACGCGGT-1 QY_2577:CCAAATCAGCTCAAAC-1
                         B                          B
QY_2577:CCAACATAGCTCAAAC-1 QY_2577:CCAGACTCATTGTCCT-1
                         B                          B
QY_2577:CCATATTTCTTGTCCA-1 QY_2577:CCCAAATAGTATTGCA-1
                         B                          B
QY_2577:CCCAATTGTTGTTGGA-1 QY_2577:CCCGTAAAGCTCATAA-1
                         B                          B
QY_2577:CCCGTTGTCGGTACGC-1 QY_2577:CCGGTTAAGGGCTTTG-1
                         B                          B
QY_2577:CCGTTATGTAGTCAAT-1 QY_2577:CCTAAATCACAGACTC-1
                         B                          B
QY_2577:CCTAAGTAGTCATTTC-1 QY_2577:CCTCCTCTCATGTTTC-1
                         B                          B
QY_2577:CCTGTAACACGTAAGG-1 QY_2577:CCTGTAACAGCAAGGC-1
                         B                          B
QY_2577:CCTTATGTCAAGTGAG-1 QY_2577:CCTTCAGGTGCATTTC-1
                         B                          B
QY_2577:CGAAGCCTCACAAGCT-1 QY_2577:CGCACAATCCCTTGCG-1
                         B                          B
QY_2577:CGCACACAGGTTAGAG-1 QY_2577:CGCATGATCCTAGTTT-1
                         B                          B
QY_2577:CGCTCAGCAGCGCTTG-1 QY_2577:CGCTCCATCATAACTG-1
                         B                          B
QY_2577:CGCTGTGCATAGACCC-1 QY_2577:CGGACCTAGGAGGACT-1
                         B                          B
QY_2577:CGGACCTAGTCATTAG-1 QY_2577:CGGAGCAAGGGCTTAT-1
                         B                          B
QY_2577:CGGATAAAGTTGTCTT-1 QY_2577:CGGCTAATCAATTACG-1
                         B                          B
QY_2577:CGGGTCTAGTATTGCA-1 QY_2577:CGTAATGGTAGGATTT-1
                         B                          B
QY_2577:CGTGAGGAGAACAAGT-1 QY_2577:CTAACCACAATAGTCT-1
                         B                          B
QY_2577:CTAATCGCAGGCTAGA-1 QY_2577:CTAATCTTCAGGATGA-1
                         B                          B
QY_2577:CTAATGTCACAATACT-1 QY_2577:CTACAACAGCTTATGA-1
                         B                          B
QY_2577:CTACGAAGTGCAACTA-1 QY_2577:CTATAACCAAGCTACC-1
                         B                          B
QY_2577:CTATGAGGTAACCACA-1 QY_2577:CTATTACTCCTAGTAA-1
                         B                          B
QY_2577:CTCATGACAATTTGGT-1 QY_2577:CTCATGACATTGCGTA-1
                         B                          B
QY_2577:CTCGCTAGTGGGTACT-1 QY_2577:CTGGCTAAGGAGGTTA-1
                         B                          B
QY_2577:CTGGTTTGTATGGTGC-1 QY_2577:CTGGTTTGTCAATAGT-1
                         B                          B
QY_2577:CTGTTGGAGGCTTAGT-1 QY_2577:CTTATGTTCCTAATTC-1
                         B                          B
QY_2577:CTTCAGGAGCTGTACG-1 QY_2577:CTTGCTCAGACACCGC-1
                         B                          B
QY_2577:CTTTATGGTAGGTTAT-1 QY_2577:CTTTCTTGTAGTAAGA-1
                         B                          B
QY_2577:CTTTGGTGTGAATCGC-1 QY_2577:CTTTGGTGTTAGCTGA-1
                         B                          B
QY_2577:CTTTGGTGTTGTTGTC-1 QY_2577:CTTTGTCCAGCAACAG-1
                         B                          B
QY_2577:GAACACAAGCGCCTAA-1 QY_2577:GAACCAAAGGAAGTAT-1
                         B                          B
QY_2577:GAAGCCTGTACTTAGG-1 QY_2577:GAAGGATGTTTAGCTC-1
                         B                          B
QY_2577:GAAGTATAGTCCTGAG-1 QY_2577:GAAGTCAAGACTAAGG-1
                         B                          B
QY_2577:GAAGTGATCAAACCTA-1 QY_2577:GACAATACAGAGGGAG-1
                         B                          B
QY_2577:GACCTGATCATAGCCG-1 QY_2577:GACTATTCACTAAGTT-1
                         B                          B
QY_2577:GAGCAAATCCTTAGTT-1 QY_2577:GAGCTAGCAGGCAAGC-1
                         B                          B
QY_2577:GAGCTGCTCAGTGAAG-1 QY_2577:GAGGCAAGTTCCGGCT-1
                         B                          B
QY_2577:GATAACGAGCGCCTAA-1 QY_2577:GATCGCTCAATTAGCT-1
                         B                          B
QY_2577:GATGCGACACCCTCAC-1 QY_2577:GATTAAGCAGCACGTT-1
                         B                          B
QY_2577:GATTAGCTCCCGTTAC-1 QY_2577:GATTGATGTTGCACAA-1
                         B                          B
QY_2577:GATTGCGTCGTTACTT-1 QY_2577:GCAATGTTCCAAGTGT-1
                         B                          B
QY_2577:GCAGCAACATGTTTGG-1 QY_2577:GCAGGCAAGCATGTTA-1
                         B                          B
QY_2577:GCAGGTTGTCATGCCC-1 QY_2577:GCCAGGAAGTTTGGTA-1
                         B                          B
QY_2577:GCCATGATCAAACTCA-1 QY_2577:GCCTCGACAAACATAG-1
                         B                          B
QY_2577:GCCTTAACACTTACAG-1 QY_2577:GCGTTTCTCGCTAAGT-1
                         B                          B
QY_2577:GCTAAGCGTTACTTGC-1 QY_2577:GCTATAGGTTCATTTG-1
                         B                          B
QY_2577:GCTGACCAGGGCCACT-1 QY_2577:GCTGCAATCCTAAATG-1
                         B                          B
QY_2577:GCTGTACCACCGTTCC-1 QY_2577:GCTTCGCGTTTCCTCC-1
                         B                          B
QY_2577:GCTTTCATCAAATCGC-1 QY_2577:GGAAGTATCAATGAGG-1
                         B                          B
QY_2577:GGACTAAAGTGAAGTG-1 QY_2577:GGATAACCAGTCTAAT-1
                         B                          B
QY_2577:GGATAACCATTTGCTC-1 QY_2577:GGCAGGATCTAGCTTT-1
                         B                          B
QY_2577:GGCCGTTAGAGAGGCT-1 QY_2577:GGCTAGACATAATCCG-1
                         B                          B
QY_2577:GGCTATGTCGCTAAGT-1 QY_2577:GGCTGTCAGAGGGACT-1
                         B                          B
QY_2577:GGGAATATCGCGACAC-1 QY_2577:GGGTCACTCATTTGTC-1
                         B                          B
QY_2577:GGGTTACGTGAGGTGA-1 QY_2577:GGGTTACGTTAGGACC-1
                         B                          B
QY_2577:GGTAACCGTGTCACGG-1 QY_2577:GGTACTTAGGTCGATT-1
                         B                          B
QY_2577:GGTATGTTCCGCAACA-1 QY_2577:GGTCCTGCAGGCTAGA-1
                         B                          B
QY_2577:GGTTCCCGTTGGATAT-1 QY_2577:GTAAGCGCACAGGATG-1
                         B                          B
QY_2577:GTACCGGGTTAGTTGG-1 QY_2577:GTACTGGTCATGACCG-1
                         B                          B
QY_2577:GTCAATATCAACAAGG-1 QY_2577:GTCCATTGTTAAGCGC-1
                         B                          B
QY_2577:GTCGGTTCACCTAAGC-1 QY_2577:GTGATGAAGTGATTCA-1
                         B                          B
QY_2577:GTGCTGATCTAACCTT-1 QY_2577:GTGGTTAGTGTTGCAA-1
                         B                          B
QY_2577:GTGTTCCTCGGCTAGC-1 QY_2577:GTTAACGGTGTTTGTC-1
                         B                          B
QY_2577:GTTAACGGTTCCGGCT-1 QY_2577:GTTAGGCGTTTACTTG-1
                         B                          B
QY_2577:GTTCACCTCACTTTAC-1 QY_2577:GTTCGCGCATCATGTG-1
                         B                          B
QY_2577:GTTCGCTTCCATCAGG-1 QY_2577:GTTTAACCACATAACT-1
                         B                          B
QY_2577:TAAAGCCTCGTCCTTA-1 QY_2577:TAAGTAGCAGCGCTTG-1
                         B                          B
QY_2577:TAAGTGCTCAGGCTAT-1 QY_2577:TACCTTTAGTTTGCGG-1
                         B                          B
QY_2577:TAGGAACCAGCAAGTG-1 QY_2577:TAGGTTATCTAAGTCA-1
                         B                          B
QY_2577:TATAGCCAGTGAACCT-1 QY_2577:TATCACGCATGACTAT-1
                         B                          B
QY_2577:TCAACAATCACAGGAA-1 QY_2577:TCAACAATCCCGTTGT-1
                         B                          B
QY_2577:TCACATAAGGAGGGTT-1 QY_2577:TCACGGATCACTTCAT-1
                         B                          B
QY_2577:TCACTGACATCAGCAC-1 QY_2577:TCCACAACATAGACTT-1
                         B                          B
QY_2577:TCCAGCAAGTCAATTG-1 QY_2577:TCCATAAAGCGATAGA-1
                         B                          B
QY_2577:TCCCTCACAATTAAGG-1 QY_2577:TCCCTCACAGGTTCAC-1
                         B                          B
QY_2577:TCGCCCATCAAAGGCA-1 QY_2577:TCGCGAGGTGGAAGGC-1
                         B                          B
QY_2577:TCTAAGGGTTGTAAAC-1 QY_2577:TCTTGACGTGATTTGG-1
                         B                          B
QY_2577:TGACCTTGTTCGCGCT-1 QY_2577:TGACTCCTCCTGATTT-1
                         B                          B
QY_2577:TGAGCCGGTTAAGGTT-1 QY_2577:TGATCAATCTATCGCC-1
                         B                          B
QY_2577:TGATGAACATGCAACC-1 QY_2577:TGCAGGCTCTTGCAGG-1
                         B                          B
QY_2577:TGCCGGTAGGTCTTGG-1 QY_2577:TGCTGGATCTAAGTCA-1
                         B                          B
QY_2577:TGCTTTAGTCACTCGC-1 QY_2577:TGGACCGGTACGCGCA-1
                         B                          B
QY_2577:TGGGCCTAGCTCAATA-1 QY_2577:TGGTTAATCCTCGATC-1
                         B                          B
QY_2577:TGGTTCCTCCATCAGG-1 QY_2577:TGGTTCCTCTTGACCC-1
                         B                          B
QY_2577:TGGTTCCTCTTTGTAC-1 QY_2577:TGGTTGAGTTTCAGGA-1
                         B                          B
QY_2577:TGTCATAAGACTAAGG-1 QY_2577:TGTCCTGGTGAGCGAA-1
                         B                          B
QY_2577:TGTGCGGGTTAACACG-1 QY_2577:TGTGGCCAGTGGCGGA-1
                         B                          B
QY_2577:TGTTATGAGACAACAG-1 QY_2577:TGTTGTGCAATTAGGA-1
                         B                          B
QY_2577:TTAATCGAGCGAGCGA-1 QY_2577:TTAGGCTAGTCATGCG-1
                         B                          B
QY_2577:TTAGTCAAGCATGCAT-1 QY_2577:TTCAACCGTTTACGTC-1
                         B                          B
QY_2577:TTCAGGTAGTATTGTG-1 QY_2577:TTCCACGGTGCTCACC-1
                         B                          B
QY_2577:TTCCTTCTCCGCTAGA-1 QY_2577:TTCGGTACATTGTCCT-1
                         B                          B
QY_2577:TTGCGTCTCCCTGACT-1 QY_2577:TTGTCCATCATAATCG-1
                         B                          B
QY_2577:TTGTGTGCAGGTTCAC-1 QY_2577:TTTACGAAGCTATTGA-1
                         B                          B
QY_2577:TTTACGCGTAGACAAA-1 QY_2577:TTTCCTGAGGGTGAAC-1
                         B                          B
QY_2577:TTTGCATTCACCTGCT-1 QY_2577:TTTGTCTAGCTGGACC-1
                         B                          B
QY_2577:TTTGTGGCATCGTTCT-1 QY_2579:AAAGCCCGTTACGCGG-1
                         B                          B
QY_2579:AAAGCTTGTAGCTAGC-1 QY_2579:AAAGGAGCAGCTACGT-1
                         B                          B
QY_2579:AACAAGCCATTGGGAG-1 QY_2579:AACAGATAGGCTTAGT-1
                         B                          B
QY_2579:AACGCCCAGTCCTTCA-1 QY_2579:AACTCACAGCTATTAG-1
                         B                          B
QY_2579:AACTTAGTCGCTTGCT-1 QY_2579:AAGACATAGACTTATG-1
                         B                          B
QY_2579:AAGCCTGTCCACAATA-1 QY_2579:AAGCTTGGTTTGCAGA-1
                         B                          B
QY_2579:AATGCAACAATCGCAC-1 QY_2579:AATTGCCAGAGAGGCT-1
                         B                          B
QY_2579:AATTGCCAGGTCGATT-1 QY_2579:AATTGTGTCATGGCTG-1
                         B                          B
QY_2579:ACACTTGCAGGCTAAG-1 QY_2579:ACATAGCTCCTTCGTA-1
                         B                          B
QY_2579:ACATCAATCTGGCAAT-1 QY_2579:ACCAAGCGTCTAACAG-1
                         B                          B
QY_2579:ACCAAGCGTGCATTTC-1 QY_2579:ACCGCAATCCTAATTC-1
                         B                          B
QY_2579:ACGAATCTCCGTAAAC-1 QY_2579:ACGCAAGCAAATGCCC-1
                         B                          B
QY_2579:ACGCAAGCACACCAAC-1 QY_2579:ACTCGCGCAAAGGTAC-1
                         B                          B
QY_2579:ACTCGCGCAGAAATTG-1 QY_2579:ACTTACTTCTCAATGA-1
                         B                          B
QY_2579:ACTTTGTTCAATGAGG-1 QY_2579:AGAAACCCATATAACC-1
                         B                          B
QY_2579:AGAAAGGCATATAACC-1 QY_2579:AGACAATAGGTCCACA-1
                         B                          B
QY_2579:AGAGAAGCAGCTAATT-1 QY_2579:AGAGAAGCAGTTGCGT-1
                         B                          B
QY_2579:AGCAAATAGTGCACGC-1 QY_2579:AGCAAGGGTTCCTGTG-1
                         B                          B
QY_2579:AGCTACTAGCTTACTT-1 QY_2579:AGCTTAATCTTAGTCT-1
                         B                          B
QY_2579:AGGATCCGTCATGCAA-1 QY_2579:AGGCTAAAGGAGGCAT-1
                         B                          B
QY_2579:AGGGTTGCAGCAACCT-1 QY_2579:AGGTTACTCCTTAGGG-1
                         B                          B
QY_2579:AGTCCTTGTTAAATGC-1 QY_2579:AGTCGCATCATTACTC-1
                         B                          B
QY_2579:AGTGCCGGTCCTTTAA-1 QY_2579:AGTGTGGCAGTATGTT-1
                         B                          B
QY_2579:AGTTGCAGTCTATCGT-1 QY_2579:AGTTGCGTCGGCTAGC-1
                         B                          B
QY_2579:AGTTGTCAGCCTCTGT-1 QY_2579:ATAATGGCATTAGGCC-1
                         B                          B
QY_2579:ATATGTCCAACTAGCC-1 QY_2579:ATATGTCCACGGTACT-1
                         B                          B
QY_2579:ATATGTCCATTGTGAT-1 QY_2579:ATCAGGTTCGTTATCT-1
                         B                          B
QY_2579:ATGACAACAGTAGCCT-1 QY_2579:ATGGCTTAGCTATTAG-1
                         B                          B
QY_2579:ATGGTTATCTAATTGG-1 QY_2579:ATGTTCAAGGTCCAAT-1
                         B                          B
QY_2579:ATGTTGTCAAACCTTG-1 QY_2579:ATTAGGTGTGGATTAT-1
                         B                          B
QY_2579:ATTAGGTGTTAAGGTT-1 QY_2579:ATTATCCTCGCATCCT-1
                         B                          B
QY_2579:ATTCCTCCAAACCTTG-1 QY_2579:ATTGGTTCAAACCCTA-1
                         B                          B
QY_2579:CAAGACAAGCGGTTAT-1 QY_2579:CAAGCTAGTGGATTCA-1
                         B                          B
QY_2579:CAAGGTTTCTGTTGCC-1 QY_2579:CAAGTAACACCCACCT-1
                         B                          B
QY_2579:CAATATGTCGCTCCAT-1 QY_2579:CAATATGTCGGTACGC-1
                         B                          B
QY_2579:CAATCGCCAACTAGCC-1 QY_2579:CAATCGCCATTAAGTC-1
                         B                          B
QY_2579:CAATGTGGTCATGCAA-1 QY_2579:CACAGGGAGACAACGA-1
                         B                          B
QY_2579:CACCGGTAGCTGGACC-1 QY_2579:CAGCATGTCCCGTTTA-1
                         B                          B
QY_2579:CAGCCAATCAATAGCC-1 QY_2579:CAGGATGCACAGAAAC-1
                         B                          B
QY_2579:CAGGCTATCATTGACA-1 QY_2579:CAGGGTGAGCCTGATG-1
                         B                          B
QY_2579:CATCAATCAAGATTCT-1 QY_2579:CATTATGAGGCGCTTA-1
                         B                          B
QY_2579:CCAACCCGTGCGCATG-1 QY_2579:CCATAGCCAGCCTGCA-1
                         B                          B
QY_2579:CCCAAACCAGTTAAAG-1 QY_2579:CCCAGCACAGGGAGCT-1
                         B                          B
QY_2579:CCGATGCAGAATGACG-1 QY_2579:CCGCAAGGTTCCTCCT-1
                         B                          B
QY_2579:CCGCCAACAATCCTGA-1 QY_2579:CCGCCAACACTCAACA-1
                         B                          B
QY_2579:CCGCTAGCACCTCAGG-1 QY_2579:CCGCTTAGTTTGCAGA-1
                         B                          B
QY_2579:CCGTTACTCATGGTTA-1 QY_2579:CCTATAGCACAGGAAT-1
                         B                          B
QY_2579:CCTGCTCCAATGCCCG-1 QY_2579:CCTTAACGTTGCAATG-1
                         B                          B
QY_2579:CGAACAAAGCACTTGG-1 QY_2579:CGATTCCTCCATCAGG-1
                         B                          B

In [93]:
#looping through cell types by making ^ into a function
get_per_sample_gex_SUMS <- function(cell.type, filename){
    print(paste(cell.type,Sys.time()))

    #pull out rows of gex.counts where BC Ident matches cell.type
    if (cell.type=='Bulk') {
        bcs <- paste0(adata_ac$dna,":",adata_ac$dna_bc)
    } else {
        bcs <- paste0(adata_ac$dna,":",adata_ac$dna_bc)[Idents(adata_ac) == cell.type]
    }
    counts <- gex.counts[,colnames(gex.counts) %in% bcs]
    print(dim(counts))

    #initialize the matrix of sample gex
    counts.df <- as.data.frame(rep(0,length(row.names(gex.counts))))
    row.names(counts.df) <- row.names(gex.counts)
    colnames(counts.df) <- c('temp')

    #go through samples and calculate sum of gex values
    for (sample in samples){
        sample_cols <- colnames(counts) %in% sample_bcs[[sample]]
        counts.cut <- counts[,sample_cols]
        
        #if only one bc, this becomes a vector which is an issue
        if (typeof(counts.cut) == 'double'){
            mean.counts <- counts.cut
        #if there are NO bcs, this will return NA (just return 0 for everything)
        } else if(length(colnames(counts.cut)) == 0){
            mean.counts <- rep(0,length(row.names(counts)))
        } else {
            mean.counts <- rowSums(counts.cut)
        }
        counts.df <- cbind(counts.df,as.data.frame(mean.counts))
     }
    fin.counts.df <- counts.df[,-c(1)]
    colnames(fin.counts.df) <- samples
    
    #export df
    write.table(fin.counts.df, filename, sep='\t',quote=FALSE)
}

In [94]:
##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.counts.tsv', sep = "")
    get_per_sample_gex_SUMS(cell.type, filename)
}

[1] "Hepatocytes 2024-09-12 23:31:00.998905"
[1] 391368  51593
[1] "T 2024-09-12 23:34:08.915293"
[1] 391368   2368
[1] "HSC 2024-09-12 23:36:01.761766"
[1] 391368   5556
[1] "Endothelial 2024-09-12 23:38:04.210682"
[1] 391368  13350
[1] "Cholangiocyte 2024-09-12 23:40:45.049408"
[1] 391368   7416
[1] "NK 2024-09-12 23:42:48.170797"
[1] 391368   1533
[1] "Myeloid 2024-09-12 23:44:25.645693"
[1] 391368  11161
[1] "Schwann 2024-09-12 23:46:49.752891"
[1] 391368     91
[1] "B 2024-09-12 23:48:25.656138"
[1] 391368   1657
[1] "Mast 2024-09-12 23:50:08.773983"
[1] 391368     50
[1] "Bulk 2024-09-12 23:51:22.678701"
[1] 391368  94775

# Calculate CPM for H3K27ac

CPM = 1000000*(peak counts/depth)

In [98]:
#looping through cell types by making ^ into a function
calculate_CPM <- function(cell.type, cpm.filename, pseudobulk.filename){
    x <- read.table(paste(pseudobulk.filename))
    
    cpm <- x
    for (i in 1:ncol(x)){
        cpm[,i] <- 1e6 * (x[,i]/sum(x[,i]))
    }
    
    #export df
    write.table(cpm, cpm.filename, sep='\t',quote=FALSE)
}

In [99]:
indir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    cpm.filename <- paste(outdir, cell.type, '_perdonor.H3K27ac.CPM.tsv', sep = "")
    pseudobulk.filename <- paste(indir, cell.type, '_perdonor.H3K27ac.counts.tsv', sep = "")
    calculate_CPM(cell.type, cpm.filename, pseudobulk.filename)
}

# Cell count matrix  - H3K27me3

In [4]:
DPT.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/'

In [7]:
H3K27me3 <- read_h5ad(paste0(DPT.dir, 'FNIH_Liver_pool.H3K27me3.peaks.h5ad'))
H3K27me3

AnnData object with n_obs × n_vars = 87059 × 466057
    obs: 'n_fragment', 'frac_dup', 'frac_mito', 'doublet_probability', 'doublet_score_x', 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'percent.ribo', 'RNA_snn_res.0.3', 'seurat_clusters', 'doublet_score_y', 'doublet_ident', 'DROPLET.TYPE', 'BEST.GUESS', 'NEXT.GUESS', 'rna', 'rna_bc', 'dna', 'library_info', 'dna_bc', 'Donor', 'Batch', 'Target', 'nCount_SCT', 'nFeature_SCT', 'SCT_snn_res.1', 'predicted.celltype', 'predicted.celltype_scores', 'predicted.cellsubtype', 'predicted.cellsubtype_scores', 'atac_bc', 'condition', 'leiden'
    var: 'count', 'selected'
    uns: 'spectral_eigenvalue'
    obsm: 'X_spectral', 'X_spectral_harmony', 'X_umap'
    obsp: 'distances'

In [7]:
adata_DPT <- qs::qread(paste0(DPT.dir, 'FNIH_Liver_pool_DPT_SNG_SoupX_reference_mapping_filtered.qs'))
adata_DPT

An object of class Seurat
70217 features across 181892 samples within 2 assays
Active assay: SCT (33616 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap

In [30]:
adata_me3 <- subset(adata_DPT, Target=='H3K27me3')
adata_me3

An object of class Seurat
70217 features across 87090 samples within 2 assays
Active assay: SCT (33616 features, 3000 variable features)
 3 layers present: counts, data, scale.data
 1 other assay present: RNA
 3 dimensional reductions calculated: pca, harmony, umap

In [31]:
rna.meta <- read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/01_DESEQ_RNA/RNA.meta.tsv',
           sep='\t', header=T)
rna.meta <- select(rna.meta, donor_demux, disease_status, condition,
               Steatosis.grade, Fibrosis.stage, Fat.distribution, Lobular.inflammation, Ballooning,
               Portal.inflammation, Hepatocyte.necrosis, MASH.CRN.score..X.8, Gender, Age, BMI)

meta <- data.frame(table(select(adata_me3[[]], donor_demux=Donor, celltype=predicted.celltype))) %>% 
    pivot_wider(values_from = Freq, names_from = celltype) %>%
    left_join(dplyr::distinct(dplyr::select(adata_me3[[]], donor_demux=Donor, batch=Batch))) %>%
    left_join(rna.meta)

meta$batch <- factor(meta$batch)

meta

write.table(meta, '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/H3K27me3.meta.tsv',
           sep='\t', col.names=T, row.names=F, quote=F)

Joining with `by = join_by(donor_demux)`
Joining with `by = join_by(donor_demux)`

   donor_demux B  Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK
1  HL150001     5  18            84          514         22 0     71     15
2  HL150009     5   9            80          713         66 0     83      6
3  HL150013    40  29           106          244         54 3    123     24
4  HL150015    23  64            67         1401         49 0     71     11
5  HL160017     9  28            39         1758         25 0    204      4
6  HL160022     1 149            20          158         23 0     42      2
7  HL160026     2  17           140         1342         94 0     18     10
8  HL160029     4 109           358          718        105 2    164     48
9  HL160030     8  59           213         1082         54 0     44     11
10 HL160032     6  58           113          109         21 0     90     33
11 HL160035     8  79           126          246         31 0     77     47
12 HL160037    27  58           138          372         18 4    225     77
13 HL160040     7  90           145         1297         95 1    204     17
14 HL160041    10  45           101          468         27 0     76     16
15 HL160042     3 115           199         1816         53 0    114     13
16 HL170044     9 184           327          565         65 0     78     17
17 HL170046    13  41           137          452         57 0     61     11
18 HL170047    12  42            64          601         54 0     75     17
19 HL170048    10  36            83          724         28 0    138     14
20 HL170049     2 117           151          266        124 0     68      1
21 HL170052     9  41           163          195         42 2     39      6
22 HL170055    26  23            53          317         46 0     90     13
23 HL170058     9 225            81          102        104 0     69      1
24 HL170060     7  10           141         1204         25 0     85     31
25 HL170062    19 115           245         1199         74 2    123     23
26 HL170064    30  54           149         1316         51 0    324     20
27 HL170065    10 167           115          305         69 2    177     14
28 HL170066     9  66           208          446         51 0    132     26
29 HL180071    34  70           114          164         98 3    115     22
30 HL180809     7  53           283          911         52 0     78     17
⋮  ⋮           ⋮  ⋮             ⋮           ⋮           ⋮   ⋮    ⋮       ⋮
57 HL210207    13  46           263          247         30 0    291     31
58 HL210521    23  83           265          213         97 3    198     45
59 HL210614     2   9            88          116         17 0     89     45
60 HL210621     5  18           136          756         23 0    139     26
61 HL210706    15 108           213         1218         57 0    242     20
62 HL210726     6 147            95          343         40 0     82      2
63 HL210727     5  34            63          122         23 0     28      7
64 HL210806    12 276            42          280         69 0     52      3
65 HL211001    10 135           242         1938         93 1    188     24
66 HL211025    36  76           188         1023         42 0    234     21
67 HL211106    18  28           143           39         25 1     85     22
68 HL211122    32 251           173          770         69 1     91     10
69 HL220127     5  71           155          118         31 0    103     13
70 HL220210    14  56           111          260         49 1    276     52
71 HL220216    30  55           117          231         58 0    259     30
72 HL220402    11 202           159          238         36 1     94     25
73 HL220405     6  64            66          523         28 0    105      9
74 HL220613    10  36           149          358         21 0    157      9
75 HL220628     9  91           189          527         20 0     29      7
76 HL220825     0  41           138          101         29 1     48     11
77 HL221006    26  64            50         1000         10 0    212     10
78 HL221019    60  97            80          229        189 0     94      7
79 HL221119    43  21           129          344         42 1    277     18
80 HL221201    31  30           148         1313         39 1    225     19
81 HL221215     4  61           128          317         30 0    117      5
82 HL230212    17  17            53          551         34 0     78      2
83 HL230302    25  29           146          113         58 0    130     15
84 HL230316    22 227           311          535         76 2    118      7
85 HL230324    10  32           140          601         19 0     93     11
86 HL230325    12  86           121         2157         72 1    225     16
   Schwann ⋯ Fibrosis.stage Fat.distribution       Lobular.inflammation
1  0       ⋯ 0              Centrizonal            0
2  3       ⋯ 0              centrizonal            0
3  1       ⋯ 2              Centrilobular, Diffuse 1
4  2       ⋯ 1              Centrilobular, Diffuse 0
5  0       ⋯ 2              Centrilobular          1
6  0       ⋯ 2              Diffuse                1
7  0       ⋯ 0              0                      0
8  1       ⋯ 0              <5%                    0
9  3       ⋯ 0              N/A                    0
10 0       ⋯ 0              N/A                    0
11 5       ⋯ 1              Diffuse                0
12 2       ⋯ 0              0                      0
13 2       ⋯ 0              0                      0
14 0       ⋯ 2              Diffuse                0
15 4       ⋯ 0              Diffuse                0
16 2       ⋯ 0              0                      0
17 3       ⋯ 1              Centrilobular          1
18 0       ⋯ 0              0                      0
19 0       ⋯ 1              Centrilobular          1
20 1       ⋯ 4              Diffuse                0
21 2       ⋯ 0                                     0
22 0       ⋯ 4              Diffuse                1
23 0       ⋯ 2              Centrilobular          1
24 0       ⋯ 2               centrilobular/Diffuse 2
25 2       ⋯ 0              0                      0
26 3       ⋯ 1              Centrilobular          2
27 1       ⋯ 0              Centrilobular          2
28 1       ⋯ 2              Diffuse                2
29 2       ⋯ 3              Diffuse                1
30 4       ⋯ 0              Centrizonal            0
⋮  ⋮       ⋱ ⋮              ⋮                      ⋮
57 2       ⋯ 0              0                      0
58 0       ⋯ 0              Diffuse                1
59 0       ⋯ 0                                     0
60 1       ⋯ 0                                     0
61 1       ⋯ 0              Peripotal              1
62 1       ⋯ 4              Diffuse                1
63 0       ⋯ 0              Centrizonal            1
64 2       ⋯ 4              Diffuse                1
65 4       ⋯ 0              N/A                    0
66 0       ⋯ 0              Diffuse                2
67 0       ⋯ 0              N/A                    0
68 2       ⋯ 3              diffuse                1
69 1       ⋯ 1              diffuse                1
70 4       ⋯ 0              N/A                    0
71 1       ⋯ 0              N/A                    0
72 2       ⋯ 0              N/A                    0
73 0       ⋯ 0              Centrizonal            2
74 0       ⋯ 0              N/A                    0
75 1       ⋯ 0              Centrizonal            1
76 0       ⋯ 0              None                   0
77 0       ⋯ 1              Centrizonal            1
78 1       ⋯ 4              Diffuse                1
79 1       ⋯ 0              None                   0
80 4       ⋯ 0              Centrizonal            0
81 3       ⋯ 1              Diffuse                1
82 0       ⋯ 1              centrizonal            1
83 1       ⋯ 2              0                      0
84 3       ⋯ 0                                     0
85 0       ⋯ 0              cntrizonal             2
86 3       ⋯ 2              diffuse                2
   Ballooning Portal.inflammation
1  0          0
2  0          0
3  1          1-2 Mild/moderate
4  0          1
5  0          2
6  1          1
7  0          0
8  0          0
9  0          0
10 0          1
11 0          0
12 0          1
13 0          0
14 1          0
15 0          0
16 0          0
17 0          1
18 0          0
19 0          1
20 1          1
21 0          0
22 1          1
23 0          0-1
24 0          1
25 0          1
26 1          1
27 0          1
28 1          2
29 0          1
30 0          0
⋮  ⋮          ⋮
57  0         0-1
58  0         1
59  0         0
60  0         1
61  0         1
62  2         1
63  0         1
64  2         1
65  0         0
66  0         2
67  0         1
68  0         1
69  2         1
70  0         1
71  0         1
72  0         0
73  0         1
74  0         0
75  0         0
76  0         0
77  0         2
78  1         1
79  0         1
80  0         1
81  1         1
82  0         2
83  1         0
84 NA         1
85  0         1
86  0         44928
   Hepatocyte.necrosis                                 MASH.CRN.score..X.8
1  0                                                   1
2  0                                                   1
3  Spotty                                              3
4  0                                                   3
5  0                                                   2
6  0                                                   5
7  Spotty                                              0
8  0                                                   0
9  0                                                   2
10 0                                                   2
11 0                                                   3
12 1 acidophil body                                    1
13 0                                                   0
14 0                                                   6
15 0                                                   3
16 0                                                   0
17 None                                                3
18 0                                                   0
19 Rare                                                2
20 Single hemorrhagic, necrotic regenerative nodule    4
21 0                                                   0
22 Rare, <1%                                           4
23 0                                                   3
24  Spotty, focal (less than 1% of hepatic parenchyma) 5
25 0                                                   0
26 Rare, <1%                                           5
27 0                                                   4
28 Spotty, focal (less than 1% of hepatic parenchyma)  6
29 0                                                   4
30 0                                                   0
⋮  ⋮                                                   ⋮
57 0                                                   0
58 rare                                                2
59 0                                                   0
60 rare                                                0
61 0                                                   2
62 0                                                   6
63 0                                                   2
64 0                                                   6
65 0                                                   0
66 Rare                                                5
67 0                                                   0
68 0                                                   3
69 0                                                   6
70 0                                                   0
71 0                                                   0
72 0                                                   0
73 0                                                   4
74 0                                                   0
75 0                                                   3
76 0                                                   0
77 0                                                   3
78 0                                                   3
79 0                                                   0
80 0                                                   1
81 0                                                   5
82 0                                                   3
83                                                     1
84 minimal centrizonal                                 0
85                                                     3
86 rare                                                5
   Gender Age BMI
1  M      47  27.10
2  M      37  29.40
3  M      45  35.00
4  M      59  29.10
5  M      31  24.00
6  F      45  29.80
7  F      25  26.00
8  F      47  30.86
9  M      29  30.20
10 M      23  29.40
11 F      47  32.20
12 M      42  34.60
13 M      51  26.70
14 M      33  35.40
15 F      34  25.90
16 M      47  32.80
17 F      53  48.06
18 M      34  23.50
19 F      48  31.96
20 F      34  23.79
21 M      29  23.60
22 M      59  27.70
23 F      58  38.30
24 F      50  29.80
25 F      79  27.85
26 M      66  37.03
27 F      57  60.60
28 M      51  37.74
29 F      52  44.40
30 M      56  24.00
⋮  ⋮      ⋮   ⋮
57 F      34  34.48
58 F      61  30.75
59 M      43  30.50
60 M      64  25.77
61 F      54  29.32
62 M      55  34.60
63 M      44  29.30
64 F      36  26.20
65 F      45  27.00
66 F      44  33.60
67 M      23  30.05
68 F      63  33.30
69 F      24  26.67
70 M      68  33.50
71 F      22  32.65
72 F      58  16.66
73 M      33  25.77
74 M      60  32.80
75 M      30  37.50
76 M      21  22.47
77 M      43  29.40
78 F      40  17.70
79 M      37  23.80
80 M      46  39.80
81 F      43  43.00
82 M      56  32.20
83 F      60  28.50
84 F      58  29.30
85 M      60  34.20
86 M      50  36.40

In [9]:
samples = as.character(unique(adata_me3$Donor))
samples

 [1] "HL210120" "HL160042" "HL210521" "HL200707" "HL170060" "HL230316"
 [7] "HL160029" "HL200805" "HL210806" "HL191025" "HL221019" "HL200525"
[13] "HL200925" "HL170049" "HL210726" "HL190326" "HL221201" "HL160030"
[19] "HL190214" "HL170046" "HL210614" "HL211106" "HL220825" "HL230302"
[25] "HL170065" "HL221119" "HL221215" "HL160026" "HL160041" "HL220405"
[31] "HL191216" "HL230324" "HL220613" "HL160032" "HL230212" "HL160040"
[37] "HL170062" "HL210706" "HL230325" "HL170058" "HL170052" "HL150001"
[43] "HL210621" "HL200115" "HL201024" "HL210727" "HL190603" "HL160017"
[49] "HL170055" "HL150009" "HL190215" "HL200212" "HL220216" "HL170047"
[55] "HL191002" "HL211001" "HL150013" "HL211025" "HL200615" "HL200529"
[61] "HL170048" "HL150015" "HL160037" "HL190909" "HL180071" "HL190114"
[67] "HL190827" "HL220210" "HL170064" "HL190624" "HL201120" "HL181010"
[73] "HL180809" "HL221006" "HL220402" "HL170044" "HL181029" "HL211122"
[79] "HL170066" "HL181031" "HL160022" "HL220628" "HL210207" "HL160035"
[85] "HL220127" "HL190606"

In [11]:
######## SET TO WHATEVER YOUR ASSIGNMENTS ARE STORED UNDER ########
Idents(object = adata_me3) <- "predicted.celltype"
head(Idents(adata_me3))

#pull out list of all cell types, removing ignore
unique_cell_types <- unique(adata_me3$predicted.celltype)
#unique_cell_types <- unique_cell_types[-c(11)]
print(unique_cell_types)


sample_bcs <- list()
for (sample in samples){
    sample_bcs[[sample]] <- paste0(adata_me3$dna,":",adata_me3$dna_bc)[adata_me3[[]]$Donor == sample]
}

##############
#### SET TO WHATEVER ASSAY YOU WANT TO USE ######
gex.counts <- t(H3K27me3$X)
dim(gex.counts)
head(gex.counts)

QY_2581:AAACAGCCAAGGTCCT-1 QY_2581:AAACAGCCAATTGACT-1
               Hepatocytes                Hepatocytes
QY_2581:AAACAGCCACCGGCTA-1 QY_2581:AAACAGCCAGCATGGA-1
                   Myeloid                Hepatocytes
QY_2581:AAACAGCCAGCCTAAC-1 QY_2581:AAACAGCCAGGCGATA-1
               Endothelial                Hepatocytes
10 Levels: Hepatocytes Myeloid Endothelial Cholangiocyte HSC T NK B ... Mast

 [1] "Hepatocytes"   "Myeloid"       "Endothelial"   "Cholangiocyte"
 [5] "HSC"           "T"             "NK"            "B"
 [9] "Schwann"       "Mast"

[1] 466057  87059

  [[ suppressing 34 column names ‘LV004:AAACAAGCACGTAGGT-1’, ‘LV004:AAACAAGCAGTGAACC-1’, ‘LV004:AAACAAGCATAGGTGC-1’ ... ]]

6 x 87059 sparse Matrix of class "dgRMatrix"

chr1:9566-11065  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:29153-30652 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:30872-32371 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:33873-35372 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:37119-38618 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
chr1:39169-40668 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

chr1:9566-11065  . . . ......
chr1:29153-30652 . . . ......
chr1:30872-32371 . . . ......
chr1:33873-35372 . . . ......
chr1:37119-38618 . . . ......
chr1:39169-40668 . . . ......

 .....suppressing 87025 columns in show(); maybe adjust options(max.print=, width=)
 ..............................

In [13]:
summary(sample_bcs)

         Length Class  Mode
HL210120  700   -none- character
HL160042 2351   -none- character
HL210521 1015   -none- character
HL200707  475   -none- character
HL170060 1511   -none- character
HL230316 1337   -none- character
HL160029 1552   -none- character
HL200805  463   -none- character
HL210806  764   -none- character
HL191025  692   -none- character
HL221019  892   -none- character
HL200525  644   -none- character
HL200925 1308   -none- character
HL170049  740   -none- character
HL210726  726   -none- character
HL190326  732   -none- character
HL221201 1848   -none- character
HL160030 1495   -none- character
HL190214  674   -none- character
HL170046  795   -none- character
HL210614  381   -none- character
HL211106  384   -none- character
HL220825  379   -none- character
HL230302  565   -none- character
HL170065  867   -none- character
HL221119  908   -none- character
HL221215  693   -none- character
HL160026 1631   -none- character
HL160041  753   -none- character
HL220405  819   -none- character
HL191216  461   -none- character
HL230324  923   -none- character
HL220613  755   -none- character
HL160032  435   -none- character
HL230212  774   -none- character
HL160040 1898   -none- character
HL170062 1838   -none- character
HL210706 1963   -none- character
HL230325 2705   -none- character
HL170058  626   -none- character
HL170052  519   -none- character
HL150001  731   -none- character
HL210621 1196   -none- character
HL200115  837   -none- character
HL201024  395   -none- character
HL210727  304   -none- character
HL190603  372   -none- character
HL160017 2092   -none- character
HL170055  605   -none- character
HL150009  979   -none- character
HL190215 2446   -none- character
HL200212 2448   -none- character
HL220216  839   -none- character
HL170047  870   -none- character
HL191002  865   -none- character
HL211001 2660   -none- character
HL150013  652   -none- character
HL211025 1670   -none- character
HL200615  802   -none- character
HL200529  708   -none- character
HL170048 1051   -none- character
HL150015 1708   -none- character
HL160037  937   -none- character
HL190909  808   -none- character
HL180071  656   -none- character
HL190114  912   -none- character
HL190827  694   -none- character
HL220210  868   -none- character
HL170064 1970   -none- character
HL190624 1001   -none- character
HL201120  566   -none- character
HL181010  804   -none- character
HL180809 1417   -none- character
HL221006 1382   -none- character
HL220402  777   -none- character
HL170044 1257   -none- character
HL181029  652   -none- character
HL211122 1425   -none- character
HL170066  949   -none- character
HL181031 1039   -none- character
HL160022  408   -none- character
HL220628  878   -none- character
HL210207  943   -none- character
HL160035  632   -none- character
HL220127  510   -none- character
HL190606  384   -none- character

In [105]:
unique_cell_types

 [1] "Hepatocytes"   "Myeloid"       "Endothelial"   "Cholangiocyte"
 [5] "HSC"           "T"             "NK"            "B"
 [9] "Schwann"       "Mast"

In [106]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

In [14]:
length(paste0(adata_me3$dna,":",adata_me3$dna_bc)[Idents(adata_me3) == 'Hepatocytes'])

[1] 49254

In [107]:
#looping through cell types by making ^ into a function
get_per_sample_gex_SUMS <- function(cell.type, filename){
    print(paste(cell.type,Sys.time()))

    #pull out rows of gex.counts where BC Ident matches cell.type
    if (cell.type=='Bulk') {
        bcs <- paste0(adata_me3$dna,":",adata_me3$dna_bc)
    } else {
        bcs <- paste0(adata_me3$dna,":",adata_me3$dna_bc)[Idents(adata_me3) == cell.type]
    }
    counts <- gex.counts[,colnames(gex.counts) %in% bcs]
    print(dim(counts))

    #initialize the matrix of sample gex
    counts.df <- as.data.frame(rep(0,length(row.names(gex.counts))))
    row.names(counts.df) <- row.names(gex.counts)
    colnames(counts.df) <- c('temp')

    #go through samples and calculate sum of gex values
    for (sample in samples){
        sample_cols <- colnames(counts) %in% sample_bcs[[sample]]
        counts.cut <- counts[,sample_cols]
        
        #if only one bc, this becomes a vector which is an issue
        if (typeof(counts.cut) == 'double'){
            mean.counts <- counts.cut
        #if there are NO bcs, this will return NA (just return 0 for everything)
        } else if(length(colnames(counts.cut)) == 0){
            mean.counts <- rep(0,length(row.names(counts)))
        } else {
            mean.counts <- rowSums(counts.cut)
        }
        counts.df <- cbind(counts.df,as.data.frame(mean.counts))
     }
    fin.counts.df <- counts.df[,-c(1)]
    colnames(fin.counts.df) <- samples
    
    #export df
    write.table(fin.counts.df, filename, sep='\t',quote=FALSE)
}

In [109]:
##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.counts.tsv', sep = "")
    get_per_sample_gex_SUMS(cell.type, filename)
}

[1] "Hepatocytes 2024-09-13 00:41:58.608979"
[1] 466057  49225
[1] "Myeloid 2024-09-13 00:46:23.680495"
[1] 466057  10257
[1] "Endothelial 2024-09-13 00:48:40.537997"
[1] 466057  11241
[1] "Cholangiocyte 2024-09-13 00:50:42.124254"
[1] 466057   6639
[1] "HSC 2024-09-13 00:52:09.145746"
[1] 466057   4424
[1] "T 2024-09-13 00:54:24.914913"
[1] 466057   2335
[1] "NK 2024-09-13 00:56:09.789103"
[1] 466057   1517
[1] "B 2024-09-13 00:57:55.467342"
[1] 466057   1259
[1] "Schwann 2024-09-13 00:59:47.522276"
[1] 466057    115
[1] "Mast 2024-09-13 01:01:25.832208"
[1] 466057     47
[1] "Bulk 2024-09-13 01:03:03.731229"
[1] 466057  87059

# Calculate CPM for H3K27me3

CPM = 1000000*(peak counts/depth)

In [110]:
#looping through cell types by making ^ into a function
calculate_CPM <- function(cell.type, cpm.filename, pseudobulk.filename){
    x <- read.table(paste(pseudobulk.filename))
    
    cpm <- x
    for (i in 1:ncol(x)){
        cpm[,i] <- 1e6 * (x[,i]/sum(x[,i]))
    }
    
    #export df
    write.table(cpm, cpm.filename, sep='\t',quote=FALSE)
}

In [111]:
indir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

##### NAME YOUR FILES #####
for (cell.type in c(unique_cell_types, 'Bulk')){
    cpm.filename <- paste(outdir, cell.type, '_perdonor.H3K27me3.CPM.tsv', sep = "")
    pseudobulk.filename <- paste(indir, cell.type, '_perdonor.H3K27me3.counts.tsv', sep = "")
    calculate_CPM(cell.type, cpm.filename, pseudobulk.filename)
}

# By CT

In [30]:
cells <- stringr::str_remove(list.files('/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/', 
                                        pattern='_perdonor.RNA.counts.tsv'), '_perdonor.RNA.counts.tsv')
cells

 [1] "B"             "Bulk"          "Cholangiocyte" "Endothelial"
 [5] "Hepatocytes"   "HSC"           "Mast"          "Myeloid"
 [9] "NK"            "Schwann"       "T"

## RNA

In [4]:
pseudobulk.counts <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/'

for (c in cells) {
    ct.counts <- rowSums(read.table(paste0(count.dir,c,'_perdonor.RNA.counts.tsv')))
    if(length(rownames(pseudobulk.counts)) == 0) {
        pseudobulk.counts <- data.frame(ct.counts)
        colnames(pseudobulk.counts) <- c
    } else {
        pseudobulk.counts[[c]] <- ct.counts[rownames(pseudobulk.counts)]
    }
}

dim(pseudobulk.counts)
head(pseudobulk.counts)

write.table(pseudobulk.counts, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/celltype.RNA.counts.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 36601    11

            B  Bulk Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid NK
MIR1302-2HG  0   83  2              8           67         1  0      5      0
FAM138A      0    0  0              0            0         0  0      0      0
OR4F5        0    6  0              3            2         0  0      1      0
AL627309.1  29 4448 75            276         3441        98  1    495     14
AL627309.3   0  112  2             10           82         4  0     13      0
AL627309.2   0   11  0              0           10         0  0      1      0
            Schwann T
MIR1302-2HG 0        0
FAM138A     0        0
OR4F5       0        0
AL627309.1  2       17
AL627309.3  0        1
AL627309.2  0        0

In [5]:
TPM.by.cell <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/'

for (c in cells) {
    ct.TPM <- rowMeans(read.table(paste0(count.dir,c,'_perdonor.RNA.TPM.tsv')), na.rm=T)
    if(length(rownames(TPM.by.cell)) == 0) {
        TPM.by.cell <- data.frame(ct.TPM)
        colnames(TPM.by.cell) <- c
    } else {
        TPM.by.cell[[c]] <- ct.TPM[rownames(TPM.by.cell)]
    }
}

dim(TPM.by.cell)
head(TPM.by.cell)

write.table(TPM.by.cell, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/RNA/celltype.RNA.TPM.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 36601    11

            B         Bulk       Cholangiocyte Endothelial Hepatocytes
MIR1302-2HG 0.0000000 0.79668592 0.3333802     0.68154667  0.83950997
FAM138A     0.0000000 0.00000000 0.0000000     0.00000000  0.00000000
OR4F5       0.0000000 0.02119961 0.0000000     0.05607578  0.02109361
AL627309.1  0.6904217 1.35000276 1.0986779     0.95430598  1.40211226
AL627309.3  0.0000000 1.18763025 0.8633086     1.02260818  1.19505026
AL627309.2  0.0000000 0.15028770 0.0000000     0.00000000  0.18388942
            HSC       Mast    Myeloid    NK        Schwann   T
MIR1302-2HG 0.3220091 0.00000 1.91072696 0.0000000 0.0000000 0.0000000
FAM138A     0.0000000 0.00000 0.00000000 0.0000000 0.0000000 0.0000000
OR4F5       0.0000000 0.00000 0.02503063 0.0000000 0.0000000 0.0000000
AL627309.1  0.7524539 0.53886 2.14812760 0.9303304 0.5439801 0.7497329
AL627309.3  0.9177773 0.00000 1.31547444 0.0000000 0.0000000 0.3803404
AL627309.2  0.0000000 0.00000 0.19748996 0.0000000 0.0000000 0.0000000

## ATAC

In [31]:
pseudobulk.counts <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

for (c in cells) {
    ct.counts <- rowSums(read.table(paste0(count.dir,c,'_perdonor.ATAC.counts.tsv')))
    if(length(rownames(pseudobulk.counts)) == 0) {
        pseudobulk.counts <- data.frame(ct.counts)
        colnames(pseudobulk.counts) <- c
    } else {
        pseudobulk.counts[[c]] <- ct.counts[rownames(pseudobulk.counts)]
    }
}

dim(pseudobulk.counts)
head(pseudobulk.counts)

write.table(pseudobulk.counts, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/celltype.ATAC.counts.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 611576     11

                   B   Bulk  Cholangiocyte Endothelial Hepatocytes HSC  Mast
chr1-9967-10267    302 21495 398           2272        14248       1025 11
chr1-16085-16372    19  1749  39            193         1241         89  1
chr1-17357-17657    29  2657  61            315         1766        176  1
chr1-29216-29497    24  2192  42            386         1216         98  1
chr1-102789-103089  10  5279  26             56         5068         43  0
chr1-136647-136947  14  1443  17             61         1197         38  0
                   Myeloid NK  Schwann T
chr1-9967-10267    2474    285 15      465
chr1-16085-16372    125     27  0       15
chr1-17357-17657    238     30  4       37
chr1-29216-29497    292     52  1       80
chr1-102789-103089   63      7  1        5
chr1-136647-136947  105      1  0       10

In [32]:
CPM.by.cell <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

for (c in cells) {
    ct.CPM <- rowMeans(read.table(paste0(count.dir,c,'_perdonor.ATAC.CPM.tsv')), na.rm=T)
    if(length(rownames(CPM.by.cell)) == 0) {
        CPM.by.cell <- data.frame(ct.CPM)
        colnames(CPM.by.cell) <- c
    } else {
        CPM.by.cell[[c]] <- ct.CPM[rownames(CPM.by.cell)]
    }
}

dim(CPM.by.cell)
head(CPM.by.cell)

write.table(CPM.by.cell, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/celltype.ATAC.CPM.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 611576     11

                   B         Bulk      Cholangiocyte Endothelial Hepatocytes
chr1-9967-10267    8.7395966 7.7023993 5.5855063     6.4358511   8.6755076
chr1-16085-16372   0.3689373 0.5886610 0.5700703     0.5608474   0.6904080
chr1-17357-17657   0.6496503 0.9222732 0.7066591     0.9302396   1.0170769
chr1-29216-29497   0.6560571 0.8481909 0.6847753     1.0352646   0.7622714
chr1-102789-103089 0.2493278 1.7533705 0.5029947     0.1619229   2.9992996
chr1-136647-136947 0.3496776 0.4750712 0.2087893     0.1753256   0.7074988
                   HSC       Mast      Myeloid   NK         Schwann   T
chr1-9967-10267    5.5550483 7.7470449 6.7632950 7.08521175 6.6466939 9.8673595
chr1-16085-16372   0.4698842 0.2032196 0.3561125 0.84943948 0.0000000 0.3289936
chr1-17357-17657   0.9070568 0.3852091 0.7205506 0.57254260 3.7784244 0.8094642
chr1-29216-29497   0.5803967 0.3221267 0.8010498 1.08348538 0.3453343 1.7418383
chr1-102789-103089 0.2329188 0.0000000 0.1928864 0.20152641 0.3060278 0.1078004
chr1-136647-136947 0.2136810 0.0000000 0.3083845 0.01512127 0.0000000 0.2246982

## H3K27ac

In [8]:
pseudobulk.counts <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

for (c in cells) {
    ct.counts <- rowSums(read.table(paste0(count.dir,c,'_perdonor.H3K27ac.counts.tsv')))
    if(length(rownames(pseudobulk.counts)) == 0) {
        pseudobulk.counts <- data.frame(ct.counts)
        colnames(pseudobulk.counts) <- c
    } else {
        pseudobulk.counts[[c]] <- ct.counts[rownames(pseudobulk.counts)]
    }
}

dim(pseudobulk.counts)
head(pseudobulk.counts)

write.table(pseudobulk.counts, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/celltype.H3K27ac.counts.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 391368     11

                 B   Bulk  Cholangiocyte Endothelial Hepatocytes HSC Mast
chr1:9595-10594  364 12496 614           1291        7180        555 4
chr1:10715-11714   0     2   0              0           2          0 0
chr1:11827-12826   0     0   0              0           0          0 0
chr1:13147-14146   2    66   2             23          32          2 0
chr1:15161-16160   2    82   0             22          39          3 0
chr1:16447-17446   3   114   7             18          61          4 0
                 Myeloid NK  Schwann T
chr1:9595-10594  1797    262 18      411
chr1:10715-11714    0      0  0        0
chr1:11827-12826    0      0  0        0
chr1:13147-14146    1      0  0        4
chr1:15161-16160   15      1  0        0
chr1:16447-17446   13      2  0        6

In [9]:
CPM.by.cell <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

for (c in cells) {
    ct.CPM <- rowMeans(read.table(paste0(count.dir,c,'_perdonor.H3K27ac.CPM.tsv')), na.rm=T)
    if(length(rownames(CPM.by.cell)) == 0) {
        CPM.by.cell <- data.frame(ct.CPM)
        colnames(CPM.by.cell) <- c
    } else {
        CPM.by.cell[[c]] <- ct.CPM[rownames(CPM.by.cell)]
    }
}

dim(CPM.by.cell)
head(CPM.by.cell)

write.table(CPM.by.cell, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/celltype.H3K27ac.CPM.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 391368     11

                 B           Bulk         Cholangiocyte Endothelial Hepatocytes
chr1:9595-10594  38.19500002 31.190656264 18.3952171    23.9507454  34.55330044
chr1:10715-11714  0.00000000  0.007055125  0.0000000     0.0000000   0.01273853
chr1:11827-12826  0.00000000  0.000000000  0.0000000     0.0000000   0.00000000
chr1:13147-14146  0.03393618  0.138665696  0.0633468     0.3799126   0.13027645
chr1:15161-16160  0.12049989  0.222224826  0.0000000     0.3861243   0.21077493
chr1:16447-17446  0.10008876  0.263694535  0.1941793     0.3070845   0.25802251
                 HSC         Mast     Myeloid    NK          Schwann
chr1:9595-10594  23.67524632 20.80016 33.4551255 34.98730481 54.12936
chr1:10715-11714  0.00000000  0.00000  0.0000000  0.00000000  0.00000
chr1:11827-12826  0.00000000  0.00000  0.0000000  0.00000000  0.00000
chr1:13147-14146  0.08479292  0.00000  0.0113805  0.00000000  0.00000
chr1:15161-16160  0.11471339  0.00000  0.2956686  0.06270469  0.00000
chr1:16447-17446  0.17502274  0.00000  0.2348281  0.26241633  0.00000
                 T
chr1:9595-10594  38.0111644
chr1:10715-11714  0.0000000
chr1:11827-12826  0.0000000
chr1:13147-14146  0.6945165
chr1:15161-16160  0.0000000
chr1:16447-17446  0.2339559

## H3K27me3

In [10]:
pseudobulk.counts <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

for (c in cells) {
    ct.counts <- rowSums(read.table(paste0(count.dir,c,'_perdonor.H3K27me3.counts.tsv')))
    if(length(rownames(pseudobulk.counts)) == 0) {
        pseudobulk.counts <- data.frame(ct.counts)
        colnames(pseudobulk.counts) <- c
    } else {
        pseudobulk.counts[[c]] <- ct.counts[rownames(pseudobulk.counts)]
    }
}

dim(pseudobulk.counts)
head(pseudobulk.counts)

write.table(pseudobulk.counts, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/celltype.H3K27me3.counts.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 466057     11

                 B  Bulk Cholangiocyte Endothelial Hepatocytes HSC Mast Myeloid
chr1:9566-11065  84 4832 264           280         3070        202 2    758
chr1:29153-30652  0   30   3             2           20          0 0      5
chr1:30872-32371  1   15   0             2           10          0 0      0
chr1:33873-35372  0    0   0             0            0          0 0      0
chr1:37119-38618  0    2   0             0            2          0 0      0
chr1:39169-40668  2   97  10             2           63          3 0     13
                 NK Schwann T
chr1:9566-11065  64 4       104
chr1:29153-30652  0 0         0
chr1:30872-32371  1 0         1
chr1:33873-35372  0 0         0
chr1:37119-38618  0 0         0
chr1:39169-40668  0 0         4

In [11]:
CPM.by.cell <- data.frame()
count.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

for (c in cells) {
    ct.CPM <- rowMeans(read.table(paste0(count.dir,c,'_perdonor.H3K27me3.CPM.tsv')), na.rm=T)
    if(length(rownames(CPM.by.cell)) == 0) {
        CPM.by.cell <- data.frame(ct.CPM)
        colnames(CPM.by.cell) <- c
    } else {
        CPM.by.cell[[c]] <- ct.CPM[rownames(CPM.by.cell)]
    }
}

dim(CPM.by.cell)
head(CPM.by.cell)

write.table(CPM.by.cell, '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/celltype.H3K27me3.CPM.tsv',
           quote=F, col.names=T, row.names=T, sep='\t')

[1] 466057     11

                 B          Bulk        Cholangiocyte Endothelial Hepatocytes
chr1:9566-11065  5.58231234 7.492685733 6.0583248     6.02581500  7.42523812
chr1:29153-30652 0.00000000 0.052173421 0.1136639     0.06504395  0.05752727
chr1:30872-32371 0.04694103 0.032131339 0.0000000     0.03585901  0.03615382
chr1:33873-35372 0.00000000 0.000000000 0.0000000     0.00000000  0.00000000
chr1:37119-38618 0.00000000 0.001419288 0.0000000     0.00000000  0.00197193
chr1:39169-40668 0.18744262 0.130742272 0.1562600     0.02639302  0.12332164
                 HSC      Mast     Myeloid    NK         Schwann  T
chr1:9566-11065  9.857673 13.81244 8.99294170 8.94276684 20.30383 4.85553219
chr1:29153-30652 0.000000  0.00000 0.06182076 0.00000000  0.00000 0.00000000
chr1:30872-32371 0.000000  0.00000 0.00000000 0.06891552  0.00000 0.01764788
chr1:33873-35372 0.000000  0.00000 0.00000000 0.00000000  0.00000 0.00000000
chr1:37119-38618 0.000000  0.00000 0.00000000 0.00000000  0.00000 0.00000000
chr1:39169-40668 0.145379  0.00000 0.11289586 0.00000000  0.00000 0.06487156

# Subset ATAC to just cell type peaks

### Map the peaks back  

In bash  

cd /nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call  
mapfile -t cells < listofcells.txt  
for cell in ${cells[@]}; do bedtools intersect -a LiverUnionPeaks.bed -b ${cell}_peaks.narrowPeak -wa > ${cell}.spec.union.peaks.bed; done

### Counts

In [33]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

In [34]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [35]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/', 
                                   cell.type, '_peaks.union.bed'))
    peaks <- paste0(peaks.tab[,1], "-", peaks.tab[,2], "-", peaks.tab[,3])
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.ATAC.counts.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.ATAC.counts.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

### CPM

In [36]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/ATAC/'

In [37]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [42]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/', 
                                   cell.type, '_peaks.union.bed'))
    peaks <- paste0(peaks.tab[,1], "-", peaks.tab[,2], "-", peaks.tab[,3])
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.ATAC.CPM.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.ATAC.CPM.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

# Subset H3K27ac to just cell type peaks

### Counts

In [7]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

In [8]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [12]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27ac/FNIH_liver_H3K27ac.', 
                                   cell.type, '.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.H3K27ac.counts.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.H3K27ac.counts.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

### CPM

In [13]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27ac/'

In [14]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [15]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27ac/FNIH_liver_H3K27ac.', 
                                   cell.type, '.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.H3K27ac.CPM.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.H3K27ac.CPM.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

#### ATAC Peaks, H3K27ac signal

In [14]:
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/'

In [15]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [21]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/', 
                                   cell.type, '_peaks.union.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_H3K27ac_donor.LiverUnionPeaks.rpm.xls', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_H3K27ac_donor.LiverUnionPeaks.rpm.ct.peaks.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

# Subset H3K27me3 to just cell type peaks

### Counts

In [16]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

In [17]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [18]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27me3/FNIH_liver_H3K27me3.', 
                                   cell.type, '.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.H3K27me3.counts.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.H3K27me3.counts.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

### CPM

In [19]:
outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/count.matrices/H3K27me3/'

In [20]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [21]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27me3/FNIH_liver_H3K27me3.', 
                                   cell.type, '.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_perdonor.H3K27me3.CPM.tsv', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_perdonor.H3K27me3.CPM.union.ct.subset.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}

#### ATAC Peaks, H3K27ac signal

In [22]:
outdir <- '/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/'

In [23]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [24]:
##### NAME YOUR FILES #####
for (cell.type in cells){
    peaks.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/', 
                                   cell.type, '_peaks.union.bed'))
    peaks <- unique(paste0(peaks.tab[,1], ":", peaks.tab[,2], "-", peaks.tab[,3]))
    full_counts <- read.table(paste(outdir, cell.type, '_H3K27me3_donor.LiverUnionPeaks.rpm.xls', sep = ""), header=T, sep='\t')
    peaks.sub <- peaks[peaks %in% rownames(full_counts)]
    new_counts <- full_counts[peaks.sub,]
    write.table(new_counts, paste(outdir, cell.type, '_H3K27me3_donor.LiverUnionPeaks.rpm.ct.peaks.tsv', sep = ""),
               sep='\t', col.names=T, row.names=T, quote=F)
}