In [1]:
library(tidyr)
library(stringr)
library(vroom)
library(data.table)
options(scipen = 999)
library(biomaRt)
library(dplyr)

Attaching package: ‘dplyr’


The following object is masked from ‘package:biomaRt’:

    select


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [2]:
library(SNPlocs.Hsapiens.dbSNP155.GRCh38)
library(SNPlocs.Hsapiens.dbSNP155.GRCh37)

Warning message:
“replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘SNPlocs.Hsapiens.dbSNP155.GRCh37’”

Attaching package: ‘SNPlocs.Hsapiens.dbSNP155.GRCh37’


The following objects are masked from ‘package:SNPlocs.Hsapiens.dbSNP155.GRCh38’:

    .loadAlleles, .loadLoc, COMPATIBLE_BSGENOMES

In [2]:
# Setup directories
traits.dir = "/nfs/lab/FinnGen_R11/finemap/summary/"
finrich.dir = '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/'
traits.bed.dir = "/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH//traits/"

In [12]:
# Grep all traits
files = dir(traits.dir, pattern = ".SUSIE.snp.filter.tsv")
files = data.frame(files = paste0(traits.dir, files), 
           trait = str_split_fixed(files, ".SUSIE.snp.filter.tsv", n = 2)[,1])
message("all traits found: ", nrow(files))

# Grep traits we need
traits.ls = paste0(finrich.dir, 'FinnGen.trait.list.txt')
traits.ls = fread(traits.ls, header = FALSE)
traits.ls$trait = basename(traits.ls$V1)
traits.ls = traits.ls %>%
  distinct(trait, .keep_all = TRUE)
message("Traits found: ", nrow(traits.ls))
traits.ls$trait = str_split_fixed(traits.ls$trait, '.gz.ldsc.sumstats.gz', n=2)[,1]

# subset files for only traits we need
files = dplyr::filter(files, trait %in% traits.ls$trait)
message("Traits with fine mapped data for: ", nrow(files))
traits.use = files$files
head(files)

all traits found: 1250

Traits found: 65

Traits with fine mapped data for: 47

  files
1 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_BMI_IRN.SUSIE.snp.filter.tsv
2 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_C3_HEPATOCELLU_CARC_EXALLC.SUSIE.snp.filter.tsv
3 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_CIRRHOSIS_BROAD.SUSIE.snp.filter.tsv
4 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_CMV_HEPATITIS.SUSIE.snp.filter.tsv
5 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_D3_ANAEMIA_B12_DEF.SUSIE.snp.filter.tsv
6 /nfs/lab/FinnGen_R11/finemap/summary/finngen_R11_D3_ANAEMIA_IRONDEF_BLOODLOSS.SUSIE.snp.filter.tsv
  trait
1 finngen_R11_BMI_IRN
2 finngen_R11_C3_HEPATOCELLU_CARC_EXALLC
3 finngen_R11_CIRRHOSIS_BROAD
4 finngen_R11_CMV_HEPATITIS
5 finngen_R11_D3_ANAEMIA_B12_DEF
6 finngen_R11_D3_ANAEMIA_IRONDEF_BLOODLOSS

In [13]:
traits.ls$trait[!traits.ls$trait %in% files$trait]

 [1] "finngen_R11_AB1_HEPATITIS_A"
 [2] "finngen_R11_AB1_HEPATITIS_B"
 [3] "finngen_R11_AB1_VIRAL_HEPATITIS"
 [4] "finngen_R11_AUTOHEP"
 [5] "finngen_R11_D3_ANAEMIA_FOLATEDEF"
 [6] "finngen_R11_D3_ANAEMIAINCHRONICDISEASE"
 [7] "finngen_R11_D3_FAMIERYTHROCYTOCIS"
 [8] "finngen_R11_D3_NOCT_HAEMOGLOBINURIA"
 [9] "finngen_R11_D3_NUTRIANAEMIAOTHER"
[10] "finngen_R11_E4_AROMAMINO"
[11] "finngen_R11_E4_CARBONAS"
[12] "finngen_R11_E4_FLUIDELECTRONAS"
[13] "finngen_R11_E4_OBESITYDRUG"
[14] "finngen_R11_FIBROLIV"
[15] "finngen_R11_K11_CHOLANGI"
[16] "finngen_R11_K11_HEPFAIL"
[17] "finngen_R11_K11_OTHINFLIV"
[18] "finngen_R11_T1D_STRICT2"

In [15]:
fread(file.use)

      trait   region                   v                   cs cs_specific_prob
1     BMI_IRN chr1:159060-3159060      1:1658830:C:G       1  0.110196821
2     BMI_IRN chr1:159060-3159060      1:1658866:G:A       1  0.016392127
3     BMI_IRN chr1:159060-3159060      1:1659060:G:A       1  0.215491114
4     BMI_IRN chr1:159060-3159060      1:1659114:A:G       1  0.016439720
5     BMI_IRN chr1:159060-3159060      1:1659220:A:G       1  0.016049844
6     BMI_IRN chr1:159060-3159060      1:1661177:A:G       1  0.098474422
7     BMI_IRN chr1:159060-3159060      1:1661420:C:A       1  0.015569091
8     BMI_IRN chr1:159060-3159060      1:1665061:C:T       1  0.204759006
9     BMI_IRN chr1:159060-3159060      1:1665581:C:G       1  0.118042179
10    BMI_IRN chr1:159060-3159060      1:1667948:A:G       1  0.017517638
11    BMI_IRN chr1:159060-3159060      1:1668108:C:T       1  0.021779557
12    BMI_IRN chr1:159060-3159060      1:1668542:C:T       1  0.014756698
13    BMI_IRN chr1:159060-3159060      1:1668717:C:G       1  0.017281513
14    BMI_IRN chr1:159060-3159060      1:1668721:C:T       1  0.026531532
15    BMI_IRN chr1:159060-3159060      1:1669576:G:A       1  0.021072244
16    BMI_IRN chr1:159060-3159060      1:1669613:G:A       1  0.020976630
17    BMI_IRN chr1:47427412-50427412   1:48630369:C:T      2  0.074504773
18    BMI_IRN chr1:47427412-50427412   1:48642379:T:C      2  0.072255004
19    BMI_IRN chr1:47427412-50427412   1:48698526:C:T      2  0.081798525
20    BMI_IRN chr1:47427412-50427412   1:48867779:A:G      2  0.030009773
21    BMI_IRN chr1:47427412-50427412   1:48882568:A:G      2  0.029648135
22    BMI_IRN chr1:47427412-50427412   1:48930832:G:A      2  0.050171488
23    BMI_IRN chr1:47427412-50427412   1:49025125:A:T      2  0.014778334
24    BMI_IRN chr1:47427412-50427412   1:49050455:T:C      2  0.014718735
25    BMI_IRN chr1:47427412-50427412   1:49068590:A:G      2  0.014401215
26    BMI_IRN chr1:47427412-50427412   1:49074357:C:T      2  0.014404558
27    BMI_IRN chr1:47427412-50427412   1:49076964:T:C      2  0.014418695
28    BMI_IRN chr1:47427412-50427412   1:49077704:A:G      2  0.014399263
29    BMI_IRN chr1:47427412-50427412   1:49115912:G:C      2  0.013904218
30    BMI_IRN chr1:47427412-50427412   1:49158130:A:C      2  0.009827816
⋮     ⋮       ⋮                        ⋮                   ⋮  ⋮
15474 BMI_IRN chrX:117270470-120270470 23:118784800:G:C    1  0.004832931
15475 BMI_IRN chrX:117270470-120270470 23:118785006:A:G    1  0.012915048
15476 BMI_IRN chrX:117270470-120270470 23:118786246:C:T    1  0.008678663
15477 BMI_IRN chrX:117270470-120270470 23:118786645:A:G    1  0.006226962
15478 BMI_IRN chrX:117270470-120270470 23:118788090:G:C    1  0.003947914
15479 BMI_IRN chrX:117270470-120270470 23:118788557:A:G    1  0.007721362
15480 BMI_IRN chrX:117270470-120270470 23:118789548:A:G    1  0.008348696
15481 BMI_IRN chrX:117270470-120270470 23:118790134:A:G    1  0.006124324
15482 BMI_IRN chrX:117270470-120270470 23:118791935:A:G    1  0.018805352
15483 BMI_IRN chrX:117270470-120270470 23:118792416:C:T    1  0.008771707
15484 BMI_IRN chrX:117270470-120270470 23:118792757:C:CATG 1  0.007656920
15485 BMI_IRN chrX:117270470-120270470 23:118792818:T:G    1  0.007362756
15486 BMI_IRN chrX:123255820-126255820 23:124728142:G:A    1  0.062367175
15487 BMI_IRN chrX:123255820-126255820 23:124729589:A:G    1  0.033237212
15488 BMI_IRN chrX:123255820-126255820 23:124729949:T:C    1  0.030007018
15489 BMI_IRN chrX:123255820-126255820 23:124730088:C:T    1  0.029341375
15490 BMI_IRN chrX:123255820-126255820 23:124730230:C:A    1  0.029907017
15491 BMI_IRN chrX:123255820-126255820 23:124732518:C:T    1  0.025330927
15492 BMI_IRN chrX:123255820-126255820 23:124735015:C:T    1  0.028839645
15493 BMI_IRN chrX:123255820-126255820 23:124739864:G:A    1  0.043396208
15494 BMI_IRN chrX:123255820-126255820 23:124744266:A:T    1  0.046036184
15495 BMI_IRN chrX:123255820-126255820 23:124745852:AT:A   1  0.043371864
15496 BMI_IRN chrX:123255820-126255820 23:124747222:C:T    1  0.044220366
15497 BMI_IRN chrX:123255820-126255820 23:124747397:A:AAT  1  0.044162232
15498 BMI_IRN chrX:123255820-126255820 23:124750334:G:A    1  0.039918448
15499 BMI_IRN chrX:123255820-126255820 23:124755820:G:A    1  0.312191677
15500 BMI_IRN chrX:123255820-126255820 23:124755871:T:G    1  0.039903185
15501 BMI_IRN chrX:123255820-126255820 23:124757374:C:T    1  0.033926863
15502 BMI_IRN chrX:123255820-126255820 23:124757467:G:A    1  0.033862516
15503 BMI_IRN chrX:123255820-126255820 23:124757719:C:T    1  0.033612614
      chromosome position  allele1 allele2 maf       beta
1     chr1        1658830  C       G       0.2318850 -0.0190573
2     chr1        1658866  G       A       0.2758810 -0.0173331
3     chr1        1659060  G       A       0.2331100 -0.0193235
4     chr1        1659114  A       G       0.2759240 -0.0173298
5     chr1        1659220  A       G       0.2758990 -0.0173223
6     chr1        1661177  A       G       0.2300870 -0.0189844
7     chr1        1661420  C       A       0.2753970 -0.0173082
8     chr1        1665061  C       T       0.2279780 -0.0193452
9     chr1        1665581  C       G       0.2445130 -0.0185402
10    chr1        1667948  A       G       0.2244160 -0.0183528
11    chr1        1668108  C       T       0.2756760  0.0174535
12    chr1        1668542  C       T       0.2237690 -0.0183152
13    chr1        1668717  C       G       0.2244020 -0.0183528
14    chr1        1668721  C       T       0.2281990 -0.0185187
15    chr1        1669576  G       A       0.2242450 -0.0184443
16    chr1        1669613  G       A       0.2242620 -0.0184429
17    chr1       48630369  C       T       0.0148008  0.0562813
18    chr1       48642379  T       C       0.0147800  0.0562796
19    chr1       48698526  C       T       0.0152200  0.0563839
20    chr1       48867779  A       G       0.0151583  0.0545892
21    chr1       48882568  A       G       0.0151579  0.0545671
22    chr1       48930832  G       A       0.0135479  0.0586076
23    chr1       49025125  A       T       0.0151377  0.0531226
24    chr1       49050455  T       C       0.0151311  0.0531115
25    chr1       49068590  A       G       0.0151323  0.0530631
26    chr1       49074357  C       T       0.0151324  0.0530636
27    chr1       49076964  T       C       0.0151323  0.0530657
28    chr1       49077704  A       G       0.0151323  0.0530629
29    chr1       49115912  G       C       0.0151293  0.0529889
30    chr1       49158130  A       C       0.0150816  0.0523022
⋮     ⋮          ⋮         ⋮       ⋮       ⋮         ⋮
15474 chr23      118784800 G       C       0.193105  0.0297164
15475 chr23      118785006 A       G       0.192150  0.0299710
15476 chr23      118786246 C       T       0.192209  0.0298897
15477 chr23      118786645 A       G       0.192981  0.0297738
15478 chr23      118788090 G       C       0.192691  0.0297069
15479 chr23      118788557 A       G       0.192199  0.0298653
15480 chr23      118789548 A       G       0.192128  0.0298872
15481 chr23      118790134 A       G       0.192748  0.0298000
15482 chr23      118791935 A       G       0.192450  0.0300342
15483 chr23      118792416 C       T       0.192172  0.0298931
15484 chr23      118792757 C       CATG    0.192020  0.0298783
15485 chr23      118792818 T       G       0.192013  0.0298709
15486 chr23      124728142 G       A       0.138031  0.0222217
15487 chr23      124729589 A       G       0.136923  0.0220483
15488 chr23      124729949 T       C       0.136883  0.0220150
15489 chr23      124730088 C       T       0.136939  0.0220019
15490 chr23      124730230 C       A       0.136883  0.0220136
15491 chr23      124732518 C       T       0.137067  0.0219299
15492 chr23      124735015 C       T       0.136861  0.0219995
15493 chr23      124739864 G       A       0.144596  0.0218312
15494 chr23      124744266 A       T       0.144541  0.0218598
15495 chr23      124745852 AT      A       0.144536  0.0218433
15496 chr23      124747222 C       T       0.144573  0.0218457
15497 chr23      124747397 A       AAT     0.144572  0.0218453
15498 chr23      124750334 G       A       0.144310  0.0218270
15499 chr23      124755820 G       A       0.148523  0.0222708
15500 chr23      124755871 T       G       0.144099  0.0218509
15501 chr23      124757374 C       T       0.144331  0.0217717
15502 chr23      124757467 G       A       0.144331  0.0217711
15503 chr23      124757719 C       T       0.144331  0.0217685
      p                                          se
1     0.00000000000865765                        0.00279136
2     0.00000000004809500                        0.00263552
3     0.00000000000402346                        0.00278582
4     0.00000000004796230                        0.00263486
5     0.00000000004931740                        0.00263538
6     0.00000000001162520                        0.00279807
7     0.00000000005165350                        0.00263600
8     0.00000000000531741                        0.00280493
9     0.00000000001217590                        0.00273531
10    0.00000000008281330                        0.00282552
11    0.00000000003640830                        0.00263728
12    0.00000000010039700                        0.00283239
13    0.00000000008381080                        0.00282629
14    0.00000000004340100                        0.00280927
15    0.00000000006870680                        0.00282738
16    0.00000000006902400                        0.00282746
17    0.00000000584292000                        0.00966834
18    0.00000000607939000                        0.00967908
19    0.00000000427917000                        0.00960050
20    0.00000001064340000                        0.00954332
21    0.00000001080610000                        0.00954377
22    0.00000000728618000                        0.01013240
23    0.00000002623430000                        0.00954605
24    0.00000002641920000                        0.00954616
25    0.00000002717500000                        0.00954591
26    0.00000002716750000                        0.00954591
27    0.00000002713380000                        0.00954591
28    0.00000002717940000                        0.00954593
29    0.00000002845440000                        0.00954636
30    0.00000004475900000                        0.00955995
⋮     ⋮                                          ⋮
15474 0.0000000000000000000000000000000001068810 0.00241860
15475 0.0000000000000000000000000000000000395094 0.00242349
15476 0.0000000000000000000000000000000000591425 0.00242328
15477 0.0000000000000000000000000000000000827180 0.00241919
15478 0.0000000000000000000000000000000001334140 0.00242136
15479 0.0000000000000000000000000000000000665580 0.00242318
15480 0.0000000000000000000000000000000000614894 0.00242370
15481 0.0000000000000000000000000000000000842752 0.00242162
15482 0.0000000000000000000000000000000000269215 0.00242258
15483 0.0000000000000000000000000000000000584925 0.00242338
15484 0.0000000000000000000000000000000000671583 0.00242437
15485 0.0000000000000000000000000000000000698715 0.00242440
15486 0.0000000000000009536740000000000424068218 0.00276641
15487 0.0000000000000019037099999999999259075893 0.00277426
15488 0.0000000000000021256900000000000343410660 0.00277484
15489 0.0000000000000021923000000000001444394674 0.00277454
15490 0.0000000000000021330400000000000453054431 0.00277482
15491 0.0000000000000025526999999999998475915728 0.00277207
15492 0.0000000000000022197299999999998821565840 0.00277477
15493 0.0000000000000008264179999999999916963693 0.00271188
15494 0.0000000000000007764260000000000068737558 0.00271285
15495 0.0000000000000008207290000000000091026757 0.00271310
15496 0.0000000000000008068630000000000121643658 0.00271269
15497 0.0000000000000008081649999999999887503835 0.00271270
15498 0.0000000000000009107520000000000916088980 0.00271537
15499 0.0000000000000001130840000000000000876794 0.00268642
15500 0.0000000000000009240600000000000704081680 0.00271894
15501 0.0000000000000010784500000000000015429176 0.00271550
15502 0.0000000000000010806900000000000142756433 0.00271551
15503 0.0000000000000010894300000000000340215566 0.00271552
      most_severe           gene_most_severe
1     intron_variant        CDK11B
2     intron_variant        CDK11B
3     upstream_gene_variant CDK11B
4     upstream_gene_variant CDK11B
5     upstream_gene_variant CDK11B
6     intron_variant        SLC35E2B
7     intron_variant        SLC35E2B
8     3_prime_UTR_variant   SLC35E2B
9     3_prime_UTR_variant   SLC35E2B
10    intron_variant        SLC35E2B
11    intron_variant        SLC35E2B
12    intron_variant        SLC35E2B
13    intron_variant        SLC35E2B
14    intron_variant        SLC35E2B
15    intron_variant        SLC35E2B
16    intron_variant        SLC35E2B
17    intron_variant        AGBL4
18    intron_variant        AGBL4
19    intron_variant        AGBL4
20    intron_variant        AGBL4
21    intron_variant        AGBL4
22    intron_variant        AGBL4
23    intron_variant        AGBL4
24    intron_variant        AGBL4
25    intron_variant        AGBL4
26    intron_variant        AGBL4
27    intron_variant        AGBL4
28    intron_variant        AGBL4
29    intron_variant        AGBL4
30    intron_variant        AGBL4
⋮     ⋮                     ⋮
15474 intron_variant        IL13RA1
15475 intron_variant        IL13RA1
15476 intron_variant        IL13RA1
15477 intron_variant        IL13RA1
15478 intron_variant        IL13RA1
15479 intron_variant        IL13RA1
15480 intron_variant        IL13RA1
15481 intron_variant        IL13RA1
15482 3_prime_UTR_variant   IL13RA1
15483 3_prime_UTR_variant   IL13RA1
15484 3_prime_UTR_variant   IL13RA1
15485 3_prime_UTR_variant   IL13RA1
15486 intron_variant        TENM1
15487 intron_variant        TENM1
15488 intron_variant        TENM1
15489 intron_variant        TENM1
15490 intron_variant        TENM1
15491 intron_variant        TENM1
15492 intron_variant        TENM1
15493 intron_variant        TENM1
15494 intron_variant        TENM1
15495 intron_variant        TENM1
15496 intron_variant        TENM1
15497 intron_variant        TENM1
15498 intron_variant        TENM1
15499 intron_variant        TENM1
15500 intron_variant        TENM1
15501 intron_variant        TENM1
15502 intron_variant        TENM1
15503 intron_variant        TENM1

In [17]:
trait.data <- fread(file.use)
trait.data$variant 
trait.data$start <- trait.data$position - 1
trait.data %>%
        dplyr::select(chromosome, start, end=position, v, allele1, allele2, maf, beta, 
                     p, se, region, cs, cs_specific_prob)

NULL

      chromosome start     end       v                   allele1 allele2
1     chr1        1658829   1658830  1:1658830:C:G       C       G
2     chr1        1658865   1658866  1:1658866:G:A       G       A
3     chr1        1659059   1659060  1:1659060:G:A       G       A
4     chr1        1659113   1659114  1:1659114:A:G       A       G
5     chr1        1659219   1659220  1:1659220:A:G       A       G
6     chr1        1661176   1661177  1:1661177:A:G       A       G
7     chr1        1661419   1661420  1:1661420:C:A       C       A
8     chr1        1665060   1665061  1:1665061:C:T       C       T
9     chr1        1665580   1665581  1:1665581:C:G       C       G
10    chr1        1667947   1667948  1:1667948:A:G       A       G
11    chr1        1668107   1668108  1:1668108:C:T       C       T
12    chr1        1668541   1668542  1:1668542:C:T       C       T
13    chr1        1668716   1668717  1:1668717:C:G       C       G
14    chr1        1668720   1668721  1:1668721:C:T       C       T
15    chr1        1669575   1669576  1:1669576:G:A       G       A
16    chr1        1669612   1669613  1:1669613:G:A       G       A
17    chr1       48630368  48630369  1:48630369:C:T      C       T
18    chr1       48642378  48642379  1:48642379:T:C      T       C
19    chr1       48698525  48698526  1:48698526:C:T      C       T
20    chr1       48867778  48867779  1:48867779:A:G      A       G
21    chr1       48882567  48882568  1:48882568:A:G      A       G
22    chr1       48930831  48930832  1:48930832:G:A      G       A
23    chr1       49025124  49025125  1:49025125:A:T      A       T
24    chr1       49050454  49050455  1:49050455:T:C      T       C
25    chr1       49068589  49068590  1:49068590:A:G      A       G
26    chr1       49074356  49074357  1:49074357:C:T      C       T
27    chr1       49076963  49076964  1:49076964:T:C      T       C
28    chr1       49077703  49077704  1:49077704:A:G      A       G
29    chr1       49115911  49115912  1:49115912:G:C      G       C
30    chr1       49158129  49158130  1:49158130:A:C      A       C
⋮     ⋮          ⋮         ⋮         ⋮                   ⋮       ⋮
15474 chr23      118784799 118784800 23:118784800:G:C    G       C
15475 chr23      118785005 118785006 23:118785006:A:G    A       G
15476 chr23      118786245 118786246 23:118786246:C:T    C       T
15477 chr23      118786644 118786645 23:118786645:A:G    A       G
15478 chr23      118788089 118788090 23:118788090:G:C    G       C
15479 chr23      118788556 118788557 23:118788557:A:G    A       G
15480 chr23      118789547 118789548 23:118789548:A:G    A       G
15481 chr23      118790133 118790134 23:118790134:A:G    A       G
15482 chr23      118791934 118791935 23:118791935:A:G    A       G
15483 chr23      118792415 118792416 23:118792416:C:T    C       T
15484 chr23      118792756 118792757 23:118792757:C:CATG C       CATG
15485 chr23      118792817 118792818 23:118792818:T:G    T       G
15486 chr23      124728141 124728142 23:124728142:G:A    G       A
15487 chr23      124729588 124729589 23:124729589:A:G    A       G
15488 chr23      124729948 124729949 23:124729949:T:C    T       C
15489 chr23      124730087 124730088 23:124730088:C:T    C       T
15490 chr23      124730229 124730230 23:124730230:C:A    C       A
15491 chr23      124732517 124732518 23:124732518:C:T    C       T
15492 chr23      124735014 124735015 23:124735015:C:T    C       T
15493 chr23      124739863 124739864 23:124739864:G:A    G       A
15494 chr23      124744265 124744266 23:124744266:A:T    A       T
15495 chr23      124745851 124745852 23:124745852:AT:A   AT      A
15496 chr23      124747221 124747222 23:124747222:C:T    C       T
15497 chr23      124747396 124747397 23:124747397:A:AAT  A       AAT
15498 chr23      124750333 124750334 23:124750334:G:A    G       A
15499 chr23      124755819 124755820 23:124755820:G:A    G       A
15500 chr23      124755870 124755871 23:124755871:T:G    T       G
15501 chr23      124757373 124757374 23:124757374:C:T    C       T
15502 chr23      124757466 124757467 23:124757467:G:A    G       A
15503 chr23      124757718 124757719 23:124757719:C:T    C       T
      maf       beta       p
1     0.2318850 -0.0190573 0.00000000000865765
2     0.2758810 -0.0173331 0.00000000004809500
3     0.2331100 -0.0193235 0.00000000000402346
4     0.2759240 -0.0173298 0.00000000004796230
5     0.2758990 -0.0173223 0.00000000004931740
6     0.2300870 -0.0189844 0.00000000001162520
7     0.2753970 -0.0173082 0.00000000005165350
8     0.2279780 -0.0193452 0.00000000000531741
9     0.2445130 -0.0185402 0.00000000001217590
10    0.2244160 -0.0183528 0.00000000008281330
11    0.2756760  0.0174535 0.00000000003640830
12    0.2237690 -0.0183152 0.00000000010039700
13    0.2244020 -0.0183528 0.00000000008381080
14    0.2281990 -0.0185187 0.00000000004340100
15    0.2242450 -0.0184443 0.00000000006870680
16    0.2242620 -0.0184429 0.00000000006902400
17    0.0148008  0.0562813 0.00000000584292000
18    0.0147800  0.0562796 0.00000000607939000
19    0.0152200  0.0563839 0.00000000427917000
20    0.0151583  0.0545892 0.00000001064340000
21    0.0151579  0.0545671 0.00000001080610000
22    0.0135479  0.0586076 0.00000000728618000
23    0.0151377  0.0531226 0.00000002623430000
24    0.0151311  0.0531115 0.00000002641920000
25    0.0151323  0.0530631 0.00000002717500000
26    0.0151324  0.0530636 0.00000002716750000
27    0.0151323  0.0530657 0.00000002713380000
28    0.0151323  0.0530629 0.00000002717940000
29    0.0151293  0.0529889 0.00000002845440000
30    0.0150816  0.0523022 0.00000004475900000
⋮     ⋮         ⋮          ⋮
15474 0.193105  0.0297164  0.0000000000000000000000000000000001068810
15475 0.192150  0.0299710  0.0000000000000000000000000000000000395094
15476 0.192209  0.0298897  0.0000000000000000000000000000000000591425
15477 0.192981  0.0297738  0.0000000000000000000000000000000000827180
15478 0.192691  0.0297069  0.0000000000000000000000000000000001334140
15479 0.192199  0.0298653  0.0000000000000000000000000000000000665580
15480 0.192128  0.0298872  0.0000000000000000000000000000000000614894
15481 0.192748  0.0298000  0.0000000000000000000000000000000000842752
15482 0.192450  0.0300342  0.0000000000000000000000000000000000269215
15483 0.192172  0.0298931  0.0000000000000000000000000000000000584925
15484 0.192020  0.0298783  0.0000000000000000000000000000000000671583
15485 0.192013  0.0298709  0.0000000000000000000000000000000000698715
15486 0.138031  0.0222217  0.0000000000000009536740000000000424068218
15487 0.136923  0.0220483  0.0000000000000019037099999999999259075893
15488 0.136883  0.0220150  0.0000000000000021256900000000000343410660
15489 0.136939  0.0220019  0.0000000000000021923000000000001444394674
15490 0.136883  0.0220136  0.0000000000000021330400000000000453054431
15491 0.137067  0.0219299  0.0000000000000025526999999999998475915728
15492 0.136861  0.0219995  0.0000000000000022197299999999998821565840
15493 0.144596  0.0218312  0.0000000000000008264179999999999916963693
15494 0.144541  0.0218598  0.0000000000000007764260000000000068737558
15495 0.144536  0.0218433  0.0000000000000008207290000000000091026757
15496 0.144573  0.0218457  0.0000000000000008068630000000000121643658
15497 0.144572  0.0218453  0.0000000000000008081649999999999887503835
15498 0.144310  0.0218270  0.0000000000000009107520000000000916088980
15499 0.148523  0.0222708  0.0000000000000001130840000000000000876794
15500 0.144099  0.0218509  0.0000000000000009240600000000000704081680
15501 0.144331  0.0217717  0.0000000000000010784500000000000015429176
15502 0.144331  0.0217711  0.0000000000000010806900000000000142756433
15503 0.144331  0.0217685  0.0000000000000010894300000000000340215566
      se         region                   cs cs_specific_prob
1     0.00279136 chr1:159060-3159060      1  0.110196821
2     0.00263552 chr1:159060-3159060      1  0.016392127
3     0.00278582 chr1:159060-3159060      1  0.215491114
4     0.00263486 chr1:159060-3159060      1  0.016439720
5     0.00263538 chr1:159060-3159060      1  0.016049844
6     0.00279807 chr1:159060-3159060      1  0.098474422
7     0.00263600 chr1:159060-3159060      1  0.015569091
8     0.00280493 chr1:159060-3159060      1  0.204759006
9     0.00273531 chr1:159060-3159060      1  0.118042179
10    0.00282552 chr1:159060-3159060      1  0.017517638
11    0.00263728 chr1:159060-3159060      1  0.021779557
12    0.00283239 chr1:159060-3159060      1  0.014756698
13    0.00282629 chr1:159060-3159060      1  0.017281513
14    0.00280927 chr1:159060-3159060      1  0.026531532
15    0.00282738 chr1:159060-3159060      1  0.021072244
16    0.00282746 chr1:159060-3159060      1  0.020976630
17    0.00966834 chr1:47427412-50427412   2  0.074504773
18    0.00967908 chr1:47427412-50427412   2  0.072255004
19    0.00960050 chr1:47427412-50427412   2  0.081798525
20    0.00954332 chr1:47427412-50427412   2  0.030009773
21    0.00954377 chr1:47427412-50427412   2  0.029648135
22    0.01013240 chr1:47427412-50427412   2  0.050171488
23    0.00954605 chr1:47427412-50427412   2  0.014778334
24    0.00954616 chr1:47427412-50427412   2  0.014718735
25    0.00954591 chr1:47427412-50427412   2  0.014401215
26    0.00954591 chr1:47427412-50427412   2  0.014404558
27    0.00954591 chr1:47427412-50427412   2  0.014418695
28    0.00954593 chr1:47427412-50427412   2  0.014399263
29    0.00954636 chr1:47427412-50427412   2  0.013904218
30    0.00955995 chr1:47427412-50427412   2  0.009827816
⋮     ⋮          ⋮                        ⋮  ⋮
15474 0.00241860 chrX:117270470-120270470 1  0.004832931
15475 0.00242349 chrX:117270470-120270470 1  0.012915048
15476 0.00242328 chrX:117270470-120270470 1  0.008678663
15477 0.00241919 chrX:117270470-120270470 1  0.006226962
15478 0.00242136 chrX:117270470-120270470 1  0.003947914
15479 0.00242318 chrX:117270470-120270470 1  0.007721362
15480 0.00242370 chrX:117270470-120270470 1  0.008348696
15481 0.00242162 chrX:117270470-120270470 1  0.006124324
15482 0.00242258 chrX:117270470-120270470 1  0.018805352
15483 0.00242338 chrX:117270470-120270470 1  0.008771707
15484 0.00242437 chrX:117270470-120270470 1  0.007656920
15485 0.00242440 chrX:117270470-120270470 1  0.007362756
15486 0.00276641 chrX:123255820-126255820 1  0.062367175
15487 0.00277426 chrX:123255820-126255820 1  0.033237212
15488 0.00277484 chrX:123255820-126255820 1  0.030007018
15489 0.00277454 chrX:123255820-126255820 1  0.029341375
15490 0.00277482 chrX:123255820-126255820 1  0.029907017
15491 0.00277207 chrX:123255820-126255820 1  0.025330927
15492 0.00277477 chrX:123255820-126255820 1  0.028839645
15493 0.00271188 chrX:123255820-126255820 1  0.043396208
15494 0.00271285 chrX:123255820-126255820 1  0.046036184
15495 0.00271310 chrX:123255820-126255820 1  0.043371864
15496 0.00271269 chrX:123255820-126255820 1  0.044220366
15497 0.00271270 chrX:123255820-126255820 1  0.044162232
15498 0.00271537 chrX:123255820-126255820 1  0.039918448
15499 0.00268642 chrX:123255820-126255820 1  0.312191677
15500 0.00271894 chrX:123255820-126255820 1  0.039903185
15501 0.00271550 chrX:123255820-126255820 1  0.033926863
15502 0.00271551 chrX:123255820-126255820 1  0.033862516
15503 0.00271552 chrX:123255820-126255820 1  0.033612614

In [22]:
# Make bed files
for (i in seq_along(traits.use)){
    # Grep files and make names
    file.use = files[i,1]
    trait.use = files[i,2]
    message("Making a bed for ", trait.use)
    out.bed.file = paste(traits.bed.dir, trait.use, "_Hg38.bed", sep = "")
    # Read table
    trait.data = fread(file.use)
    # Manipolate table
    trait.data$variant 
    trait.data$start <- trait.data$position - 1
    trait.data <- trait.data %>%
        dplyr::select(chromosome, start, end=position, v, allele1, allele2, maf, beta, 
                     p, se, trait, region, cs, cs_specific_prob)
    # Write bed
    print(trait.use)
    print(head(trait.data))
    write.table(trait.data,
                file = out.bed.file,
                col.names = F, row.names = F, sep = "\t", quote = F)
}

Making a bed for finngen_R11_BMI_IRN

[1] "finngen_R11_BMI_IRN"
   chromosome   start     end             v allele1 allele2      maf       beta
       <char>   <num>   <int>        <char>  <char>  <char>    <num>      <num>
1:       chr1 1658829 1658830 1:1658830:C:G       C       G 0.231885 -0.0190573
2:       chr1 1658865 1658866 1:1658866:G:A       G       A 0.275881 -0.0173331
3:       chr1 1659059 1659060 1:1659060:G:A       G       A 0.233110 -0.0193235
4:       chr1 1659113 1659114 1:1659114:A:G       A       G 0.275924 -0.0173298
5:       chr1 1659219 1659220 1:1659220:A:G       A       G 0.275899 -0.0173223
6:       chr1 1661176 1661177 1:1661177:A:G       A       G 0.230087 -0.0189844
                     p         se   trait              region    cs
                 <num>      <num>  <char>              <char> <int>
1: 0.00000000000865765 0.00279136 BMI_IRN chr1:159060-3159060     1
2: 0.00000000004809500 0.00263552 BMI_IRN chr1:159060-3159060     1
3: 0.00000000000402346 0.00278582 BMI_IRN chr1:159060-3159060     1
4: 0.00000000004796230 0.00263486 BMI_IRN chr1:159060-3159060     1
5: 0.00000000004931740 0.00263538 BMI_IRN chr1:159060-3159060     1
6: 0.00000000001162520 0.00279807 BMI_IRN chr1:159060-3159060     1
   cs_specific_prob
              <num>
1:       0.11019682
2:       0.01639213
3:       0.21549111
4:       0.01643972
5:       0.01604984
6:       0.09847442

Making a bed for finngen_R11_C3_HEPATOCELLU_CARC_EXALLC

[1] "finngen_R11_C3_HEPATOCELLU_CARC_EXALLC"
   chromosome    start      end               v allele1 allele2       maf
       <char>    <num>    <int>          <char>  <char>  <char>     <num>
1:      chr19 19245098 19245099 19:19245099:A:G       A       G 0.0488500
2:      chr19 19282904 19282905 19:19282905:G:A       G       A 0.1584750
3:      chr19 19295316 19295317 19:19295317:G:A       G       A 0.0487731
4:      chr19 19296460 19296461 19:19296461:A:G       A       G 0.0489047
5:      chr19 19297354 19297355 19:19297355:G:A       G       A 0.0486753
6:      chr19 19310030 19310031 19:19310031:C:G       C       G 0.0486360
         beta                                p        se
        <num>                            <num>     <num>
1: -0.1057400 0.427057000000000019923618310713 0.1331340
2:  0.6849900 0.000000000000000000000000207444 0.0657571
3: -0.0717712 0.590142999999999973148590015626 0.1332480
4: -0.0623591 0.639562999999999992617460975453 0.1331580
5: -0.0706565 0.595462999999999964551022912929 0.1330790
6: -0.0691508 0.603936000000000028364866011543 0.1333030
                        trait                  region    cs cs_specific_prob
                       <char>                  <char> <int>            <num>
1: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     2       0.41185778
2: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     1       1.00000000
3: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     2       0.07190059
4: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     2       0.03992992
5: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     2       0.06637535
6: C3_HEPATOCELLU_CARC_EXALLC chr19:17782905-20782905     2       0.06199245

Making a bed for finngen_R11_CIRRHOSIS_BROAD

[1] "finngen_R11_CIRRHOSIS_BROAD"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr4 87291569 87291570 4:87291570:G:A       G       A 0.227431
2:       chr4 87294311 87294312 4:87294312:A:G       A       G 0.227298
3:       chr4 87296625 87296626 4:87296626:G:C       G       C 0.227239
4:       chr4 87297571 87297572 4:87297572:A:G       A       G 0.227242
5:       chr4 87298959 87298960 4:87298960:A:G       A       G 0.227246
6:       chr4 87299393 87299394 4:87299394:C:T       C       T 0.227175
        beta                     p        se           trait
       <num>                 <num>     <num>          <char>
1: -0.190353 0.0000000000000432912 0.0252099 CIRRHOSIS_BROAD
2: -0.190310 0.0000000000000443507 0.0252148 CIRRHOSIS_BROAD
3: -0.190231 0.0000000000000453942 0.0252145 CIRRHOSIS_BROAD
4: -0.190247 0.0000000000000452272 0.0252150 CIRRHOSIS_BROAD
5: -0.190311 0.0000000000000446786 0.0252182 CIRRHOSIS_BROAD
6: -0.190309 0.0000000000000454883 0.0252257 CIRRHOSIS_BROAD
                   region    cs cs_specific_prob
                   <char> <int>            <num>
1: chr4:85810713-88810713     1      0.003243634
2: chr4:85810713-88810713     1      0.003150966
3: chr4:85810713-88810713     1      0.003077859
4: chr4:85810713-88810713     1      0.003088871
5: chr4:85810713-88810713     1      0.003125354
6: chr4:85810713-88810713     1      0.003077426

Making a bed for finngen_R11_CMV_HEPATITIS

[1] "finngen_R11_CMV_HEPATITIS"
   chromosome     start       end               v allele1 allele2         maf
       <char>     <num>     <int>          <char>  <char>  <char>       <num>
1:       chr6 112758340 112758341 6:112758341:T:A       T       A 0.000311497
      beta              p       se         trait                   region    cs
     <num>          <num>    <num>        <char>                   <char> <int>
1: 4.63839 0.000000014239 0.817988 CMV_HEPATITIS chr6:111258341-114258341     1
   cs_specific_prob
              <num>
1:        0.9648579

Making a bed for finngen_R11_D3_ANAEMIA_B12_DEF

[1] "finngen_R11_D3_ANAEMIA_B12_DEF"
   chromosome     start       end                  v allele1 allele2      maf
       <char>     <num>     <int>             <char>  <char>  <char>    <num>
1:       chr1 113761185 113761186    1:113761186:C:A       C       A 0.145970
2:       chr1 113834945 113834946    1:113834946:A:G       A       G 0.147649
3:       chr1 200746619 200746620   1:200746620:AT:A      AT       A 0.321960
4:       chr1 200749440 200749441 1:200749441:C:CTTG       C    CTTG 0.325374
5:       chr1 200757450 200757451    1:200757451:A:G       A       G 0.325375
6:       chr1 200772584 200772585    1:200772585:T:G       T       G 0.325380
        beta                                         p        se
       <num>                                     <num>     <num>
1:  0.357257 0.000000000000000000000000000000001377530 0.0295787
2: -0.360655 0.000000000000000000000000000000000130287 0.0293918
3:  0.131004 0.000000043657599999999997801641501721931 0.0239260
4:  0.125199 0.000000153748000000000007980038721835947 0.0238564
5:  0.125196 0.000000153832999999999998484129346172644 0.0238563
6:  0.125296 0.000000150611999999999998957052153858438 0.0238577
                trait                   region    cs cs_specific_prob
               <char>                   <char> <int>            <num>
1: D3_ANAEMIA_B12_DEF chr1:112334946-115334946     1       0.08908152
2: D3_ANAEMIA_B12_DEF chr1:112334946-115334946     1       0.91040996
3: D3_ANAEMIA_B12_DEF chr1:199246620-202246620     1       0.13523057
4: D3_ANAEMIA_B12_DEF chr1:199246620-202246620     1       0.04174290
5: D3_ANAEMIA_B12_DEF chr1:199246620-202246620     1       0.04172099
6: D3_ANAEMIA_B12_DEF chr1:199246620-202246620     1       0.04254932

Making a bed for finngen_R11_D3_ANAEMIA_IRONDEF_BLOODLOSS

[1] "finngen_R11_D3_ANAEMIA_IRONDEF_BLOODLOSS"
   chromosome    start      end                               v allele1
       <char>    <num>    <int>                          <char>  <char>
1:      chr17 58358768 58358769                 17:58358769:C:T       C
2:      chr17 58440937 58440938                 17:58440938:T:A       T
3:      chr17 58480781 58480782 17:58480782:T:TCTATCTATCTATCTAC       T
             allele2       maf     beta                      p        se
              <char>     <num>    <num>                  <num>     <num>
1:                 T 0.0130231 0.557466 0.00000000000000104184 0.0694936
2:                 A 0.0123798 0.547313 0.00000000000001791430 0.0714064
3: TCTATCTATCTATCTAC 0.0124071 0.543437 0.00000000000002720820 0.0714019
                          trait                  region    cs cs_specific_prob
                         <char>                  <char> <int>            <num>
1: D3_ANAEMIA_IRONDEF_BLOODLOSS chr17:56858769-61637498     1       0.87028032
2: D3_ANAEMIA_IRONDEF_BLOODLOSS chr17:56858769-61637498     1       0.05529479
3: D3_ANAEMIA_IRONDEF_BLOODLOSS chr17:56858769-61637498     1       0.03690226

Making a bed for finngen_R11_D3_ANAEMIA_IRONDEF_NAS

[1] "finngen_R11_D3_ANAEMIA_IRONDEF_NAS"
   chromosome     start       end                v allele1 allele2       maf
       <char>     <num>     <int>           <char>  <char>  <char>     <num>
1:       chr1 169191219 169191220  1:169191220:C:T       C       T 0.0206181
2:       chr1 169238940 169238941  1:169238941:C:T       C       T 0.0205680
3:       chr1 169247173 169247174  1:169247174:C:G       C       G 0.0206210
4:       chr1 169331815 169331816 1:169331816:C:CA       C      CA 0.0212640
5:       chr1 169355554 169355555  1:169355555:T:C       T       C 0.0201690
6:       chr1 169465788 169465789  1:169465789:C:T       C       T 0.0199140
        beta                   p        se                  trait
       <num>               <num>     <num>                 <char>
1: -0.341991 0.00000000000639882 0.0497769 D3_ANAEMIA_IRONDEF_NAS
2:  0.340147 0.00000000000883283 0.0498431 D3_ANAEMIA_IRONDEF_NAS
3:  0.342165 0.00000000000626470 0.0497803 D3_ANAEMIA_IRONDEF_NAS
4:  0.331994 0.00000000001104330 0.0488785 D3_ANAEMIA_IRONDEF_NAS
5:  0.348895 0.00000000000487304 0.0504970 D3_ANAEMIA_IRONDEF_NAS
6:  0.344870 0.00000000001163320 0.0508307 D3_ANAEMIA_IRONDEF_NAS
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr1:168049811-171049811     1       0.06489563
2: chr1:168049811-171049811     1       0.04762394
3: chr1:168049811-171049811     1       0.06623151
4: chr1:168049811-171049811     1       0.03843725
5: chr1:168049811-171049811     1       0.08429763
6: chr1:168049811-171049811     1       0.03655452

Making a bed for finngen_R11_D3_ANAEMIA_IRONDEF

[1] "finngen_R11_D3_ANAEMIA_IRONDEF"
   chromosome     start       end               v allele1 allele2       maf
       <char>     <num>     <int>          <char>  <char>  <char>     <num>
1:       chr1 169549810 169549811 1:169549811:C:T       C       T 0.0199779
2:       chr4  25970242  25970243  4:25970243:C:T       C       T 0.0354720
3:       chr7  75831074  75831075  7:75831075:A:G       A       G 0.0725740
4:       chr7  75832876  75832877  7:75832877:A:G       A       G 0.0725760
5:       chr7  75833201  75833202  7:75833202:C:T       C       T 0.0727960
6:       chr7  75833255  75833256  7:75833256:A:G       A       G 0.0727930
        beta                      p        se              trait
       <num>                  <num>     <num>             <char>
1: -0.349856 0.00000000000000254976 0.0442229 D3_ANAEMIA_IRONDEF
2: -0.178176 0.00000002159930000000 0.0318246 D3_ANAEMIA_IRONDEF
3: -0.117505 0.00000001787270000000 0.0208659 D3_ANAEMIA_IRONDEF
4: -0.117578 0.00000001749440000000 0.0208652 D3_ANAEMIA_IRONDEF
5: -0.115720 0.00000002848130000000 0.0208485 D3_ANAEMIA_IRONDEF
6: -0.115722 0.00000002846620000000 0.0208484 D3_ANAEMIA_IRONDEF
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr1:168049811-171049811     1       0.95017021
2:   chr4:24470243-27470243     1       0.98526291
3:   chr7:74349890-77349890     1       0.04224817
4:   chr7:74349890-77349890     1       0.04308529
5:   chr7:74349890-77349890     1       0.02747679
6:   chr7:74349890-77349890     1       0.02749522

Making a bed for finngen_R11_D3_ANAEMIA

[1] "finngen_R11_D3_ANAEMIA"
   chromosome     start       end               v allele1 allele2       maf
       <char>     <num>     <int>          <char>  <char>  <char>     <num>
1:       chr1 113761185 113761186 1:113761186:C:A       C       A 0.1451720
2:       chr1 113834945 113834946 1:113834946:A:G       A       G 0.1469230
3:       chr6 103867825 103867826 6:103867826:G:A       G       A 0.0924769
4:       chr6 103870607 103870608 6:103870608:C:T       C       T 0.0887686
5:       chr6 103871333 103871334 6:103871334:T:C       T       C 0.0959238
6:       chr6 103877410 103877411 6:103877411:T:G       T       G 0.0958248
         beta                      p        se      trait
        <num>                  <num>     <num>     <char>
1:  0.1185680 0.00000000000001299870 0.0153868 D3_ANAEMIA
2: -0.1184830 0.00000000000000960285 0.0152993 D3_ANAEMIA
3: -0.0946249 0.00000071986300000000 0.0190933 D3_ANAEMIA
4: -0.0935576 0.00000147764000000000 0.0194335 D3_ANAEMIA
5: -0.0933818 0.00000064473300000000 0.0187615 D3_ANAEMIA
6: -0.0935337 0.00000062489900000000 0.0187692 D3_ANAEMIA
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr1:112334946-115334946     1       0.43425518
2: chr1:112334946-115334946     1       0.56036564
3: chr6:102452813-105452813     1       0.03214262
4: chr6:102452813-105452813     1       0.01698227
5: chr6:102452813-105452813     1       0.03630894
6: chr6:102452813-105452813     1       0.03738410

Making a bed for finngen_R11_D3_ANAEMIANAS

[1] "finngen_R11_D3_ANAEMIANAS"
   chromosome     start       end               v allele1 allele2        maf
       <char>     <num>     <int>          <char>  <char>  <char>      <num>
1:       chr1 234458015 234458016 1:234458016:A:C       A       C 0.01154370
2:       chr1 234463136 234463137 1:234463137:T:G       T       G 0.01156260
3:       chr3  24284680  24284681  3:24284681:A:G       A       G 0.00705229
4:       chr3  24313792  24313793  3:24313793:T:A       T       A 0.00941220
5:       chr3  24428729  24428730  3:24428730:G:A       G       A 0.00704259
6:       chr3  24428730  24428731  3:24428731:C:T       C       T 0.00704259
        beta                p        se         trait                   region
       <num>            <num>     <num>        <char>                   <char>
1: -0.350831 0.00000000746965 0.0606972 D3_ANAEMIANAS chr1:232958016-235958016
2: -0.347357 0.00000001317620 0.0611138 D3_ANAEMIANAS chr1:232958016-235958016
3: -0.370979 0.00000078485600 0.0751106 D3_ANAEMIANAS   chr3:22813793-25813793
4: -0.362571 0.00000003434160 0.0657102 D3_ANAEMIANAS   chr3:22813793-25813793
5: -0.360959 0.00000172187000 0.0754577 D3_ANAEMIANAS   chr3:22813793-25813793
6: -0.360959 0.00000172187000 0.0754577 D3_ANAEMIANAS   chr3:22813793-25813793
      cs cs_specific_prob
   <int>            <num>
1:     1       0.62519529
2:     1       0.36621901
3:     1       0.04728531
4:     1       0.87593460
5:     1       0.02265679
6:     1       0.02265679

Making a bed for finngen_R11_D3_COAGDEF_PURPUR_HAEMORRHAGIC

[1] "finngen_R11_D3_COAGDEF_PURPUR_HAEMORRHAGIC"
   chromosome     start       end                v allele1 allele2       maf
       <char>     <num>     <int>           <char>  <char>  <char>     <num>
1:       chr1 169129898 169129899  1:169129899:G:A       G       A 0.0604138
2:       chr1 169165888 169165889  1:169165889:A:C       A       C 0.0606979
3:       chr1 169171805 169171806 1:169171806:G:GT       G      GT 0.0618600
4:       chr1 169303212 169303213  1:169303213:A:T       A       T 0.0463040
5:       chr1 169303214 169303215  1:169303215:G:A       G       A 0.0463040
6:       chr1 169327625 169327626  1:169327626:C:T       C       T 0.0607720
        beta
       <num>
1:  0.608170
2:  0.606278
3:  0.597512
4: -0.737316
5: -0.737316
6: -0.605995
                                                                                                                              p
                                                                                                                          <num>
1: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006824959999999999647859657491
2: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005240830000000000283912234888
3: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000757705000000000040051222317338
4: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000119674
5: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000119674
6: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005155850000000000298902828765
          se                          trait                   region    cs
       <num>                         <char>                   <char> <int>
1: 0.0294267 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
2: 0.0293171 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
3: 0.0292344 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
4: 0.0319752 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
5: 0.0319752 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
6: 0.0293023 D3_COAGDEF_PURPUR_HAEMORRHAGIC chr1:167009161-172082090     2
   cs_specific_prob
              <num>
1:       0.06940880
2:       0.08370517
3:       0.03766255
4:       0.14050852
5:       0.14050852
6:       0.08306232

Making a bed for finngen_R11_D3_COAGDEF

[1] "finngen_R11_D3_COAGDEF"
   chromosome     start       end               v allele1 allele2        maf
       <char>     <num>     <int>          <char>  <char>  <char>      <num>
1:       chr1 169498415 169498416 1:169498416:G:A       G       A 0.01986500
2:       chr1 169549810 169549811 1:169549811:C:T       C       T 0.01997880
3:      chr11  46172704  46172705 11:46172705:G:C       G       C 0.00294442
4:      chr11  46276338  46276339 11:46276339:G:A       G       A 0.00289952
5:      chr11  46396128  46396129 11:46396129:C:T       C       T 0.00509547
6:      chr11  46517665  46517666 11:46517666:C:G       C       G 0.00291394
       beta                                                                p
      <num>                                                            <num>
1: -1.59083 0.00000000000000000000000000000000000000000000000000000004011440
2:  1.60044 0.00000000000000000000000000000000000000000000000000000000248485
3:  1.80575 0.00000000000007721470000000000570524126262059117397002546562268
4:  1.76880 0.00000000000034411199999999997806348726660028485772706285938938
5:  1.54720 0.00000000000002554470000000000032152958043505772733734412484330
6:  1.79124 0.00000000000008245179999999999608225967592735936273181177047498
         se      trait                   region    cs cs_specific_prob
      <num>     <char>                   <char> <int>            <num>
1: 0.100788 D3_COAGDEF chr1:167556373-173321171     1      0.059487907
2: 0.100287 D3_COAGDEF chr1:167556373-173321171     1      0.939823225
3: 0.241572 D3_COAGDEF  chr11:44857267-48546991     1      0.028149553
4: 0.243103 D3_COAGDEF  chr11:44857267-48546991     1      0.006710375
5: 0.203068 D3_COAGDEF  chr11:44857267-48546991     1      0.076751497
6: 0.239909 D3_COAGDEF  chr11:44857267-48546991     1      0.026216053

Making a bed for finngen_R11_D3_COAGDEFNAS

[1] "finngen_R11_D3_COAGDEFNAS"
   chromosome     start       end               v allele1 allele2         maf
       <char>     <num>     <int>          <char>  <char>  <char>       <num>
1:       chr1 165514660 165514661 1:165514661:C:T       C       T 0.007026700
2:       chr1 166063872 166063873 1:166063873:C:T       C       T 0.000345765
3:       chr1 167117540 167117541 1:167117541:A:G       A       G 0.000296113
4:       chr1 167313458 167313459 1:167313459:A:G       A       G 0.016220200
5:       chr1 167385787 167385788 1:167385788:A:G       A       G 0.000460213
6:       chr1 167437072 167437073 1:167437073:G:A       G       A 0.000944205
      beta                                 p       se         trait
     <num>                             <num>    <num>        <char>
1: 1.12793 0.0000000000000612491000000000020 0.150283 D3_COAGDEFNAS
2: 2.38849 0.0000006611350000000000236413450 0.480346 D3_COAGDEFNAS
3: 2.55389 0.0000001736840000000000086194970 0.488736 D3_COAGDEFNAS
4: 1.07072 0.0000000000000000000000000414381 0.101307 D3_COAGDEFNAS
5: 2.19736 0.0000000751761000000000030600480 0.408558 D3_COAGDEFNAS
6: 1.84701 0.0000000047947900000000001484049 0.315505 D3_COAGDEFNAS
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr1:164645313-165938305     1        0.9969850
2: chr1:165961410-167477587     5        0.2190278
3: chr1:165961410-167477587     5        0.7369516
4: chr1:165961410-167477587     1        1.0000000
5: chr1:165961410-167477587     3        0.9754917
6: chr1:165961410-167477587     2        0.9985588

Making a bed for finngen_R11_D3_COAGOTHER

[1] "finngen_R11_D3_COAGOTHER"
   chromosome     start       end               v allele1 allele2        maf
       <char>     <num>     <int>          <char>  <char>  <char>      <num>
1:       chr1 168920134 168920135 1:168920135:A:G       A       G 0.01406600
2:       chr1 169056815 169056816 1:169056816:G:A       G       A 0.01932840
3:       chr1 169105909 169105910 1:169105910:G:A       G       A 0.13283400
4:       chr1 169106210 169106211 1:169106211:T:C       T       C 0.15282400
5:       chr1 169135547 169135548 1:169135548:G:C       G       C 0.00318825
6:       chr1 169135667 169135668 1:169135668:T:C       T       C 0.01085230
         beta
        <num>
1:  1.8508900
2:  1.8040600
3: -0.1479740
4:  0.6109230
5: -0.5288070
6:  0.0288288
                                                                                                                                                                                                                                                   p
                                                                                                                                                                                                                                               <num>
1: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000216272000000000007445863104890649620495218617484836653
2: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000220293
3: 0.00071855499999999995330152158246050930756609886884689331054687500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
4: 0.00000000000000000000000000000000000000000000000000000000000000000000000040907200000000001753429728306674755714865035314331266101391420507083050414148266343557179595913104031442548007773458636032116495300948785405757001911837563140073444955
5: 0.03929610000000000047393200475198682397603988647460937500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
6: 0.83526800000000001045208364303107373416423797607421875000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
          se        trait                   region    cs cs_specific_prob
       <num>       <char>                   <char> <int>            <num>
1: 0.0635663 D3_COAGOTHER chr1:165043945-175550100     3        0.8653447
2: 0.0551879 D3_COAGOTHER chr1:165043945-175550100     3        0.1292481
3: 0.0437481 D3_COAGOTHER chr1:165043945-175550100    10        1.0000000
4: 0.0337783 D3_COAGOTHER chr1:165043945-175550100     1        0.9989609
5: 0.2565680 D3_COAGOTHER chr1:165043945-175550100     5        1.0000000
6: 0.1386330 D3_COAGOTHER chr1:165043945-175550100     6        1.0000000

Making a bed for finngen_R11_D3_HAEMOLYTICANAEMIA

[1] "finngen_R11_D3_HAEMOLYTICANAEMIA"
   chromosome     start       end                v allele1 allele2         maf
       <char>     <num>     <int>           <char>  <char>  <char>       <num>
1:      chr13 111396040 111396041 13:111396041:G:A       G       A 0.000282485
      beta                 p       se                trait
     <num>             <num>    <num>               <char>
1: 3.02419 0.000000000686594 0.490212 D3_HAEMOLYTICANAEMIA
                      region    cs cs_specific_prob
                      <char> <int>            <num>
1: chr13:109896041-112896041     1        0.9993639

Making a bed for finngen_R11_D3_HEREDOTHCLOFACTORS

[1] "finngen_R11_D3_HEREDOTHCLOFACTORS"
   chromosome     start       end               v allele1 allele2        maf
       <char>     <num>     <int>          <char>  <char>  <char>      <num>
1:       chr1 169121509 169121510 1:169121510:T:C       T       C 0.01999800
2:       chr1 169135547 169135548 1:169135548:G:C       G       C 0.00319571
3:       chr1 169135667 169135668 1:169135668:T:C       T       C 0.01084970
4:       chr1 169140154 169140155 1:169140155:G:A       G       A 0.41157100
5:       chr1 169141797 169141798 1:169141798:G:A       G       A 0.41154600
6:       chr1 169142422 169142423 1:169142423:C:T       C       T 0.41154300
         beta
        <num>
1:  2.4238400
2: -0.5088010
3: -0.0429127
4:  0.3072360
5:  0.3073400
6:  0.3073650
                                                                                                     p
                                                                                                 <num>
1: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000148149
2: 0.4969680000000000208437711535225389525294303894042968750000000000000000000000000000000000000000000
3: 0.9154120000000000034745539778668899089097976684570312500000000000000000000000000000000000000000000
4: 0.0001357809999999999930626187749638233981386292725801467895507812500000000000000000000000000000000
5: 0.0001351199999999999938008615751883212396933231502771377563476562500000000000000000000000000000000
6: 0.0001349520000000000048961251719603637866384815424680709838867187500000000000000000000000000000000
          se                 trait                   region    cs
       <num>                <char>                   <char> <int>
1: 0.1187810 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     3
2: 0.7490430 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     9
3: 0.4040190 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     8
4: 0.0805183 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     4
5: 0.0805201 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     4
6: 0.0805202 D3_HEREDOTHCLOFACTORS chr1:167167014-170020526     4
   cs_specific_prob
              <num>
1:        0.1837239
2:        1.0000000
3:        1.0000000
4:        0.1958005
5:        0.5550595
6:        0.2067541

Making a bed for finngen_R11_E4_AMINO

[1] "finngen_R11_E4_AMINO"
   chromosome    start      end               v allele1 allele2        maf
       <char>    <num>    <int>          <char>  <char>  <char>      <num>
1:      chr14 22765343 22765344 14:22765344:T:G       T       G 0.00332008
2:      chr14 22775937 22775938 14:22775938:T:A       T       A 0.00322221
      beta                  p       se    trait                  region    cs
     <num>              <num>    <num>   <char>                  <char> <int>
1: 2.36971 0.0000000000365258 0.358097 E4_AMINO chr14:21265344-24265344     1
2: 2.31003 0.0000000004052470 0.369488 E4_AMINO chr14:21265344-24265344     1
   cs_specific_prob
              <num>
1:       0.90616968
2:       0.09280386

Making a bed for finngen_R11_E4_AMINOTRANSPORT

[1] "finngen_R11_E4_AMINOTRANSPORT"
   chromosome    start      end               v allele1 allele2        maf
       <char>    <num>    <int>          <char>  <char>  <char>      <num>
1:      chr19 32864716 32864717 19:32864717:G:A       G       A 0.00179306
      beta               p       se             trait                  region
     <num>           <num>    <num>            <char>                  <char>
1: 3.17872 0.0000000439218 0.580662 E4_AMINOTRANSPORT chr19:31364717-34364717
      cs cs_specific_prob
   <int>            <num>
1:     1        0.9648598

Making a bed for finngen_R11_E4_CARBO

[1] "finngen_R11_E4_CARBO"
   chromosome     start       end               v allele1 allele2        maf
       <char>     <num>     <int>          <char>  <char>  <char>      <num>
1:       chr9 101411825 101411826 9:101411826:T:C       T       C 0.00624095
2:       chr9 101427573 101427574 9:101427574:C:G       C       G 0.00540697
      beta                    p       se    trait                  region    cs
     <num>                <num>    <num>   <char>                  <char> <int>
1: 2.08374 0.000000000008338730 0.304970 E4_CARBO chr9:99927574-104817056     1
2: 2.19798 0.000000000000216073 0.299515 E4_CARBO chr9:99927574-104817056     1
   cs_specific_prob
              <num>
1:       0.02820108
2:       0.94968060

Making a bed for finngen_R11_E4_FE_DEF

[1] "finngen_R11_E4_FE_DEF"
   chromosome    start      end                               v allele1
       <char>    <num>    <int>                          <char>  <char>
1:      chr17 58358768 58358769                 17:58358769:C:T       C
2:      chr17 58440937 58440938                 17:58440938:T:A       T
3:      chr17 58480781 58480782 17:58480782:T:TCTATCTATCTATCTAC       T
4:      chr17 58739322 58739323                 17:58739323:C:T       C
             allele2       maf    beta                    p       se     trait
              <char>     <num>   <num>                <num>    <num>    <char>
1:                 T 0.0135015 1.20301 0.000000000000431221 0.166039 E4_FE_DEF
2:                 A 0.0128327 1.19073 0.000000000002582260 0.170134 E4_FE_DEF
3: TCTATCTATCTATCTAC 0.0128619 1.17964 0.000000000004349110 0.170337 E4_FE_DEF
4:                 T 0.0128538 1.17851 0.000000000004455540 0.170258 E4_FE_DEF
                    region    cs cs_specific_prob
                    <char> <int>            <num>
1: chr17:56858769-61369487     1       0.71642439
2: chr17:56858769-61369487     1       0.12807501
3: chr17:56858769-61369487     1       0.07757854
4: chr17:56858769-61369487     1       0.07579644

Making a bed for finngen_R11_E4_FH_IHD

[1] "finngen_R11_E4_FH_IHD"
   chromosome     start       end                v allele1 allele2       maf
       <char>     <num>     <int>           <char>  <char>  <char>     <num>
1:       chr1  55039973  55039974   1:55039974:G:T       G       T 0.0369654
2:       chr1  55119170  55119171   1:55119171:G:A       G       A 0.0335855
3:       chr1 109274569 109274570  1:109274570:A:G       A       G 0.2158260
4:       chr1 109274967 109274968  1:109274968:G:T       G       T 0.2156290
5:       chr1 109275215 109275216  1:109275216:T:C       T       C 0.2143440
6:       chr1 109275535 109275536 1:109275536:C:CT       C      CT 0.2145200
        beta                    p        se     trait                   region
       <num>                <num>     <num>    <char>                   <char>
1: -0.583695 0.000000000000191779 0.0793666 E4_FH_IHD   chr1:53539974-56539974
2: -0.574324 0.000000000004107710 0.0828342 E4_FH_IHD   chr1:53539974-56539974
3: -0.227279 0.000000000003156460 0.0326055 E4_FH_IHD chr1:107774968-110774968
4: -0.229789 0.000000000001789370 0.0325942 E4_FH_IHD chr1:107774968-110774968
5:  0.224704 0.000000000005843860 0.0326443 E4_FH_IHD chr1:107774968-110774968
6:  0.225538 0.000000000004934010 0.0326514 E4_FH_IHD chr1:107774968-110774968
      cs cs_specific_prob
   <int>            <num>
1:     1       0.92558426
2:     1       0.04664393
3:     1       0.12866480
4:     1       0.22239232
5:     1       0.07136276
6:     1       0.08394847

Making a bed for finngen_R11_E4_FH

[1] "finngen_R11_E4_FH"
   chromosome     start       end                v allele1 allele2       maf
       <char>     <num>     <int>           <char>  <char>  <char>     <num>
1:       chr1  55039973  55039974   1:55039974:G:T       G       T 0.0374568
2:       chr1  55053500  55053501   1:55053501:G:A       G       A 0.4741220
3:       chr1 109274569 109274570  1:109274570:A:G       A       G 0.2162500
4:       chr1 109274967 109274968  1:109274968:G:T       G       T 0.2160440
5:       chr1 109275215 109275216  1:109275216:T:C       T       C 0.2147660
6:       chr1 109275535 109275536 1:109275536:C:CT       C      CT 0.2149180
        beta                          p        se  trait
       <num>                      <num>     <num> <char>
1: -0.517159 0.000000000000000000178484 0.0572983  E4_FH
2:  0.143356 0.000000000000052191500000 0.0190473  E4_FH
3: -0.168775 0.000000000000778395000000 0.0235557  E4_FH
4: -0.170799 0.000000000000407568000000 0.0235486  E4_FH
5:  0.165437 0.000000000002296150000000 0.0235826  E4_FH
6:  0.166045 0.000000000001923980000000 0.0235863  E4_FH
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1:   chr1:53539974-56539974     1       0.99421955
2:   chr1:53539974-56539974     2       0.97248864
3: chr1:107774968-110774968     1       0.14168013
4: chr1:107774968-110774968     1       0.26510326
5: chr1:107774968-110774968     1       0.05043230
6: chr1:107774968-110774968     1       0.05973263

Making a bed for finngen_R11_E4_FLUIDELECTRO

[1] "finngen_R11_E4_FLUIDELECTRO"
Empty data.table (0 rows and 14 cols): chromosome,start,end,v,allele1,allele2...

Making a bed for finngen_R11_E4_OBESITY

[1] "finngen_R11_E4_OBESITY"
   chromosome     start       end               v allele1 allele2       maf
       <char>     <num>     <int>          <char>  <char>  <char>     <num>
1:       chr1 109539928 109539929 1:109539929:T:G       T       G 0.0564640
2:       chr1 109540263 109540264 1:109540264:C:T       C       T 0.0564633
3:       chr1 109571881 109571882 1:109571882:C:T       C       T 0.0547910
4:       chr1 109588898 109588899 1:109588899:A:G       A       G 0.0551975
5:       chr1 109594261 109594262 1:109594262:T:C       T       C 0.0551719
6:       chr1 109604698 109604699 1:109604699:C:T       C       T 0.0583160
       beta                   p        se      trait                   region
      <num>               <num>     <num>     <char>                   <char>
1: 0.119207 0.00000000012881600 0.0185434 E4_OBESITY chr1:108104699-111104699
2: 0.119164 0.00000000013023300 0.0185415 E4_OBESITY chr1:108104699-111104699
3: 0.122260 0.00000000007705490 0.0187912 E4_OBESITY chr1:108104699-111104699
4: 0.123446 0.00000000004086020 0.0187014 E4_OBESITY chr1:108104699-111104699
5: 0.123446 0.00000000004127620 0.0187055 E4_OBESITY chr1:108104699-111104699
6: 0.124289 0.00000000000963385 0.0182460 E4_OBESITY chr1:108104699-111104699
      cs cs_specific_prob
   <int>            <num>
1:     1       0.02679576
2:     1       0.02652524
3:     1       0.04381053
4:     1       0.08005950
5:     1       0.07934026
6:     1       0.31272157

Making a bed for finngen_R11_E4_OBESITYCAL

[1] "finngen_R11_E4_OBESITYCAL"
   chromosome     start       end               v allele1 allele2       maf
       <char>     <num>     <int>          <char>  <char>  <char>     <num>
1:       chr1 109571881 109571882 1:109571882:C:T       C       T 0.0546947
2:       chr1 109588898 109588899 1:109588899:A:G       A       G 0.0550983
3:       chr1 109594261 109594262 1:109594262:T:C       T       C 0.0550732
4:       chr1 109604698 109604699 1:109604699:C:T       C       T 0.0582194
5:       chr1 109612065 109612066 1:109612066:T:C       T       C 0.0552269
6:       chr1 109629553 109629554 1:109629554:C:T       C       T 0.0536493
       beta                 p        se         trait                   region
      <num>             <num>     <num>        <char>                   <char>
1: 0.133365 0.000000001312620 0.0219862 E4_OBESITYCAL chr1:108104699-111104699
2: 0.134193 0.000000000863575 0.0218812 E4_OBESITYCAL chr1:108104699-111104699
3: 0.134416 0.000000000815793 0.0218854 E4_OBESITYCAL chr1:108104699-111104699
4: 0.137162 0.000000000127606 0.0213315 E4_OBESITYCAL chr1:108104699-111104699
5: 0.134206 0.000000000855264 0.0218779 E4_OBESITYCAL chr1:108104699-111104699
6: 0.136712 0.000000000707701 0.0221779 E4_OBESITYCAL chr1:108104699-111104699
      cs cs_specific_prob
   <int>            <num>
1:     1       0.03015083
2:     1       0.04486899
3:     1       0.04734770
4:     1       0.27414844
5:     1       0.04533752
6:     1       0.05472428

Making a bed for finngen_R11_E4_OBESITYNAS

[1] "finngen_R11_E4_OBESITYNAS"
   chromosome     start       end                  v allele1 allele2      maf
       <char>     <num>     <int>             <char>  <char>  <char>    <num>
1:       chr1 177899854 177899855    1:177899855:G:A       G       A 0.183977
2:       chr1 177903769 177903770    1:177903770:G:A       G       A 0.183975
3:       chr1 177904074 177904075    1:177904075:G:T       G       T 0.183981
4:       chr1 177904705 177904706    1:177904706:G:A       G       A 0.183976
5:       chr1 177906378 177906379    1:177906379:A:G       A       G 0.184262
6:       chr1 177906823 177906824 1:177906824:GCTA:G    GCTA       G 0.183976
        beta                p        se         trait                   region
       <num>            <num>     <num>        <char>                   <char>
1: 0.0905404 0.00000000542988 0.0155209 E4_OBESITYNAS chr1:176425456-179425456
2: 0.0905183 0.00000000544628 0.0155185 E4_OBESITYNAS chr1:176425456-179425456
3: 0.0898190 0.00000000712541 0.0155183 E4_OBESITYNAS chr1:176425456-179425456
4: 0.0905055 0.00000000547331 0.0155185 E4_OBESITYNAS chr1:176425456-179425456
5: 0.0906727 0.00000000507680 0.0155138 E4_OBESITYNAS chr1:176425456-179425456
6: 0.0905075 0.00000000546827 0.0155184 E4_OBESITYNAS chr1:176425456-179425456
      cs cs_specific_prob
   <int>            <num>
1:     1       0.03720755
2:     1       0.03710041
3:     1       0.02884685
4:     1       0.03692912
5:     1       0.03964689
6:     1       0.03696408

Making a bed for finngen_R11_E4_OBESITYXTRMALV

[1] "finngen_R11_E4_OBESITYXTRMALV"
   chromosome    start      end                  v allele1 allele2      maf
       <char>    <num>    <int>             <char>  <char>  <char>    <num>
1:      chr16 53765356 53765357 16:53765357:GACC:G    GACC       G 0.425891
2:      chr16 53765365 53765366   16:53765366:G:GT       G      GT 0.425893
3:      chr16 53765366 53765367    16:53765367:G:T       G       T 0.425893
4:      chr16 53765383 53765384    16:53765384:C:T       C       T 0.425896
5:      chr16 53765594 53765595    16:53765595:G:A       G       A 0.425919
6:      chr16 53765934 53765935    16:53765935:G:A       G       A 0.425756
       beta                    p        se             trait
      <num>                <num>     <num>            <char>
1: 0.277411 0.000000000000892483 0.0388197 E4_OBESITYXTRMALV
2: 0.277403 0.000000000000893511 0.0388194 E4_OBESITYXTRMALV
3: 0.277403 0.000000000000893511 0.0388194 E4_OBESITYXTRMALV
4: 0.277395 0.000000000000895159 0.0388197 E4_OBESITYXTRMALV
5: 0.277435 0.000000000000889816 0.0388207 E4_OBESITYXTRMALV
6: 0.277938 0.000000000000809282 0.0388204 E4_OBESITYXTRMALV
                    region    cs cs_specific_prob
                    <char> <int>            <num>
1: chr16:52272541-55272541     1      0.002825241
2: chr16:52272541-55272541     1      0.002822170
3: chr16:52272541-55272541     1      0.002822170
4: chr16:52272541-55272541     1      0.002817085
5: chr16:52272541-55272541     1      0.002833896
6: chr16:52272541-55272541     1      0.003102220

Making a bed for finngen_R11_F5_ALCOHOL_DEPENDENCE

[1] "finngen_R11_F5_ALCOHOL_DEPENDENCE"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr1 66009918 66009919 1:66009919:A:G       A       G 0.486329
2:       chr1 66037833 66037834 1:66037834:T:C       T       C 0.434823
3:       chr1 66041403 66041404 1:66041404:G:A       G       A 0.434675
4:       chr1 66043330 66043331 1:66043331:A:C       A       C 0.411320
5:       chr1 66044088 66044089 1:66044089:G:A       G       A 0.411335
6:       chr1 66045720 66045721 1:66045721:A:G       A       G 0.411328
        beta               p        se                 trait
       <num>           <num>     <num>                <char>
1: 0.0741222 0.0000001077230 0.0139506 F5_ALCOHOL_DEPENDENCE
2: 0.0716324 0.0000002756070 0.0139379 F5_ALCOHOL_DEPENDENCE
3: 0.0719325 0.0000002456180 0.0139377 F5_ALCOHOL_DEPENDENCE
4: 0.0789863 0.0000000199581 0.0140736 F5_ALCOHOL_DEPENDENCE
5: 0.0788819 0.0000000208320 0.0140736 F5_ALCOHOL_DEPENDENCE
6: 0.0791514 0.0000000187521 0.0140760 F5_ALCOHOL_DEPENDENCE
                   region    cs cs_specific_prob
                   <char> <int>            <num>
1: chr1:64545721-67545721     1      0.011654400
2: chr1:64545721-67545721     1      0.005344684
3: chr1:64545721-67545721     1      0.005954153
4: chr1:64545721-67545721     1      0.060958307
5: chr1:64545721-67545721     1      0.058543813
6: chr1:64545721-67545721     1      0.064642671

Making a bed for finngen_R11_F5_ALCOHOLAC

[1] "finngen_R11_F5_ALCOHOLAC"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr4 99318161 99318162 4:99318162:T:C       T       C 0.005039
       beta                   p       se        trait                  region
      <num>               <num>    <num>       <char>                  <char>
1: 0.927594 0.00000000000635331 0.134991 F5_ALCOHOLAC chr4:97818162-100818162
      cs cs_specific_prob
   <int>            <num>
1:     1        0.9999613

Making a bed for finngen_R11_GEST_DIABETES

[1] "finngen_R11_GEST_DIABETES"
   chromosome     start       end                 v allele1 allele2      maf
       <char>     <num>     <int>            <char>  <char>  <char>    <num>
1:       chr1 117596430 117596431   1:117596431:C:G       C       G 0.372626
2:       chr1 117598888 117598889 1:117598889:C:CCT       C     CCT 0.361996
3:       chr1 117599935 117599936   1:117599936:A:C       A       C 0.362780
4:       chr1 117600894 117600895   1:117600895:A:G       A       G 0.373512
5:       chr1 117601325 117601326   1:117601326:A:G       A       G 0.373289
6:       chr1 117611354 117611355   1:117611355:T:G       T       G 0.363173
         beta                p        se         trait                   region
        <num>            <num>     <num>        <char>                   <char>
1: -0.0697329 0.00000000538468 0.0119512 GEST_DIABETES chr1:116099936-119099936
2: -0.0689178 0.00000000977890 0.0120181 GEST_DIABETES chr1:116099936-119099936
3: -0.0701589 0.00000000516084 0.0120096 GEST_DIABETES chr1:116099936-119099936
4: -0.0694121 0.00000000620926 0.0119449 GEST_DIABETES chr1:116099936-119099936
5: -0.0692209 0.00000000685772 0.0119462 GEST_DIABETES chr1:116099936-119099936
6:  0.0683764 0.00000001231710 0.0120058 GEST_DIABETES chr1:116099936-119099936
      cs cs_specific_prob
   <int>            <num>
1:     1       0.10909768
2:     1       0.06139087
3:     1       0.11275511
4:     1       0.09477730
5:     1       0.08617146
6:     1       0.04945204

Making a bed for finngen_R11_HEIGHT_IRN

[1] "finngen_R11_HEIGHT_IRN"
   chromosome   start     end              v allele1 allele2      maf
       <char>   <num>   <int>         <char>  <char>  <char>    <num>
1:       chr1 8450516 8450517  1:8450517:T:C       T       C 0.300425
2:       chr1 8451440 8451441 1:8451441:C:CA       C      CA 0.300726
3:       chr1 8464816 8464817  1:8464817:G:A       G       A 0.300901
4:       chr1 8466081 8466082  1:8466082:G:A       G       A 0.300871
5:       chr1 8469463 8469464  1:8469464:T:C       T       C 0.300880
6:       chr1 8471050 8471051  1:8471051:A:G       A       G 0.300638
         beta                  p         se      trait                region
        <num>              <num>      <num>     <char>                <char>
1: -0.0117884 0.0000000000847227 0.00181584 HEIGHT_IRN chr1:6558425-12382807
2: -0.0118772 0.0000000000605480 0.00181543 HEIGHT_IRN chr1:6558425-12382807
3: -0.0118075 0.0000000000769130 0.00181472 HEIGHT_IRN chr1:6558425-12382807
4: -0.0117667 0.0000000000895365 0.00181483 HEIGHT_IRN chr1:6558425-12382807
5: -0.0118149 0.0000000000748859 0.00181474 HEIGHT_IRN chr1:6558425-12382807
6: -0.0117345 0.0000000001015500 0.00181519 HEIGHT_IRN chr1:6558425-12382807
      cs cs_specific_prob
   <int>            <num>
1:     5      0.002858381
2:     5      0.003994688
3:     5      0.003374619
4:     5      0.002955761
5:     5      0.003488914
6:     5      0.002738008

Making a bed for finngen_R11_K11_ALCOLIV

[1] "finngen_R11_K11_ALCOLIV"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr4 87275166 87275167 4:87275167:G:T       G       T 0.232810
2:       chr4 87280347 87280348 4:87280348:G:T       G       T 0.227513
3:       chr4 87280399 87280400 4:87280400:C:G       C       G 0.227473
4:       chr4 87284782 87284783 4:87284783:G:A       G       A 0.227512
5:       chr4 87285001 87285002 4:87285002:T:C       T       C 0.227512
6:       chr4 87285531 87285532 4:87285532:C:T       C       T 0.227512
        beta                 p        se       trait                 region
       <num>             <num>     <num>      <char>                 <char>
1: -0.183235 0.000000001170010 0.0301161 K11_ALCOLIV chr4:85810240-88810240
2: -0.186243 0.000000000884341 0.0303872 K11_ALCOLIV chr4:85810240-88810240
3: -0.186170 0.000000000902880 0.0303917 K11_ALCOLIV chr4:85810240-88810240
4: -0.186245 0.000000000884382 0.0303876 K11_ALCOLIV chr4:85810240-88810240
5: -0.186246 0.000000000884321 0.0303876 K11_ALCOLIV chr4:85810240-88810240
6: -0.186247 0.000000000884118 0.0303877 K11_ALCOLIV chr4:85810240-88810240
      cs cs_specific_prob
   <int>            <num>
1:     1       0.01196813
2:     1       0.01452317
3:     1       0.01425265
4:     1       0.01452234
5:     1       0.01452503
6:     1       0.01452611

Making a bed for finngen_R11_K11_CHOLANGI_STRICT

[1] "finngen_R11_K11_CHOLANGI_STRICT"
   chromosome     start       end               v allele1 allele2      maf
       <char>     <num>     <int>          <char>  <char>  <char>    <num>
1:       chr9 114293565 114293566 9:114293566:A:G       A       G 0.274252
        beta                p       se               trait
       <num>            <num>    <num>              <char>
1: -0.414501 0.00000000128342 0.068293 K11_CHOLANGI_STRICT
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr9:112793566-115793566     1        0.9635009

Making a bed for finngen_R11_K11_CHOLECYST

[1] "finngen_R11_K11_CHOLECYST"
   chromosome    start      end                 v allele1 allele2       maf
       <char>    <num>    <int>            <char>  <char>  <char>     <num>
1:       chr2 43825603 43825604 2:43825604:GTTA:G    GTTA       G 0.0768115
2:       chr2 43827851 43827852    2:43827852:G:A       G       A 0.0768976
3:       chr2 43830430 43830431    2:43830431:A:C       A       C 0.0770496
4:       chr2 43830685 43830686 2:43830686:TCTC:T    TCTC       T 0.0769781
5:       chr2 43831061 43831062    2:43831062:G:A       G       A 0.0769799
6:       chr2 43835958 43835959    2:43835959:G:C       G       C 0.0791895
       beta                            p        se         trait
      <num>                        <num>     <num>        <char>
1: 0.321298 0.00000000000000000001119180 0.0344588 K11_CHOLECYST
2: 0.321012 0.00000000000000000001111730 0.0344255 K11_CHOLECYST
3: 0.320715 0.00000000000000000001104840 0.0343913 K11_CHOLECYST
4: 0.320486 0.00000000000000000001193440 0.0343969 K11_CHOLECYST
5: 0.320506 0.00000000000000000001177330 0.0343937 K11_CHOLECYST
6: 0.327460 0.00000000000000000000041011 0.0338685 K11_CHOLECYST
                   region    cs cs_specific_prob
                   <char> <int>            <num>
1: chr2:42339108-45339108     1       0.01175496
2: chr2:42339108-45339108     1       0.01180567
3: chr2:42339108-45339108     1       0.01184235
4: chr2:42339108-45339108     1       0.01096532
5: chr2:42339108-45339108     1       0.01111464
6: chr2:42339108-45339108     1       0.26694480

Making a bed for finngen_R11_K11_CHOLECYSTECTOMY

[1] "finngen_R11_K11_CHOLECYSTECTOMY"
   chromosome     start       end                 v allele1 allele2      maf
       <char>     <num>     <int>            <char>  <char>  <char>    <num>
1:       chr1 150715889 150715890 1:150715890:AAT:A     AAT       A 0.465903
2:       chr1 150751270 150751271   1:150751271:T:C       T       C 0.354762
3:       chr1 150756199 150756200   1:150756200:T:C       T       C 0.354107
4:       chr1 150757506 150757507   1:150757507:G:A       G       A 0.354184
5:       chr1 150757707 150757708   1:150757708:C:A       C       A 0.354172
6:       chr1 150763103 150763104  1:150763104:TA:T      TA       T 0.354297
         beta               p         se               trait
        <num>           <num>      <num>              <char>
1: -0.0448057 0.0000000690049 0.00830697 K11_CHOLECYSTECTOMY
2: -0.0433645 0.0000005806710 0.00867718 K11_CHOLECYSTECTOMY
3: -0.0429744 0.0000007331620 0.00867755 K11_CHOLECYSTECTOMY
4: -0.0429984 0.0000007191510 0.00867583 K11_CHOLECYSTECTOMY
5: -0.0430966 0.0000006789220 0.00867605 K11_CHOLECYSTECTOMY
6: -0.0432462 0.0000006231460 0.00867717 K11_CHOLECYSTECTOMY
                     region    cs cs_specific_prob
                     <char> <int>            <num>
1: chr1:149474014-152474014     1      0.003697271
2: chr1:149474014-152474014     1      0.001378401
3: chr1:149474014-152474014     1      0.001107220
4: chr1:149474014-152474014     1      0.001127702
5: chr1:149474014-152474014     1      0.001190149
6: chr1:149474014-152474014     1      0.001289561

Making a bed for finngen_R11_K11_CHOLELITH

[1] "finngen_R11_K11_CHOLELITH"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr1 41908228 41908229 1:41908229:T:C       T       C 0.297993
2:       chr1 41927329 41927330 1:41927330:G:A       G       A 0.297952
3:       chr1 41935259 41935260 1:41935260:A:T       A       T 0.297954
4:       chr1 41943850 41943851 1:41943851:A:C       A       C 0.300452
5:       chr1 41946575 41946576 1:41946576:G:C       G       C 0.300293
6:       chr1 41959824 41959825 1:41959825:C:T       C       T 0.300802
        beta                  p         se         trait                 region
       <num>              <num>      <num>        <char>                 <char>
1: 0.0537099 0.0000000000305914 0.00808435 K11_CHOLELITH chr1:40435260-43435260
2: 0.0537913 0.0000000000284381 0.00808351 K11_CHOLELITH chr1:40435260-43435260
3: 0.0537920 0.0000000000284119 0.00808347 K11_CHOLELITH chr1:40435260-43435260
4: 0.0507516 0.0000000002983460 0.00805627 K11_CHOLELITH chr1:40435260-43435260
5: 0.0507454 0.0000000003015020 0.00805738 K11_CHOLELITH chr1:40435260-43435260
6: 0.0510995 0.0000000002214830 0.00805268 K11_CHOLELITH chr1:40435260-43435260
      cs cs_specific_prob
   <int>            <num>
1:     1       0.11619778
2:     1       0.12458913
3:     1       0.12469242
4:     1       0.01323337
5:     1       0.01315185
6:     1       0.01759929

Making a bed for finngen_R11_K11_DISLIVOTH

[1] "finngen_R11_K11_DISLIVOTH"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr1 16177885 16177886 1:16177886:T:C       T       C 0.275838
2:       chr1 16178053 16178054 1:16178054:T:C       T       C 0.275847
3:       chr1 16178808 16178809 1:16178809:T:C       T       C 0.263127
4:       chr1 16178824 16178825 1:16178825:A:G       A       G 0.317822
5:       chr1 16179412 16179413 1:16179413:C:T       C       T 0.275838
6:       chr1 16179764 16179765 1:16179765:A:G       A       G 0.275834
       beta               p        se         trait                 region
      <num>           <num>     <num>        <char>                 <char>
1: 0.100195 0.0000007047740 0.0202004 K11_DISLIVOTH chr1:14684399-17684399
2: 0.100197 0.0000007044010 0.0202004 K11_DISLIVOTH chr1:14684399-17684399
3: 0.102885 0.0000005348110 0.0205221 K11_DISLIVOTH chr1:14684399-17684399
4: 0.106181 0.0000000407568 0.0193494 K11_DISLIVOTH chr1:14684399-17684399
5: 0.100255 0.0000006942250 0.0202006 K11_DISLIVOTH chr1:14684399-17684399
6: 0.100185 0.0000007070660 0.0202010 K11_DISLIVOTH chr1:14684399-17684399
      cs cs_specific_prob
   <int>            <num>
1:     1       0.01381858
2:     1       0.01382512
3:     1       0.01785560
4:     1       0.19675307
5:     1       0.01401296
6:     1       0.01377621

Making a bed for finngen_R11_K11_FIBROCHIRLIV

[1] "finngen_R11_K11_FIBROCHIRLIV"
   chromosome    start      end               v allele1 allele2       maf
       <char>    <num>    <int>          <char>  <char>  <char>     <num>
1:      chr19 19245098 19245099 19:19245099:A:G       A       G 0.0490868
2:      chr19 19282904 19282905 19:19282905:G:A       G       A 0.1580820
3:      chr19 19295316 19295317 19:19295317:G:A       G       A 0.0490116
4:      chr19 19296460 19296461 19:19296461:A:G       A       G 0.0491377
5:      chr19 19297354 19297355 19:19297355:G:A       G       A 0.0489127
6:      chr19 19310030 19310031 19:19310031:C:G       C       G 0.0488732
         beta                    p        se            trait
        <num>                <num>     <num>           <char>
1: -0.0970322 0.153068000000000010 0.0679127 K11_FIBROCHIRLIV
2:  0.2819020 0.000000000000100763 0.0378906 K11_FIBROCHIRLIV
3: -0.1113790 0.101675000000000001 0.0680473 K11_FIBROCHIRLIV
4: -0.1108160 0.103375999999999996 0.0680393 K11_FIBROCHIRLIV
5: -0.1097490 0.106620000000000006 0.0680161 K11_FIBROCHIRLIV
6: -0.1135020 0.095516900000000002 0.0680880 K11_FIBROCHIRLIV
                    region    cs cs_specific_prob
                    <char> <int>            <num>
1: chr19:17782905-20782905     2       0.02039830
2: chr19:17782905-20782905     1       1.00000000
3: chr19:17782905-20782905     2       0.09082905
4: chr19:17782905-20782905     2       0.08095902
5: chr19:17782905-20782905     2       0.07624663
6: chr19:17782905-20782905     2       0.11090157

Making a bed for finngen_R11_K11_LIVER

[1] "finngen_R11_K11_LIVER"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr4 87280347 87280348 4:87280348:G:T       G       T 0.227222
2:       chr4 87280399 87280400 4:87280400:C:G       C       G 0.227182
3:       chr4 87282675 87282676 4:87282676:A:G       A       G 0.338028
4:       chr4 87284782 87284783 4:87284783:G:A       G       A 0.227221
5:       chr4 87285001 87285002 4:87285002:T:C       T       C 0.227221
6:       chr4 87285531 87285532 4:87285532:C:T       C       T 0.227221
         beta                    p        se     trait                 region
        <num>                <num>     <num>    <char>                 <char>
1: -0.1059480 0.000000000002425490 0.0151191 K11_LIVER chr4:85810240-88810240
2: -0.1058200 0.000000000002591190 0.0151209 K11_LIVER chr4:85810240-88810240
3: -0.0954562 0.000000000000689604 0.0132920 K11_LIVER chr4:85810240-88810240
4: -0.1059510 0.000000000002423820 0.0151193 K11_LIVER chr4:85810240-88810240
5: -0.1059570 0.000000000002417690 0.0151194 K11_LIVER chr4:85810240-88810240
6: -0.1059570 0.000000000002417690 0.0151194 K11_LIVER chr4:85810240-88810240
      cs cs_specific_prob
   <int>            <num>
1:     1      0.004301983
2:     1      0.004034921
3:     1      0.004406422
4:     1      0.004305134
5:     1      0.004315336
6:     1      0.004315349

Making a bed for finngen_R11_K11_TOXLIV

[1] "finngen_R11_K11_TOXLIV"
   chromosome    start      end              v allele1 allele2         maf
       <char>    <num>    <int>         <char>  <char>  <char>       <num>
1:       chr1 12865706 12865707 1:12865707:C:T       C       T 0.000399973
2:       chr1 12871402 12871403 1:12871403:C:G       C       G 0.000353761
3:       chr1 13402036 13402037 1:13402037:C:T       C       T 0.000443449
      beta               p       se      trait                 region    cs
     <num>           <num>    <num>     <char>                 <char> <int>
1: 3.45636 0.0000000195420 0.615449 K11_TOXLIV chr1:11371403-14371403     1
2: 3.47185 0.0000000155239 0.613870 K11_TOXLIV chr1:11371403-14371403     1
3: 3.18210 0.0000001187650 0.600920 K11_TOXLIV chr1:11371403-14371403     1
   cs_specific_prob
              <num>
1:       0.40965085
2:       0.50865887
3:       0.07534218

Making a bed for finngen_R11_NAFLD

[1] "finngen_R11_NAFLD"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr3 12890203 12890204 3:12890204:C:G       C       G 0.109158
2:       chr3 12900908 12900909 3:12900909:G:A       G       A 0.191170
3:       chr3 12904641 12904642 3:12904642:G:A       G       A 0.146962
4:       chr3 12915404 12915405 3:12915405:C:T       C       T 0.170471
5:       chr3 12920573 12920574 3:12920574:G:A       G       A 0.170743
6:       chr3 12921413 12921414 3:12921414:G:A       G       A 0.170718
        beta               p        se  trait                 region    cs
       <num>           <num>     <num> <char>                 <char> <int>
1: -0.233845 0.0000001179860 0.0441501  NAFLD chr3:11400909-14400909     1
2: -0.189562 0.0000000336961 0.0343343  NAFLD chr3:11400909-14400909     1
3: -0.198688 0.0000002170450 0.0383264  NAFLD chr3:11400909-14400909     1
4: -0.184590 0.0000002404750 0.0357388  NAFLD chr3:11400909-14400909     1
5: -0.185078 0.0000002228950 0.0357351  NAFLD chr3:11400909-14400909     1
6: -0.184947 0.0000002273740 0.0357355  NAFLD chr3:11400909-14400909     1
   cs_specific_prob
              <num>
1:       0.15198951
2:       0.49036057
3:       0.08606707
4:       0.07822883
5:       0.08396885
6:       0.08242152

Making a bed for finngen_R11_NASH

[1] "finngen_R11_NASH"
   chromosome    start      end               v allele1 allele2      maf
       <char>    <num>    <int>          <char>  <char>  <char>    <num>
1:      chr22 43928846 43928847 22:43928847:C:G       C       G 0.227121
2:      chr22 43928849 43928850 22:43928850:C:T       C       T 0.226955
3:      chr22 43928974 43928975 22:43928975:G:A       G       A 0.226656
4:      chr22 43945023 43945024 22:43945024:C:T       C       T 0.275359
       beta                  p        se  trait                  region    cs
      <num>              <num>     <num> <char>                  <char> <int>
1: 0.624529 0.0000000000309457 0.0940273   NASH chr22:42428975-45428975     1
2: 0.625280 0.0000000000292820 0.0940251   NASH chr22:42428975-45428975     1
3: 0.626611 0.0000000000267055 0.0940337   NASH chr22:42428975-45428975     1
4: 0.575930 0.0000000002517560 0.0910431   NASH chr22:42428975-45428975     1
   cs_specific_prob
              <num>
1:       0.28783285
2:       0.30341068
3:       0.33100412
4:       0.04136608

Making a bed for finngen_R11_P16_NEONTAL_JAUND_OTH_UNSP_CAUSES

[1] "finngen_R11_P16_NEONTAL_JAUND_OTH_UNSP_CAUSES"
   chromosome    start      end               v allele1 allele2         maf
       <char>    <num>    <int>          <char>  <char>  <char>       <num>
1:      chr12 97570428 97570429 12:97570429:T:A       T       A 0.000446787
2:      chr12 97712650 97712651 12:97712651:G:A       G       A 0.000534307
3:      chr12 97738739 97738740 12:97738740:T:C       T       C 0.000533629
4:      chr12 97764905 97764906 12:97764906:T:C       T       C 0.000406654
5:      chr12 97782684 97782685 12:97782685:G:C       G       C 0.000528005
      beta               p       se                             trait
     <num>           <num>    <num>                            <char>
1: 4.00498 0.0000000570059 0.737844 P16_NEONTAL_JAUND_OTH_UNSP_CAUSES
2: 3.88909 0.0000000123660 0.682944 P16_NEONTAL_JAUND_OTH_UNSP_CAUSES
3: 3.89226 0.0000000118228 0.682581 P16_NEONTAL_JAUND_OTH_UNSP_CAUSES
4: 4.20291 0.0000000282150 0.756986 P16_NEONTAL_JAUND_OTH_UNSP_CAUSES
5: 3.88333 0.0000000125086 0.682165 P16_NEONTAL_JAUND_OTH_UNSP_CAUSES
                    region    cs cs_specific_prob
                    <char> <int>            <num>
1: chr12:96238740-99238740     1       0.06309534
2: chr12:96238740-99238740     1       0.26550200
3: chr12:96238740-99238740     1       0.27698302
4: chr12:96238740-99238740     1       0.12208646
5: chr12:96238740-99238740     1       0.26267706

Making a bed for finngen_R11_T1D_EARLY

[1] "finngen_R11_T1D_EARLY"
   chromosome     start       end               v allele1 allele2      maf
       <char>     <num>     <int>          <char>  <char>  <char>    <num>
1:       chr1 113761185 113761186 1:113761186:C:A       C       A 0.146187
2:       chr1 113834945 113834946 1:113834946:A:G       A       G 0.147875
3:       chr4 122146652 122146653 4:122146653:G:A       G       A 0.454209
4:       chr4 122155739 122155740 4:122155740:A:G       A       G 0.454322
5:       chr4 122195706 122195707 4:122195707:T:G       T       G 0.454240
6:       chr4 122195839 122195840 4:122195840:T:C       T       C 0.454091
        beta                                                           p
       <num>                                                       <num>
1:  0.512249 0.000000000000000000000000000000000000000000000000000226152
2: -0.510109 0.000000000000000000000000000000000000000000000000000156892
3:  0.138608 0.000000335358999999999978989373818419328365791898249881342
4:  0.139087 0.000000306006000000000020485013641977078968636760691879317
5:  0.141139 0.000000203057999999999990936179450860821216195972738205455
6:  0.140594 0.000000225496999999999997511246330704481888318468918441795
          se     trait                   region    cs cs_specific_prob
       <num>    <char>                   <char> <int>            <num>
1: 0.0336358 T1D_EARLY chr1:112334946-115334946     1      0.410522425
2: 0.0334429 T1D_EARLY chr1:112334946-115334946     1      0.589477568
3: 0.0271653 T1D_EARLY chr4:120705785-123705785     1      0.006440875
4: 0.0271669 T1D_EARLY chr4:120705785-123705785     1      0.006994669
5: 0.0271604 T1D_EARLY chr4:120705785-123705785     1      0.010109881
6: 0.0271574 T1D_EARLY chr4:120705785-123705785     1      0.009202027

Making a bed for finngen_R11_T1D

[1] "finngen_R11_T1D"
   chromosome     start       end                 v allele1 allele2      maf
       <char>     <num>     <int>            <char>  <char>  <char>    <num>
1:       chr1 113761185 113761186   1:113761186:C:A       C       A 0.145649
2:       chr1 113834945 113834946   1:113834946:A:G       A       G 0.147343
3:       chr2 203826814 203826815   2:203826815:C:T       C       T 0.324210
4:       chr2 203827471 203827472 2:203827472:AAC:A     AAC       A 0.324211
5:       chr2 203829539 203829540   2:203829540:G:A       G       A 0.319490
6:       chr2 203832142 203832143  2:203832143:TA:T      TA       T 0.319477
        beta
       <num>
1:  0.512073
2: -0.509891
3: -0.143558
4: -0.143535
5: -0.146953
6: -0.147353
                                                                                      p
                                                                                  <num>
1: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000431817
2: 0.0000000000000000000000000000000000000000000000000000000000000000000000000000230569
3: 0.0000000017442099999999999149540380618769210008256465016529546119272708892822265625
4: 0.0000000017518200000000000572129618190537168886944385803872137330472469329833984375
5: 0.0000000008192189999999999810793859925702863761243222029406751971691846847534179688
6: 0.0000000007362069999999999579602744106889174180441415273890015669167041778564453125
          se  trait                   region    cs cs_specific_prob
       <num> <char>                   <char> <int>            <num>
1: 0.0275543    T1D chr1:112334946-115334946     1       0.35807421
2: 0.0273873    T1D chr1:112334946-115334946     1       0.64192579
3: 0.0238468    T1D chr2:202380280-205380280     1       0.01470056
4: 0.0238459    T1D chr2:202380280-205380280     1       0.01463483
5: 0.0239292    T1D chr2:202380280-205380280     1       0.02899110
6: 0.0239282    T1D chr2:202380280-205380280     1       0.03216860

Making a bed for finngen_R11_T2D_WIDE

[1] "finngen_R11_T2D_WIDE"
   chromosome    start      end               v allele1 allele2      maf
       <char>    <num>    <int>          <char>  <char>  <char>    <num>
1:       chr1 39121715 39121716  1:39121716:A:C       A       C 0.188581
2:       chr1 39124736 39124737  1:39124737:G:T       G       T 0.188488
3:       chr1 39126106 39126107  1:39126107:C:T       C       T 0.188449
4:       chr1 39128429 39128430  1:39128430:C:T       C       T 0.258722
5:       chr1 39130464 39130465  1:39130465:T:A       T       A 0.276816
6:       chr1 39134206 39134207 1:39134207:A:AT       A      AT 0.259602
         beta                  p         se    trait                 region
        <num>              <num>      <num>   <char>                 <char>
1:  0.0610198 0.0000000000900741 0.00941269 T2D_WIDE chr1:37748602-40748602
2:  0.0606539 0.0000000001171010 0.00941387 T2D_WIDE chr1:37748602-40748602
3:  0.0610762 0.0000000000871565 0.00941413 T2D_WIDE chr1:37748602-40748602
4: -0.0551588 0.0000000000594292 0.00842742 T2D_WIDE chr1:37748602-40748602
5: -0.0541641 0.0000000000519996 0.00825032 T2D_WIDE chr1:37748602-40748602
6: -0.0547512 0.0000000000807421 0.00842430 T2D_WIDE chr1:37748602-40748602
      cs cs_specific_prob
   <int>            <num>
1:     1      0.005722689
2:     1      0.004465460
3:     1      0.005896971
4:     1      0.004497469
5:     1      0.005664133
6:     1      0.003414917

Making a bed for finngen_R11_T2D

[1] "finngen_R11_T2D"
   chromosome    start      end              v allele1 allele2      maf
       <char>    <num>    <int>         <char>  <char>  <char>    <num>
1:       chr1 16071879 16071880 1:16071880:T:C       T       C 0.276480
2:       chr1 16079191 16079192 1:16079192:A:T       A       T 0.405681
3:       chr1 16079666 16079667 1:16079667:T:C       T       C 0.426247
4:       chr1 16080093 16080094 1:16080094:T:C       T       C 0.405830
5:       chr1 16080338 16080339 1:16080339:T:C       T       C 0.426576
6:       chr1 16080988 16080989 1:16080989:T:C       T       C 0.405297
         beta                 p         se  trait                 region    cs
        <num>             <num>      <num> <char>                 <char> <int>
1: -0.0395122 0.000000018724900 0.00702640    T2D chr1:14582314-17582314     1
2:  0.0368400 0.000000007322000 0.00637000    T2D chr1:14582314-17582314     1
3:  0.0386815 0.000000000936030 0.00632055    T2D chr1:14582314-17582314     1
4:  0.0367697 0.000000007806210 0.00636970    T2D chr1:14582314-17582314     1
5:  0.0387899 0.000000000848086 0.00632205    T2D chr1:14582314-17582314     1
6:  0.0365255 0.000000009942600 0.00637253    T2D chr1:14582314-17582314     1
   cs_specific_prob
              <num>
1:      0.008326319
2:      0.030720645
3:      0.203447063
4:      0.028939103
5:      0.223467673
6:      0.023132731

In [23]:
trait.data

     chromosome start     end       v                  allele1 allele2
1    chr1       16071879  16071880  1:16071880:T:C     T       C
2    chr1       16079191  16079192  1:16079192:A:T     A       T
3    chr1       16079666  16079667  1:16079667:T:C     T       C
4    chr1       16080093  16080094  1:16080094:T:C     T       C
5    chr1       16080338  16080339  1:16080339:T:C     T       C
6    chr1       16080988  16080989  1:16080989:T:C     T       C
7    chr1       16081231  16081232  1:16081232:C:A     C       A
8    chr1       16081328  16081329  1:16081329:C:T     C       T
9    chr1       16082313  16082314  1:16082314:T:A     T       A
10   chr1       16083674  16083675  1:16083675:C:G     C       G
11   chr1       16083682  16083683  1:16083683:G:C     G       C
12   chr1       20402395  20402396  1:20402396:T:A     T       A
13   chr1       20405926  20405927  1:20405927:G:A     G       A
14   chr1       20406742  20406743  1:20406743:C:G     C       G
15   chr1       20406882  20406883  1:20406883:T:C     T       C
16   chr1       20407505  20407506  1:20407506:C:G     C       G
17   chr1       20407874  20407875  1:20407875:C:A     C       A
18   chr1       20408019  20408020  1:20408020:G:C     G       C
19   chr1       20408254  20408255  1:20408255:A:G     A       G
20   chr1       20408317  20408318  1:20408318:T:C     T       C
21   chr1       20408576  20408577  1:20408577:G:A     G       A
22   chr1       20408742  20408743  1:20408743:T:G     T       G
23   chr1       20408838  20408839  1:20408839:G:A     G       A
24   chr1       21662482  21662483  1:21662483:C:T     C       T
25   chr1       21663479  21663480  1:21663480:C:T     C       T
26   chr1       21664748  21664749  1:21664749:AT:A    AT      A
27   chr1       21664778  21664779  1:21664779:G:T     G       T
28   chr1       21666676  21666677  1:21666677:A:C     A       C
29   chr1       21667106  21667107  1:21667107:A:G     A       G
30   chr1       26279799  26279800  1:26279800:C:T     C       T
⋮    ⋮          ⋮         ⋮         ⋮                  ⋮       ⋮
7458 chr23      131930529 131930530 23:131930530:C:A   C       A
7459 chr23      131930861 131930862 23:131930862:G:A   G       A
7460 chr23      131964863 131964864 23:131964864:T:C   T       C
7461 chr23      132576869 132576870 23:132576870:AAG:A AAG     A
7462 chr23      132598261 132598262 23:132598262:G:A   G       A
7463 chr23      132599464 132599465 23:132599465:G:A   G       A
7464 chr23      132701250 132701251 23:132701251:T:C   T       C
7465 chr23      132999083 132999084 23:132999084:CA:C  CA      C
7466 chr23      133188870 133188871 23:133188871:T:A   T       A
7467 chr23      133279558 133279559 23:133279559:C:T   C       T
7468 chr23      133341466 133341467 23:133341467:G:A   G       A
7469 chr23      133402772 133402773 23:133402773:G:C   G       C
7470 chr23      133408852 133408853 23:133408853:T:A   T       A
7471 chr23      133414729 133414730 23:133414730:G:A   G       A
7472 chr23      133430230 133430231 23:133430231:C:G   C       G
7473 chr23      133459011 133459012 23:133459012:C:T   C       T
7474 chr23      133501519 133501520 23:133501520:T:C   T       C
7475 chr23      133622816 133622817 23:133622817:C:T   C       T
7476 chr23      133625849 133625850 23:133625850:T:C   T       C
7477 chr23      133744767 133744768 23:133744768:C:T   C       T
7478 chr23      133865940 133865941 23:133865941:T:C   T       C
7479 chr23      133875931 133875932 23:133875932:T:C   T       C
7480 chr23      133897185 133897186 23:133897186:G:A   G       A
7481 chr23      134118028 134118029 23:134118029:C:T   C       T
7482 chr23      134234675 134234676 23:134234676:T:C   T       C
7483 chr23      134243803 134243804 23:134243804:T:C   T       C
7484 chr23      153633472 153633473 23:153633473:A:C   A       C
7485 chr23      153633475 153633476 23:153633476:A:C   A       C
7486 chr23      153634466 153634467 23:153634467:A:G   A       G
7487 chr23      153635029 153635030 23:153635030:C:T   C       T
     maf       beta
1    0.276480  -0.0395122
2    0.405681   0.0368400
3    0.426247   0.0386815
4    0.405830   0.0367697
5    0.426576   0.0387899
6    0.405297   0.0365255
7    0.405640   0.0368375
8    0.405697   0.0367145
9    0.426292   0.0390651
10   0.424640   0.0372034
11   0.424528   0.0372434
12   0.477061  -0.0346841
13   0.477144  -0.0345592
14   0.476008  -0.0345524
15   0.476093  -0.0345991
16   0.475772  -0.0346850
17   0.475967  -0.0346139
18   0.475962  -0.0346155
19   0.475953  -0.0346109
20   0.475951  -0.0346175
21   0.475966  -0.0345961
22   0.475883  -0.0346852
23   0.475975  -0.0345679
24   0.195144   0.0402696
25   0.194986   0.0404542
26   0.187302  -0.0416651
27   0.187302  -0.0416631
28   0.171358  -0.0430635
29   0.171352  -0.0429594
30   0.133606  -0.0585765
⋮    ⋮         ⋮
7458 0.0117873  0.1239930
7459 0.0117908  0.1243260
7460 0.0129905  0.1089590
7461 0.0127188  0.1092820
7462 0.0127215  0.1093910
7463 0.0127230  0.1094260
7464 0.0130547  0.1130400
7465 0.0123504  0.1260090
7466 0.0137530  0.1033440
7467 0.0137244  0.1013900
7468 0.0136809  0.1017400
7469 0.0134520  0.1074930
7470 0.0135565  0.1077940
7471 0.0134523  0.1071220
7472 0.0130182  0.1148930
7473 0.0128616  0.1118090
7474 0.0128503  0.1116040
7475 0.0128851  0.1095240
7476 0.0123633  0.1137460
7477 0.0128631  0.1121380
7478 0.0131334  0.1096130
7479 0.0131081  0.1092830
7480 0.0132627  0.1093590
7481 0.0254994  0.0811324
7482 0.0127636  0.1070630
7483 0.0127636  0.1070630
7484 0.2743310 -0.0919780
7485 0.2742790 -0.0920551
7486 0.2740250 -0.0921914
7487 0.2740710 -0.0926101
     p
1    0.000000018724900
2    0.000000007322000
3    0.000000000936030
4    0.000000007806210
5    0.000000000848086
6    0.000000009942600
7    0.000000007344460
8    0.000000008309220
9    0.000000000661317
10   0.000000004333410
11   0.000000004152690
12   0.000000032330300
13   0.000000035984000
14   0.000000036860400
15   0.000000035490300
16   0.000000033920300
17   0.000000036246800
18   0.000000036318700
19   0.000000036665700
20   0.000000036496400
21   0.000000037362900
22   0.000000034604300
23   0.000000038540700
24   0.000000314956000
25   0.000000277211000
26   0.000000180347000
27   0.000000180572000
28   0.000000180011000
29   0.000000191955000
30   0.000000000284643
⋮    ⋮
7458 0.000000069436800000000004071186270049320654607072356157004833221
7459 0.000000063471699999999997859092800214786400658795173512771725655
7460 0.000000700583999999999995258309886531078447546860843431204557419
7461 0.000000821031999999999989604522552394394452335291134659200906754
7462 0.000000801050999999999964408439051544164044571516569703817367554
7463 0.000000794804000000000001180248173499043318201984220650047063828
7464 0.000000247086999999999994300208666642149069048173259943723678589
7465 0.000000024283400000000001570766390221467467824822961119934916496
7466 0.000001514400000000000061066581479030102030947091407142579555511
7467 0.000002362979999999999947683142556553725910362118156626820564270
7468 0.000002244860000000000052004095474345035654550883919000625610352
7469 0.000000695968999999999976763601083895594001660356298089027404785
7470 0.000000642851000000000043353330040490911656547723396215587854385
7471 0.000000759206999999999950500559429272806610811130667570978403091
7472 0.000000159334999999999990444567925067242963876879002782516181469
7473 0.000000378991999999999983307294188633607134875092015136033296585
7474 0.000000399585999999999988912353574010971613006404368206858634949
7475 0.000000637293999999999962557506016230801648703163664322346448898
7476 0.000000410223000000000006670804967440213673057769483420997858047
7477 0.000000350922000000000023784552235714406798194886505370959639549
7478 0.000000596554000000000035827121217663071561787546670529991388321
7479 0.000000669915000000000026822747582061490234650591446552425622940
7480 0.000000609269999999999949315970543956000327057154208887368440628
7481 0.000000328163000000000024931965780100595608814728620927780866623
7482 0.000001603429999999999952355121506097912487120993318967521190643
7483 0.000001603429999999999952355121506097912487120993318967521190643
7484 0.000000000000000000000000000000000000000000000000000000001179510
7485 0.000000000000000000000000000000000000000000000000000000000952138
7486 0.000000000000000000000000000000000000000000000000000000000675772
7487 0.000000000000000000000000000000000000000000000000000000000230303
     se         trait region                   cs cs_specific_prob
1    0.00702640 T2D   chr1:14582314-17582314   1  0.008326319
2    0.00637000 T2D   chr1:14582314-17582314   1  0.030720645
3    0.00632055 T2D   chr1:14582314-17582314   1  0.203447063
4    0.00636970 T2D   chr1:14582314-17582314   1  0.028939103
5    0.00632205 T2D   chr1:14582314-17582314   1  0.223467673
6    0.00637253 T2D   chr1:14582314-17582314   1  0.023132731
7    0.00637013 T2D   chr1:14582314-17582314   1  0.030607316
8    0.00637176 T2D   chr1:14582314-17582314   1  0.027302837
9    0.00632626 T2D   chr1:14582314-17582314   1  0.281767696
10   0.00633688 T2D   chr1:14582314-17582314   1  0.048401125
11   0.00633607 T2D   chr1:14582314-17582314   1  0.050253260
12   0.00627389 T2D   chr1:18902396-21902396   1  0.091329924
13   0.00627264 T2D   chr1:18902396-21902396   1  0.082096499
14   0.00627624 T2D   chr1:18902396-21902396   1  0.078289722
15   0.00627712 T2D   chr1:18902396-21902396   1  0.080799087
16   0.00628364 T2D   chr1:18902396-21902396   1  0.084179797
17   0.00628404 T2D   chr1:18902396-21902396   1  0.079651744
18   0.00628473 T2D   chr1:18902396-21902396   1  0.079515068
19   0.00628581 T2D   chr1:18902396-21902396   1  0.078788946
20   0.00628607 T2D   chr1:18902396-21902396   1  0.079143004
21   0.00628690 T2D   chr1:18902396-21902396   1  0.077454100
22   0.00628767 T2D   chr1:18902396-21902396   1  0.083228171
23   0.00628804 T2D   chr1:18902396-21902396   1  0.075004451
24   0.00787396 T2D   chr1:18902396-21902396   3  0.063773740
25   0.00787304 T2D   chr1:18902396-21902396   3  0.072796120
26   0.00798406 T2D   chr1:18902396-21902396   3  0.269102952
27   0.00798403 T2D   chr1:18902396-21902396   3  0.268783533
28   0.00825149 T2D   chr1:18902396-21902396   3  0.165035891
29   0.00825036 T2D   chr1:18902396-21902396   3  0.154769322
30   0.00928766 T2D   chr1:24779800-27779800   1  0.018515038
⋮    ⋮          ⋮     ⋮                        ⋮  ⋮
7458 0.02299300 T2D   chrX:131499084-134499084 1  0.117225834
7459 0.02298620 T2D   chrX:131499084-134499084 1  0.127403533
7460 0.02196230 T2D   chrX:131499084-134499084 1  0.013721808
7461 0.02216540 T2D   chrX:131499084-134499084 1  0.011897490
7462 0.02216580 T2D   chrX:131499084-134499084 1  0.012172224
7463 0.02216610 T2D   chrX:131499084-134499084 1  0.012259289
7464 0.02190750 T2D   chrX:131499084-134499084 1  0.036138968
7465 0.02258900 T2D   chrX:131499084-134499084 1  0.316735860
7466 0.02148820 T2D   chrX:131499084-134499084 1  0.006623919
7467 0.02148280 T2D   chrX:131499084-134499084 1  0.004386201
7468 0.02150930 T2D   chrX:131499084-134499084 1  0.004598093
7469 0.02166110 T2D   chrX:131499084-134499084 1  0.013507636
7470 0.02165450 T2D   chrX:131499084-134499084 1  0.014485544
7471 0.02166010 T2D   chrX:131499084-134499084 1  0.012464364
7472 0.02192010 T2D   chrX:131499084-134499084 1  0.052638579
7473 0.02201300 T2D   chrX:131499084-134499084 1  0.023675122
7474 0.02201630 T2D   chrX:131499084-134499084 1  0.022534951
7475 0.02199470 T2D   chrX:131499084-134499084 1  0.014642850
7476 0.02246110 T2D   chrX:131499084-134499084 1  0.022022832
7477 0.02201460 T2D   chrX:131499084-134499084 1  0.025409257
7478 0.02195620 T2D   chrX:131499084-134499084 1  0.015418384
7479 0.02198900 T2D   chrX:131499084-134499084 1  0.013854681
7480 0.02192320 T2D   chrX:131499084-134499084 1  0.015150906
7481 0.01588800 T2D   chrX:131499084-134499084 1  0.008583615
7482 0.02231450 T2D   chrX:131499084-134499084 1  0.006144224
7483 0.02231450 T2D   chrX:131499084-134499084 1  0.006144224
7484 0.00574684 T2D   chrX:152135030-155135030 1  0.107912744
7485 0.00574687 T2D   chrX:152135030-155135030 1  0.133243169
7486 0.00574773 T2D   chrX:152135030-155135030 1  0.186285528
7487 0.00574992 T2D   chrX:152135030-155135030 1  0.539962754

# MVP cALT GWAS

In [21]:
mvp.cred <- read.table('/nfs/lab/projects/nash_nafld_liver/GWAS/MVP_GWAS/NAFLD.EUR.MVP.2021.credset.tsv', 
                      sep='\t', header=T)

dim(mvp.cred)
head(mvp.cred)

[1] 847  16

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438    1  220970028 A  G   0.295 -0.079 0.0080
2            rs74816838  rs74816838   1  161643560 T  C   0.112  0.087 0.0128
3            rs147998249 rs147998249  8  145732180 C  G   0.003 -2.019 0.1230
4            rs2954038   rs2954038    8  126507389 C  A   0.306  0.139 0.0079
5            rs10883451  rs10883451  10  101924418 C  T   0.477 -0.161 0.0073
6            rs11601507  rs11601507  11    5701074 A  C   0.073  0.088 0.0139
  P
1 0.00000000000000000000008039999999999999864096596417245010147951715910327833582246120133069089419564079435077
2 0.00000000001089999999999999919511412312280704316538870735087130015017464756965637207031250000000000000000000
3 0.00000000000000000000000000000000000000000000000000000000000075199999999999997444967613752069318118968540010
4 0.00000000000000000000000000000000000000000000000000000000000000000000021199999999999999972464379988412862845
5 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000036
6 0.00000000021600000000000000373345155738237380674271470581970788771286606788635253906250000000000000000000000
  N      PP      Nominated.Gene     Biological.Prior.Gene Not.in.Trans.Ethnic
1 164197 99.54%  MTARC1             MTARC1
2 164197 96.21%  FCGR2A;FCGR2B      FCGR2A;FCGR2B         *
3 164197 100.00% GPT                GPT                   *
4 164197 99.99%  lnc-TRIB1-2;WASHC5 TRIB1
5 164197 98.90%  ERLIN1             ERLIN1
6 164197 99.82%  TRIM5              TRIM5

In [23]:
sum(str_detect(mvp.cred$CS.SNP, 'rs'))
sum(str_detect(mvp.cred$LEAD.SNP, 'rs'))

[1] 847

[1] 847

Warning message:
“package ‘biomaRt’ was built under R version 4.3.2”

In [50]:
#Select mart
ensembl <- useEnsembl("snp",dataset = "hsapiens_snp") # ,GRCh = "38" automatically connects to hg38

#get genomic position
SNPs <- getBM(attributes=c("refsnp_id",
                   "chr_name",
                   "chrom_start",
                   "chrom_end"),
    filters ="snp_filter", values =mvp.cred$CS.SNP, mart = ensembl, uniqueRows=TRUE)

dim(SNPs)

SNPs.filt <- filter(SNPs, chr_name %in% as.character(1:22))

dim(SNPs.filt)
head(SNPs.filt)

[1] 847   4

  refsnp_id chr_name chrom_start chrom_end
1 rs1337098 1        219536844   219536844
2 rs1337101 1        219552758   219552758
3 rs1415293 1        219556664   219556664
4 rs2993027 1        219535689   219535689
5 rs4233540 1         16180889    16180889
6 rs4500327 1        219531863   219531863

In [96]:
mvp.cred.hg38 <- SNPs.filt

mvp.cred.hg38$chrom_start <- mvp.cred.hg38$chrom_end - 1
mvp.cred.hg38 <- dplyr::select(mvp.cred.hg38, CS.SNP=refsnp_id, chr.hg38=chr_name, start.hg38=chrom_start, end.hg38=chrom_end)

mvp.cred.hg38 <- left_join(mvp.cred, mvp.cred.hg38)

dim(mvp.cred.hg38)
head(mvp.cred.hg38)

Joining with `by = join_by(CS.SNP)`

[1] 847  19

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438    1  220970028 A  G   0.295 -0.079 0.0080
2            rs74816838  rs74816838   1  161643560 T  C   0.112  0.087 0.0128
3            rs147998249 rs147998249  8  145732180 C  G   0.003 -2.019 0.1230
4            rs2954038   rs2954038    8  126507389 C  A   0.306  0.139 0.0079
5            rs10883451  rs10883451  10  101924418 C  T   0.477 -0.161 0.0073
6            rs11601507  rs11601507  11    5701074 A  C   0.073  0.088 0.0139
  P
1 0.00000000000000000000008039999999999999864096596417245010147951715910327833582246120133069089419564079435077
2 0.00000000001089999999999999919511412312280704316538870735087130015017464756965637207031250000000000000000000
3 0.00000000000000000000000000000000000000000000000000000000000075199999999999997444967613752069318118968540010
4 0.00000000000000000000000000000000000000000000000000000000000000000000021199999999999999972464379988412862845
5 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000036
6 0.00000000021600000000000000373345155738237380674271470581970788771286606788635253906250000000000000000000000
  N      PP      Nominated.Gene     Biological.Prior.Gene Not.in.Trans.Ethnic
1 164197 99.54%  MTARC1             MTARC1
2 164197 96.21%  FCGR2A;FCGR2B      FCGR2A;FCGR2B         *
3 164197 100.00% GPT                GPT                   *
4 164197 99.99%  lnc-TRIB1-2;WASHC5 TRIB1
5 164197 98.90%  ERLIN1             ERLIN1
6 164197 99.82%  TRIM5              TRIM5
  chr.hg38 start.hg38 end.hg38
1 1        220796685  220796686
2 1        161673769  161673770
3 8        144506796  144506797
4 8        125495146  125495147
5 10       100164660  100164661
6 11         5679843    5679844

In [102]:
mvp.cred.hg38.bed <- mvp.cred.hg38
mvp.cred.hg38.bed$variant = paste0(mvp.cred.hg38.bed$chr.hg38,":",mvp.cred.hg38.bed$end.hg38,":",
                              mvp.cred.hg38.bed$EA,":",mvp.cred.hg38.bed$NEA)
mvp.cred.hg38.bed$PP <- as.numeric(str_remove(mvp.cred.hg38.bed$PP, "%")) / 100
mvp.cred.hg38.bed$chr.hg38 <- paste0('chr',mvp.cred.hg38.bed$chr.hg38)
mvp.cred.hg38.bed <- dplyr::select(mvp.cred.hg38.bed, chr=chr.hg38, start=start.hg38, end=end.hg38, rsid=CS.SNP, variant, 
              p=P, beta=Beta, cs_id=LEAD.SNP, prob=PP)

dim(mvp.cred.hg38.bed)
head(mvp.cred.hg38.bed)

[1] 847   9

  chr   start     end       rsid        variant
1 chr1  220796685 220796686 rs2642438   1:220796686:A:G
2 chr1  161673769 161673770 rs74816838  1:161673770:T:C
3 chr8  144506796 144506797 rs147998249 8:144506797:C:G
4 chr8  125495146 125495147 rs2954038   8:125495147:C:A
5 chr10 100164660 100164661 rs10883451  10:100164661:C:T
6 chr11   5679843   5679844 rs11601507  11:5679844:A:C
  p
1 0.00000000000000000000008039999999999999864096596417245010147951715910327833582246120133069089419564079435077
2 0.00000000001089999999999999919511412312280704316538870735087130015017464756965637207031250000000000000000000
3 0.00000000000000000000000000000000000000000000000000000000000075199999999999997444967613752069318118968540010
4 0.00000000000000000000000000000000000000000000000000000000000000000000021199999999999999972464379988412862845
5 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000036
6 0.00000000021600000000000000373345155738237380674271470581970788771286606788635253906250000000000000000000000
  beta   cs_id       prob
1 -0.079 rs2642438   0.9954
2  0.087 rs74816838  0.9621
3 -2.019 rs147998249 1.0000
4  0.139 rs2954038   0.9999
5 -0.161 rs10883451  0.9890
6  0.088 rs11601507  0.9982

In [98]:
write.table(mvp.cred.hg38,'/nfs/lab/projects/nash_nafld_liver/GWAS/MVP_GWAS/NAFLD.EUR.MVP.2021.credset.hg38.tsv', 
                      sep='\t', col.names=T, row.names=F, quote=F)

In [103]:
write.table(mvp.cred.hg38.bed,
                file = '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/traits/MVP.NAFLD.EUR.MVP.2021.credset.bed',
                col.names = F, row.names = F, sep = "\t", quote = F)

# MVP cALT GWAS Meta

In [3]:
mvp.cred <- read.table('/nfs/lab/projects/nash_nafld_liver/GWAS/MVP_GWAS/NAFLD.TRANS.MVP.2021.credset.tsv', 
                      sep='\t', header=T)

dim(mvp.cred)
head(mvp.cred)

[1] 1088   15

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438   1   220970028 A  G   0.274 -0.075 0.0074
2            rs6734238   rs6734238   2   113841030 G  A   0.407 -0.057 0.0064
3            rs138033684 rs138033684 6    71895252 G  T   0.006  0.677 0.1120
4            rs2980888   rs2980888   8   126507308 T  C   0.286  0.130 0.0072
5            rs4484649   rs4484649   8    10571491 C  A   0.419  0.045 0.0066
6            rs4841132   rs4841132   8     9183596 A  G   0.106  0.123 0.0105
  P
1 0.00000000000000000000000665000000000000064055202399371392829886468625600066
2 0.00000000000000000049400000000000002917898166094407597743373033908031695741
3 0.00000000142000000000000005948853843069142749433453332130738999694585800171
4 0.00000000000000000000000000000000000000000000000000000000000000000000000421
5 0.00000000001380000000000000016672219910420134087597476835185261734295636415
6 0.00000000000000000000000000000006620000000000000192604372938984848598959739
  N      PP     Nominated.Gene     Biological.Prior.Gene
1 218595 96.86% MTARC1             MTARC1
2 218595 99.04% IL1RN              IL1RN
3  37364 96.31% OGFRL1             OGFRL1
4 218595 99.95% lnc-TRIB1-2;WASHC5 TRIB1
5 218595 98.51% SOX7;RP1L1;C8orf74 RP1L1;SOX7
6 218595 98.79% PPP1R3B            PPP1R3B;TNKS;MFHAS1

In [4]:
# Are my snps named correctly - four aren't, skipping them
sum(str_detect(mvp.cred$CS.SNP, 'rs'))
sum(str_detect(mvp.cred$LEAD.SNP, 'rs'))

[1] 1084

[1] 1088

In [5]:
head(mvp.cred$CS.SNP)

[1] "rs2642438"   "rs6734238"   "rs138033684" "rs2980888"   "rs4484649"
[6] "rs4841132"

In [1]:
# Load the package
library(SNPlocs.Hsapiens.dbSNP155.GRCh38)

Loading required package: BSgenome

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors

Loading required package: stats4


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: GenomicRanges

Loading required package: Biostrings

Loading required package: XVector


Attaching package: ‘Biostrings’


The following object is masked from ‘package:base’:

    strsplit


Loading required package: BiocIO

Loading required package: rtracklayer


Attaching package: ‘rtracklayer’


The following object is masked from ‘package:BiocIO’:

    FileForFormat


Warning message:
“replacing previous import ‘utils::findMatches’ by ‘S4Vectors::findMatches’ when loading ‘SNPlocs.Hsapiens.dbSNP155.GRCh38’”

In [2]:
# Read in the supporting data
snps <- SNPlocs.Hsapiens.dbSNP155.GRCh38
snpcount(snps)
seqinfo(snps)

       1        2        3        4        5        6        7        8
75018827 79800406 65297222 62943150 58975130 54890615 52513853 49808065
       9       10       11       12       13       14       15       16
41429208 43919217 45144118 43436160 32601707 29144464 27215990 29493439
      17       18       19       20       21       22        X        Y
26217755 25582976 19590577 20830213 12400011 12798923 37808263  2153980
      MT
    7179

Seqinfo object with 25 sequences (1 circular) from GRCh38.p13 genome:
  seqnames seqlengths isCircular     genome
  1         248956422      FALSE GRCh38.p13
  2         242193529      FALSE GRCh38.p13
  3         198295559      FALSE GRCh38.p13
  4         190214555      FALSE GRCh38.p13
  5         181538259      FALSE GRCh38.p13
  ...             ...        ...        ...
  21         46709983      FALSE GRCh38.p13
  22         50818468      FALSE GRCh38.p13
  X         156040895      FALSE GRCh38.p13
  Y          57227415      FALSE GRCh38.p13
  MT            16569       TRUE GRCh38.p13

In [3]:
snpsById(snps, 'rs12081055', ifnotfound='warning')

UnstitchedGPos object with 1 position and 2 metadata columns:
      seqnames       pos strand |   RefSNP_id alleles_as_ambig
         <Rle> <integer>  <Rle> | <character>      <character>
  [1]        1  13941547      * |  rs12081055                Y
  -------
  seqinfo: 25 sequences (1 circular) from GRCh38.p13 genome

In [4]:
snpsById(snps, c('rs12081055', 'rs200755829', 'rs397795410', 'rs58913475'), ifnotfound='warning')

Warning message in rowids2rowidx(user_rowids, ids, x_rowids_env, ifnotfound):
“SNP ids not found: rs200755829, rs397795410, rs58913475

  They were dropped.”

UnstitchedGPos object with 1 position and 2 metadata columns:
      seqnames       pos strand |   RefSNP_id alleles_as_ambig
         <Rle> <integer>  <Rle> | <character>      <character>
  [1]        1  13941547      * |  rs12081055                Y
  -------
  seqinfo: 25 sequences (1 circular) from GRCh38.p13 genome

In [11]:
# These four snps are all low probability; okay to drop
mvp.cred$CS.SNP[!str_detect(mvp.cred$CS.SNP, 'rs')]

    CS.Type LEAD.SNP  CS.SNP        Chr Position EA NEA EAF   Beta  SE
370         rs686250  chr6:32582603 6   32582603 A  G   0.371 0.037 0.0065
426         rs686250  chr6:32446981 6   32446981 A  G   0.412 0.034 0.0064
440         rs686250  chr6:32444938 6   32444938 C  G   0.409 0.034 0.0065
588         rs1658943 chr9:6660172  9    6660172 G  C   0.169 0.040 0.0089
    P            N      PP    Nominated.Gene
370 0.0000000203 218595 3.72% HLA-DRA;HLA-DQA2;HLA-DQB2;HLA-DOB;PSMB8;PSMB9
426 0.0000001430 218595 0.50% HLA-DRA;HLA-DQA2;HLA-DQB2;HLA-DOB;PSMB8;PSMB9
440 0.0000001740 218595 0.39% HLA-DRA;HLA-DQA2;HLA-DQB2;HLA-DOB;PSMB8;PSMB9
588 0.0000066600 218595 0.24% UHRF2
    Biological.Prior.Gene
370 HLA
426 HLA
440 HLA
588 UHRF2

In [15]:
# Look up SNP positions
my_snps <- snpsById(snps, mvp.cred$CS.SNP[str_detect(mvp.cred$CS.SNP, 'rs')], ifnotfound='warning')
my_snps

UnstitchedGPos object with 1084 positions and 2 metadata columns:
         seqnames       pos strand |   RefSNP_id alleles_as_ambig
            <Rle> <integer>  <Rle> | <character>      <character>
     [1]        1 220796686      * |   rs2642438                N
     [2]        2 113083453      * |   rs6734238                R
     [3]        6  71185549      * | rs138033684                K
     [4]        8 125495066      * |   rs2980888                Y
     [5]        8  10713981      * |   rs4484649                M
     ...      ...       ...    ... .         ...              ...
  [1080]       22  36154019      * |    rs132646                Y
  [1081]       22  36148681      * |    rs132641                D
  [1082]       22  28704723      * |   rs1547014                Y
  [1083]       22  28711207      * |   rs5752775                N
  [1084]       22  28709427      * |   rs5752773                V
  -------
  seqinfo: 25 sequences (1 circular) from GRCh38.p13 genome

In [33]:
# Convert to dataframe
my_snps.df <- select(data.frame(my_snps), CS.SNP=RefSNP_id, chr.hg38=seqnames, end.hg38=pos)
my_snps.df <- mutate(my_snps.df, start.hg38=end.hg38-1)

dim(my_snps.df)
head(my_snps.df)

[1] 1084    4

  CS.SNP      chr.hg38 end.hg38  start.hg38
1 rs2642438   1        220796686 220796685
2 rs6734238   2        113083453 113083452
3 rs138033684 6         71185549  71185548
4 rs2980888   8        125495066 125495065
5 rs4484649   8         10713981  10713980
6 rs4841132   8          9326086   9326085

In [35]:
# Region to credible set data
mvp.cred.hg38 <- inner_join(mvp.cred,my_snps.df)
dim(mvp.cred.hg38)
head(mvp.cred.hg38)

Joining with `by = join_by(CS.SNP)`

[1] 1084   18

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438   1   220970028 A  G   0.274 -0.075 0.0074
2            rs6734238   rs6734238   2   113841030 G  A   0.407 -0.057 0.0064
3            rs138033684 rs138033684 6    71895252 G  T   0.006  0.677 0.1120
4            rs2980888   rs2980888   8   126507308 T  C   0.286  0.130 0.0072
5            rs4484649   rs4484649   8    10571491 C  A   0.419  0.045 0.0066
6            rs4841132   rs4841132   8     9183596 A  G   0.106  0.123 0.0105
  P
1 0.00000000000000000000000665000000000000064055202399371392829886468625600066
2 0.00000000000000000049400000000000002917898166094407597743373033908031695741
3 0.00000000142000000000000005948853843069142749433453332130738999694585800171
4 0.00000000000000000000000000000000000000000000000000000000000000000000000421
5 0.00000000001380000000000000016672219910420134087597476835185261734295636415
6 0.00000000000000000000000000000006620000000000000192604372938984848598959739
  N      PP     Nominated.Gene     Biological.Prior.Gene chr.hg38 end.hg38
1 218595 96.86% MTARC1             MTARC1                1        220796686
2 218595 99.04% IL1RN              IL1RN                 2        113083453
3  37364 96.31% OGFRL1             OGFRL1                6         71185549
4 218595 99.95% lnc-TRIB1-2;WASHC5 TRIB1                 8        125495066
5 218595 98.51% SOX7;RP1L1;C8orf74 RP1L1;SOX7            8         10713981
6 218595 98.79% PPP1R3B            PPP1R3B;TNKS;MFHAS1   8          9326086
  start.hg38
1 220796685
2 113083452
3  71185548
4 125495065
5  10713980
6   9326085

In [36]:
mvp.cred.hg38.bed <- mvp.cred.hg38
mvp.cred.hg38.bed$variant = paste0(mvp.cred.hg38.bed$chr.hg38,":",mvp.cred.hg38.bed$end.hg38,":",
                              mvp.cred.hg38.bed$EA,":",mvp.cred.hg38.bed$NEA)
mvp.cred.hg38.bed$PP <- as.numeric(str_remove(mvp.cred.hg38.bed$PP, "%")) / 100
mvp.cred.hg38.bed$chr.hg38 <- paste0('chr',mvp.cred.hg38.bed$chr.hg38)
mvp.cred.hg38.bed <- dplyr::select(mvp.cred.hg38.bed, chr=chr.hg38, start=start.hg38, end=end.hg38, rsid=CS.SNP, variant, 
              p=P, beta=Beta, cs_id=LEAD.SNP, prob=PP)

dim(mvp.cred.hg38.bed)
head(mvp.cred.hg38.bed)

[1] 1084    9

  chr  start     end       rsid        variant
1 chr1 220796685 220796686 rs2642438   1:220796686:A:G
2 chr2 113083452 113083453 rs6734238   2:113083453:G:A
3 chr6  71185548  71185549 rs138033684 6:71185549:G:T
4 chr8 125495065 125495066 rs2980888   8:125495066:T:C
5 chr8  10713980  10713981 rs4484649   8:10713981:C:A
6 chr8   9326085   9326086 rs4841132   8:9326086:A:G
  p
1 0.00000000000000000000000665000000000000064055202399371392829886468625600066
2 0.00000000000000000049400000000000002917898166094407597743373033908031695741
3 0.00000000142000000000000005948853843069142749433453332130738999694585800171
4 0.00000000000000000000000000000000000000000000000000000000000000000000000421
5 0.00000000001380000000000000016672219910420134087597476835185261734295636415
6 0.00000000000000000000000000000006620000000000000192604372938984848598959739
  beta   cs_id       prob
1 -0.075 rs2642438   0.9686
2 -0.057 rs6734238   0.9904
3  0.677 rs138033684 0.9631
4  0.130 rs2980888   0.9995
5  0.045 rs4484649   0.9851
6  0.123 rs4841132   0.9879

In [37]:
write.table(mvp.cred.hg38,'/nfs/lab/projects/nash_nafld_liver/GWAS/MVP_GWAS/NAFLD.TRANS.MVP.2021.credset.hg38.tsv', 
                      sep='\t', col.names=T, row.names=F, quote=F)

In [38]:
write.table(mvp.cred.hg38.bed,
                file = '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/traits/MVP.NAFLD.TRANS.MVP.2021.credset.bed',
                col.names = F, row.names = F, sep = "\t", quote = F)

In [39]:
write.table(mvp.cred.hg38.bed,
                file = '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/traits/MVP.NAFLD.TRANS.MVP.2021.credset.bed',
                col.names = F, row.names = F, sep = "\t", quote = F)

# DESeq Reuslts Bed

In [3]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/02_DESEQ_ATAC/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [5]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'ATAC.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

In [9]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/H3K27ac.peak.mats/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [4]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

In [5]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [6]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "T:Fibrosis.stage.dds.res"

# H3K27ac ATAC Sites

In [7]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/ATAC_Peaks/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [8]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_ATAC_Peaks.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Ballooning.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27ac TSS

In [9]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/08_H3K27ac_DESEQ/tss/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [10]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27ac_TSS.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27me3 ATAC Sites

In [11]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/ATAC_Peaks/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [12]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_ATAC_Peaks.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# H3K27me3 TSS Sites

In [13]:
deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/09_H3K27me3_DESEQ/tss/'
bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/'

In [14]:
for (file in list.files(deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    if (contrast %in% c('Age.dds.res', 'Age.scaled.dds.res','BMI.dds.res', 'BMI.scaled.dds.res',
                       'Lobular.inflammation.dds.res', 'MASH.CRN.score..X.8.dds.res', 
                       'MASH_vs_Control.pseudocount.dds.res','MASL_vs_Control.pseudocount.dds.res',
                        'MetALD_vs_Control.pseudocount.dds.res')) {
        next
    }
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(deseq.outdir, file))
    res <- distinct(res)
    
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.nominal.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, pvalue < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, pvalue < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.nominal.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    
    if (nrow(filter(res, padj < 0.05 & log2FoldChange < 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange < 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.padj.down.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
    if (nrow(filter(res, padj < 0.05 & log2FoldChange > 0)) > 0) {
        write.table(str_split(unique(rownames(filter(res, padj < 0.05 & log2FoldChange > 0))), "[-:]", simplify=T),
                paste0(bed.dir, 'H3K27me3_TSS.', file, '.padj.up.bed'), sep='\t', col.names=F, row.names=F, quote=F)
    }
}

[1] "B:Fibrosis.stage.dds.res"
[1] "B:MASH_ALL_vs_Control.dds.res"
[1] "B:MASH_vs_Control.dds.res"
[1] "B:MASL_vs_Control.dds.res"
[1] "B:MetALD_vs_Control.dds.res"
[1] "B:Steatosis.grade.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:MASH_ALL_vs_Control.dds.res"
[1] "Cholangiocyte:MASH_vs_Control.dds.res"
[1] "Cholangiocyte:MASL_vs_Control.dds.res"
[1] "Cholangiocyte:MetALD_vs_Control.dds.res"
[1] "Cholangiocyte:Steatosis.grade.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Endothelial:MASH_ALL_vs_Control.dds.res"
[1] "Endothelial:MASH_vs_Control.dds.res"
[1] "Endothelial:MASL_vs_Control.dds.res"
[1] "Endothelial:MetALD_vs_Control.dds.res"
[1] "Endothelial:Steatosis.grade.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "Hepatocytes:MASH_ALL_vs_Control.dds.res"
[1] "Hepatocytes:MASH_vs_Control.dds.res"
[1] "Hepatocytes:MASL_vs_Control.dds.res"
[1] "Hepatocytes:MetALD_vs_Control.dds.res"
[1] "Hepatocytes:Steatosis.grade.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "HSC:MASH_ALL_vs_Control.dds.res"
[1] "HSC:MASH_vs_Control.dds.res"
[1] "HSC:MASL_vs_Control.dds.res"
[1] "HSC:MetALD_vs_Control.dds.res"
[1] "HSC:Steatosis.grade.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "Myeloid:MASH_ALL_vs_Control.dds.res"
[1] "Myeloid:MASH_vs_Control.dds.res"
[1] "Myeloid:MASL_vs_Control.dds.res"
[1] "Myeloid:MetALD_vs_Control.dds.res"
[1] "Myeloid:Steatosis.grade.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "NK:MASH_ALL_vs_Control.dds.res"
[1] "NK:MASH_vs_Control.dds.res"
[1] "NK:MASL_vs_Control.dds.res"
[1] "NK:MetALD_vs_Control.dds.res"
[1] "NK:Steatosis.grade.dds.res"
[1] "T:Fibrosis.stage.dds.res"
[1] "T:MASH_ALL_vs_Control.dds.res"
[1] "T:MASH_vs_Control.dds.res"
[1] "T:MASL_vs_Control.dds.res"
[1] "T:MetALD_vs_Control.dds.res"
[1] "T:Steatosis.grade.dds.res"

# Not in latest run

Yang's correlation sites moved to:
/tscc/projects/ps-gaultonlab/welison/FNIH.Liver/11_FINRICH/sites (which is /nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/sites/* on ophelia)
Also to: /nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/sites/

In [209]:
ref.deseq.outdir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/old.atac.deseq/'
back.bed.dir <- '/nfs/lab/projects/nash_nafld_liver/downstream_all/11_FINRICH/background/'

In [215]:
for (file in list.files(ref.deseq.outdir, pattern='.dds.res')) {
    cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
    contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]
    
    if (cell == 'Bulk') {
        next
    }
    print(paste0(cell, ":", contrast))
    
    res <- read.table(paste0(ref.deseq.outdir, file))
    res <- distinct(res)
    
    write.table(str_split(unique(rownames(res)), "[-:]", simplify=T),
            paste0(back.bed.dir, cell, "_DEfibrosis_atac_peaks.bed"), sep='\t', col.names=F, row.names=F, quote=F)
}

[1] "B:Fibrosis.stage.dds.res"
[1] "Cholangiocyte:Fibrosis.stage.dds.res"
[1] "Endothelial:Fibrosis.stage.dds.res"
[1] "Hepatocytes:Fibrosis.stage.dds.res"
[1] "HSC:Fibrosis.stage.dds.res"
[1] "Myeloid:Fibrosis.stage.dds.res"
[1] "NK:Fibrosis.stage.dds.res"
[1] "T:Fibrosis.stage.dds.res"

In [214]:
file <- list.files(ref.deseq.outdir, pattern='.dds.res')[1]
cell <- str_split_fixed(string = file, pattern = '_', n = 2)[1]
contrast <- str_split_fixed(string = file, pattern = '_', n = 2)[2]

file
cell
contrast

[1] "B_Fibrosis.stage.dds.res"

[1] "B"

[1] "Fibrosis.stage.dds.res"

# Write Backround sets  
Need to remove doublets

Multiome:
cp /nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltype.peaks/*_union.* .

In [34]:
cells <- unlist(read.table('/nfs/lab/projects/nash_nafld_liver/downstream_all/celltypes_peak_call/listofcells.txt'))
cells

back.bed.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/11_FINRICH/background/'

for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27me3/FNIH_liver_H3K27me3.', 
                                   c, '.bed'))
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/projects/nash_nafld_liver/downstream_all/DPT.files/10.conserved_peaks/celltype_H3K27ac/FNIH_liver_H3K27ac.', 
                                   c, '.bed'))
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

            V11             V12             V13             V14             V15
            "B" "Cholangiocyte"   "Endothelial"   "Hepatocytes"           "HSC"
            V16             V17             V18             V19            V110
         "Mast"       "Myeloid"            "NK"       "Schwann"             "T"

In [35]:
# Get TSS sites
for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/tss_mtx/',c,'_H3K27ac_donor_count.CPM.xls')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac_TSS.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
    
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/tss_mtx/',c,'_H3K27me3_donor_count.CPM.xls')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3_TSS.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}

In [36]:
# Get TSS sites
for (c in cells) {
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/',c,'_H3K27ac_donor.LiverUnionPeaks.cpm.ct.peaks.tsv')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27ac_ATAC_Peaks.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
    
    peak.tab <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/DPT.files/LiverUnionPeak_mtx/',c,'_H3K27me3_donor.LiverUnionPeaks.cpm.ct.peaks.tsv')) %>%
        rownames() %>%
        str_split('-|:', simplify=T) %>%
        as.data.frame()
    write.table(distinct(peak.tab), paste0(back.bed.dir,'H3K27me3_ATAC_Peaks.',c,'_background.bed'), 
                quote=F, col.names=F, row.names=F, sep='\t')
}