In [11]:
library(dplyr)
library(tidyr)

In [2]:
meta <- read.table('/nfs/lab/projects/nash_nafld_liver/downstream_outputs/chromvar_SC/seurat_meta.txt', 
                  sep='\t', header=T)
dim(meta)
head(meta)

[1] 408178     71

                                           orig.ident    nCount_RNA
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 SeuratProject 1629
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 SeuratProject 9791
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 SeuratProject 3222
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 SeuratProject 2806
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 SeuratProject 6370
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 SeuratProject 2351
                                           nFeature_RNA percent.mt
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 1173         0.06138735
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 3730         0.00000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 1911         0.06207325
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 1670         0.03563792
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 2897         0.00000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 1399         0.63802637
                                           nCount_RNA_raw nFeature_RNA_raw
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1  1644          1185
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 10043          3858
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  3270          1938
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  2844          1689
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1  6506          2984
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  2382          1420
                                           donor_demux nCount_SCT nFeature_SCT
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 HL160042    2219       1169
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 HL170046    2804       1750
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 HL190326    3128       1906
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 HL160029    2802       1666
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 HL170060    3391       2235
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 HL190326    2468       1395
                                           SCT.weight ⋯ MASH.CRN.score..X.8
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.4101630  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.6005030  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.6803172  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 0.5316383  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 0.4956006  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 0.4492367  ⋯ 4
                                           Diagnosis
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 Marked small droplet steatosis; Preservation injury?
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 Minimally active Steatohepatitis, grade 2, stage 1a
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 Could be ischemia preservation injury, not steatohepatitis
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 near normal liver
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 Chronic steatohepatitis, grade 3, stage 2 fibrosis
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 Could be ischemia preservation injury, not steatohepatitis
                                           Peaks.weight value barcode
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.5898370    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.3994970    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.3196828    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 0.4683617    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 0.5043994    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 0.5507633    1     NA
                                           cellsubtype            celltype
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 Sinusoidal.Endothelial Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 Hepatocytes.Zone2      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 Hepatocytes.Zone3      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 Sinusoidal.Endothelial Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 Hepatocytes.Zone3      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 Vascular.Endothelial   Endothelial
                                           nCount_Peaks_Full
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 15443
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1  8325
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 10247
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  9071
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 11971
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  7727
                                           nFeature_Peaks_Full Fibrosis.stage
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 13442               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1  7459               1
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  9172               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  8067               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 10609               2
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  6869               0

In [3]:
meta$ct_disease <- paste0(meta$celltype, "_", meta$condition)

dim(meta)
head(meta)

[1] 408178     72

                                           orig.ident    nCount_RNA
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 SeuratProject 1629
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 SeuratProject 9791
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 SeuratProject 3222
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 SeuratProject 2806
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 SeuratProject 6370
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 SeuratProject 2351
                                           nFeature_RNA percent.mt
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 1173         0.06138735
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 3730         0.00000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 1911         0.06207325
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 1670         0.03563792
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 2897         0.00000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 1399         0.63802637
                                           nCount_RNA_raw nFeature_RNA_raw
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1  1644          1185
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 10043          3858
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  3270          1938
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  2844          1689
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1  6506          2984
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  2382          1420
                                           donor_demux nCount_SCT nFeature_SCT
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 HL160042    2219       1169
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 HL170046    2804       1750
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 HL190326    3128       1906
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 HL160029    2802       1666
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 HL170060    3391       2235
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 HL190326    2468       1395
                                           SCT.weight ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.4101630  ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.6005030  ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.6803172  ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 0.5316383  ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 0.4956006  ⋯
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 0.4492367  ⋯
                                           Diagnosis
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 Marked small droplet steatosis; Preservation injury?
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 Minimally active Steatohepatitis, grade 2, stage 1a
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 Could be ischemia preservation injury, not steatohepatitis
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 near normal liver
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 Chronic steatohepatitis, grade 3, stage 2 fibrosis
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 Could be ischemia preservation injury, not steatohepatitis
                                           Peaks.weight value barcode
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.5898370    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.3994970    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.3196828    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 0.4683617    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 0.5043994    1     NA
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 0.5507633    1     NA
                                           cellsubtype            celltype
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 Sinusoidal.Endothelial Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 Hepatocytes.Zone2      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 Hepatocytes.Zone3      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 Sinusoidal.Endothelial Endothelial
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 Hepatocytes.Zone3      Hepatocytes
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 Vascular.Endothelial   Endothelial
                                           nCount_Peaks_Full
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 15443
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1  8325
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 10247
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  9071
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 11971
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  7727
                                           nFeature_Peaks_Full Fibrosis.stage
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 13442               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1  7459               1
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  9172               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1  8067               0
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 10609               2
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1  6869               0
                                           ct_disease
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 Endothelial_MASL
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 Hepatocytes_MASH
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 Hepatocytes_MASL
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGGCCTG-1 Endothelial_Control
MM_1341_1_2_MM_1337_1_2_AAACAGCCATGTTGGC-1 Hepatocytes_MetALD
MM_1341_1_2_MM_1337_1_2_AAACAGCCATTGACAT-1 Endothelial_MASL

In [3]:
cell <- unique(meta$cellsubtype)

filter(meta, cell==cellsubtype)

Warning message:
“There was 1 warning in `filter()`.
ℹ In argument: `cell == cellsubtype`.
Caused by warning in `cell == cellsubtype`:
! longer object length is not a multiple of shorter object length”

                                           orig.ident    nCount_RNA
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 SeuratProject  1629
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 SeuratProject  9791
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 SeuratProject  3222
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 SeuratProject  5226
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 SeuratProject  3194
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 SeuratProject   965
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 SeuratProject  2398
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 SeuratProject  3134
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 SeuratProject  2386
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 SeuratProject  5528
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 SeuratProject   926
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 SeuratProject   866
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 SeuratProject  2978
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 SeuratProject  2092
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 SeuratProject  1758
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 SeuratProject  2104
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 SeuratProject  1380
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 SeuratProject 11379
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 SeuratProject  2154
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 SeuratProject  1514
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 SeuratProject  3865
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 SeuratProject  3268
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 SeuratProject  2668
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 SeuratProject 12509
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 SeuratProject  1440
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 SeuratProject  3140
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 SeuratProject   838
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 SeuratProject  2247
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 SeuratProject  1352
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 SeuratProject  6946
⋮                                          ⋮             ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     SeuratProject  1122
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     SeuratProject  3978
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     SeuratProject  6248
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     SeuratProject  4872
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     SeuratProject  2204
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     SeuratProject  8347
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     SeuratProject  7154
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     SeuratProject  7514
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     SeuratProject  8545
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     SeuratProject 12118
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     SeuratProject  8879
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     SeuratProject  8665
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     SeuratProject  4792
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     SeuratProject  6919
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     SeuratProject  1037
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     SeuratProject  5469
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     SeuratProject  4954
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     SeuratProject  5633
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     SeuratProject  6237
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     SeuratProject 17768
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     SeuratProject  5252
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     SeuratProject  4632
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     SeuratProject 12025
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     SeuratProject  8184
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     SeuratProject 11906
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     SeuratProject  4167
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     SeuratProject  8688
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     SeuratProject   777
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     SeuratProject  5402
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     SeuratProject 15067
                                           nFeature_RNA percent.mt
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 1173         0.061387354
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 3730         0.000000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 1911         0.062073246
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 2759         0.000000000
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 1895         0.093926111
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1  763         0.207253886
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 1472         0.208507089
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 1769         0.000000000
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 1564         0.000000000
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 2680         0.000000000
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1  708         0.000000000
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1  665         0.346420323
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 1793         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 1479         0.047801147
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 1301         0.113765643
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 1452         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1  982         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 4100         0.008788118
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 1394         0.046425255
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 1114         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 2074         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 1707         1.070991432
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 1682         0.000000000
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 3775         0.015988488
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1  986         0.069444444
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 1792         0.031847134
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1  626         0.357995227
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 1452         0.000000000
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 1003         0.073964497
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 2991         0.000000000
⋮                                          ⋮            ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1      746         0.089126560
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     2116         0.201106083
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     2728         0.016005122
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     2102         0.041050903
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     1379         0.181488203
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     3340         0.000000000
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     2704         0.027956388
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     3097         0.000000000
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     3308         0.000000000
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     3736         0.057765308
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     3076         0.000000000
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     3475         0.011540681
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     2324         0.020868114
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     2872         0.000000000
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1      751         0.000000000
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     2689         0.091424392
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     2338         0.020185709
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     2699         0.088762649
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     2750         0.032066699
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     4541         0.005628095
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     2434         0.057121097
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     2199         0.107944732
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     3588         0.000000000
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     3092         0.048875855
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     4043         0.974298673
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     1823         0.095992321
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     3260         0.000000000
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1      601         0.257400257
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     2453         0.000000000
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     4204         0.006637021
                                           nCount_RNA_raw nFeature_RNA_raw
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1  1644          1185
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 10043          3858
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  3270          1938
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1  5327          2812
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1  3241          1921
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1   970           767
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1  2424          1488
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1  3184          1803
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1  2423          1585
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1  5644          2733
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1   933           712
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1   875           674
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1  3024          1817
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1  2118          1500
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1  1779          1317
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1  2130          1469
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1  1391           988
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 11703          4218
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1  2172          1403
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1  1530          1124
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1  3953          2128
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1  3309          1728
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1  2715          1710
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 12805          3887
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1  1458           997
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1  3185          1824
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1   841           627
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1  2262          1464
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1  1363          1010
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1  7103          3072
⋮                                          ⋮              ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1      1127           751
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1      4018          2140
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1      6334          2772
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1      4912          2122
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1      2223          1388
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1      8447          3379
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1      7232          2740
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1      7607          3136
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1      8652          3357
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     12274          3793
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1      9005          3127
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1      8806          3531
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1      4836          2341
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1      7025          2917
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1      1043           753
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1      5535          2714
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1      5014          2363
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1      5695          2728
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1      6298          2779
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     18043          4622
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1      5303          2455
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1      4682          2217
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     12196          3649
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1      8292          3138
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     12074          4105
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1      4192          1838
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1      8798          3296
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1       778           602
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1      5464          2484
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     15278          4266
                                           donor_demux nCount_SCT nFeature_SCT
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 HL160042    2219       1169
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 HL170046    2804       1750
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 HL190326    3128       1906
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 HL200805    3593       2611
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 HL190326    3141       1893
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 HL230316    2030        793
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 HL220825    2485       1469
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 HL190326    3076       1767
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 HL190326    2470       1561
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 HL210726    3541       2423
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 HL210120    2082        748
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 HL170046    1927        740
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 HL170046    2961       1788
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 HL200925    2332       1476
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 HL230316    2192       1300
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 HL170046    2343       1450
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 HL200707    2498        982
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 HL230316    2852       1776
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 HL210120    2390       1392
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 HL190326    2321       1110
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 HL210806    3369       2071
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 HL210120    3161       1703
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 HL170046    2685       1682
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 HL210120    2904       1623
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 HL200805    2391        986
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 HL191025    3092       1790
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 HL170049    1945        694
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 HL230316    2401       1449
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 HL230316    2460       1010
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 HL190326    3208       2023
⋮                                          ⋮           ⋮          ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     HL170058    4602       1577
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     HL150015    5148       2110
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     HL160026    6164       2723
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     HL160037    5386       2100
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     HL210621    4960       1458
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     HL210621    6475       3336
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     HL150009    6448       2696
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     HL230324    6516       3095
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     HL190215    6423       3305
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     HL190114    6469       3019
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     HL160040    6451       3074
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     HL160040    6504       3472
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     HL211001    5353       2324
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     HL211001    6390       2870
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     HL210621    4546       1671
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     HL210621    5555       2683
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     HL210706    5394       2336
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     HL150009    5665       2696
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     HL150015    6163       2748
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     HL170058    5796       2481
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     HL190215    5492       2434
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     HL170052    5335       2198
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     HL160017    6437       2932
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     HL230324    6491       3090
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     HL150009    6599       3360
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     HL170055    5242       1818
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     HL160017    6457       3257
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     HL200212    4377       1794
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     HL230324    5538       2452
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     HL170052    6027       2709
                                           SCT.weight ⋯ MASH.CRN.score..X.8
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.4101630  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.6005030  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.6803172  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 0.5305685  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 0.8975532  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 0.4995380  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 0.5318612  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 0.9516511  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 0.7328417  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 0.6411623  ⋯ 6
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 0.5648848  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 0.9942223  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 0.4250199  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 0.6638382  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 0.9832365  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 0.7407324  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 0.7346358  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 0.7866507  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 0.7817777  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 0.5165043  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 0.5727130  ⋯ 6
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 0.3301886  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 0.7480180  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 0.8122284  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 0.5925272  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 0.8309334  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 0.9997513  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 0.5210050  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 0.6043902  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 0.9418107  ⋯ 4
⋮                                          ⋮          ⋱ ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     0.5907971  ⋯ 3
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     0.8057492  ⋯ 3
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     0.4723170  ⋯ 0
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     0.5174117  ⋯ 1
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     0.5401495  ⋯ 0
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     0.9015664  ⋯ 0
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     0.6086190  ⋯ 1
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     0.6909563  ⋯ 3
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     0.9930385  ⋯ 0
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     0.7972647  ⋯ 6
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     0.6614122  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     0.5817982  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     0.9999906  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     0.7194609  ⋯ 0
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     0.6911579  ⋯ 0
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     0.6209573  ⋯ 0
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     0.8818744  ⋯ 2
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     0.6225869  ⋯ 1
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     0.6524449  ⋯ 3
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     0.7832207  ⋯ 3
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     0.9200486  ⋯ 0
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     0.9837636  ⋯ 0
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     0.8762140  ⋯ 2
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     0.6270335  ⋯ 3
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     1.0000000  ⋯ 1
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     0.5818298  ⋯ 4
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     0.9981949  ⋯ 2
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     0.5907961  ⋯ 3
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     0.9045377  ⋯ 3

In [4]:
write.table(unique(meta$cellsubtype), 
           paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/subtypes.list.txt'),
           sep='\t', quote=F, row.names=F, col.names=F)

In [10]:
for (cell in unique(meta$cellsubtype)) {
    write.table(row.names(filter(meta, cell==cellsubtype)), 
               paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/barcodes/cellsubtype/', cell, '.barcode.prefix.txt'),
               sep='\t', quote=F, row.names=F, col.names=F)
}

In [3]:
cell <- unique(meta$ct_disease)

filter(meta, cell==ct_disease)

Warning message:
“There was 1 warning in `filter()`.
ℹ In argument: `cell == cellsubtype`.
Caused by warning in `cell == cellsubtype`:
! longer object length is not a multiple of shorter object length”

                                           orig.ident    nCount_RNA
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 SeuratProject  1629
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 SeuratProject  9791
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 SeuratProject  3222
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 SeuratProject  5226
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 SeuratProject  3194
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 SeuratProject   965
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 SeuratProject  2398
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 SeuratProject  3134
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 SeuratProject  2386
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 SeuratProject  5528
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 SeuratProject   926
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 SeuratProject   866
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 SeuratProject  2978
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 SeuratProject  2092
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 SeuratProject  1758
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 SeuratProject  2104
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 SeuratProject  1380
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 SeuratProject 11379
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 SeuratProject  2154
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 SeuratProject  1514
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 SeuratProject  3865
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 SeuratProject  3268
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 SeuratProject  2668
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 SeuratProject 12509
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 SeuratProject  1440
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 SeuratProject  3140
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 SeuratProject   838
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 SeuratProject  2247
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 SeuratProject  1352
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 SeuratProject  6946
⋮                                          ⋮             ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     SeuratProject  1122
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     SeuratProject  3978
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     SeuratProject  6248
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     SeuratProject  4872
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     SeuratProject  2204
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     SeuratProject  8347
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     SeuratProject  7154
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     SeuratProject  7514
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     SeuratProject  8545
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     SeuratProject 12118
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     SeuratProject  8879
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     SeuratProject  8665
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     SeuratProject  4792
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     SeuratProject  6919
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     SeuratProject  1037
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     SeuratProject  5469
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     SeuratProject  4954
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     SeuratProject  5633
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     SeuratProject  6237
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     SeuratProject 17768
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     SeuratProject  5252
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     SeuratProject  4632
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     SeuratProject 12025
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     SeuratProject  8184
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     SeuratProject 11906
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     SeuratProject  4167
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     SeuratProject  8688
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     SeuratProject   777
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     SeuratProject  5402
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     SeuratProject 15067
                                           nFeature_RNA percent.mt
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 1173         0.061387354
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 3730         0.000000000
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 1911         0.062073246
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 2759         0.000000000
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 1895         0.093926111
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1  763         0.207253886
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 1472         0.208507089
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 1769         0.000000000
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 1564         0.000000000
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 2680         0.000000000
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1  708         0.000000000
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1  665         0.346420323
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 1793         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 1479         0.047801147
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 1301         0.113765643
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 1452         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1  982         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 4100         0.008788118
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 1394         0.046425255
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 1114         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 2074         0.000000000
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 1707         1.070991432
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 1682         0.000000000
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 3775         0.015988488
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1  986         0.069444444
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 1792         0.031847134
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1  626         0.357995227
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 1452         0.000000000
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 1003         0.073964497
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 2991         0.000000000
⋮                                          ⋮            ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1      746         0.089126560
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     2116         0.201106083
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     2728         0.016005122
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     2102         0.041050903
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     1379         0.181488203
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     3340         0.000000000
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     2704         0.027956388
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     3097         0.000000000
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     3308         0.000000000
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     3736         0.057765308
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     3076         0.000000000
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     3475         0.011540681
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     2324         0.020868114
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     2872         0.000000000
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1      751         0.000000000
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     2689         0.091424392
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     2338         0.020185709
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     2699         0.088762649
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     2750         0.032066699
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     4541         0.005628095
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     2434         0.057121097
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     2199         0.107944732
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     3588         0.000000000
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     3092         0.048875855
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     4043         0.974298673
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     1823         0.095992321
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     3260         0.000000000
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1      601         0.257400257
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     2453         0.000000000
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     4204         0.006637021
                                           nCount_RNA_raw nFeature_RNA_raw
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1  1644          1185
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 10043          3858
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1  3270          1938
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1  5327          2812
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1  3241          1921
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1   970           767
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1  2424          1488
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1  3184          1803
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1  2423          1585
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1  5644          2733
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1   933           712
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1   875           674
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1  3024          1817
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1  2118          1500
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1  1779          1317
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1  2130          1469
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1  1391           988
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 11703          4218
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1  2172          1403
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1  1530          1124
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1  3953          2128
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1  3309          1728
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1  2715          1710
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 12805          3887
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1  1458           997
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1  3185          1824
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1   841           627
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1  2262          1464
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1  1363          1010
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1  7103          3072
⋮                                          ⋮              ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1      1127           751
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1      4018          2140
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1      6334          2772
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1      4912          2122
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1      2223          1388
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1      8447          3379
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1      7232          2740
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1      7607          3136
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1      8652          3357
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     12274          3793
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1      9005          3127
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1      8806          3531
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1      4836          2341
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1      7025          2917
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1      1043           753
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1      5535          2714
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1      5014          2363
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1      5695          2728
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1      6298          2779
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     18043          4622
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1      5303          2455
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1      4682          2217
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     12196          3649
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1      8292          3138
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     12074          4105
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1      4192          1838
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1      8798          3296
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1       778           602
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1      5464          2484
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     15278          4266
                                           donor_demux nCount_SCT nFeature_SCT
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 HL160042    2219       1169
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 HL170046    2804       1750
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 HL190326    3128       1906
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 HL200805    3593       2611
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 HL190326    3141       1893
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 HL230316    2030        793
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 HL220825    2485       1469
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 HL190326    3076       1767
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 HL190326    2470       1561
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 HL210726    3541       2423
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 HL210120    2082        748
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 HL170046    1927        740
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 HL170046    2961       1788
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 HL200925    2332       1476
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 HL230316    2192       1300
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 HL170046    2343       1450
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 HL200707    2498        982
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 HL230316    2852       1776
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 HL210120    2390       1392
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 HL190326    2321       1110
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 HL210806    3369       2071
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 HL210120    3161       1703
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 HL170046    2685       1682
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 HL210120    2904       1623
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 HL200805    2391        986
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 HL191025    3092       1790
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 HL170049    1945        694
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 HL230316    2401       1449
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 HL230316    2460       1010
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 HL190326    3208       2023
⋮                                          ⋮           ⋮          ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     HL170058    4602       1577
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     HL150015    5148       2110
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     HL160026    6164       2723
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     HL160037    5386       2100
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     HL210621    4960       1458
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     HL210621    6475       3336
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     HL150009    6448       2696
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     HL230324    6516       3095
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     HL190215    6423       3305
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     HL190114    6469       3019
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     HL160040    6451       3074
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     HL160040    6504       3472
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     HL211001    5353       2324
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     HL211001    6390       2870
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     HL210621    4546       1671
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     HL210621    5555       2683
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     HL210706    5394       2336
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     HL150009    5665       2696
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     HL150015    6163       2748
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     HL170058    5796       2481
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     HL190215    5492       2434
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     HL170052    5335       2198
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     HL160017    6437       2932
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     HL230324    6491       3090
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     HL150009    6599       3360
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     HL170055    5242       1818
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     HL160017    6457       3257
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     HL200212    4377       1794
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     HL230324    5538       2452
QY_2410_2_QY_2409_2_TTTGTGGCACAGAAAC-1     HL170052    6027       2709
                                           SCT.weight ⋯ MASH.CRN.score..X.8
MM_1341_1_2_MM_1337_1_2_AAACAGCCACAGACTC-1 0.4101630  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCAGTTATGT-1 0.6005030  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAACAGCCATCGTTCT-1 0.6803172  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAAGGACGTTTAAAGC-1 0.5305685  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACAAAGGTGCTAGAC-1 0.8975532  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACAGATAGCTGGACC-1 0.4995380  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACATTGTCCACCTTA-1 0.5318612  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AACCGCTCAATTGACT-1 0.9516511  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACCTAATCTTGTTCG-1 0.7328417  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AACCTCACAAACTCAT-1 0.6411623  ⋯ 6
MM_1341_1_2_MM_1337_1_2_AACGGTAAGTAGCGGG-1 0.5648848  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AACTAGCTCTGCAAAC-1 0.9942223  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AACTTAGTCTTAGCGG-1 0.4250199  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCGAATCAAACTCA-1 0.6638382  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAGCGAATCCGGTTAG-1 0.9832365  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AAGCGCTGTAGTAAGA-1 0.7407324  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTAGGACC-1 0.7346358  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AAGCTTGGTTCACTGT-1 0.7866507  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AAGTAGCCAGCAACCT-1 0.7817777  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AAGTGCAAGGTTAGAG-1 0.5165043  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AAGTTACGTGCATTTC-1 0.5727130  ⋯ 6
MM_1341_1_2_MM_1337_1_2_AAGTTACGTTTGGGTA-1 0.3301886  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AATAACCGTCACCAAA-1 0.7480180  ⋯ 3
MM_1341_1_2_MM_1337_1_2_AATAACCGTCATTAGG-1 0.8122284  ⋯ 5
MM_1341_1_2_MM_1337_1_2_AATCCCTGTCAGGCCA-1 0.5925272  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATCCCTGTGCAACTA-1 0.8309334  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AATCCGTAGTTGTCTT-1 0.9997513  ⋯ 4
MM_1341_1_2_MM_1337_1_2_AATTCGTCATGCTCCC-1 0.5210050  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGAGGTGG-1 0.6043902  ⋯ 0
MM_1341_1_2_MM_1337_1_2_AATTTGGTCGGTAACT-1 0.9418107  ⋯ 4
⋮                                          ⋮          ⋱ ⋮
QY_2410_2_QY_2409_2_TTCTTAGGTATTTGCC-1     0.5907971  ⋯ 3
QY_2410_2_QY_2409_2_TTGACATCAGCTAACC-1     0.8057492  ⋯ 3
QY_2410_2_QY_2409_2_TTGACATCAGCTAATT-1     0.4723170  ⋯ 0
QY_2410_2_QY_2409_2_TTGACTAAGTTTGTCT-1     0.5174117  ⋯ 1
QY_2410_2_QY_2409_2_TTGAGCTAGACTTATG-1     0.5401495  ⋯ 0
QY_2410_2_QY_2409_2_TTGCAACAGCCTGACA-1     0.9015664  ⋯ 0
QY_2410_2_QY_2409_2_TTGCACACAATCATGT-1     0.6086190  ⋯ 1
QY_2410_2_QY_2409_2_TTGCACACACAGAACG-1     0.6909563  ⋯ 3
QY_2410_2_QY_2409_2_TTGCACACACTAAGTT-1     0.9930385  ⋯ 0
QY_2410_2_QY_2409_2_TTGCATTTCGTTTCGC-1     0.7972647  ⋯ 6
QY_2410_2_QY_2409_2_TTGCCCGTCCCGCCTA-1     0.6614122  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCGCTTCTA-1     0.5817982  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCGTTTCTG-1     0.9999906  ⋯ 0
QY_2410_2_QY_2409_2_TTGCGTCTCTTTGTAC-1     0.7194609  ⋯ 0
QY_2410_2_QY_2409_2_TTGCTTAGTATTGCAG-1     0.6911579  ⋯ 0
QY_2410_2_QY_2409_2_TTGGCGGGTAATTAGC-1     0.6209573  ⋯ 0
QY_2410_2_QY_2409_2_TTGGCTGAGGGATGAC-1     0.8818744  ⋯ 2
QY_2410_2_QY_2409_2_TTGGGCCAGGCTAAGA-1     0.6225869  ⋯ 1
QY_2410_2_QY_2409_2_TTGGTGAGTGCTAGCG-1     0.6524449  ⋯ 3
QY_2410_2_QY_2409_2_TTGTCCATCATCCTCA-1     0.7832207  ⋯ 3
QY_2410_2_QY_2409_2_TTGTCCATCTCAATTC-1     0.9200486  ⋯ 0
QY_2410_2_QY_2409_2_TTTAACGAGGTTAGCT-1     0.9837636  ⋯ 0
QY_2410_2_QY_2409_2_TTTAGCAAGGTGTCCA-1     0.8762140  ⋯ 2
QY_2410_2_QY_2409_2_TTTCCACCACAGGGAC-1     0.6270335  ⋯ 3
QY_2410_2_QY_2409_2_TTTCTCACAGGCCATT-1     1.0000000  ⋯ 1
QY_2410_2_QY_2409_2_TTTCTTGCACTAAGCC-1     0.5818298  ⋯ 4
QY_2410_2_QY_2409_2_TTTGAGTCATAGCTTG-1     0.9981949  ⋯ 2
QY_2410_2_QY_2409_2_TTTGCGGAGGGTTATC-1     0.5907961  ⋯ 3
QY_2410_2_QY_2409_2_TTTGTCCCATTCCTCG-1     0.9045377  ⋯ 3

In [8]:
write.table(sort(unique(meta$ct_disease)), 
           paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/celltypes_by_disease.list.txt'),
           sep='\t', quote=F, row.names=F, col.names=F)

In [6]:
for (cell in unique(meta$ct_disease)) {
    write.table(row.names(filter(meta, cell==ct_disease)), 
               paste0('/nfs/lab/tscc/welison/FNIH.Liver/peak-call-pipeline/barcodes/celltypes_by_disease/', cell, '.barcode.prefix.txt'),
               sep='\t', quote=F, row.names=F, col.names=F)
}

In [7]:
sort(unique(meta$ct_disease))

 [1] "B_Control"             "B_MASH"                "B_MASL"
 [4] "B_MetALD"              "Cholangiocyte_Control" "Cholangiocyte_MASH"
 [7] "Cholangiocyte_MASL"    "Cholangiocyte_MetALD"  "Endothelial_Control"
[10] "Endothelial_MASH"      "Endothelial_MASL"      "Endothelial_MetALD"
[13] "Hepatocytes_Control"   "Hepatocytes_MASH"      "Hepatocytes_MASL"
[16] "Hepatocytes_MetALD"    "HSC_Control"           "HSC_MASH"
[19] "HSC_MASL"              "HSC_MetALD"            "Mast_Control"
[22] "Mast_MASH"             "Mast_MASL"             "Mast_MetALD"
[25] "Myeloid_Control"       "Myeloid_MASH"          "Myeloid_MASL"
[28] "Myeloid_MetALD"        "NK_Control"            "NK_MASH"
[31] "NK_MASL"               "NK_MetALD"             "Schwann_Control"
[34] "Schwann_MASH"          "Schwann_MASL"          "Schwann_MetALD"
[37] "T_Control"             "T_MASH"                "T_MASL"
[40] "T_MetALD"