In [2]:
import scanpy as sc

In [3]:
# defining rank genes zones for tangram
# using all masl samples in RNA multiple
# downsampling for 10k cells out of all masl cells for tangram reference
# running rank genes on downsamples 10k cell reference

In [4]:
adata_masl = sc.read_h5ad('/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/spatial/spatial_scr/condition_h5ad/MASL.h5ad')
sc.pp.normalize_total(adata_masl) #it seems like its raw counts
# Logarithmize the data
sc.pp.log1p(adata_masl)
adata_masl_heps = adata_masl[adata_masl.obs['celltype'].isin(['Hepatocytes'])]
adata_masl_heps.obs['donor_demux'].value_counts()

donor_demux
HL181031    9572
HL150001    8760
HL230324    6674
HL221201    5846
HL210706    5019
HL150015    4421
HL160030    3785
HL170048    3455
HL220405    2931
HL190326    2853
HL220628    2762
HL200212    2533
HL160035    2417
HL190909    2359
HL150009    2317
HL211025    2044
HL160032    1751
HL200615    1696
HL170065    1656
HL190603    1518
HL160042    1031
HL200707     987
HL210727     886
HL210521     695
HL201120     342
Name: count, dtype: int64

In [8]:
adata_masl_heps.obs['cellsubtype'].value_counts()

cellsubtype
Hepatocytes.Zone3    31720
Hepatocytes.Zone2    26433
Hepatocytes.Zone1    16416
Name: count, dtype: int64

In [6]:
# remove stress and senescent clusters

In [9]:
adata_masl_heps = adata_masl_heps[~adata_masl_heps.obs['cellsubtype'].isin(['Hepatocytes.Senescent', 'Hepatocytes.Stress'])]
adata_masl_heps.obs['cellsubtype'].value_counts()

cellsubtype
Hepatocytes.Zone3    31720
Hepatocytes.Zone2    26433
Hepatocytes.Zone1    16416
Name: count, dtype: int64

In [10]:
adata_masl_heps

View of AnnData object with n_obs × n_vars = 74569 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [ ]:
# no stressed population?

In [11]:
sc_cells = 10000

In [12]:
# User input: Set n_obs to number of cells to keep

sc.pp.subsample(adata_masl_heps, n_obs=sc_cells, random_state=42)

In [13]:
adata_masl_heps

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [14]:
sc_cells = 10000

In [15]:
# User input: Set n_obs to number of cells to keep

sc.pp.subsample(adata_masl_heps, n_obs=sc_cells, random_state=42)

In [16]:
adata_masl_heps

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [17]:
sc.tl.rank_genes_groups(adata_masl_heps, groupby="cellsubtype", use_raw=False)

In [18]:
import pandas as pd
import csv

In [19]:
markers_df_adata_masl_heps = pd.DataFrame(adata_masl_heps.uns["rank_genes_groups"]["names"]).iloc[:, :]

In [20]:
markers_df_adata_masl_heps

      Hepatocytes.Zone1 Hepatocytes.Zone2 Hepatocytes.Zone3
0                   SDS               FGG           SLCO1B3
1                   HAL              NREP            CYP3A4
2                SLC7A2               FGA           SLCO1B7
3                 PDE7B               CRP           ZNF385D
4                  CPS1        AC007221.1              ADH4
...                 ...               ...               ...
36596           ZNF385D        AC004053.1             PDE7B
36597              ADH4           ZNF385D             FGF14
36598           SLCO1B7           SLCO1B7              AFF3
36599            CYP3A4            CYP3A4               HAL
36600           SLCO1B3           SLCO1B3        AC007221.1

[36601 rows x 3 columns]

In [21]:
# Iterate through each column and save it to a text file
for celltype in markers_df_adata_masl_heps.columns:
    #celltype = 'Hepatocytes.Senescent'
        # Extract the genes for the current cell type
    genes = markers_df_adata_masl_heps[celltype].dropna()  # Drop any NaN values if present
    
    # Add quotes around each gene
    genes_with_quotes = [f'{gene}' for gene in genes]
    #print(genes.head())
    # Create a dataframe with column name "x"
    output_df = pd.DataFrame(genes_with_quotes, columns=["x"])
    
    
    print(output_df.head())
    # Save to a text file named after the cell type
    output_df.to_csv(f"/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/scripts/zone_gene_lists/MASL_alldonors_nosen_stress_{celltype}_RNA_Multiome_RankGenesALL.txt",
                     index=False, sep="\t",quoting=csv.QUOTE_ALL)

        x
0     SDS
1     HAL
2  SLC7A2
3   PDE7B
4    CPS1
            x
0         FGG
1        NREP
2         FGA
3         CRP
4  AC007221.1
         x
0  SLCO1B3
1   CYP3A4
2  SLCO1B7
3  ZNF385D
4     ADH4

In [22]:

markers_df_adata_masl_heps_top50 = pd.DataFrame(adata_masl_heps.uns["rank_genes_groups"]["names"]).iloc[0:50, :]
markers_df_adata_masl_heps_top50.head()

  Hepatocytes.Zone1 Hepatocytes.Zone2 Hepatocytes.Zone3
0               SDS               FGG           SLCO1B3
1               HAL              NREP            CYP3A4
2            SLC7A2               FGA           SLCO1B7
3             PDE7B               CRP           ZNF385D
4              CPS1        AC007221.1              ADH4

In [23]:
markers_df_adata_masl_heps_top50.shape # Check out dimensions

(50, 3)

In [24]:
import numpy as np

In [25]:
markers_df_adata_masl_heps_top50 = list(np.unique(markers_df_adata_masl_heps_top50.melt().value.values))   # Create an array of the unique markers across all the cell types
len(markers_df_adata_masl_heps_top50)

148

In [26]:
adata_masl_heps

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p', 'rank_genes_groups'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [27]:
adata_masl_heps.__dict__['_raw'].__dict__['_var'] = adata_masl_heps.__dict__['_raw'].__dict__['_var'].rename(columns={'_index': 'features'})

In [28]:
import os

In [29]:
gene_nums = 50

export_dir = '/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250214_tangram_preprocessing_genelist50_liver_masl_heps_alldonors_top50_nosen_stress/'

if not os.path.isdir(export_dir):
    os.mkdir(export_dir)

print(export_dir)

/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250214_tangram_preprocessing_genelist50_liver_masl_heps_alldonors_top50_nosen_stress/

In [30]:
# Write out the preprocessed objects to be fed into a python script that runs tangram

adata_masl_heps.write(export_dir + 'Preprocessed_adsc.h5ad')
#ad_sp.write(export_dir + 'Preprocessed_adsp.h5ad')

file = open(export_dir +'markers','w')
for item in markers_df_adata_masl_heps_top50:
	file.write(item+"\n")
file.close()

In [31]:
test = sc.read_h5ad('/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250214_tangram_preprocessing_genelist50_liver_masl_heps_alldonors_top50_nosen_stress/Preprocessed_adsc.h5ad')

In [32]:
test

AnnData object with n_obs × n_vars = 10000 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p', 'rank_genes_groups'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'

In [24]:
test = sc.read_h5ad('/tscc/projects/ps-epigen/users/cmiciano/Liver/RNA/outputs/sandbox/spatial/250225_tangram_preprocessing_genelist50_liver_masl_heps_HL230324_top50/Preprocessed_adsc.h5ad')

In [25]:
test

AnnData object with n_obs × n_vars = 6674 × 36601
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'percent.mt', 'nCount_RNA_raw', 'nFeature_RNA_raw', 'donor_demux', 'nCount_SCT', 'nFeature_SCT', 'SCT.weight', 'seurat_clusters', 'log_nCount_SCT', 'log_nFeature_SCT', 'lane', 'batch', 'gex_raw_reads', 'gex_mapped_reads', 'gex_conf_intergenic_reads', 'gex_conf_exonic_reads', 'gex_conf_intronic_reads', 'gex_conf_exonic_unique_reads', 'gex_conf_exonic_antisense_reads', 'gex_conf_exonic_dup_reads', 'gex_exonic_umis', 'gex_conf_intronic_unique_reads', 'gex_conf_intronic_antisense_reads', 'gex_conf_intronic_dup_reads', 'gex_intronic_umis', 'gex_conf_txomic_unique_reads', 'gex_umis_count', 'gex_genes_count', 'atac_raw_reads', 'atac_unmapped_reads', 'atac_lowmapq', 'atac_dup_reads', 'atac_chimeric_reads', 'atac_mitochondrial_reads', 'atac_fragments', 'atac_TSS_fragments', 'atac_peak_region_fragments', 'atac_peak_region_cutsites', 'TSS.enrichment', 'TSS.percentile', 'condition', 'disease_status', 'library', 'amulet', 'nCount_Peaks', 'nFeature_Peaks', 'Description', 'Age', 'BMI', 'Gender', 'Alcoholic..2..Drinks.Day.', 'Steatosis.grade', 'Steatosis..', 'Fat.distribution', 'Lobular.inflammation', 'Ballooning', 'Portal.inflammation', 'Hepatocyte.necrosis', 'MASH.CRN.score..X.8', 'Diagnosis', 'Peaks.weight', 'value', 'barcode', 'cellsubtype', 'celltype', 'nCount_Peaks_Full', 'nFeature_Peaks_Full', 'Fibrosis.stage', 'spatial_annotations'
    var: 'features'
    uns: 'log1p', 'rank_genes_groups'
    obsm: 'X_umap.atac', 'X_umap.rna', 'X_umap.wnn'