In [1]:
library(dplyr)
library(tidyr)
library(stringr)
library(vroom)

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [ ]:
# Read in data, for QTLs only keep summary stat variants

In [51]:
cred.set <- read.table('/nfs/lab/projects/nash_nafld_liver/GWAS/MVP_GWAS/NAFLD.TRANS.MVP.2021.credset.hg38.tsv', sep='\t', header=T)
dim(cred.set)
head(cred.set)

[1] 1084   18

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438   rs2642438   1   220970028 A  G   0.274 -0.075 0.0074
2            rs6734238   rs6734238   2   113841030 G  A   0.407 -0.057 0.0064
3            rs138033684 rs138033684 6    71895252 G  T   0.006  0.677 0.1120
4            rs2980888   rs2980888   8   126507308 T  C   0.286  0.130 0.0072
5            rs4484649   rs4484649   8    10571491 C  A   0.419  0.045 0.0066
6            rs4841132   rs4841132   8     9183596 A  G   0.106  0.123 0.0105
  P        N      PP     Nominated.Gene     Biological.Prior.Gene chr.hg38
1 6.65e-24 218595 96.86% MTARC1             MTARC1                1
2 4.94e-19 218595 99.04% IL1RN              IL1RN                 2
3 1.42e-09  37364 96.31% OGFRL1             OGFRL1                6
4 4.21e-72 218595 99.95% lnc-TRIB1-2;WASHC5 TRIB1                 8
5 1.38e-11 218595 98.51% SOX7;RP1L1;C8orf74 RP1L1;SOX7            8
6 6.62e-32 218595 98.79% PPP1R3B            PPP1R3B;TNKS;MFHAS1   8
  end.hg38  start.hg38
1 220796686 220796685
2 113083453 113083452
3  71185549  71185548
4 125495066 125495065
5  10713981  10713980
6   9326086   9326085

In [19]:
coloc.results.dir <- '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/qtl.coloc/gwas/coloc.res/'
coloc.res <- read.table(paste0(coloc.results.dir, '241205_WE_Full_Coloc_Summary_Stats_PP4_0.8_r2_0.5.tsv'),
                        sep='\t', header=T)
dim(coloc.res)
head(coloc.res)

[1] 213  16

  nsnps PP.H0.abf    PP.H1.abf    PP.H2.abf    PP.H3.abf   PP.H4.abf cell
1 2825  9.681856e-10 1.149327e-04 2.216742e-07 0.025340263 0.9745446 Bulk
2 2566  2.705990e-05 2.476040e-02 1.156288e-05 0.009614698 0.9655863 Bulk
3 5058  5.088451e-02 6.435270e-02 1.102903e-02 0.013087567 0.8606462 Bulk
4 5057  3.724166e-02 5.371677e-02 8.071817e-03 0.010752443 0.8902173 Bulk
5 2439  2.088562e-34 1.195832e-10 1.869171e-25 0.106127774 0.8938722 Bulk
6 2412  4.655157e-12 5.397353e-11 4.166160e-03 0.047355445 0.9484784 Bulk
  modality feature                  qtl.lead   qtl.pval     qtl.pos
1 ATAC     chr1-16189980-16190280   rs1497406  1.547193e-10  16178825
2 ATAC     chr1-229256817-229257117 rs10916454 2.233151e-09 229253038
3 ATAC     chr10-26710287-26710575  rs2477276  5.178316e-08  26666136
4 ATAC     chr10-26711375-26711675  rs2477276  3.571726e-08  26666136
5 ATAC     chr11-61820741-61821041  rs174576   2.043734e-17  61836038
6 ATAC     chr11-61832766-61833066  rs174576   4.284548e-07  61836038
  gwas.lead  gwas.pval qtl.pos.1 r2
1 rs1497406  1.458e-08  16178825 1.000
2 rs12041301 9.290e-06 229245010 0.816
3 rs2477276  2.912e-05  26666136 1.000
4 rs2477276  2.912e-05  26666136 1.000
5 rs174535   3.105e-15  61783884 0.911
6 rs174535   3.105e-15  61783884 0.911

In [20]:
sum(cred.set$CS.SNP %in% coloc.res$gwas.lead)

[1] 16

In [21]:
cell <- c('Hepatocytes')
atac.qtl.coloc.vars.res <- data.frame()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Myeloid')) {
    for (i in 1:22) {
        atac.qtl.coloc.vars.res <- vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/05_caQTLs/outs/',cell,'.cis_qtl_pairs.chr',i,'.parquet.sig.tsv')) %>%
            filter(variant_id %in% c(cred.set$CS.SNP)) %>%
            mutate(cell=cell) %>%
            rbind(atac.qtl.coloc.vars.res)
    }
}

dim(atac.qtl.coloc.vars.res)
head(atac.qtl.coloc.vars.res)

Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 183 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 393 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 9 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 38 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 296 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 130 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 50 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 72 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 55 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 547 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 91 Columns: 12

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 747 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 10 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 181 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 117 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 216 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 20 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 25 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 60 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 35 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 139 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (12): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 166 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 17 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 37 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 39 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6318 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7422 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6265 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6175 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5955 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 14396 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 9295 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5919 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5179 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4045 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4666 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 4007 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1333 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4407 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1948 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3527 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 16440 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 801 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3281 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2591 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1761 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2778 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 34376 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 32452 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 26048 Columns: 12

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 22693 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 18829 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 31951 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 25230 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 25644 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 9927 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 16975 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 17340 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 15263 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 7432 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 11745 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 11019 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 10828 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 68169 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 12192 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8525 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 11194 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5075 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 9074 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1603 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1708 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1460 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 951 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 763 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4616 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1719 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Rows: 1518 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 755 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1030 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1846 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 465 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 591 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 412 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 334 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1163 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4075 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 287 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 869 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 809 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 583 Columns: 12

── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 581 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 10352 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 9168 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6450 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 6780 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5443 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 17973 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8667 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4722 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3992 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5632 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 4814 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 5347 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2138 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2337 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3941 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3447 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 25900 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2062 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 3112 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2597 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1569 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1807 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 1260   13

  phenotype_id          variant_id start_distance end_distance af
1 chr19-4327352-4327620 rs35013670  9675           9408        0.3779070
2 chr19-4327352-4327620 rs28654688 12821          12554        0.4418605
3 chr19-4327352-4327620 rs3810367  15497          15230        0.4476744
4 chr19-4327651-4327951 rs35013670  9376           9077        0.3779070
5 chr19-4327651-4327951 rs28654688 12522          12223        0.4418605
6 chr19-4327651-4327951 rs12978346 13093          12794        0.3023256
  ma_samples ma_count pval_nominal slope     slope_se  pval_nominal_threshold
1 56         65       5.542695e-07 0.8183219 0.1437315 3.04817e-06
2 65         76       1.947807e-06 0.7966865 0.1490473 3.04817e-06
3 66         77       2.106467e-06 0.7794851 0.1464282 3.04817e-06
4 56         65       2.155003e-06 0.8106108 0.1524574 3.29284e-06
5 65         76       8.085321e-07 0.8481727 0.1517498 3.29284e-06
6 45         52       1.143572e-06 0.7831656 0.1425668 3.29284e-06
  sig.qtl cell
1 TRUE    Myeloid
2 TRUE    Myeloid
3 TRUE    Myeloid
4 TRUE    Myeloid
5 TRUE    Myeloid
6 TRUE    Myeloid

In [22]:
rna.qtl.coloc.vars.res <- data.frame()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Myeloid')) {
    rna.qtl.coloc.vars.res <- vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/04_eQTLs/outs/',cell,'.cis_qtl_pairs.chr.qvalue.sig.tsv')) %>%
        filter(variant_id %in% c(cred.set$CS.SNP)) %>%
        mutate(cell=cell) %>%
        rbind(rna.qtl.coloc.vars.res)
}

dim(rna.qtl.coloc.vars.res)
head(rna.qtl.coloc.vars.res)

Rows: 653 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8140 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 23747 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 75380 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8952 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 27044 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (8): start_distance, af, ma_samples, ma_count, pval_nominal, slope, slop...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 52 12

  phenotype_id variant_id start_distance af        ma_samples ma_count
1 HSD17B13     rs10433879  -12898        0.2034884 30         35
2 HLA-DQB1     rs968155   -255445        0.6453488 48         61
3 HLA-DQB1     rs9271406   -48572        0.5930232 54         70
4 EPHA2        rs11588341   15484        0.5232558 61         82
5 EPHA2        rs1497407    17041        0.4883721 60         84
6 EPHA2        rs7519043    17959        0.5174419 62         83
  pval_nominal slope      slope_se   sig.qtl pval_nominal_threshold cell
1 4.227959e-06  0.7136446 0.13917176 TRUE    1.03562e-05            Myeloid
2 8.382722e-06 -0.5900655 0.11959907 TRUE    1.02602e-05            Myeloid
3 8.116191e-08 -0.6510572 0.10469777 TRUE    1.02602e-05            Myeloid
4 9.513265e-06 -0.3773269 0.07704365 TRUE    2.53574e-05            Hepatocytes
5 8.349330e-06 -0.3804022 0.07708509 TRUE    2.53574e-05            Hepatocytes
6 6.773970e-06 -0.3836847 0.07682361 TRUE    2.53574e-05            Hepatocytes

In [23]:
H3K27ac.qtl.coloc.vars.res <- data.frame()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Myeloid')) {
    H3K27ac.qtl.coloc.vars.res <- vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/06_H3K27acQTLs/outs/',cell,'.cis_qtl_pairs.chr.qvalue.sig.tsv')) %>%
        filter(variant_id %in% c(cred.set$CS.SNP)) %>%
        mutate(cell=cell) %>%
        rbind(H3K27ac.qtl.coloc.vars.res)
}

dim(H3K27ac.qtl.coloc.vars.res)
head(H3K27ac.qtl.coloc.vars.res)

Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 1653 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 19948 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 697 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 101  13

  phenotype_id         variant_id start_distance end_distance af
1 chr8:8227666-8228665 rs2979172  225331         224333       0.6395349
2 chr8:8227666-8228665 rs4841040  569350         568352       0.5872093
3 chr8:8227666-8228665 rs6994038  575361         574363       0.5872093
4 chr8:8227666-8228665 rs4841042  579445         578447       0.5930232
5 chr8:8227666-8228665 rs7823757  585000         584002       0.5813953
6 chr8:8227666-8228665 rs60315134 585422         584424       0.5813953
  ma_samples ma_count pval_nominal slope      slope_se  sig.qtl
1 47         62       1.630880e-09 -0.9632696 0.1324173 TRUE
2 56         71       5.232810e-09 -0.9810939 0.1409638 TRUE
3 56         71       2.781884e-08 -0.9362662 0.1438492 TRUE
4 54         70       5.722191e-09 -0.9160417 0.1320748 TRUE
5 56         72       6.893619e-09 -0.9762346 0.1417808 TRUE
6 56         72       6.893619e-09 -0.9762346 0.1417808 TRUE
  pval_nominal_threshold cell
1 1.09088e-07            Myeloid
2 1.09088e-07            Myeloid
3 1.09088e-07            Myeloid
4 1.09088e-07            Myeloid
5 1.09088e-07            Myeloid
6 1.09088e-07            Myeloid

In [24]:
H3K27me3.qtl.coloc.vars.res <- data.frame()

for (cell in c('B','Cholangiocyte','Endothelial','Hepatocytes','HSC','Myeloid')) {
    H3K27me3.qtl.coloc.vars.res <- vroom(paste0('/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/07_H3K27me3QTLs/outs/',cell,'.cis_qtl_pairs.chr.qvalue.sig.tsv')) %>%
        filter(variant_id %in% c(cred.set$CS.SNP)) %>%
        mutate(cell=cell) %>%
        rbind(H3K27me3.qtl.coloc.vars.res)
}

dim(H3K27me3.qtl.coloc.vars.res)
head(H3K27me3.qtl.coloc.vars.res)

Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 54 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 31798 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 0 Columns: 11
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (11): phenotype_id, variant_id, start_distance, end_distance, af, ma_sam...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 101 Columns: 12
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): phenotype_id, variant_id
dbl (9): start_distance, end_distance, af, ma_samples, ma_count, pval_nomina...
lgl (1): sig.qtl

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 14 13

  phenotype_id           variant_id start_distance end_distance af
1 chr6:32550868-32552367 rs9268839  -89874         -91372       0.5174419
2 chr6:32550868-32552367 rs13211921 -75810         -77308       0.5174419
3 chr6:32550868-32552367 rs9391879  -75474         -76972       0.5174419
4 chr6:32550868-32552367 rs12195589 -74062         -75560       0.5174419
5 chr6:32550868-32552367 rs28895253 -73736         -75234       0.5174419
6 chr6:32550868-32552367 rs28895257 -73532         -75030       0.5174419
  ma_samples ma_count pval_nominal slope     slope_se  sig.qtl
1 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
2 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
3 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
4 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
5 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
6 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
  pval_nominal_threshold cell
1 4.81518e-07            Hepatocytes
2 4.81518e-07            Hepatocytes
3 4.81518e-07            Hepatocytes
4 4.81518e-07            Hepatocytes
5 4.81518e-07            Hepatocytes
6 4.81518e-07            Hepatocytes

In [ ]:
# Quick look at overlap

In [25]:
length(unique(cred.set$LEAD.SNP))

[1] 77

In [26]:
sum(cred.set$CS.SNP %in% atac.qtl.coloc.vars.res$variant_id)
sum(cred.set$CS.SNP %in% rna.qtl.coloc.vars.res$variant_id)
sum(cred.set$CS.SNP %in% H3K27ac.qtl.coloc.vars.res$variant_id)
sum(cred.set$CS.SNP %in% H3K27me3.qtl.coloc.vars.res$variant_id)

sum(cred.set$CS.SNP %in% c(atac.qtl.coloc.vars.res$variant_id,rna.qtl.coloc.vars.res$variant_id,
                           H3K27ac.qtl.coloc.vars.res$variant_id,H3K27me3.qtl.coloc.vars.res$variant_id))

[1] 410

[1] 49

[1] 49

[1] 14

[1] 423

In [27]:
unique(atac.qtl.coloc.vars.res$cell)
unique(rna.qtl.coloc.vars.res$cell)
unique(H3K27ac.qtl.coloc.vars.res$cell)
unique(H3K27me3.qtl.coloc.vars.res$cell)

[1] "Myeloid"       "HSC"           "Hepatocytes"   "Endothelial"
[5] "Cholangiocyte" "B"

[1] "Myeloid"     "Hepatocytes" "Endothelial"

[1] "Myeloid"     "Hepatocytes" "Endothelial"

[1] "Hepatocytes"

In [28]:
filter(atac.qtl.coloc.vars.res, cell==cell)

     phenotype_id              variant_id start_distance end_distance af
1    chr19-4327352-4327620     rs35013670   9675           9408       0.3779070
2    chr19-4327352-4327620     rs28654688  12821          12554       0.4418605
3    chr19-4327352-4327620     rs3810367   15497          15230       0.4476744
4    chr19-4327651-4327951     rs35013670   9376           9077       0.3779070
5    chr19-4327651-4327951     rs28654688  12522          12223       0.4418605
6    chr19-4327651-4327951     rs12978346  13093          12794       0.3023256
7    chr19-4327651-4327951     rs3810368   15081          14782       0.2965116
8    chr19-4327651-4327951     rs3810367   15198          14899       0.4476744
9    chr19-4328187-4328487     rs12978346  12557          12258       0.3023256
10   chr17-63834872-63835172   rs57553639 -63734         -64033       0.3255814
11   chr17-63834872-63835172   rs58131426 -57858         -58157       0.3255814
12   chr17-63834872-63835172   rs2584641  -49344         -49643       0.3255814
13   chr17-63834872-63835172   rs2665840  -38926         -39225       0.3255814
14   chr17-63834872-63835172   rs2727332  -33649         -33948       0.3255814
15   chr17-63834872-63835172   rs2584632  -31592         -31891       0.3255814
16   chr17-63834872-63835172   rs2584630  -24672         -24971       0.3255814
17   chr17-63834872-63835172   rs2727292  -18486         -18785       0.3255814
18   chr17-63834872-63835172   rs2665835   -8975          -9274       0.3255814
19   chr17-63834872-63835172   rs2584623   -5554          -5853       0.3255814
20   chr17-63834872-63835172   rs13030     -3677          -3976       0.3255814
21   chr17-63834872-63835172   rs2584620     959            660       0.3255814
22   chr17-63834872-63835172   rs2665799    7490           7191       0.3255814
23   chr17-63834872-63835172   rs2727329   12333          12034       0.3255814
24   chr17-63834872-63835172   rs2584614   17212          16913       0.3255814
25   chr17-63834872-63835172   rs2584613   19300          19001       0.3255814
26   chr17-63834872-63835172   rs35448669  26690          26391       0.3255814
27   chr12-121167241-121167541 rs2857590    1014            715       0.2848837
28   chr12-121167241-121167541 rs1718131    1274            975       0.2848837
29   chr12-121167241-121167541 rs1653610    1360           1061       0.2848837
30   chr12-121167241-121167541 rs1618709    1872           1573       0.2848837
⋮    ⋮                         ⋮          ⋮              ⋮            ⋮
1231 chr8-8228311-8228611      rs2409092  596370         596071       0.5872093
1232 chr8-8228311-8228611      rs1533058  599368         599069       0.5872093
1233 chr8-8227864-8228164      rs2979172  225133         224834       0.6395349
1234 chr8-8227864-8228164      rs4841040  569152         568853       0.5872093
1235 chr8-8227864-8228164      rs6994038  575163         574864       0.5872093
1236 chr8-8227864-8228164      rs4841042  579247         578948       0.5930232
1237 chr8-8227864-8228164      rs7823757  584802         584503       0.5813953
1238 chr8-8227864-8228164      rs60315134 585224         584925       0.5813953
1239 chr8-8227864-8228164      rs11784052 586587         586288       0.5872093
1240 chr8-8227864-8228164      rs4841045  587204         586905       0.5872093
1241 chr8-8227864-8228164      rs13259216 588226         587927       0.5872093
1242 chr8-8227864-8228164      rs882462   593155         592856       0.5813953
1243 chr8-8227864-8228164      rs57312668 595102         594803       0.5872093
1244 chr8-8227864-8228164      rs2409092  596817         596518       0.5872093
1245 chr8-8227864-8228164      rs1533058  599815         599516       0.5872093
1246 chr8-8228311-8228611      rs2979172  224686         224387       0.6395349
1247 chr8-8228311-8228611      rs4841040  568705         568406       0.5872093
1248 chr8-8228311-8228611      rs6994038  574716         574417       0.5872093
1249 chr8-8228311-8228611      rs4841042  578800         578501       0.5930232
1250 chr8-8228311-8228611      rs7823757  584355         584056       0.5813953
1251 chr8-8228311-8228611      rs60315134 584777         584478       0.5813953
1252 chr8-8228311-8228611      rs11784052 586140         585841       0.5872093
1253 chr8-8228311-8228611      rs4841045  586757         586458       0.5872093
1254 chr8-8228311-8228611      rs13259216 587779         587480       0.5872093
1255 chr8-8228311-8228611      rs882462   592708         592409       0.5813953
1256 chr8-8228311-8228611      rs11775523 593354         593055       0.5872093
1257 chr8-8228311-8228611      rs1039915  593792         593493       0.5930232
1258 chr8-8228311-8228611      rs57312668 594655         594356       0.5872093
1259 chr8-8228311-8228611      rs2409092  596370         596071       0.5872093
1260 chr8-8228311-8228611      rs1533058  599368         599069       0.5872093
     ma_samples ma_count pval_nominal slope      slope_se
1    56         65       5.542695e-07  0.8183219 0.1437315
2    65         76       1.947807e-06  0.7966865 0.1490473
3    66         77       2.106467e-06  0.7794851 0.1464282
4    56         65       2.155003e-06  0.8106108 0.1524574
5    65         76       8.085321e-07  0.8481727 0.1517498
6    45         52       1.143572e-06  0.7831656 0.1425668
7    45         51       1.676921e-06  0.7826868 0.1452934
8    66         77       1.988750e-06  0.8080804 0.1513433
9    45         52       2.433819e-06  0.5466126 0.1034675
10   47         56       6.351207e-06 -0.6809292 0.1358419
11   47         56       6.351207e-06 -0.6809292 0.1358419
12   47         56       6.351207e-06 -0.6809292 0.1358419
13   47         56       6.351207e-06 -0.6809292 0.1358419
14   47         56       6.351207e-06 -0.6809292 0.1358419
15   47         56       6.351207e-06 -0.6809292 0.1358419
16   47         56       6.351207e-06 -0.6809292 0.1358419
17   47         56       6.351207e-06 -0.6809292 0.1358419
18   47         56       6.351207e-06 -0.6809292 0.1358419
19   47         56       6.351207e-06 -0.6809292 0.1358419
20   47         56       6.351207e-06 -0.6809292 0.1358419
21   47         56       6.351207e-06 -0.6809292 0.1358419
22   47         56       6.351207e-06 -0.6809292 0.1358419
23   47         56       6.351207e-06 -0.6809292 0.1358419
24   47         56       6.351207e-06 -0.6809292 0.1358419
25   47         56       6.351207e-06 -0.6809292 0.1358419
26   47         56       6.351207e-06 -0.6809292 0.1358419
27   42         49       2.883939e-06  0.6597506 0.1260173
28   42         49       2.883939e-06  0.6597506 0.1260173
29   42         49       2.883939e-06  0.6597506 0.1260173
30   42         49       2.883939e-06  0.6597506 0.1260173
⋮    ⋮          ⋮        ⋮            ⋮          ⋮
1231 56         71       5.350162e-10 -1.0119930 0.1335846
1232 56         71       5.350162e-10 -1.0119930 0.1335846
1233 47         62       1.274845e-09 -0.9176182 0.1249991
1234 56         71       5.265978e-10 -0.9771583 0.1289133
1235 56         71       1.878108e-10 -0.9978528 0.1269644
1236 54         70       8.880569e-10 -0.9238093 0.1241902
1237 56         72       3.984267e-10 -0.9787574 0.1278511
1238 56         72       3.984267e-10 -0.9787574 0.1278511
1239 55         71       6.163621e-10 -0.9622616 0.1276651
1240 55         71       6.163621e-10 -0.9622616 0.1276651
1241 54         71       9.317418e-10 -0.9333239 0.1256885
1242 56         72       1.368078e-09 -0.9456959 0.1291592
1243 56         71       1.486142e-07 -0.8693023 0.1435949
1244 56         71       1.486142e-07 -0.8693023 0.1435949
1245 56         71       1.486142e-07 -0.8693023 0.1435949
1246 47         62       4.638804e-09 -0.8702576 0.1244574
1247 56         71       1.144367e-11 -1.0064007 0.1167038
1248 56         71       1.013459e-11 -1.0119766 0.1168971
1249 54         70       3.019296e-11 -0.9474948 0.1133730
1250 56         72       7.917561e-12 -1.0081533 0.1155473
1251 56         72       7.917561e-12 -1.0081533 0.1155473
1252 55         71       7.943987e-12 -0.9985215 0.1144554
1253 55         71       7.943987e-12 -0.9985215 0.1144554
1254 54         71       4.676211e-12 -0.9821742 0.1107233
1255 56         72       3.652882e-11 -0.9748945 0.1173833
1256 55         71       7.152499e-09 -0.8796076 0.1279322
1257 55         70       3.412433e-09 -0.9060807 0.1280634
1258 56         71       2.502791e-09 -0.9267010 0.1294473
1259 56         71       2.502791e-09 -0.9267010 0.1294473
1260 56         71       2.502791e-09 -0.9267010 0.1294473
     pval_nominal_threshold sig.qtl cell
1    3.04817e-06            TRUE    Myeloid
2    3.04817e-06            TRUE    Myeloid
3    3.04817e-06            TRUE    Myeloid
4    3.29284e-06            TRUE    Myeloid
5    3.29284e-06            TRUE    Myeloid
6    3.29284e-06            TRUE    Myeloid
7    3.29284e-06            TRUE    Myeloid
8    3.29284e-06            TRUE    Myeloid
9    3.05865e-06            TRUE    Myeloid
10   1.04769e-05            TRUE    Myeloid
11   1.04769e-05            TRUE    Myeloid
12   1.04769e-05            TRUE    Myeloid
13   1.04769e-05            TRUE    Myeloid
14   1.04769e-05            TRUE    Myeloid
15   1.04769e-05            TRUE    Myeloid
16   1.04769e-05            TRUE    Myeloid
17   1.04769e-05            TRUE    Myeloid
18   1.04769e-05            TRUE    Myeloid
19   1.04769e-05            TRUE    Myeloid
20   1.04769e-05            TRUE    Myeloid
21   1.04769e-05            TRUE    Myeloid
22   1.04769e-05            TRUE    Myeloid
23   1.04769e-05            TRUE    Myeloid
24   1.04769e-05            TRUE    Myeloid
25   1.04769e-05            TRUE    Myeloid
26   1.04769e-05            TRUE    Myeloid
27   7.30254e-06            TRUE    Myeloid
28   7.30254e-06            TRUE    Myeloid
29   7.30254e-06            TRUE    Myeloid
30   7.30254e-06            TRUE    Myeloid
⋮    ⋮                      ⋮       ⋮
1231 8.36159e-07            TRUE    Cholangiocyte
1232 8.36159e-07            TRUE    Cholangiocyte
1233 1.63162e-07            TRUE    B
1234 1.63162e-07            TRUE    B
1235 1.63162e-07            TRUE    B
1236 1.63162e-07            TRUE    B
1237 1.63162e-07            TRUE    B
1238 1.63162e-07            TRUE    B
1239 1.63162e-07            TRUE    B
1240 1.63162e-07            TRUE    B
1241 1.63162e-07            TRUE    B
1242 1.63162e-07            TRUE    B
1243 1.63162e-07            TRUE    B
1244 1.63162e-07            TRUE    B
1245 1.63162e-07            TRUE    B
1246 2.36873e-07            TRUE    B
1247 2.36873e-07            TRUE    B
1248 2.36873e-07            TRUE    B
1249 2.36873e-07            TRUE    B
1250 2.36873e-07            TRUE    B
1251 2.36873e-07            TRUE    B
1252 2.36873e-07            TRUE    B
1253 2.36873e-07            TRUE    B
1254 2.36873e-07            TRUE    B
1255 2.36873e-07            TRUE    B
1256 2.36873e-07            TRUE    B
1257 2.36873e-07            TRUE    B
1258 2.36873e-07            TRUE    B
1259 2.36873e-07            TRUE    B
1260 2.36873e-07            TRUE    B

In [52]:
cred.set.coloc <- cred.set

for(cell.type in unique(atac.qtl.coloc.vars.res$cell)) {
    cred.set.coloc[[paste0('ATAC.QTL.Intersect.',cell.type)]] <- FALSE
    cred.set.coloc[cred.set.coloc$CS.SNP %in% filter(atac.qtl.coloc.vars.res, cell==cell.type)$variant_id,][[paste0('ATAC.QTL.Intersect.',cell.type)]] <- TRUE
}

for(cell.type in unique(rna.qtl.coloc.vars.res$cell)) {
    cred.set.coloc[[paste0('RNA.QTL.Intersect.',cell.type)]] <- FALSE
    cred.set.coloc[cred.set.coloc$CS.SNP %in% filter(rna.qtl.coloc.vars.res, cell==cell.type)$variant_id,][[paste0('RNA.QTL.Intersect.',cell.type)]] <- TRUE
}

for(cell.type in unique(H3K27ac.qtl.coloc.vars.res$cell)) {
    cred.set.coloc[[paste0('H3K27ac.QTL.Intersect.',cell.type)]] <- FALSE
    cred.set.coloc[cred.set.coloc$CS.SNP %in% filter(H3K27ac.qtl.coloc.vars.res, cell==cell.type)$variant_id,][[paste0('H3K27ac.QTL.Intersect.',cell.type)]] <- TRUE
}

for(cell.type in unique(H3K27me3.qtl.coloc.vars.res$cell)) {
    cred.set.coloc[[paste0('H3K27me3.QTL.Intersect.',cell.type)]] <- FALSE
    cred.set.coloc[cred.set.coloc$CS.SNP %in% filter(H3K27me3.qtl.coloc.vars.res, cell==cell.type)$variant_id,][[paste0('H3K27me3.QTL.Intersect.',cell.type)]] <- TRUE
}

#cred.set.coloc

select(cred.set.coloc,LEAD.SNP, contains('QTL.Intersect')) %>%
    group_by(LEAD.SNP) %>%
    summarise_all(any) %>%
    select(-LEAD.SNP) %>%
    summarise_all(sum)

  ATAC.QTL.Intersect.Myeloid ATAC.QTL.Intersect.HSC
1 8                          2
  ATAC.QTL.Intersect.Hepatocytes ATAC.QTL.Intersect.Endothelial
1 26                             7
  ATAC.QTL.Intersect.Cholangiocyte ATAC.QTL.Intersect.B
1 2                                1
  RNA.QTL.Intersect.Myeloid RNA.QTL.Intersect.Hepatocytes
1 2                         6
  RNA.QTL.Intersect.Endothelial H3K27ac.QTL.Intersect.Myeloid
1 1                             1
  H3K27ac.QTL.Intersect.Hepatocytes H3K27ac.QTL.Intersect.Endothelial
1 6                                 2
  H3K27me3.QTL.Intersect.Hepatocytes
1 2

# Start by joining summary stats and credible sets

In [35]:
head(cred.set)

  CS.Type    LEAD.SNP    CS.SNP      Chr Position  EA NEA EAF   Beta   SE     ⋯
1 Single SNP rs2642438   rs2642438   1   220970028 A  G   0.274 -0.075 0.0074 ⋯
2            rs6734238   rs6734238   2   113841030 G  A   0.407 -0.057 0.0064 ⋯
3            rs138033684 rs138033684 6    71895252 G  T   0.006  0.677 0.1120 ⋯
4            rs2980888   rs2980888   8   126507308 T  C   0.286  0.130 0.0072 ⋯
5            rs4484649   rs4484649   8    10571491 C  A   0.419  0.045 0.0066 ⋯
6            rs4841132   rs4841132   8     9183596 A  G   0.106  0.123 0.0105 ⋯
  ATAC.QTL.Coloc.Endothelial ATAC.QTL.Coloc.Cholangiocyte ATAC.QTL.Coloc.B
1 FALSE                      FALSE                        FALSE
2 FALSE                      FALSE                        FALSE
3 FALSE                      FALSE                        FALSE
4 FALSE                      FALSE                        FALSE
5 FALSE                      FALSE                        FALSE
6 FALSE                      FALSE                        FALSE
  RNA.QTL.Coloc.Myeloid RNA.QTL.Coloc.Hepatocytes RNA.QTL.Coloc.Endothelial
1 FALSE                 FALSE                     FALSE
2 FALSE                 FALSE                     FALSE
3 FALSE                 FALSE                     FALSE
4 FALSE                 FALSE                     FALSE
5 FALSE                 FALSE                     FALSE
6 FALSE                  TRUE                     FALSE
  H3K27ac.QTL.Coloc.Myeloid H3K27ac.QTL.Coloc.Hepatocytes
1 FALSE                     FALSE
2 FALSE                     FALSE
3 FALSE                     FALSE
4 FALSE                     FALSE
5 FALSE                     FALSE
6 FALSE                     FALSE
  H3K27ac.QTL.Coloc.Endothelial H3K27me3.QTL.Coloc.Hepatocytes
1 FALSE                         FALSE
2 FALSE                         FALSE
3 FALSE                         FALSE
4 FALSE                         FALSE
5 FALSE                         FALSE
6 FALSE                         FALSE

In [46]:
head(atac.qtl.coloc.vars.res)

  phenotype_id          variant_id start_distance end_distance af
1 chr19-4327352-4327620 rs35013670  9675           9408        0.3779070
2 chr19-4327352-4327620 rs28654688 12821          12554        0.4418605
3 chr19-4327352-4327620 rs3810367  15497          15230        0.4476744
4 chr19-4327651-4327951 rs35013670  9376           9077        0.3779070
5 chr19-4327651-4327951 rs28654688 12522          12223        0.4418605
6 chr19-4327651-4327951 rs12978346 13093          12794        0.3023256
  ma_samples ma_count pval_nominal slope     slope_se  pval_nominal_threshold
1 56         65       5.542695e-07 0.8183219 0.1437315 3.04817e-06
2 65         76       1.947807e-06 0.7966865 0.1490473 3.04817e-06
3 66         77       2.106467e-06 0.7794851 0.1464282 3.04817e-06
4 56         65       2.155003e-06 0.8106108 0.1524574 3.29284e-06
5 65         76       8.085321e-07 0.8481727 0.1517498 3.29284e-06
6 45         52       1.143572e-06 0.7831656 0.1425668 3.29284e-06
  sig.qtl cell
1 TRUE    Myeloid
2 TRUE    Myeloid
3 TRUE    Myeloid
4 TRUE    Myeloid
5 TRUE    Myeloid
6 TRUE    Myeloid

In [49]:
inner_join(cred.set, atac.qtl.coloc.vars.res, join_by(CS.SNP==variant_id)) %>%
    select(LEAD.SNP, cell) %>% distinct() %>% group_by(cell) %>% summarise(count=n())

  cell          count
1 B              1
2 Cholangiocyte  2
3 Endothelial    7
4 HSC            2
5 Hepatocytes   26
6 Myeloid        8

In [ ]:
# That worked okay for caQTLs, let's merge all QTL sumamry stats

In [53]:
caQTL.cred.set.overlap.full <- filter(atac.qtl.coloc.vars.res, variant_id %in% cred.set$CS.SNP) %>%
    select(caQTL.Peak=phenotype_id, variant_id, qtl.cell=cell, qtp.pval_nominal=pval_nominal, sig.qtl, qtl.slope=slope, qtl.slope_se=slope_se) %>%
    distinct() %>%
    filter(!is.na(variant_id)) %>%
    left_join(select(cred.set, -Chr, -Position, -Nominated.Gene, -Biological.Prior.Gene, start.hg38, pos.hg38=end.hg38), by=join_by('variant_id'=='CS.SNP'))
   

length(unique(caQTL.cred.set.overlap.full$LEAD.SNP))
caQTL.cred.set.overlap.full

[1] 31

     caQTL.Peak                variant_id qtl.cell      qtp.pval_nominal
1    chr19-4327352-4327620     rs35013670 Myeloid       5.542695e-07
2    chr19-4327352-4327620     rs28654688 Myeloid       1.947807e-06
3    chr19-4327352-4327620     rs3810367  Myeloid       2.106467e-06
4    chr19-4327651-4327951     rs35013670 Myeloid       2.155003e-06
5    chr19-4327651-4327951     rs28654688 Myeloid       8.085321e-07
6    chr19-4327651-4327951     rs12978346 Myeloid       1.143572e-06
7    chr19-4327651-4327951     rs3810368  Myeloid       1.676921e-06
8    chr19-4327651-4327951     rs3810367  Myeloid       1.988750e-06
9    chr19-4328187-4328487     rs12978346 Myeloid       2.433819e-06
10   chr17-63834872-63835172   rs57553639 Myeloid       6.351207e-06
11   chr17-63834872-63835172   rs58131426 Myeloid       6.351207e-06
12   chr17-63834872-63835172   rs2584641  Myeloid       6.351207e-06
13   chr17-63834872-63835172   rs2665840  Myeloid       6.351207e-06
14   chr17-63834872-63835172   rs2727332  Myeloid       6.351207e-06
15   chr17-63834872-63835172   rs2584632  Myeloid       6.351207e-06
16   chr17-63834872-63835172   rs2584630  Myeloid       6.351207e-06
17   chr17-63834872-63835172   rs2727292  Myeloid       6.351207e-06
18   chr17-63834872-63835172   rs2665835  Myeloid       6.351207e-06
19   chr17-63834872-63835172   rs2584623  Myeloid       6.351207e-06
20   chr17-63834872-63835172   rs13030    Myeloid       6.351207e-06
21   chr17-63834872-63835172   rs2584620  Myeloid       6.351207e-06
22   chr17-63834872-63835172   rs2665799  Myeloid       6.351207e-06
23   chr17-63834872-63835172   rs2727329  Myeloid       6.351207e-06
24   chr17-63834872-63835172   rs2584614  Myeloid       6.351207e-06
25   chr17-63834872-63835172   rs2584613  Myeloid       6.351207e-06
26   chr17-63834872-63835172   rs35448669 Myeloid       6.351207e-06
27   chr12-121167241-121167541 rs2857590  Myeloid       2.883939e-06
28   chr12-121167241-121167541 rs1718131  Myeloid       2.883939e-06
29   chr12-121167241-121167541 rs1653610  Myeloid       2.883939e-06
30   chr12-121167241-121167541 rs1618709  Myeloid       2.883939e-06
⋮    ⋮                         ⋮          ⋮             ⋮
1231 chr8-8228311-8228611      rs2409092  Cholangiocyte 5.350162e-10
1232 chr8-8228311-8228611      rs1533058  Cholangiocyte 5.350162e-10
1233 chr8-8227864-8228164      rs2979172  B             1.274845e-09
1234 chr8-8227864-8228164      rs4841040  B             5.265978e-10
1235 chr8-8227864-8228164      rs6994038  B             1.878108e-10
1236 chr8-8227864-8228164      rs4841042  B             8.880569e-10
1237 chr8-8227864-8228164      rs7823757  B             3.984267e-10
1238 chr8-8227864-8228164      rs60315134 B             3.984267e-10
1239 chr8-8227864-8228164      rs11784052 B             6.163621e-10
1240 chr8-8227864-8228164      rs4841045  B             6.163621e-10
1241 chr8-8227864-8228164      rs13259216 B             9.317418e-10
1242 chr8-8227864-8228164      rs882462   B             1.368078e-09
1243 chr8-8227864-8228164      rs57312668 B             1.486142e-07
1244 chr8-8227864-8228164      rs2409092  B             1.486142e-07
1245 chr8-8227864-8228164      rs1533058  B             1.486142e-07
1246 chr8-8228311-8228611      rs2979172  B             4.638804e-09
1247 chr8-8228311-8228611      rs4841040  B             1.144367e-11
1248 chr8-8228311-8228611      rs6994038  B             1.013459e-11
1249 chr8-8228311-8228611      rs4841042  B             3.019296e-11
1250 chr8-8228311-8228611      rs7823757  B             7.917561e-12
1251 chr8-8228311-8228611      rs60315134 B             7.917561e-12
1252 chr8-8228311-8228611      rs11784052 B             7.943987e-12
1253 chr8-8228311-8228611      rs4841045  B             7.943987e-12
1254 chr8-8228311-8228611      rs13259216 B             4.676211e-12
1255 chr8-8228311-8228611      rs882462   B             3.652882e-11
1256 chr8-8228311-8228611      rs11775523 B             7.152499e-09
1257 chr8-8228311-8228611      rs1039915  B             3.412433e-09
1258 chr8-8228311-8228611      rs57312668 B             2.502791e-09
1259 chr8-8228311-8228611      rs2409092  B             2.502791e-09
1260 chr8-8228311-8228611      rs1533058  B             2.502791e-09
     sig.qtl qtl.slope  qtl.slope_se CS.Type LEAD.SNP   EA NEA EAF   Beta
1    TRUE     0.8183219 0.1437315            rs3810367  C  T   0.353 0.031
2    TRUE     0.7966865 0.1490473            rs3810367  G  A   0.370 0.036
3    TRUE     0.7794851 0.1464282            rs3810367  G  T   0.374 0.037
4    TRUE     0.8106108 0.1524574            rs3810367  C  T   0.353 0.031
5    TRUE     0.8481727 0.1517498            rs3810367  G  A   0.370 0.036
6    TRUE     0.7831656 0.1425668            rs3810367  A  C   0.283 0.034
7    TRUE     0.7826868 0.1452934            rs3810367  A  G   0.283 0.034
8    TRUE     0.8080804 0.1513433            rs3810367  G  T   0.374 0.037
9    TRUE     0.5466126 0.1034675            rs3810367  A  C   0.283 0.034
10   TRUE    -0.6809292 0.1358419            rs2727324  T  C   0.315 0.038
11   TRUE    -0.6809292 0.1358419            rs2727324  C  T   0.316 0.038
12   TRUE    -0.6809292 0.1358419            rs2727324  G  A   0.317 0.037
13   TRUE    -0.6809292 0.1358419            rs2727324  G  A   0.318 0.036
14   TRUE    -0.6809292 0.1358419            rs2727324  A  T   0.318 0.036
15   TRUE    -0.6809292 0.1358419            rs2727324  A  G   0.317 0.037
16   TRUE    -0.6809292 0.1358419            rs2727324  A  T   0.313 0.038
17   TRUE    -0.6809292 0.1358419            rs2727324  G  A   0.313 0.038
18   TRUE    -0.6809292 0.1358419            rs2727324  T  C   0.312 0.038
19   TRUE    -0.6809292 0.1358419            rs2727324  A  G   0.312 0.038
20   TRUE    -0.6809292 0.1358419            rs2727324  T  C   0.312 0.038
21   TRUE    -0.6809292 0.1358419            rs2727324  A  G   0.311 0.038
22   TRUE    -0.6809292 0.1358419            rs2727324  G  A   0.311 0.038
23   TRUE    -0.6809292 0.1358419            rs2727324  T  C   0.309 0.038
24   TRUE    -0.6809292 0.1358419            rs2727324  T  C   0.309 0.038
25   TRUE    -0.6809292 0.1358419            rs2727324  G  C   0.309 0.038
26   TRUE    -0.6809292 0.1358419            rs2727324  A  G   0.309 0.038
27   TRUE     0.6597506 0.1260173            rs1626329  A  C   0.396 0.048
28   TRUE     0.6597506 0.1260173            rs1626329  A  G   0.396 0.048
29   TRUE     0.6597506 0.1260173            rs1626329  A  G   0.396 0.048
30   TRUE     0.6597506 0.1260173            rs1626329  T  C   0.396 0.048
⋮    ⋮       ⋮          ⋮            ⋮       ⋮          ⋮  ⋮   ⋮     ⋮
1231 TRUE    -1.0119930 0.1335846            rs60315134 T  A   0.453 0.035
1232 TRUE    -1.0119930 0.1335846            rs60315134 G  A   0.456 0.035
1233 TRUE    -0.9176182 0.1249991            rs60315134 C  G   0.487 0.034
1234 TRUE    -0.9771583 0.1289133            rs60315134 C  T   0.452 0.034
1235 TRUE    -0.9978528 0.1269644            rs60315134 A  C   0.450 0.034
1236 TRUE    -0.9238093 0.1241902            rs60315134 A  G   0.461 0.034
1237 TRUE    -0.9787574 0.1278511            rs60315134 A  T   0.456 0.035
1238 TRUE    -0.9787574 0.1278511            rs60315134 G  A   0.457 0.036
1239 TRUE    -0.9622616 0.1276651            rs60315134 T  C   0.456 0.036
1240 TRUE    -0.9622616 0.1276651            rs60315134 G  A   0.456 0.036
1241 TRUE    -0.9333239 0.1256885            rs60315134 C  A   0.459 0.035
1242 TRUE    -0.9456959 0.1291592            rs60315134 A  G   0.453 0.035
1243 TRUE    -0.8693023 0.1435949            rs60315134 A  G   0.455 0.035
1244 TRUE    -0.8693023 0.1435949            rs60315134 T  A   0.453 0.035
1245 TRUE    -0.8693023 0.1435949            rs60315134 G  A   0.456 0.035
1246 TRUE    -0.8702576 0.1244574            rs60315134 C  G   0.487 0.034
1247 TRUE    -1.0064007 0.1167038            rs60315134 C  T   0.452 0.034
1248 TRUE    -1.0119766 0.1168971            rs60315134 A  C   0.450 0.034
1249 TRUE    -0.9474948 0.1133730            rs60315134 A  G   0.461 0.034
1250 TRUE    -1.0081533 0.1155473            rs60315134 A  T   0.456 0.035
1251 TRUE    -1.0081533 0.1155473            rs60315134 G  A   0.457 0.036
1252 TRUE    -0.9985215 0.1144554            rs60315134 T  C   0.456 0.036
1253 TRUE    -0.9985215 0.1144554            rs60315134 G  A   0.456 0.036
1254 TRUE    -0.9821742 0.1107233            rs60315134 C  A   0.459 0.035
1255 TRUE    -0.9748945 0.1173833            rs60315134 A  G   0.453 0.035
1256 TRUE    -0.8796076 0.1279322            rs60315134 G  A   0.455 0.036
1257 TRUE    -0.9060807 0.1280634            rs60315134 C  T   0.455 0.035
1258 TRUE    -0.9267010 0.1294473            rs60315134 A  G   0.455 0.035
1259 TRUE    -0.9267010 0.1294473            rs60315134 T  A   0.453 0.035
1260 TRUE    -0.9267010 0.1294473            rs60315134 G  A   0.456 0.035
     SE     P        N      PP     chr.hg38 pos.hg38  start.hg38
1    0.0066 3.15e-06 218595 0.51%  19         4337028   4337027
2    0.0067 4.74e-08 218595 21.09% 19         4340174   4340173
3    0.0066 3.77e-08 218595 38.43% 19         4342850   4342849
4    0.0066 3.15e-06 218595 0.51%  19         4337028   4337027
5    0.0067 4.74e-08 218595 21.09% 19         4340174   4340173
6    0.0072 3.25e-06 218595 0.55%  19         4340745   4340744
7    0.0073 3.16e-06 218595 0.53%  19         4342733   4342732
8    0.0066 3.77e-08 218595 38.43% 19         4342850   4342849
9    0.0072 3.25e-06 218595 0.55%  19         4340745   4340744
10   0.0072 1.71e-07 218595 1.27%  17        63771139  63771138
11   0.0071 1.61e-07 218595 1.38%  17        63777015  63777014
12   0.0070 1.26e-07 218595 1.29%  17        63785529  63785528
13   0.0068 1.49e-07 218595 1.12%  17        63795947  63795946
14   0.0068 1.17e-07 218595 1.52%  17        63801224  63801223
15   0.0068 7.94e-08 218595 2.26%  17        63803281  63803280
16   0.0069 5.05e-08 218595 3.04%  17        63810201  63810200
17   0.0069 4.66e-08 218595 3.29%  17        63816387  63816386
18   0.0069 3.79e-08 218595 3.85%  17        63825898  63825897
19   0.0069 3.67e-08 218595 4.17%  17        63829319  63829318
20   0.0068 2.51e-08 218595 6.97%  17        63831196  63831195
21   0.0069 3.77e-08 218595 4.17%  17        63835832  63835831
22   0.0069 3.96e-08 218595 3.85%  17        63842363  63842362
23   0.0069 4.59e-08 218595 3.29%  17        63847206  63847205
24   0.0069 3.67e-08 218595 4.17%  17        63852085  63852084
25   0.0069 3.43e-08 218595 4.51%  17        63854173  63854172
26   0.0070 5.11e-08 218595 2.98%  17        63861563  63861562
27   0.0066 1.81e-13 218595 1.08%  12       121168256 121168255
28   0.0066 2.01e-13 218595 1.08%  12       121168516 121168515
29   0.0066 1.76e-13 218595 1.20%  12       121168602 121168601
30   0.0066 1.52e-13 218595 1.35%  12       121169114 121169113
⋮    ⋮      ⋮        ⋮      ⋮      ⋮        ⋮         ⋮
1231 0.0067 2.39e-07 218595 0.31%  8        8824682   8824681
1232 0.0067 1.25e-07 218595 0.54%  8        8827680   8827679
1233 0.0065 2.41e-07 218595 0.29%  8        8452998   8452997
1234 0.0066 3.76e-07 218595 0.20%  8        8797017   8797016
1235 0.0065 2.63e-07 218595 0.29%  8        8803028   8803027
1236 0.0065 1.41e-07 218595 0.47%  8        8807112   8807111
1237 0.0066 6.40e-08 218595 0.81%  8        8812667   8812666
1238 0.0065 2.88e-08 218595 2.68%  8        8813089   8813088
1239 0.0066 5.92e-08 218595 0.96%  8        8814452   8814451
1240 0.0066 3.82e-08 218595 1.33%  8        8815069   8815068
1241 0.0065 1.20e-07 218595 0.59%  8        8816091   8816090
1242 0.0066 9.18e-08 218595 0.75%  8        8821020   8821019
1243 0.0066 1.16e-07 218595 0.64%  8        8822967   8822966
1244 0.0067 2.39e-07 218595 0.31%  8        8824682   8824681
1245 0.0067 1.25e-07 218595 0.54%  8        8827680   8827679
1246 0.0065 2.41e-07 218595 0.29%  8        8452998   8452997
1247 0.0066 3.76e-07 218595 0.20%  8        8797017   8797016
1248 0.0065 2.63e-07 218595 0.29%  8        8803028   8803027
1249 0.0065 1.41e-07 218595 0.47%  8        8807112   8807111
1250 0.0066 6.40e-08 218595 0.81%  8        8812667   8812666
1251 0.0065 2.88e-08 218595 2.68%  8        8813089   8813088
1252 0.0066 5.92e-08 218595 0.96%  8        8814452   8814451
1253 0.0066 3.82e-08 218595 1.33%  8        8815069   8815068
1254 0.0065 1.20e-07 218595 0.59%  8        8816091   8816090
1255 0.0066 9.18e-08 218595 0.75%  8        8821020   8821019
1256 0.0066 5.61e-08 218595 1.13%  8        8821666   8821665
1257 0.0066 1.27e-07 218595 0.54%  8        8822104   8822103
1258 0.0066 1.16e-07 218595 0.64%  8        8822967   8822966
1259 0.0067 2.39e-07 218595 0.31%  8        8824682   8824681
1260 0.0067 1.25e-07 218595 0.54%  8        8827680   8827679

In [57]:
head(rna.qtl.coloc.vars.res)
head(atac.qtl.coloc.vars.res)
head(H3K27ac.qtl.coloc.vars.res)
head(H3K27me3.qtl.coloc.vars.res)

  phenotype_id variant_id start_distance af        ma_samples ma_count
1 HSD17B13     rs10433879  -12898        0.2034884 30         35
2 HLA-DQB1     rs968155   -255445        0.6453488 48         61
3 HLA-DQB1     rs9271406   -48572        0.5930232 54         70
4 EPHA2        rs11588341   15484        0.5232558 61         82
5 EPHA2        rs1497407    17041        0.4883721 60         84
6 EPHA2        rs7519043    17959        0.5174419 62         83
  pval_nominal slope      slope_se   sig.qtl pval_nominal_threshold cell
1 4.227959e-06  0.7136446 0.13917176 TRUE    1.03562e-05            Myeloid
2 8.382722e-06 -0.5900655 0.11959907 TRUE    1.02602e-05            Myeloid
3 8.116191e-08 -0.6510572 0.10469777 TRUE    1.02602e-05            Myeloid
4 9.513265e-06 -0.3773269 0.07704365 TRUE    2.53574e-05            Hepatocytes
5 8.349330e-06 -0.3804022 0.07708509 TRUE    2.53574e-05            Hepatocytes
6 6.773970e-06 -0.3836847 0.07682361 TRUE    2.53574e-05            Hepatocytes

  phenotype_id          variant_id start_distance end_distance af
1 chr19-4327352-4327620 rs35013670  9675           9408        0.3779070
2 chr19-4327352-4327620 rs28654688 12821          12554        0.4418605
3 chr19-4327352-4327620 rs3810367  15497          15230        0.4476744
4 chr19-4327651-4327951 rs35013670  9376           9077        0.3779070
5 chr19-4327651-4327951 rs28654688 12522          12223        0.4418605
6 chr19-4327651-4327951 rs12978346 13093          12794        0.3023256
  ma_samples ma_count pval_nominal slope     slope_se  pval_nominal_threshold
1 56         65       5.542695e-07 0.8183219 0.1437315 3.04817e-06
2 65         76       1.947807e-06 0.7966865 0.1490473 3.04817e-06
3 66         77       2.106467e-06 0.7794851 0.1464282 3.04817e-06
4 56         65       2.155003e-06 0.8106108 0.1524574 3.29284e-06
5 65         76       8.085321e-07 0.8481727 0.1517498 3.29284e-06
6 45         52       1.143572e-06 0.7831656 0.1425668 3.29284e-06
  sig.qtl cell
1 TRUE    Myeloid
2 TRUE    Myeloid
3 TRUE    Myeloid
4 TRUE    Myeloid
5 TRUE    Myeloid
6 TRUE    Myeloid

  phenotype_id         variant_id start_distance end_distance af
1 chr8:8227666-8228665 rs2979172  225331         224333       0.6395349
2 chr8:8227666-8228665 rs4841040  569350         568352       0.5872093
3 chr8:8227666-8228665 rs6994038  575361         574363       0.5872093
4 chr8:8227666-8228665 rs4841042  579445         578447       0.5930232
5 chr8:8227666-8228665 rs7823757  585000         584002       0.5813953
6 chr8:8227666-8228665 rs60315134 585422         584424       0.5813953
  ma_samples ma_count pval_nominal slope      slope_se  sig.qtl
1 47         62       1.630880e-09 -0.9632696 0.1324173 TRUE
2 56         71       5.232810e-09 -0.9810939 0.1409638 TRUE
3 56         71       2.781884e-08 -0.9362662 0.1438492 TRUE
4 54         70       5.722191e-09 -0.9160417 0.1320748 TRUE
5 56         72       6.893619e-09 -0.9762346 0.1417808 TRUE
6 56         72       6.893619e-09 -0.9762346 0.1417808 TRUE
  pval_nominal_threshold cell
1 1.09088e-07            Myeloid
2 1.09088e-07            Myeloid
3 1.09088e-07            Myeloid
4 1.09088e-07            Myeloid
5 1.09088e-07            Myeloid
6 1.09088e-07            Myeloid

  phenotype_id           variant_id start_distance end_distance af
1 chr6:32550868-32552367 rs9268839  -89874         -91372       0.5174419
2 chr6:32550868-32552367 rs13211921 -75810         -77308       0.5174419
3 chr6:32550868-32552367 rs9391879  -75474         -76972       0.5174419
4 chr6:32550868-32552367 rs12195589 -74062         -75560       0.5174419
5 chr6:32550868-32552367 rs28895253 -73736         -75234       0.5174419
6 chr6:32550868-32552367 rs28895257 -73532         -75030       0.5174419
  ma_samples ma_count pval_nominal slope     slope_se  sig.qtl
1 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
2 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
3 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
4 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
5 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
6 64         83       1.36998e-07  0.7758834 0.1276958 TRUE
  pval_nominal_threshold cell
1 4.81518e-07            Hepatocytes
2 4.81518e-07            Hepatocytes
3 4.81518e-07            Hepatocytes
4 4.81518e-07            Hepatocytes
5 4.81518e-07            Hepatocytes
6 4.81518e-07            Hepatocytes

In [68]:
# Fix columns to match
rna.qtl.coloc.vars.res.mod <- rna.qtl.coloc.vars.res %>% mutate(modality='RNA')
atac.qtl.coloc.vars.res.mod <- select(atac.qtl.coloc.vars.res, -end_distance) %>%
    relocate(pval_nominal_threshold, .after = sig.qtl) %>% mutate(modality='ATAC')
H3K27ac.qtl.coloc.vars.res.mod <- select(H3K27ac.qtl.coloc.vars.res, -end_distance) %>% mutate(modality='H3K27ac')
H3K27me3.qtl.coloc.vars.res.mod <- select(H3K27me3.qtl.coloc.vars.res, -end_distance) %>% mutate(modality='H3K27me3')

In [69]:
head(rna.qtl.coloc.vars.res.mod)
head(atac.qtl.coloc.vars.res.mod)
head(H3K27ac.qtl.coloc.vars.res.mod)
head(H3K27me3.qtl.coloc.vars.res.mod)

  phenotype_id variant_id start_distance af        ma_samples ma_count
1 HSD17B13     rs10433879  -12898        0.2034884 30         35
2 HLA-DQB1     rs968155   -255445        0.6453488 48         61
3 HLA-DQB1     rs9271406   -48572        0.5930232 54         70
4 EPHA2        rs11588341   15484        0.5232558 61         82
5 EPHA2        rs1497407    17041        0.4883721 60         84
6 EPHA2        rs7519043    17959        0.5174419 62         83
  pval_nominal slope      slope_se   sig.qtl pval_nominal_threshold cell
1 4.227959e-06  0.7136446 0.13917176 TRUE    1.03562e-05            Myeloid
2 8.382722e-06 -0.5900655 0.11959907 TRUE    1.02602e-05            Myeloid
3 8.116191e-08 -0.6510572 0.10469777 TRUE    1.02602e-05            Myeloid
4 9.513265e-06 -0.3773269 0.07704365 TRUE    2.53574e-05            Hepatocytes
5 8.349330e-06 -0.3804022 0.07708509 TRUE    2.53574e-05            Hepatocytes
6 6.773970e-06 -0.3836847 0.07682361 TRUE    2.53574e-05            Hepatocytes
  modality
1 RNA
2 RNA
3 RNA
4 RNA
5 RNA
6 RNA

  phenotype_id          variant_id start_distance af        ma_samples ma_count
1 chr19-4327352-4327620 rs35013670  9675          0.3779070 56         65
2 chr19-4327352-4327620 rs28654688 12821          0.4418605 65         76
3 chr19-4327352-4327620 rs3810367  15497          0.4476744 66         77
4 chr19-4327651-4327951 rs35013670  9376          0.3779070 56         65
5 chr19-4327651-4327951 rs28654688 12522          0.4418605 65         76
6 chr19-4327651-4327951 rs12978346 13093          0.3023256 45         52
  pval_nominal slope     slope_se  sig.qtl pval_nominal_threshold cell
1 5.542695e-07 0.8183219 0.1437315 TRUE    3.04817e-06            Myeloid
2 1.947807e-06 0.7966865 0.1490473 TRUE    3.04817e-06            Myeloid
3 2.106467e-06 0.7794851 0.1464282 TRUE    3.04817e-06            Myeloid
4 2.155003e-06 0.8106108 0.1524574 TRUE    3.29284e-06            Myeloid
5 8.085321e-07 0.8481727 0.1517498 TRUE    3.29284e-06            Myeloid
6 1.143572e-06 0.7831656 0.1425668 TRUE    3.29284e-06            Myeloid
  modality
1 ATAC
2 ATAC
3 ATAC
4 ATAC
5 ATAC
6 ATAC

  phenotype_id         variant_id start_distance af        ma_samples ma_count
1 chr8:8227666-8228665 rs2979172  225331         0.6395349 47         62
2 chr8:8227666-8228665 rs4841040  569350         0.5872093 56         71
3 chr8:8227666-8228665 rs6994038  575361         0.5872093 56         71
4 chr8:8227666-8228665 rs4841042  579445         0.5930232 54         70
5 chr8:8227666-8228665 rs7823757  585000         0.5813953 56         72
6 chr8:8227666-8228665 rs60315134 585422         0.5813953 56         72
  pval_nominal slope      slope_se  sig.qtl pval_nominal_threshold cell
1 1.630880e-09 -0.9632696 0.1324173 TRUE    1.09088e-07            Myeloid
2 5.232810e-09 -0.9810939 0.1409638 TRUE    1.09088e-07            Myeloid
3 2.781884e-08 -0.9362662 0.1438492 TRUE    1.09088e-07            Myeloid
4 5.722191e-09 -0.9160417 0.1320748 TRUE    1.09088e-07            Myeloid
5 6.893619e-09 -0.9762346 0.1417808 TRUE    1.09088e-07            Myeloid
6 6.893619e-09 -0.9762346 0.1417808 TRUE    1.09088e-07            Myeloid
  modality
1 H3K27ac
2 H3K27ac
3 H3K27ac
4 H3K27ac
5 H3K27ac
6 H3K27ac

  phenotype_id           variant_id start_distance af        ma_samples
1 chr6:32550868-32552367 rs9268839  -89874         0.5174419 64
2 chr6:32550868-32552367 rs13211921 -75810         0.5174419 64
3 chr6:32550868-32552367 rs9391879  -75474         0.5174419 64
4 chr6:32550868-32552367 rs12195589 -74062         0.5174419 64
5 chr6:32550868-32552367 rs28895253 -73736         0.5174419 64
6 chr6:32550868-32552367 rs28895257 -73532         0.5174419 64
  ma_count pval_nominal slope     slope_se  sig.qtl pval_nominal_threshold
1 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
2 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
3 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
4 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
5 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
6 83       1.36998e-07  0.7758834 0.1276958 TRUE    4.81518e-07
  cell        modality
1 Hepatocytes H3K27me3
2 Hepatocytes H3K27me3
3 Hepatocytes H3K27me3
4 Hepatocytes H3K27me3
5 Hepatocytes H3K27me3
6 Hepatocytes H3K27me3

In [70]:
# Do they match? If so bind them
sum(length(colnames(rna.qtl.coloc.vars.res.mod)) == length(colnames(atac.qtl.coloc.vars.res.mod)))
sum(length(colnames(rna.qtl.coloc.vars.res.mod)) == length(colnames(H3K27ac.qtl.coloc.vars.res.mod)))
sum(length(colnames(rna.qtl.coloc.vars.res.mod)) == length(colnames(H3K27me3.qtl.coloc.vars.res.mod)))

sum(colnames(rna.qtl.coloc.vars.res.mod) == colnames(atac.qtl.coloc.vars.res.mod))
sum(colnames(rna.qtl.coloc.vars.res.mod) == colnames(H3K27ac.qtl.coloc.vars.res.mod))
sum(colnames(rna.qtl.coloc.vars.res.mod) == colnames(H3K27me3.qtl.coloc.vars.res.mod))

[1] 1

[1] 1

[1] 1

[1] 13

[1] 13

[1] 13

In [71]:
qtl.cs.vars <- rbind(rna.qtl.coloc.vars.res.mod, atac.qtl.coloc.vars.res.mod) %>%
    rbind(H3K27ac.qtl.coloc.vars.res.mod) %>%
    rbind(H3K27me3.qtl.coloc.vars.res.mod)

dim(qtl.cs.vars)
head(qtl.cs.vars)

[1] 1427   13

  phenotype_id variant_id start_distance af        ma_samples ma_count
1 HSD17B13     rs10433879  -12898        0.2034884 30         35
2 HLA-DQB1     rs968155   -255445        0.6453488 48         61
3 HLA-DQB1     rs9271406   -48572        0.5930232 54         70
4 EPHA2        rs11588341   15484        0.5232558 61         82
5 EPHA2        rs1497407    17041        0.4883721 60         84
6 EPHA2        rs7519043    17959        0.5174419 62         83
  pval_nominal slope      slope_se   sig.qtl pval_nominal_threshold cell
1 4.227959e-06  0.7136446 0.13917176 TRUE    1.03562e-05            Myeloid
2 8.382722e-06 -0.5900655 0.11959907 TRUE    1.02602e-05            Myeloid
3 8.116191e-08 -0.6510572 0.10469777 TRUE    1.02602e-05            Myeloid
4 9.513265e-06 -0.3773269 0.07704365 TRUE    2.53574e-05            Hepatocytes
5 8.349330e-06 -0.3804022 0.07708509 TRUE    2.53574e-05            Hepatocytes
6 6.773970e-06 -0.3836847 0.07682361 TRUE    2.53574e-05            Hepatocytes
  modality
1 RNA
2 RNA
3 RNA
4 RNA
5 RNA
6 RNA

In [76]:
qtl.cred.set <- select(qtl.cs.vars, qtl.feature=phenotype_id, variant_id, qtl.cell=cell, qtp.pval_nominal=pval_nominal, sig.qtl, qtl.slope=slope, qtl.slope_se=slope_se, qtl.modality=modality) %>%
    distinct() %>%
    filter(!is.na(variant_id)) %>%
    left_join(select(cred.set, -Chr, -Position, -Nominated.Gene, -Biological.Prior.Gene, start.hg38, pos.hg38=end.hg38), by=join_by('variant_id'=='CS.SNP'))
   

length(unique(qtl.cred.set$LEAD.SNP))

select(qtl.cred.set, LEAD.SNP, qtl.cell, qtl.modality) %>% distinct() %>% group_by(qtl.cell,qtl.modality) %>% summarise(count=n())
select(qtl.cred.set, LEAD.SNP, qtl.cell) %>% distinct() %>% group_by(qtl.cell) %>% summarise(count=n())

qtl.cred.set

[1] 33

`summarise()` has grouped output by 'qtl.cell'. You can override using the `.groups` argument.

   qtl.cell      qtl.modality count
1  B             ATAC          1
2  Cholangiocyte ATAC          2
3  Endothelial   ATAC          7
4  Endothelial   H3K27ac       2
5  Endothelial   RNA           1
6  HSC           ATAC          2
7  Hepatocytes   ATAC         26
8  Hepatocytes   H3K27ac       6
9  Hepatocytes   H3K27me3      2
10 Hepatocytes   RNA           6
11 Myeloid       ATAC          8
12 Myeloid       H3K27ac       1
13 Myeloid       RNA           2

  qtl.cell      count
1 B              1
2 Cholangiocyte  2
3 Endothelial    7
4 HSC            2
5 Hepatocytes   28
6 Myeloid        9

     qtl.feature              variant_id qtl.cell    qtp.pval_nominal sig.qtl
1    HSD17B13                 rs10433879 Myeloid     4.227959e-06     TRUE
2    HLA-DQB1                 rs968155   Myeloid     8.382722e-06     TRUE
3    HLA-DQB1                 rs9271406  Myeloid     8.116191e-08     TRUE
4    EPHA2                    rs11588341 Hepatocytes 9.513265e-06     TRUE
5    EPHA2                    rs1497407  Hepatocytes 8.349330e-06     TRUE
6    EPHA2                    rs7519043  Hepatocytes 6.773970e-06     TRUE
7    EPHA2                    rs7538833  Hepatocytes 1.494710e-06     TRUE
8    EPHA2                    rs1497406  Hepatocytes 1.063339e-05     TRUE
9    EPHA2                    rs4661718  Hepatocytes 3.125939e-06     TRUE
10   EPHA2                    rs6677710  Hepatocytes 1.494710e-06     TRUE
11   EPHA2                    rs12057175 Hepatocytes 1.494710e-06     TRUE
12   EPHA2                    rs4537547  Hepatocytes 1.494710e-06     TRUE
13   EPHA2                    rs36086195 Hepatocytes 1.306627e-05     TRUE
14   EFHD1                    rs7604422  Hepatocytes 2.466109e-12     TRUE
15   EFHD1                    rs11689178 Hepatocytes 7.546706e-12     TRUE
16   EFHD1                    rs11683367 Hepatocytes 1.700641e-13     TRUE
17   HSD17B13                 rs28679728 Hepatocytes 9.917196e-08     TRUE
18   HSD17B13                 rs28419230 Hepatocytes 9.917196e-08     TRUE
19   HSD17B13                 rs28528308 Hepatocytes 9.917196e-08     TRUE
20   HSD17B13                 rs13112784 Hepatocytes 9.917196e-08     TRUE
21   HSD17B13                 rs13117201 Hepatocytes 9.917196e-08     TRUE
22   HSD17B13                 rs4607179  Hepatocytes 9.917196e-08     TRUE
23   HSD17B13                 rs10003948 Hepatocytes 9.917196e-08     TRUE
24   HSD17B13                 rs13139418 Hepatocytes 9.917196e-08     TRUE
25   HSD17B13                 rs13102451 Hepatocytes 9.917196e-08     TRUE
26   HSD17B13                 rs28456144 Hepatocytes 9.917196e-08     TRUE
27   HSD17B13                 rs10433937 Hepatocytes 9.917196e-08     TRUE
28   HSD17B13                 rs10433879 Hepatocytes 4.735815e-08     TRUE
29   AC021736.1               rs4841132  Hepatocytes 2.033959e-06     TRUE
30   AC021242.2               rs4841132  Hepatocytes 1.102711e-07     TRUE
⋮    ⋮                        ⋮          ⋮           ⋮                ⋮
1398 chr9:133274696-133275695 rs514659   Endothelial 5.898807e-08     TRUE
1399 chr9:133274696-133275695 rs545971   Endothelial 5.898807e-08     TRUE
1400 chr9:133274696-133275695 rs597988   Endothelial 5.898807e-08     TRUE
1401 chr9:133274696-133275695 rs597974   Endothelial 5.898807e-08     TRUE
1402 chr9:133274696-133275695 rs576123   Endothelial 5.898807e-08     TRUE
1403 chr9:133274696-133275695 rs576125   Endothelial 5.898807e-08     TRUE
1404 chr9:133274696-133275695 rs491626   Endothelial 5.898807e-08     TRUE
1405 chr9:133274696-133275695 rs492488   Endothelial 5.898807e-08     TRUE
1406 chr9:133274696-133275695 rs495203   Endothelial 5.898807e-08     TRUE
1407 chr9:133274696-133275695 rs582094   Endothelial 5.898807e-08     TRUE
1408 chr9:133274696-133275695 rs2769071  Endothelial 5.898807e-08     TRUE
1409 chr9:133274696-133275695 rs677355   Endothelial 5.898807e-08     TRUE
1410 chr9:133274696-133275695 rs676457   Endothelial 5.898807e-08     TRUE
1411 chr9:133274696-133275695 rs527210   Endothelial 5.898807e-08     TRUE
1412 chr9:133274696-133275695 rs554833   Endothelial 5.898807e-08     TRUE
1413 chr9:133274696-133275695 rs505922   Endothelial 2.501666e-08     TRUE
1414 chr6:32550868-32552367   rs9268839  Hepatocytes 1.369980e-07     TRUE
1415 chr6:32550868-32552367   rs13211921 Hepatocytes 1.369980e-07     TRUE
1416 chr6:32550868-32552367   rs9391879  Hepatocytes 1.369980e-07     TRUE
1417 chr6:32550868-32552367   rs12195589 Hepatocytes 1.369980e-07     TRUE
1418 chr6:32550868-32552367   rs28895253 Hepatocytes 1.369980e-07     TRUE
1419 chr6:32550868-32552367   rs28895257 Hepatocytes 1.369980e-07     TRUE
1420 chr6:32550868-32552367   rs28895258 Hepatocytes 1.369980e-07     TRUE
1421 chr6:32550868-32552367   rs28895259 Hepatocytes 1.369980e-07     TRUE
1422 chr6:32550868-32552367   rs17203619 Hepatocytes 1.369980e-07     TRUE
1423 chr6:32550868-32552367   rs29001652 Hepatocytes 1.369980e-07     TRUE
1424 chr6:32550868-32552367   rs29001478 Hepatocytes 1.369980e-07     TRUE
1425 chr6:32550868-32552367   rs29001568 Hepatocytes 1.369980e-07     TRUE
1426 chr6:32550868-32552367   rs28732247 Hepatocytes 1.369980e-07     TRUE
1427 chr8:8227347-8228846     rs2979172  Hepatocytes 4.605818e-08     TRUE
     qtl.slope  qtl.slope_se qtl.modality CS.Type LEAD.SNP   ⋯ NEA EAF   Beta
1     0.7136446 0.13917176   RNA                  rs10433937 ⋯ G   0.255 -0.081
2    -0.5900655 0.11959907   RNA                  rs686250   ⋯ T   0.462 -0.036
3    -0.6510572 0.10469777   RNA                  rs686250   ⋯ A   0.454  0.034
4    -0.3773269 0.07704365   RNA                  rs36086195 ⋯ G   0.483 -0.039
5    -0.3804022 0.07708509   RNA                  rs36086195 ⋯ C   0.483 -0.042
6    -0.3836847 0.07682361   RNA                  rs36086195 ⋯ T   0.485 -0.039
7    -0.3871493 0.07144354   RNA                  rs36086195 ⋯ C   0.360 -0.039
8    -0.3844107 0.07900385   RNA                  rs36086195 ⋯ G   0.475 -0.039
9    -0.3672506 0.07045192   RNA                  rs36086195 ⋯ T   0.364 -0.039
10   -0.3871493 0.07144354   RNA                  rs36086195 ⋯ C   0.360 -0.040
11   -0.3871493 0.07144354   RNA                  rs36086195 ⋯ G   0.359 -0.039
12   -0.3871493 0.07144354   RNA                  rs36086195 ⋯ G   0.358 -0.039
13   -0.3810083 0.07926785   RNA                  rs36086195 ⋯ T   0.475 -0.043
14    0.8622920 0.09530172   RNA                  rs11683367 ⋯ A   0.408 -0.056
15    0.8831438 0.10106630   RNA                  rs11683367 ⋯ C   0.413 -0.055
16    0.9259033 0.09448564   RNA                  rs11683367 ⋯ T   0.402 -0.057
17    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.257 -0.080
18    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.256 -0.080
19    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.255 -0.079
20    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.256 -0.079
21    0.7722697 0.12528765   RNA                  rs10433937 ⋯ T   0.256 -0.079
22    0.7722697 0.12528765   RNA                  rs10433937 ⋯ A   0.256 -0.079
23    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.256 -0.079
24    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.256 -0.079
25    0.7722697 0.12528765   RNA                  rs10433937 ⋯ A   0.256 -0.079
26    0.7722697 0.12528765   RNA                  rs10433937 ⋯ G   0.255 -0.080
27    0.7722697 0.12528765   RNA                  rs10433937 ⋯ T   0.255 -0.081
28    0.8196465 0.12878188   RNA                  rs10433937 ⋯ G   0.255 -0.081
29    0.8410187 0.15769760   RNA                  rs4841132  ⋯ G   0.106  0.123
30    0.9321876 0.15194294   RNA                  rs4841132  ⋯ G   0.106  0.123
⋮    ⋮          ⋮            ⋮            ⋮       ⋮          ⋱ ⋮   ⋮     ⋮
1398 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ A   0.357 0.041
1399 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ C   0.357 0.041
1400 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ T   0.355 0.041
1401 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ A   0.356 0.041
1402 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ T   0.356 0.041
1403 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ G   0.356 0.041
1404 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ C   0.357 0.040
1405 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ G   0.357 0.040
1406 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ C   0.357 0.040
1407 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ A   0.357 0.040
1408 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ A   0.356 0.040
1409 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ G   0.357 0.041
1410 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ A   0.356 0.040
1411 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ C   0.356 0.040
1412 -0.8992823 0.1426285    H3K27ac              rs687621   ⋯ C   0.353 0.040
1413 -0.8970646 0.1372207    H3K27ac              rs687621   ⋯ T   0.336 0.041
1414  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ A   0.412 0.035
1415  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ T   0.412 0.034
1416  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ C   0.411 0.034
1417  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ C   0.412 0.034
1418  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ G   0.407 0.034
1419  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ A   0.412 0.034
1420  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ C   0.412 0.034
1421  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ A   0.412 0.034
1422  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ T   0.412 0.034
1423  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ A   0.412 0.034
1424  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ G   0.412 0.034
1425  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ G   0.412 0.034
1426  0.7758834 0.1276958    H3K27me3             rs686250   ⋯ A   0.411 0.034
1427 -0.9257569 0.1452817    H3K27me3             rs60315134 ⋯ G   0.487 0.034
     SE     P        N      PP     chr.hg38 pos.hg38  start.hg38
1    0.0077 5.59e-26 218595 15.93% 4         87309988  87309987
2    0.0063 1.16e-08 218595 5.82%  6         32412938  32412937
3    0.0064 1.25e-07 218595 0.50%  6         32619811  32619810
4    0.0067 5.65e-09 218595 3.41%  1         16171553  16171552
5    0.0068 6.50e-10 218595 29.37% 1         16173110  16173109
6    0.0067 4.52e-09 218595 4.06%  1         16174028  16174027
7    0.0068 6.68e-09 218595 2.29%  1         16177886  16177885
8    0.0066 3.56e-09 218595 5.18%  1         16178825  16178824
9    0.0066 4.96e-09 218595 3.63%  1         16179413  16179412
10   0.0068 5.12e-09 218595 2.95%  1         16181123  16181122
11   0.0069 8.68e-09 218595 1.56%  1         16181880  16181879
12   0.0069 9.07e-09 218595 1.56%  1         16184303  16184302
13   0.0068 4.50e-10 218595 42.37% 1         16184399  16184398
14   0.0065 1.23e-17 218595 48.93% 2        232645051 232645050
15   0.0066 5.89e-17 218595 4.56%  2        232645141 232645140
16   0.0066 6.38e-18 218595 45.80% 2        232645301 232645300
17   0.0077 7.72e-26 218595 9.26%  4         87265289  87265288
18   0.0076 2.55e-25 218595 11.16% 4         87275167  87275166
19   0.0076 6.38e-25 218595 4.28%  4         87280348  87280347
20   0.0076 1.75e-25 218595 4.91%  4         87287745  87287744
21   0.0076 1.73e-25 218595 4.91%  4         87291707  87291706
22   0.0076 1.73e-25 218595 4.91%  4         87292992  87292991
23   0.0076 1.90e-25 218595 4.28%  4         87295786  87295785
24   0.0076 1.78e-25 218595 4.91%  4         87296626  87296625
25   0.0076 2.17e-25 218595 3.74%  4         87298960  87298959
26   0.0076 2.03e-25 218595 14.70% 4         87303345  87303344
27   0.0077 5.28e-26 218595 13.91% 4         87308948  87308947
28   0.0077 5.59e-26 218595 15.93% 4         87309988  87309987
29   0.0105 6.62e-32 218595 98.79% 8          9326086   9326085
30   0.0105 6.62e-32 218595 98.79% 8          9326086   9326085
⋮    ⋮      ⋮        ⋮      ⋮      ⋮        ⋮         ⋮
1398 0.0066 8.23e-10 218595 3.36%  9        133266790 133266789
1399 0.0066 1.07e-09 218595 2.79%  9        133267960 133267959
1400 0.0066 6.66e-10 218595 4.45%  9        133268872 133268871
1401 0.0066 6.46e-10 218595 4.89%  9        133268885 133268884
1402 0.0066 6.47e-10 218595 4.89%  9        133268896 133268895
1403 0.0066 6.47e-10 218595 4.89%  9        133268897 133268896
1404 0.0066 1.21e-09 218595 2.32%  9        133269461 133269460
1405 0.0066 1.21e-09 218595 2.32%  9        133269548 133269547
1406 0.0066 1.18e-09 218595 2.54%  9        133269828 133269827
1407 0.0066 1.13e-09 218595 2.54%  9        133270074 133270073
1408 0.0066 1.25e-09 218595 2.32%  9        133270565 133270564
1409 0.0066 9.45e-10 218595 3.06%  9        133270615 133270614
1410 0.0066 1.31e-09 218595 2.32%  9        133270797 133270796
1411 0.0066 1.60e-09 218595 1.93%  9        133271001 133271000
1412 0.0066 1.16e-09 218595 2.54%  9        133271745 133271744
1413 0.0067 1.37e-09 218595 1.62%  9        133273813 133273812
1414 0.0064 6.45e-08 218595 1.15%  6         32460995  32460994
1415 0.0064 1.23e-07 218595 0.59%  6         32475059  32475058
1416 0.0064 1.35e-07 218595 0.54%  6         32475395  32475394
1417 0.0064 1.31e-07 218595 0.54%  6         32476807  32476806
1418 0.0065 2.72e-07 218595 0.26%  6         32477133  32477132
1419 0.0064 1.33e-07 218595 0.54%  6         32477337  32477336
1420 0.0064 1.33e-07 218595 0.54%  6         32477340  32477339
1421 0.0064 1.30e-07 218595 0.54%  6         32477481  32477480
1422 0.0064 1.36e-07 218595 0.54%  6         32479145  32479144
1423 0.0064 1.55e-07 218595 0.46%  6         32479334  32479333
1424 0.0064 1.52e-07 218595 0.50%  6         32479385  32479384
1425 0.0064 1.35e-07 218595 0.54%  6         32479564  32479563
1426 0.0064 1.36e-07 218595 0.54%  6         32479697  32479696
1427 0.0065 2.41e-07 218595 0.29%  8          8452998   8452997

# Add if it is a coloc example

In [80]:
coloc.select <- coloc.res %>%
    select(PP.H4.abf, qtl.cell=cell, qtl.modality=modality, qtl.feature=feature, gwas.lead, gwas.pval, qtl.pos1=qtl.pos, r2)

dim(coloc.select)
head(coloc.select)

[1] 213   8

  PP.H4.abf qtl.cell qtl.modality qtl.feature              gwas.lead  gwas.pval
1 0.9745446 Bulk     ATAC         chr1-16189980-16190280   rs1497406  1.458e-08
2 0.9655863 Bulk     ATAC         chr1-229256817-229257117 rs12041301 9.290e-06
3 0.8606462 Bulk     ATAC         chr10-26710287-26710575  rs2477276  2.912e-05
4 0.8902173 Bulk     ATAC         chr10-26711375-26711675  rs2477276  2.912e-05
5 0.8938722 Bulk     ATAC         chr11-61820741-61821041  rs174535   3.105e-15
6 0.9484784 Bulk     ATAC         chr11-61832766-61833066  rs174535   3.105e-15
  qtl.pos1  r2
1  16178825 1.000
2 229253038 0.816
3  26666136 1.000
4  26666136 1.000
5  61836038 0.911
6  61836038 0.911

In [85]:
qtl.cred.set.coloc <- left_join(qtl.cred.set, coloc.select) %>%
    mutate(is.coloc=!is.na(PP.H4.abf))

dim(qtl.cred.set.coloc)
head(qtl.cred.set.coloc)

select(qtl.cred.set.coloc, LEAD.SNP, qtl.cell, qtl.modality) %>% distinct() %>% group_by(qtl.cell,qtl.modality) %>% summarise(count=n())
select(qtl.cred.set.coloc, LEAD.SNP, qtl.cell) %>% distinct() %>% group_by(qtl.cell) %>% summarise(count=n())

select(qtl.cred.set.coloc, LEAD.SNP, qtl.cell, qtl.modality, is.coloc) %>% distinct() %>% group_by(qtl.cell,qtl.modality, is.coloc) %>% summarise(count=n())
select(qtl.cred.set.coloc, LEAD.SNP, qtl.cell, is.coloc) %>% distinct() %>% group_by(qtl.cell, is.coloc) %>% summarise(count=n())

Joining with `by = join_by(qtl.feature, qtl.cell, qtl.modality)`

[1] 1427   27

  qtl.feature variant_id qtl.cell    qtp.pval_nominal sig.qtl qtl.slope
1 HSD17B13    rs10433879 Myeloid     4.227959e-06     TRUE     0.7136446
2 HLA-DQB1    rs968155   Myeloid     8.382722e-06     TRUE    -0.5900655
3 HLA-DQB1    rs9271406  Myeloid     8.116191e-08     TRUE    -0.6510572
4 EPHA2       rs11588341 Hepatocytes 9.513265e-06     TRUE    -0.3773269
5 EPHA2       rs1497407  Hepatocytes 8.349330e-06     TRUE    -0.3804022
6 EPHA2       rs7519043  Hepatocytes 6.773970e-06     TRUE    -0.3836847
  qtl.slope_se qtl.modality CS.Type LEAD.SNP   ⋯ PP     chr.hg38 pos.hg38
1 0.13917176   RNA                  rs10433937 ⋯ 15.93% 4        87309988
2 0.11959907   RNA                  rs686250   ⋯ 5.82%  6        32412938
3 0.10469777   RNA                  rs686250   ⋯ 0.50%  6        32619811
4 0.07704365   RNA                  rs36086195 ⋯ 3.41%  1        16171553
5 0.07708509   RNA                  rs36086195 ⋯ 29.37% 1        16173110
6 0.07682361   RNA                  rs36086195 ⋯ 4.06%  1        16174028
  start.hg38 PP.H4.abf gwas.lead gwas.pval qtl.pos1 r2    is.coloc
1 87309987          NA NA               NA       NA    NA FALSE
2 32412937          NA NA               NA       NA    NA FALSE
3 32619810          NA NA               NA       NA    NA FALSE
4 16171552   0.8909272 rs1497406 1.458e-08 16177886 0.824  TRUE
5 16173109   0.8909272 rs1497406 1.458e-08 16177886 0.824  TRUE
6 16174027   0.8909272 rs1497406 1.458e-08 16177886 0.824  TRUE

`summarise()` has grouped output by 'qtl.cell'. You can override using the `.groups` argument.

   qtl.cell      qtl.modality count
1  B             ATAC          1
2  Cholangiocyte ATAC          2
3  Endothelial   ATAC          7
4  Endothelial   H3K27ac       2
5  Endothelial   RNA           1
6  HSC           ATAC          2
7  Hepatocytes   ATAC         26
8  Hepatocytes   H3K27ac       6
9  Hepatocytes   H3K27me3      2
10 Hepatocytes   RNA           6
11 Myeloid       ATAC          8
12 Myeloid       H3K27ac       1
13 Myeloid       RNA           2

  qtl.cell      count
1 B              1
2 Cholangiocyte  2
3 Endothelial    7
4 HSC            2
5 Hepatocytes   28
6 Myeloid        9

`summarise()` has grouped output by 'qtl.cell', 'qtl.modality'. You can override using the `.groups` argument.

   qtl.cell      qtl.modality is.coloc count
1  B             ATAC         FALSE     1
2  Cholangiocyte ATAC         FALSE     2
3  Endothelial   ATAC         FALSE     7
4  Endothelial   ATAC          TRUE     1
5  Endothelial   H3K27ac      FALSE     2
6  Endothelial   H3K27ac       TRUE     1
7  Endothelial   RNA           TRUE     1
8  HSC           ATAC         FALSE     2
9  Hepatocytes   ATAC         FALSE    18
10 Hepatocytes   ATAC          TRUE    16
11 Hepatocytes   H3K27ac      FALSE     4
12 Hepatocytes   H3K27ac       TRUE     4
13 Hepatocytes   H3K27me3     FALSE     2
14 Hepatocytes   RNA          FALSE     2
15 Hepatocytes   RNA           TRUE     5
16 Myeloid       ATAC         FALSE     8
17 Myeloid       H3K27ac      FALSE     1
18 Myeloid       RNA          FALSE     2

`summarise()` has grouped output by 'qtl.cell'. You can override using the `.groups` argument.

  qtl.cell      is.coloc count
1 B             FALSE     1
2 Cholangiocyte FALSE     2
3 Endothelial   FALSE     7
4 Endothelial    TRUE     1
5 HSC           FALSE     2
6 Hepatocytes   FALSE    20
7 Hepatocytes    TRUE    17
8 Myeloid       FALSE     9

In [87]:
write.table(qtl.cred.set.coloc, '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/250325_WE_All_Mod_QTLs_cred_set_coloc_join.tsv', 
            sep='\t', col.names=T, row.names=F, quote=F)

In [88]:
gc()

       used    (Mb) gc trigger (Mb) max used (Mb)
Ncells  900642 48.1 1417395    75.7 1417395  75.7
Vcells 2046011 15.7 8388608    64.0 4770614  36.4

# Overlapping cRE or Active state

In [97]:
in.peak.df <- data.frame()
in.active.df <- data.frame()


for (cell in unique(qtl.cred.set.coloc$qtl.cell)) {
    in.peak.df <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/GWAS/peak.overlap/',cell,
                '.peak.MVP.NAFLD.TRANS.MVP.2021.credset.hg38.bed')) %>%
        select(variant_id=V4, V11) %>%
        filter(V11!=-1) %>%
        select(-V11) %>%
        mutate(qtl.cell=cell, is.in.peak=TRUE) %>%
        rbind(in.peak.df)
    
    in.active.df <- read.table(paste0('/nfs/lab/tscc/welison/FNIH.Liver/GWAS/peak.overlap/',cell,
                      '.states.MVP.NAFLD.TRANS.MVP.2021.credset.hg38.bed')) %>%
        select(variant_id=V4, V13) %>%
        filter(V13=='E5') %>%
        select(-V13) %>%
        mutate(qtl.cell=cell, is.in.active=TRUE) %>%
        rbind(in.active.df)
}

dim(in.peak.df)
group_by(in.peak.df, qtl.cell) %>% summarise(count=n())
dim(in.active.df)
group_by(in.active.df, qtl.cell) %>% summarise(count=n())

[1] 466   3

  qtl.cell      count
1 B              42
2 Cholangiocyte  68
3 Endothelial    73
4 HSC            79
5 Hepatocytes   115
6 Myeloid        89

[1] 1133    3

  qtl.cell      count
1 B              64
2 Cholangiocyte 141
3 Endothelial   167
4 HSC           128
5 Hepatocytes   397
6 Myeloid       236

In [103]:
qtl.cred.set.coloc.peak.active <- left_join(qtl.cred.set.coloc, in.peak.df, ) %>%
    left_join(in.active.df) %>%
    mutate(is.in.peak=ifelse(is.na(is.in.peak), FALSE, is.in.peak),
          is.in.active=ifelse(is.na(is.in.active), FALSE, is.in.active))

dim(qtl.cred.set.coloc.peak.active)
head(qtl.cred.set.coloc.peak.active)

Joining with `by = join_by(variant_id, qtl.cell)`
Joining with `by = join_by(variant_id, qtl.cell)`

[1] 1427   29

  qtl.feature variant_id qtl.cell    qtp.pval_nominal sig.qtl qtl.slope
1 HSD17B13    rs10433879 Myeloid     4.227959e-06     TRUE     0.7136446
2 HLA-DQB1    rs968155   Myeloid     8.382722e-06     TRUE    -0.5900655
3 HLA-DQB1    rs9271406  Myeloid     8.116191e-08     TRUE    -0.6510572
4 EPHA2       rs11588341 Hepatocytes 9.513265e-06     TRUE    -0.3773269
5 EPHA2       rs1497407  Hepatocytes 8.349330e-06     TRUE    -0.3804022
6 EPHA2       rs7519043  Hepatocytes 6.773970e-06     TRUE    -0.3836847
  qtl.slope_se qtl.modality CS.Type LEAD.SNP   ⋯ pos.hg38 start.hg38 PP.H4.abf
1 0.13917176   RNA                  rs10433937 ⋯ 87309988 87309987          NA
2 0.11959907   RNA                  rs686250   ⋯ 32412938 32412937          NA
3 0.10469777   RNA                  rs686250   ⋯ 32619811 32619810          NA
4 0.07704365   RNA                  rs36086195 ⋯ 16171553 16171552   0.8909272
5 0.07708509   RNA                  rs36086195 ⋯ 16173110 16173109   0.8909272
6 0.07682361   RNA                  rs36086195 ⋯ 16174028 16174027   0.8909272
  gwas.lead gwas.pval qtl.pos1 r2    is.coloc is.in.peak is.in.active
1 NA               NA       NA    NA FALSE    FALSE      FALSE
2 NA               NA       NA    NA FALSE    FALSE      FALSE
3 NA               NA       NA    NA FALSE    FALSE      FALSE
4 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE
5 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE
6 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE

In [105]:
select(qtl.cred.set.coloc.peak.active, LEAD.SNP, qtl.cell, is.in.peak) %>% distinct() %>% group_by(qtl.cell,is.in.peak) %>% summarise(count=n())
select(qtl.cred.set.coloc.peak.active, LEAD.SNP, qtl.cell, is.in.active) %>% distinct() %>% group_by(qtl.cell,is.in.active) %>% summarise(count=n())
select(qtl.cred.set.coloc.peak.active, LEAD.SNP, qtl.cell) %>% distinct() %>% group_by(qtl.cell) %>% summarise(count=n())

select(qtl.cred.set.coloc.peak.active, LEAD.SNP, is.in.peak) %>% distinct() %>% group_by(is.in.peak) %>% summarise(count=n())
select(qtl.cred.set.coloc.peak.active, LEAD.SNP, is.in.active) %>% distinct() %>% group_by(is.in.active) %>% summarise(count=n())

`summarise()` has grouped output by 'qtl.cell'. You can override using the `.groups` argument.

   qtl.cell      is.in.peak count
1  B             FALSE       1
2  B              TRUE       1
3  Cholangiocyte FALSE       2
4  Cholangiocyte  TRUE       2
5  Endothelial   FALSE       7
6  Endothelial    TRUE       3
7  HSC           FALSE       2
8  HSC            TRUE       1
9  Hepatocytes   FALSE      25
10 Hepatocytes    TRUE      16
11 Myeloid       FALSE       9
12 Myeloid        TRUE       6

`summarise()` has grouped output by 'qtl.cell'. You can override using the `.groups` argument.

   qtl.cell      is.in.active count
1  B             FALSE         1
2  Cholangiocyte FALSE         2
3  Cholangiocyte  TRUE         1
4  Endothelial   FALSE         6
5  Endothelial    TRUE         4
6  HSC           FALSE         2
7  Hepatocytes   FALSE        17
8  Hepatocytes    TRUE        23
9  Myeloid       FALSE         9
10 Myeloid        TRUE         5

  qtl.cell      count
1 B              1
2 Cholangiocyte  2
3 Endothelial    7
4 HSC            2
5 Hepatocytes   28
6 Myeloid        9

  is.in.peak count
1 FALSE      31
2  TRUE      20

  is.in.active count
1 FALSE        24
2  TRUE        26

In [106]:
write.table(qtl.cred.set.coloc.peak.active, '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/250325_WE_All_Mod_QTLs_cred_set_coloc_join_peak_state_overlap.tsv', 
            sep='\t', col.names=T, row.names=F, quote=F)

# Add chromBPNet

In [109]:
chrombp <- read.table('/nfs/lab/tscc/welison/FNIH.Liver/13_chromBPNet_Peaks/variant_prediction/Control_snps_snp_scores.tsv', header=T)
dim(chrombp) 
head(chrombp)

[1] 1084    8

  CHR  POS0      REF ALT META_DATA log_counts_diff log_probs_diff_abs_sum
1 chr1 220796685 A   G   0.9686     0.197049620    104.89130
2 chr2 113083452 G   A   0.9904    -0.047235966    -28.07371
3 chr6  71185548 G   T   0.9631    -0.007250309    -10.40595
4 chr8 125495065 T   C   0.9995     0.107834340     35.40631
5 chr8  10713980 C   A   0.9851     0.169893740     44.13598
6 chr8   9326085 A   G   0.9879     0.204382180     71.86758
  probs_jsd_diff
1  0.047965051
2 -0.016617813
3 -0.006723976
4  0.017021200
5  0.020204187
6  0.034811529

In [121]:
Hep.cs <- filter(qtl.cred.set.coloc.peak.active, qtl.cell=='Hepatocytes') %>%
    select(LEAD.SNP) %>% unlist() %>% unique()

length(Hep.cs)
head(Hep.cs)

[1] 28

[1] "rs36086195" "rs11683367" "rs10433937" "rs4841132"  "rs10883451"
[6] "rs1547014"

In [129]:
chrombp.good.effect <- inner_join(cred.set, chrombp, join_by(start.hg38 == POS0)) %>%
    select(-Nominated.Gene, -Biological.Prior.Gene, -chr.hg38, -end.hg38, 
           -start.hg38, -CHR, -META_DATA, -REF, -ALT) %>%
    filter(abs(log_counts_diff) > 0.025) 

filter(chrombp.good.effect, LEAD.SNP %in% Hep.cs) %>% select(LEAD.SNP) %>% distinct()
dim(chrombp.good.effect)
head(chrombp.good.effect)

   LEAD.SNP
1  rs4484649
2  rs4841132
3  rs36086195
4  rs11683409
5  rs2943652
6  rs6543007
7  rs4683438
8  rs7653249
9  rs10433937
10 rs686250
11 rs60315134
12 rs35199395
13 rs4918722
14 rs56175344
15 rs34123446
16 rs9668670
17 rs11621792
18 rs3935942
19 rs7168849
20 rs56094641
21 rs3810367
22 rs4805033
23 rs6059896
24 rs1547014

[1] 260  16

  CS.Type    LEAD.SNP   CS.SNP     Chr Position  EA NEA EAF   Beta   SE
1 Single SNP rs2642438  rs2642438   1  220970028 A  G   0.274 -0.075 0.0074
2            rs6734238  rs6734238   2  113841030 G  A   0.407 -0.057 0.0064
3            rs2980888  rs2980888   8  126507308 T  C   0.286  0.130 0.0072
4            rs4484649  rs4484649   8   10571491 C  A   0.419  0.045 0.0066
5            rs4841132  rs4841132   8    9183596 A  G   0.106  0.123 0.0105
6            rs11601507 rs11601507 11    5701074 A  C   0.072  0.099 0.0128
  P        N      PP      log_counts_diff log_probs_diff_abs_sum probs_jsd_diff
1 6.65e-24 218595 96.86%   0.19704962     104.89130               0.04796505
2 4.94e-19 218595 99.04%  -0.04723597     -28.07371              -0.01661781
3 4.21e-72 218595 99.95%   0.10783434      35.40631               0.01702120
4 1.38e-11 218595 98.51%   0.16989374      44.13598               0.02020419
5 6.62e-32 218595 98.79%   0.20438218      71.86758               0.03481153
6 1.53e-14 218595 100.00%  0.06414437      28.70793               0.01305975

In [133]:
colnames(chrombp.good.effect)

 [1] "CS.Type"                "LEAD.SNP"               "CS.SNP"
 [4] "Chr"                    "Position"               "EA"
 [7] "NEA"                    "EAF"                    "Beta"
[10] "SE"                     "P"                      "N"
[13] "PP"                     "log_counts_diff"        "log_probs_diff_abs_sum"
[16] "probs_jsd_diff"

In [135]:
chrombp.good.effect.to.join <- select(chrombp.good.effect,CS.SNP, chrombp_log_counts_diff=log_counts_diff, 
                                     chrombp_log_probs_diff_abs_sum=log_probs_diff_abs_sum,
                                     chrombp_probs_jsd_diff=probs_jsd_diff)

qtl.cred.set.coloc.peak.active_chrombp <- left_join(qtl.cred.set.coloc.peak.active, chrombp.good.effect.to.join, join_by(variant_id==CS.SNP))

dim(qtl.cred.set.coloc.peak.active)
head(qtl.cred.set.coloc.peak.active)

[1] 1427   29

  qtl.feature variant_id qtl.cell    qtp.pval_nominal sig.qtl qtl.slope
1 HSD17B13    rs10433879 Myeloid     4.227959e-06     TRUE     0.7136446
2 HLA-DQB1    rs968155   Myeloid     8.382722e-06     TRUE    -0.5900655
3 HLA-DQB1    rs9271406  Myeloid     8.116191e-08     TRUE    -0.6510572
4 EPHA2       rs11588341 Hepatocytes 9.513265e-06     TRUE    -0.3773269
5 EPHA2       rs1497407  Hepatocytes 8.349330e-06     TRUE    -0.3804022
6 EPHA2       rs7519043  Hepatocytes 6.773970e-06     TRUE    -0.3836847
  qtl.slope_se qtl.modality CS.Type LEAD.SNP   ⋯ pos.hg38 start.hg38 PP.H4.abf
1 0.13917176   RNA                  rs10433937 ⋯ 87309988 87309987          NA
2 0.11959907   RNA                  rs686250   ⋯ 32412938 32412937          NA
3 0.10469777   RNA                  rs686250   ⋯ 32619811 32619810          NA
4 0.07704365   RNA                  rs36086195 ⋯ 16171553 16171552   0.8909272
5 0.07708509   RNA                  rs36086195 ⋯ 16173110 16173109   0.8909272
6 0.07682361   RNA                  rs36086195 ⋯ 16174028 16174027   0.8909272
  gwas.lead gwas.pval qtl.pos1 r2    is.coloc is.in.peak is.in.active
1 NA               NA       NA    NA FALSE    FALSE      FALSE
2 NA               NA       NA    NA FALSE    FALSE      FALSE
3 NA               NA       NA    NA FALSE    FALSE      FALSE
4 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE
5 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE
6 rs1497406 1.458e-08 16177886 0.824  TRUE    FALSE       TRUE

In [136]:
write.table(qtl.cred.set.coloc.peak.active, '/nfs/lab/tscc/welison/FNIH.Liver/tensorQTL/250325_WE_All_Mod_QTLs_cred_set_coloc_join_peak_state_overlap_chromBP.tsv', 
            sep='\t', col.names=T, row.names=F, quote=F)